import { test } from "node:test";
import assert from "node:assert";

import { getPlannerData } from "../utils/plannerCatalog.js";

// backend/catalog/games/age-of-empires-2-de.json - 357 real achievements sourced
// from a live ISteamUserStats/GetSchemaForGame/v2 response for appid
// 813780 (fetched through this app's own services/steamApi.js).
// All 357 ship a real, official Steam description. Age of Empires II: Definitive Edition has no
// Steam-hidden achievements.
// difficulty/estimatedTime remain curatorial judgments, same convention
// as every other planner difficulty/time field in this catalog.
const ageOfEmpires2De = getPlannerData("age-of-empires-2-de");

test("getPlannerData('age-of-empires-2-de') returns real planner data with 357 curated achievements", () => {

    assert.ok(ageOfEmpires2De, "expected real planner data for age-of-empires-2-de");
    assert.ok(Array.isArray(ageOfEmpires2De.achievements));
    assert.strictEqual(ageOfEmpires2De.achievements.length, 357);

});

test("every Age of Empires II: Definitive Edition achievement has a unique id from 1 to 357 and a unique apiname", () => {

    const ids = ageOfEmpires2De.achievements.map(a => a.id);
    const apinames = ageOfEmpires2De.achievements.map(a => a.apiname);

    assert.deepStrictEqual([...ids].sort((a, b) => a - b), Array.from({ length: 357 }, (_, i) => i + 1));
    assert.strictEqual(new Set(ids).size, 357);
    assert.strictEqual(new Set(apinames).size, 357);

});

test("every Age of Empires II: Definitive Edition achievement has a valid difficulty (1-5), a positive estimatedTime, and non-empty name/description", () => {

    for (const achievement of ageOfEmpires2De.achievements) {

        assert.ok(
            Number.isInteger(achievement.difficulty) && achievement.difficulty >= 1 && achievement.difficulty <= 5,
            `${achievement.name} has an out-of-range difficulty: ${achievement.difficulty}`
        );

        assert.ok(
            Number.isInteger(achievement.estimatedTime) && achievement.estimatedTime > 0,
            `${achievement.name} has an invalid estimatedTime: ${achievement.estimatedTime}`
        );

        assert.ok(achievement.name?.length > 0, "achievement is missing a name");
        assert.ok(achievement.description?.length > 0, `${achievement.name} is missing a description`);
        assert.ok(achievement.apiname?.length > 0, `${achievement.name} is missing an apiname`);

    }

});

test("every one of the 357 official Age of Empires II: Definitive Edition achievement name+description pairs matches the live GetSchemaForGame response", () => {

    const officialAchievements = [
        ["Aztec Victory", "Win a game playing as the Aztecs."],
        ["Berber Victory", "Win a game playing as the Berbers."],
        ["Briton Victory", "Win a game playing as the Britons."],
        ["Bulgarian Victory", "Win a game playing as the Bulgarians."],
        ["Burmese Victory", "Win a game playing as the Burmese."],
        ["Byzantine Victory", "Win a game playing as the Byzantines."],
        ["Celtic Victory", "Win a game playing as the Celts."],
        ["Chinese Victory", "Win a game playing as the Chinese."],
        ["Cuman Victory", "Win a game playing as the Cumans."],
        ["Ethiopian Victory", "Win a game playing as the Ethiopians."],
        ["Frankish Victory", "Win a game playing as the Franks."],
        ["Gothic Victory", "Win a game playing as the Goths."],
        ["Hunnic Victory", "Win a game playing as the Huns."],
        ["Inca Victory", "Win a game playing as the Incas."],
        ["Hindustani Victory", "Won a game playing as the Hindustanis."],
        ["Italian Victory", "Win a game playing as the Italians."],
        ["Japanese Victory", "Win a game playing as the Japanese."],
        ["Khmer Victory", "Win a game playing as the Khmer."],
        ["Korean Victory", "Win a game playing as the Koreans."],
        ["Magyar Victory", "Win a game playing as the Magyars."],
        ["Malay Victory", "Win a game playing as the Malay."],
        ["Malian Victory", "Win a game playing as the Malians."],
        ["Mayan Victory", "Win a game playing as the Mayans."],
        ["Mongol Victory", "Win a game playing as the Mongols."],
        ["Persian Victory", "Win a game playing as the Persians."],
        ["Portuguese Victory", "Win a game playing as the Portuguese."],
        ["Saracen Victory", "Win a game playing as the Saracens."],
        ["Slavic Victory", "Win a game playing as the Slavs."],
        ["Spanish Victory", "Win a game playing as the Spanish."],
        ["Tatar Victory", "Win a game playing as the Tatars."],
        ["Teutonic Victory", "Win a game playing as the Teutons."],
        ["Turkish Victory", "Win a game playing as the Turks."],
        ["Vietnamese Victory", "Win a game playing as the Vietnamese."],
        ["Viking Victory", "Win a game playing as the Vikings."],
        ["Guardian of Scotland", "Complete the William Wallace Campaign."],
        ["Iron Maid", "Complete the Joan of Arc Campaign."],
        ["Custodian of the Holy Land", "Complete the Saladin Campaign."],
        ["For the Horde!", "Complete the Genghis Khan Campaign."],
        ["The Emperor Strikes Back", "Complete the Barbarossa Campaign."],
        ["Huney, I Shrunk the Romans", "Complete the Attila the Hun Campaign."],
        ["El Campeador", "Complete the El Cid Campaign."],
        ["Emperor of Tenochtitlan", "Complete the Montezuma Campaign."],
        ["The Thicker the Hay, the Easier Mowed", "Complete the Alaric Campaign."],
        ["Vladislav, Baby Don't Hurt Me", "Complete the Dracula Campaign."],
        ["A Tale of One City", "Complete the Bari Campaign."],
        ["Renaissance Man", "Complete the Sforza Campaign."],
        ["Earth Shaker", "Complete the Pachacuti Campaign."],
        ["The Blind Archer", "Complete the Prithviraj Campaign."],
        ["Master of the Maghreb", "Complete the Tariq ibn Ziyad Campaign."],
        ["King of Africa", "Complete the Sundjata Campaign."],
        ["Age of Discovery", "Complete the Francisco de Almeida Campaign."],
        ["Destroyer of Axum", "Complete the Yodit Campaign."],
        ["Island Hopper", "Complete the Gajah Mada Campaign."],
        ["King of the Just Laws", "Complete the Suryavarman I Campaign."],
        ["Cakkavatti", "Complete the Bayinnaung Campaign."],
        ["Rebel with a Cause", "Complete the Le Loi Campaign."],
        ["Empire of the Steppes", "Complete the Tamerlane Campaign."],
        ["The Cabbage King", "Complete the Ivaylo Campaign."],
        ["Yes we Khan!", "Complete the Kotyan Khan Campaign."],
        ["Battle Beast", "Complete all Historical Battles in single player."],
        ["Wololo", "Convert 1,000 units."],
        ["Unexpected", "Convert 100 units using Spanish Missionaries."],
        ["Losing Your Religion", "Convert an enemy Monk."],
        ["Chain Reaction", "Blow up an enemy Demolition Ship with a Demolition Ship of your own."],
        ["Kaboom", "Kill 1,000 enemy units using Demolition Ships."],
        ["Bull's Eye", "Destroy a Trebuchet with another Trebuchet."],
        ["The Wonder, the Wonder, the...Oh, Never Mind", "Prevent the Korean Wonder from being destroyed in the \"Noryang Point (1598)\" mission of the Historical Battles."],
        ["A Truly Holy Emperor", "Convert the Cathedral in Milan without acquiring a single Villager in the third Barbarossa mission \"Pope and Antipope\"."],
        ["No Wonder on my Watch", "Destroy every enemy Wonder before it is completed in the sixth Attila the Hun mission \"The Fall of Rome\"."],
        ["Diplomacy is for the Meek", "Kill the Scythian Prince and defeat the Scythians in the first Attila the Hun mission \"The Scourge of God\"."],
        ["The Kushluk Assassination", "Kill Kushluk before 20 minutes have elapsed in the second Genghis Khan mission \"A Life of Revenge\"."],
        ["I Was in China Before", "Defeat the Jin before they start constructing a Wonder in the third Genghis Khan mission \"Into China\"."],
        ["Offense Is the Best Defense", "Defeat all opponents before constructing a Wonder in the sixth Saladin mission \"The Lion and the Demon\"."],
        ["The Go-Getter", "Defeat the Hungarians before Subotai has arrived in the sixth Genghis Khan mission \"Pax Mongolica\"."],
        ["Furor Teutonicus", "Defeat all opponents instead of collecting the required Relics in the first Barbarossa mission \"Holy Roman Emperor\"."],
        ["Truly Countless Bodies", "Defeat all opponents before 30 minutes have elapsed in the fifth Attila the Hun mission \"The Catalaunian Fields\"."],
        ["Hot & Spicy", "Prevent Tabasco from being defeated in the third Montezuma mission \"Quetzalcoatl\"."],
        ["Battleship", "Win the Historical Battle \"Lepanto (1571)\" without allowing any Turkish Transport Ship to unload on your shores."],
        ["Relic Hoarder", "Collect all Relics on the map in the fifth Suryavarman mission \"Nirvanapada\"."],
        ["The Missionary", "Collect all Relics in the first El Cid mission \"Brother Against Brother\"."],
        ["Turkish Delight", "Win \"Bapheus (1302)\" by defeating Turkish factions without allying with them in single player."],
        ["Lone Warrior", "Win \"Kurikara (1183)\" without forming an alliance with the Hojo clan in single player."],
        ["Fire with Fire", "Amass 10 Condottieri, 10 Genoese Crossbowmen, and 10 Bombard Cannons in the fifth Dracula mission \"The Night Falls\"."],
        ["Raging Wildfire", "Conquer Delhi at least 5 minutes before the timer expires in the fourth Tamerlane mission \"Sultan of Hindustan\"."],
        ["Chasing the Crown", "Kill King Takayutpi before 5 minutes have elapsed in the first Bayinnaung mission \"The Burmese Tigers\"."],
        ["Friends, Countrymen, Lend Me Your Ears", "Convert Afonso de Albuquerque without killing a single Portuguese unit in the fifth Francisco de Almeida mission \"A Son's Blood\"."],
        ["Numerous As the Grains of Sand", "Win the second Alaric mission \"Razing Hellas\" while training no military units aside from infantry."],
        ["Rome Was Destroyed in One Day", "Destroy all Roman Castles before 30 minutes have elapsed in the fourth Alaric mission \"The Giant Falls\"."],
        ["Smoke on the Water", "Purchase 20 Dragon Ships in the Historical Battle \"Lake Poyang (1363)\"."],
        ["With the Help of My Sisters", "Amass an army of at least 100 Gbeto Warriors in the fourth Sundjata mission \"Blood on the River Bank\"."],
        ["Roar like a Lion", "Win the fifth Sundjata mission \"The Lion's Den\" on Hard difficulty."],
        ["An Army Marches on Its Stomach", "Complete all secondary objectives and destroy all of Dagnajan's smaller bases before Dagnajan and his army march in the third Yodit mission \"A Fallen Crown\"."],
        ["No Royal Hair Touched", "Reach the King before 10 minutes have elapsed in the second Gajah Mada mission \"Unconditional Loyalty\"."],
        ["Not a Greek Tragedy", "Win without losing any of your four heroes in the fifth Le Loi mission \"A Three-Pronged Attack\"."],
        ["Cuman Flush", "Win the second Kotyan mission \"The Battle at the Kalka River\" without advancing to the Castle Age."],
        ["He Won't Be Back", "Assist King Bela and defeat the Austrian Duke Frederick in the fifth Kotyan mission \"A New Home\" before 45 minutes have elapsed."],
        ["Pitched Battle", "Successfully defend Cuzco without constructing any new walls or gates in the second Pachacuti mission \"The Field of Blood\"."],
        ["D-Day (D stands for Demo)", "Destroy an enemy Transport Ship with a Demolition Ship."],
        ["Eternal Gratitude", "Encounter a Penguin in the Historical Battle \"Vinlandsaga\"."],
        ["It's a Treb!", "Kill 25 units with Trebuchets."],
        ["Mango Shots", "Kill 500 units with Mangonels."],
        ["Hun, What Are You doing?", "Burn down 200 buildings with Tarkans."],
        ["Knocking On Your Door", "Demolish 200 buildings with Battering Rams."],
        ["Castle Crusher", "Destroy 50 Castles."],
        ["Out With a Bang", "Kill an enemy King with a Petard or Demolition Ship."],
        ["Lithuanian Victory", "Win a game playing as the Lithuanians."],
        ["Karambolage", "Spam the enemy with 500 Karambit Warriors in a single game."],
        ["Elephantastic", "Train 40 War or Battle Elephants in a single game."],
        ["Fighting From Afar", "Create 500 Longbowmen in a single match."],
        ["90kg Over 300 Meters", "Build 300 Trebuchets."],
        ["Frankly My Dear...", "Create 100 Throwing Axemen in a single match."],
        ["Anyone Order a Pizza?", "Train 1,000 Condottieri as a non-Italian civilization."],
        ["Sushi Lover", "Build 30 Japanese Fishing Ships."],
        ["Out of Their Element", "Destroy a ship using a melee unit."],
        ["Castle of Doubt", "Lose an unfinished Castle that is at least 95% complete."],
        ["The Wonder, the Wonder, Noooooo...", "Build a Wonder."],
        ["Pleasant Peasant", "Build 1,000 Farms in total."],
        ["Supremely Unexpected", "Win a match as the Spanish while only creating Villagers."],
        ["The King Is Dead, Long Live the King!", "Win a Regicide game."],
        ["Marco Polo", "Explore 99% of a ludicrously sized map."],
        ["Relic Hunter", "Collect 100 Relics."],
        ["Bird Shooting", "Kill an enemy Scout Cavalry with your Town Center."],
        ["Dark Dinner", "Eat 2 Wild Boars in the Dark Age."],
        ["Dark Humor", "Kill 20 Villagers with Militia in the Dark Age."],
        ["Masterpiece", "Win alone against 3 human opponents."],
        ["Final Countdown", "Destroy an opponent's Wonder with less than 100 years remaining on the Wonder Victory countdown."],
        ["Howdy Neighbor", "Scale an enemy wall using a Siege Tower."],
        ["Too Lame To Tame", "Loot 500 gold with Keshiks."],
        ["Rest in Peace", "Beat an AI opponent on \"Peaceful\" difficulty in a 1v1 game."],
        ["With Moderation", "Beat an AI opponent on \"Moderate\" difficulty in a 1v1 game."],
        ["Rough Ride", "Beat an AI opponent on \"Hard\" difficulty in a 1v1 game."],
        ["Barbaric Manners", "Beat an AI opponent on \"Hardest\" difficulty in a 1v1 game."],
        ["Prominent Player", "Beat an AI opponent on \"Extreme\" difficulty in a 1v1 game."],
        ["Sheep Hoarder", "Gather 20 Sheep in a Random Map game."],
        ["Homeless", "Delete your starting Town Center and still win the game."],
        ["Easy Going", "Beat an AI opponent on \"Standard\" difficulty in a 1v1 game."],
        ["No Suntzu Light", "Shoot 100,000 arrows with your Chu Ko Nu."],
        ["Age of Empires", "Win a game with every civilization."],
        ["The English Justinian", "Complete the Edward Longshanks campaign."],
        ["The Good, the Bold, and the Fearless", "Complete the Grand Dukes of the West campaign."],
        ["Haute Culture", "Complete the Hautevilles campaign."],
        ["Unchivalrous Pragmatist", "Defeat Simon the Younger's army before the baronial forces attack in \"Vain Ambition\"."],
        ["Throne Thief", "Steal the Stone of Scone in the fourth Edward Longshanks mission \"Toom Tabard\"."],
        ["Malleus Scotorum", "Kill William Wallace before Robert the Bruce betrays you in \"Hammer of the Scots\"."],
        ["No Wheels", "Do not construct a single siege weapon in the mission \"A Kingdom Divided\"."],
        ["A Second Hastings", "Wipe out Humphrey's base before defeating Jacqueline in \"The Hook and Cod Wars\"."],
        ["Shut Up La Hire!", "Defeat the French army before capturing Joan of Arc in the mission \"The Maid Falls\"."],
        ["Self-Made Man", "Win without allying with Argyrus or Guaimar in the mission \"Guiscard Arrives\"."],
        ["Haute, Haute, brief candle!", "Inspire a rebellion in the second Hautevilles mission \"Roger in Sicily\"."],
        ["Italy Jones and the First Crusade", "Do not lose a hero in the fourth Hautevilles mission \"Bohemond in the East\"."],
        ["Burgundian Victory", "Win a game playing as the Burgundians."],
        ["Sicilian Victory", "Win a game playing as the Sicilians."],
        ["Golden Spurs", "Transform 50 Villagers by researching Flemish Revolution."],
        ["Tour d'Italie", "Construct a Donjon and use it to train a Serjeant."],
        ["Bond of Brothers", "Complete the Algirdas and Kestutis campaign."],
        ["Tolerant Piety", "Build a Monastery or Shrine in every Lithuanian village in \"Family Affairs\"."],
        ["Scattered Horde", "Kill all enemy commanders before defeating their hordes in \"The Tatar Yoke\"."],
        ["Mint Condition", "Deliver the Ransom Cart undamaged in \"In the Shadow of the Throne\"."],
        ["Star of the Poles", "Complete the Jadwiga campaign."],
        ["Protector of the Realm", "Win without losing any neutral towns to Halych in \"Star of the Poles\"."],
        ["No Baggage", "Defeat the Crimean Tatars without building a Town Center in \"Vytautas' Crusade\"."],
        ["No Quarter", "Kill Ulrich von Jungingen and Nicolas von Renys in \"The Fruits of Her Labor\"."],
        ["Man of the Chalice", "Complete the Jan Zizka campaign."],
        ["Malevolent Marauder", "Destroy all 6 Bohemian villages in \"The One-Eyed Wanderer\"."],
        ["Zizkov Hill", "Do not lose the Old Tower northeast of your city in \"The Golden City\"."],
        ["Against All", "Defeat the Crusaders in the fifth Jan Zizka mission \"The Emperor's Fury\"."],
        ["Bohemian Victory", "Win a game playing as the Bohemians."],
        ["Polish Victory", "Win a game playing as the Poles."],
        ["Rhapsody of the Bohemians", "Train 10 Houfnices as the Bohemians."],
        ["Fast Food", "Gather 500 food by constructing farms next to Folwarks as the Poles."],
        ["The Persian Tiger", "Complete the Babur campaign."],
        ["Never Trust a Campaign AI", "Ignore Kabul's offer to form a non-aggression pact in \"The Last Timurids\"."],
        ["An Offer You Khan't Refuse", "Convert both Alam Khan and Daulat Khan in \"The Battle of Panipat\"."],
        ["The Renovator", "Repair all 4 Town Centers in the devastated villages in \"The Rajputs\"."],
        ["Like Father, Like Son", "Complete the Rajendra campaign."],
        ["No Rest for the Wicked", "Defeat Mannaram and Polonnaruwa without capturing a Town Center in Rajendra #2."],
        ["Eye of the Tiger", "Defeat Srivijaya, Madurai, the Chalukyan Empire and the Pirates in Rajendra 3."],
        ["No Wonder You Won", "Win the game before Mahipala completes his Wonder in \"Sacred Waters\"."],
        ["Won't You Take Me by the Hand", "Complete the Devapala campaign."],
        ["Huna Join Me?", "Convert all 3 Huna Khans in \"Renunciation\"."],
        ["Construction Cancellation", "Destroy the Rashtrakuta Wonder before it is completed in \"Liberation?\"."],
        ["Parinirvana", "Accumulate 100 piety points in \"Enlightenment\"."],
        ["Raja of the People", "Save both allied villages in \"Born of Fire\" on Hard difficulty."],
        ["Hopeless Romantic", "Win \"Hand of a Princess\" with 12+ minutes remaining on the timer."],
        ["Inspiring Poet", "Convert all Rajas before the Ghorids attack in Prithviraj #5 on Hard difficulty."],
        ["Bengali Victory", "Win a game playing as the Bengalis."],
        ["Dravidian Victory", "Win a game playing as the Dravidians."],
        ["Gurjara Victory", "Win a game playing as the Gurjaras."],
        ["Face My Ratha", "Train 10 Rathas as the Bengalis."],
        ["King of the Seas", "Sink 10 enemy ships with Thirisadais as the Dravidians."],
        ["Forged in the Heat of Battle", "Train 10 Chakram Throwers as the Gurjaras."],
        ["Not Just a Militia", "Upgrade your Militia to Men-at-Arms"],
        ["Family Feudal", "Advance to the Feudal Age in a Campaign Scenario"],
        ["Can I be Frank with You?", "Win the \"Tours (732)\" Co-Op Historical Battle with an AI or Human Teammate"],
        ["Challenge Accepted", "Win any Medal in any Art of War Challenge"],
        ["Going for the Gold", "Win a Gold Medal in any Art of War Challenge"],
        ["Wingman", "Win a Skirmish or Multiplayer Game with a Human or AI Teammate"],
        ["Baby Boomer", "Queue 5 Villagers at the Town Center in the Dark Age"],
        ["Bull Market", "Create a Trade Route with another Market"],
        ["Bon Voyage", "Turn on Auto-Scout in any Game Mode"],
        ["Prepare for Boar!", "Research Loom at the Town Center"],
        ["The God of War", "Complete the Sargon campaign."],
        ["Not Cutting Corners", "Subdue both Sippar and Borsippa in \"The Chosen One\"."],
        ["Expedited Delivery", "Bring the Artifact to each city-state before 30 minutes have elapsed in \"Divine Will\"."],
        ["Ur Out of Here", "Destroy Ur's Wonder before it is completed in \"The Prophecy\"."],
        ["Back to Square One", "Complete the Pyrrhus campaign."],
        ["What Would Alexander Have Done?", "Win with all allied Town Centers remaining in \"A Second Alexander\"."],
        ["Greece'd Lightning", "Win before Demetrius arrives in \"The Many Kings of Macedon\"."],
        ["The Best Defense...", "Defeat all enemies in \"Sisyphus\"."],
        ["Optimus Princeps", "Complete the Trajan campaign."],
        ["Are You Not Entertained?", "Win \"Legates and Legions\" in less than 10 minutes."],
        ["I Am Legion", "Defeat the Dacian Army in \"Heads Will Roll\"."],
        ["You Have No Power Here!", "Lose less than 5 units to conversion in \"An Old Enemy\"."],
        ["Roman Victory", "Win a game as the Romans."],
        ["Assyrian Victory", "Win a game as the Assyrians in Return of Rome."],
        ["Babylonian Victory", "Win a game as the Babylonians in Return of Rome."],
        ["Carthaginian Victory", "Win a game as the Carthaginians in Return of Rome."],
        ["Choson Victory", "Win a game as the Choson in Return of Rome."],
        ["Egyptian Victory", "Win a game as the Egyptians in Return of Rome."],
        ["Greek Victory", "Win a game as the Greeks in Return of Rome."],
        ["Hittite Victory", "Win a game as the Hittites in Return of Rome."],
        ["Lac Viet Victory", "Win a game as the Lac Viet in Return of Rome"],
        ["Macedonian Victory", "Win a game as the Macedonians in Return of Rome."],
        ["Minoan Victory", "Win a game as the Minoans in Return of Rome."],
        ["Palmyran Victory", "Win a game as the Palmyrans in Return of Rome."],
        ["Persian Victory", "Win a game as the Persians in Return of Rome."],
        ["Phoenician Victory", "Win a game as the Phoenicians in Return of Rome."],
        ["Roman Victory", "Win a game as the Romans in Return of Rome."],
        ["Shang Victory", "Win a game as the Shang in Return of Rome."],
        ["Sumerian Victory", "Win a game as the Sumerians in Return of Rome."],
        ["Yamato Victory", "Win a game as the Yamato in Return of Rome."],
        ["Ride for Ruin!", "Kill 15 units with Scouts in the Tool Age in Return of Rome."],
        ["Calm, Cool, and Collected", "Win 3 games in a row in Return of Rome."],
        ["Agile as a Sparrow", "Win a game without losing a single unit in Return of Rome."],
        ["I Wonder Why I Did That?", "Win a game by constructing a Wonder in Return of Rome."],
        ["Forged in Iron", "Reach the Iron Age before 20 minutes of game time have elapsed in Return of Rome."],
        ["Chariotable Numbers", "Train 60 Chariot Archers in Return of Rome."],
        ["Builder of Civilizations", "Complete the Ascent of Egypt campaign."],
        ["Tactical Retreat", "Complete The First Punic War campaign."],
        ["Philhellene", "Complete the Glory of Greece Campaign"],
        ["Law Maker", "Complete the Voices of Babylon Campaign"],
        ["Call Me Ismail", "Complete the Ismail campaign."],
        ["Sneak Attack", "Kill Farrukh Yasar before he reaches his fortress in \"The Red Hats\"."],
        ["Landslide Election", "Capture all Tabriz noblemen in \"Road to Royalty\"."],
        ["I Ain't 'Fraid of No Guns", "Defeat the Ottomans in \"Khata'i\"."],
        ["Lord of the Mountains", "Complete the Thoros the Great campaign."],
        ["Bounty Hunter", "Convert at least three Byzantine generals in \"The Emperor's Revenge\"."],
        ["Raiding Party!", "Defeat all enemy Cypriot players in \"Bloody Crestwaves\"."],
        ["Church Sanctuary", "Do not lose any Tarsos Villagers in \"Of Turncoats and Traitors\"."],
        ["Georgia On My Mind", "Complete the Tamar campaign."],
        ["Game's Over Yury", "Defeat Yury before the end of the siege in \"Yury's Revenge\"."],
        ["Auntie Dearest", "Ensure Alexios completes his Wonder in \"Tamar the Builder\"."],
        ["Alexandra the Great", "Complete all side-quests in \"The Queen in the Panther's Skin\"."],
        ["Armenian Victory", "Win a game playing as the Armenians."],
        ["Georgian Victory", "Win a game playing as the Georgians."],
        ["Heroes and Villains", "Complete all Victors and Vanquished scenarios on any difficulty."],
        ["Lost Vikings", "Find three lost Vikings in \"Finehair (870)\"."],
        ["The Old-fashioned Way", "Win without constructing a Trebuchet in \"Stephen (1135)\"."],
        ["Daimyo of the Nine Provinces", "Defeat the Shogun and conquer all Nine Provinces by 1600 CE in \"Shimazu (1545)\"."],
        ["Plebeian Preserver", "Do not lose a Villager in \"Constantine XI (1453).\""],
        ["Vandalized", "Sack Rome by 455 CE in \"Gaiseric (406)\"."],
        ["United We Fall", "Obtain four allies before the Mongols arrive in \"Mstislav (1203)\"."],
        ["Age of Vikings", "Find all Viking heroes in \"Ironside (859)\"."],
        ["Generational Ambitions", "Achieve all of a leader's ambitions in \"Seljuk (985)\"."],
        ["Bread and Circuses", "Support the winning chariot team in \"Komnenos (1081)\"."],
        ["Galleon Bling", "Capture a Spanish Galleon in \"Drake (1572)\"."],
        ["So Epic", "Complete all 50 Saga objectives in \"Ragnar (850)\"."],
        ["Civis Romanus", "Do not lose a city in \"Vortigern (440)\"."],
        ["Seeds of Their Own Destruction", "Win \"Vortigern (440)\" after recruiting Saxon Foederati twelve times."],
        ["A Most Convenient Death", "Ensure Carloman dies in \"Charlemagne (768).\""],
        ["Faster Than a Speeding Cannonball", "Kill Constantine XI and capture the Hagia Sophia before 15 May 1453 in \"Fetih (1453)\"."],
        ["Trust No One", "Win \"Robert (921)\" by attacking and defeating all dukes and the King of the Franks."],
        ["Coup D'état", "Win \"Robert (921)\" by gaining the support of at least three dukes."],
        ["Saxon Revenge", "Defeat West Francia in \"Otto (936)\"."],
        ["Shogun", "Win \"Nobunaga (1551)\" on Hard difficulty with any faction."],
        ["Nemesis", "Finish the entire Chronicles: Battle for Greece campaign."],
        ["Enter the Epic", "Complete \"Prologue: Gates of the Gods\"."],
        ["Leader of Men", "Attain all available aura upgrades in the Battle for Greece campaign."],
        ["Fight in the Shade", "Survive at Thermopylae for 5 minutes after completing the main objective in \"The Hot Gates\"."],
        ["First Citizen", "Complete \"Within the Long Walls\" without your favor ever dropping below 50."],
        ["All Accounted For", "Do not lose a single resource cart in \"Greeks Bearing Gifts\"."],
        ["A Suitable Satrap", "Complete \"The Ionian Revolt\" without Aristagoras ever holding more than four towns simultaneously."],
        ["Friend of Artemisia", "Assist Artemisia in both \"Chasing Smoke\" and \"Earth and Water\"."],
        ["The Great King's Wrath", "Defeat all enemy players in \"Earth and Water\""],
        ["Marathonomachos", "Find and complete all quests in \"The Battle of Marathon\"."],
        ["Admirable Admiral", "Research all naval technologies in \"Raise the Sails\"."],
        ["Thundering Zeus!", "Do not lose a single Market or Port in Byzantium during \"Wrath of the Regent\"."],
        ["Friend of the Helots", "Complete \"Pyres on the Coast\" without looting any Messenian tombs."],
        ["Tomb Raider", "Complete \"Pyres on the Coast\" after looting every Messenian tomb."],
        ["Sack and Burn", "Loot Notium, Priene, and the three cities specified by Cyrus in \"Blood and Gold\"."],
        ["Crisis Management", "Complete \"The Fruits of Empire\" without demanding medium or high tribute."],
        ["Blockade Breaker", "Destroy both naval blockades in \"Divine Salamis\"."],
        ["Philolacon", "Give a relic to the Spartans in both \"Across the Wine-Dark Sea\" and \"Wrath of the Regent\"."],
        ["Reject the Regent", "Give a relic to Salamis in \"Across the Wine-Dark Sea\" and to Polycritus in \"Wrath of the Regent\"."],
        ["Combined Arms", "Complete \"The Fall of Athens\" without researching any special infantry technologies."],
        ["By Ahuramazda's Grace", "Research an Achaemenid Town Center upgrade."],
        ["Political Animal", "Change your policy as the Athenians."],
        ["Promachos", "Kill 10 enemy units with a Spartan Polemarch."],
        ["Achaemenid Victory", "Win a game playing as the Achaemenid in Chronicles: Battle for Greece."],
        ["Athenian Victory", "Win a game playing as the Athenians in Chronicles: Battle for Greece."],
        ["Spartan Victory", "Win a game playing as the Spartans in Chronicles: Battle for Greece."],
        ["But It's Provocative", "Provoke Fu Jian before he is ready in \"Xie An (383)\""],
        ["Wei Victory", "Win a game playing as the Wei."],
        ["Shu Victory", "Win a game playing as the Shu."],
        ["Wu Victory", "Win a game playing as the Wu."],
        ["The Imperial Uncle", "Complete the Liu Bei campaign."],
        ["A Hero Comes; He Gains Renown", "Use one of your heroes' active abilities in Liu Bei 1."],
        ["Awaken the Dragon", "Deploy Zhuge Liang's fire trap in Liu Bei 3."],
        ["Man of the People", "Bring all Civilian Carriages to Sun Quan in Liu Bei 4."],
        ["Hero of Chaos", "Complete the Cao Cao campaign."],
        ["Horses for Courses", "Train no military units aside from mounted units in Cao Cao 1."],
        ["Like Taking Candy From A Baby", "Take Ye before defeating any of the brothers in Cao Cao 4."],
        ["Do Not Pursue Lü Bu", "Defeat Lü Bu before 20 minutes have elapsed in Cao Cao 2."],
        ["King of the Southlands", "Complete the Sun Clan campaign."],
        ["The Tiger of Jiangdong", "Defeat Dong Zhuo's Raiders in Sun Clan 1."],
        ["The Little Conqueror", "Defeat the White Tiger in Sun Clan 3."],
        ["I Am Coming For You, Liu Biao", "Capture all Castles in Sun Clan 4."],
        ["Drive-By Barrage", "Build 20 War Chariots as the Shu."],
        ["Shu'ing Enemies", "Kill 50 units with White Feather Guards as the Shu."],
        ["Time for a Raise", "Fully promote 10 Tiger Cavalry as the Wei."],
        ["Wei March on Our Stomachs", "Generate 5000 food with Tuntian as the Wei."],
        ["Acid Rain", "Destroy 20 buildings with Fire Archers as the Wu."],
        ["Dare to Die", "Re-equip 20 shields with Jian Swordsmen as the Wu."],
        ["Jurchens Victory", "Win a game playing as the Jurchens."],
        ["Khitans Victory", "Win a game playing as the Khitans."],
        ["Fireworks Show", "Fire 100 projectiles with Rocket Carts."],
        ["I'm On Fire... Fireball!", "Kill 50 units with Fire Lancers' charged attacks."],
        ["I Am the Storm", "Do 10000 damage with Grenadiers and Rocket Carts with Thunderclap Bombs researched as the Jurchens."],
        ["Steppe People", "Build 50 Pastures as the Khitans."],
        ["Iron Army", "Block 100 attacks with Iron Pagodas as the Jurchens."],
        ["Medieval Slasher", "Kill 50 units with Liao Daos as the Khitans."],
        ["The Great", "Finish the entire Chronicles: Alexander the Great campaign."],
        ["More Danger, More Glory", "Always side with Cleitus in \"Let the Prince Decide\"."],
        ["Basileus", "Reach 100 Legitimacy in \"Right to Rule\"."],
        ["Blood in the Streets", "In \"Woe unto Thebes\", capture all four Theban landmarks as Alexander in under 25 minutes."],
        ["Supply Surplus", "Gather the required resources in under 25 minutes in \"The Cilician Gates\"."],
        ["Alexandria Eschate", "Fully upgrade every district in \"The City at the End of the World\"."],
        ["Amphibious Assault", "In \"The Battle of the Hydaspes\", hold every landing zone simultaneously."],
        ["Chokehold", "Complete \"No Escape\" without allowing more than half of the specified number of Cathaeans to escape."],
        ["Indica", "Complete the Indica (discover all events) and gather all treasures in \"A Voyage of Discovery\"."],
        ["Sing, Goddess, the Wrath of Alexander", "Defeat all 4 Cossaean Tribes in \"Wrath\"."],
        ["Macedonian Victory (Chronicles)", "Win a game playing as the Macedonians in Chronicles: Alexander the Great."],
        ["Thracian Victory", "Win a game playing as the Thracians."],
        ["Puru Victory", "Win a game playing as the Puru."],
        ["Chile Con Carnage", "Complete the Lautaro campaign."],
        ["Homeland Insecurity", "Always have at least three allied villages under your control in \"Gods of Death and Terror\"."],
        ["Our Little Ponies", "Bring all 25 horses to the allied corral in \"The Battle of Tucapel."],
        ["Golden Paths", "Complete the El Dorado campaign."],
        ["One Does Not Simply Take Iraca", "Do not allow your enemy to ever win the state of Iraca over to their side in \"Zipa and Zaque.\""],
        ["Expedition Impossible", "Defeat Quesada's and Federmann's expeditions in \"The Golden King\" before the timer runs out."],
        ["Warden of the Jungle", "Complete the Arariboia campaign."],
        ["Dynamite Deluxe", "Find and blow up all gunpowder barrels in \"Up in Smoke\"."],
        ["Tupi or not Tupi", "Win the mission \"Exodus\" without losing more than 3 refugee carts."],
        ["Mapuche Victory", "Win a game playing as the Mapuche."],
        ["Muisca Victory", "Win a game playing as the Muisca."],
        ["Tupi Victory", "Win a game playing as the Tupi."],
        ["Surveillance Network", "Construct 10 Outposts with Champi Warriors."],
    ];

    assert.strictEqual(officialAchievements.length, 357, "sanity check on this test's own reference list");

    const dataPairs = ageOfEmpires2De.achievements
        .map(a => [a.name, a.description])
        .sort((a, b) => a[0].localeCompare(b[0]));

    const expectedPairs = [...officialAchievements].sort((a, b) => a[0].localeCompare(b[0]));

    assert.deepStrictEqual(dataPairs, expectedPairs);

});
