import { test } from "node:test";
import assert from "node:assert";

import { getPlannerData } from "../utils/plannerCatalog.js";

// backend/catalog/games/civilization-5.json - 286 real achievements sourced
// from a live ISteamUserStats/GetSchemaForGame/v2 response for appid
// 8930 (fetched through this app's own services/steamApi.js).
// This game has no hidden achievements: all 286 ship a real, official
// Steam description, quoted verbatim below.
// difficulty/estimatedTime/missable remain curatorial judgments.
const game = getPlannerData("civilization-5");

test("getPlannerData('civilization-5') returns real planner data with 286 curated achievements", () => {

    assert.ok(game, "expected real planner data for civilization-5");
    assert.ok(Array.isArray(game.achievements));
    assert.strictEqual(game.achievements.length, 286);

});

test("every Sid Meier's Civilization V achievement has a unique id from 1 to 286 and a unique apiname", () => {

    const ids = game.achievements.map(a => a.id);
    const apinames = game.achievements.map(a => a.apiname);

    assert.deepStrictEqual([...ids].sort((a, b) => a - b), Array.from({ length: 286 }, (_, i) => i + 1));
    assert.strictEqual(new Set(ids).size, 286);
    assert.strictEqual(new Set(apinames).size, 286);

});

test("every Sid Meier's Civilization V achievement has a valid difficulty (1-5), a positive estimatedTime, and non-empty name/description", () => {

    for (const achievement of game.achievements) {

        assert.ok(
            Number.isInteger(achievement.difficulty) && achievement.difficulty >= 1 && achievement.difficulty <= 5,
            `${achievement.name} has an out-of-range difficulty: ${achievement.difficulty}`
        );

        assert.ok(
            Number.isInteger(achievement.estimatedTime) && achievement.estimatedTime > 0,
            `${achievement.name} has an invalid estimatedTime: ${achievement.estimatedTime}`
        );

        assert.ok(achievement.name?.length > 0, "achievement is missing a name");
        assert.ok(achievement.description?.length > 0, `${achievement.name} is missing a description`);
        assert.ok(achievement.apiname?.length > 0, `${achievement.name} is missing an apiname`);

    }

});

test("every one of the 286 Sid Meier's Civilization V achievement name+description pairs matches the live GetSchemaForGame response", () => {

    const officialAchievements = [
        ["A Magnificent Victory", "Beat the game on any difficulty setting as Suleiman."],
        ["A Righteous Victory", "Win on Immortal"],
        ["A Woman's Work", "Beat the game on any difficulty setting as Wu Zetian."],
        ["Access Denied", "Construct the Great Firewall Wonder."],
        ["Age of Empire", "Beat the game on any difficulty setting as Darius."],
        ["All Aboard the Orient Express", "Discover a route to the Orient."],
        ["All Roads Lead to Rome", "Build a road with a Roman Legion."],
        ["All-Achieving Zeus", "Win on Deity in the Wonders of the Ancient World scenario."],
        ["Amongst the Catacombs of Nephren-Ka", "Beat the game on any difficulty setting as Ramesses II."],
        ["Apocalypse Now", "As the Maya, nuke a city in the year 2012."],
        ["Arab Trader", "Trade a luxury resource to another Civ that you earned through a city with a Bazaar."],
        ["Arabian Knights", "Beat the game on any difficulty setting as Harun al-Rashid."],
        ["Artistic License", "Fully explore the Aesthetics Policy track."],
        ["Au in the EU", "Return a Treasure to Europe."],
        ["Austrian Succession", "Beat the game on any difficulty as Maria Theresa."],
        ["Axis Powered", "Win a Diplomatic Victory using the Autocracy Ideology."],
        ["Baby Steps", "Beat the game on the Settler difficulty level."],
        ["Baktun the Future", "Beat the game on any difficulty as Pacal."],
        ["Barbarian Warlord", "As Bismarck, convert the Barbarians from 10 camps to your side."],
        ["Barbary Pirate", "As Suleiman, accumulate a navy with 10 Barbarian naval units."],
        ["Battlefield Earth", "Beat the game on an Earth-type Map."],
        ["Better Red Than Dead", "Win a Conquest Victory using the Order Ideology."],
        ["Blood and Iron", "Beat the game on any difficulty setting as Bismarck."],
        ["Bollywood", "As Gandhi, win a cultural victory with 3 or fewer cities in your empire."],
        ["Bolt and Arrow", "Build Statue of Zeus and Temple of Artemis in the same city"],
        ["Book 'em Danno!", "Find Hawaii in a random map game"],
        ["Bora! Bora! Bora!", "Win as Tahiti"],
        ["Bright-Eyed Athena", "Win on Immortal in the Wonders of the Ancient World scenario."],
        ["British Invasion", "Perform a Concert Tour with an English Great Musician in American territory."],
        ["Built in (Almost) a Day", "Complete a Wonder in a city with three Trade Routes supplying production to it."],
        ["By the Waters of Babylon", "Beat the game on any difficulty setting as Nebuchadnezzar II."],
        ["Capture of Brielle", "Capture a Spanish Coastal City with a Dutch Sea Beggar."],
        ["Celtic Thunder", "Beat the game on any difficulty as Boudicca."],
        ["Charming.  Really.", "Beat the game on the Prince difficulty level."],
        ["City of Gold", "Develop a city to produce more than 100 gold per turn."],
        ["City of Lights", "Develop a city to produce more than 100 culture per turn."],
        ["City of Science", "Develop a city to produce more than 100 science per turn."],
        ["Colonize This!", "Beat the game on any difficulty as Haile Selassie."],
        ["Conquest of the World", "As Alexander, defeat every known player by 350 BC."],
        ["Dancer, Actress, Empress, Victor", "Beat the game on any difficulty as Empress Theodora."],
        ["Dark Horse", "Win a Diplomatic Victory without ever being the host of the World Congress."],
        ["Death Before Shame", "Fully Explore the Honor Policy Track."],
        ["Defender of the Faith", "Beat the game on any difficulty as Gustavus Adolphus."],
        ["Diplomacy by Other Means", "Fully Explore the Autocracy Policy Track."],
        ["Discoverer", "Playing as Italy in Scramble for Africa, earn the VP for finding two Natural Wonders."],
        ["Do you have a little Captain in you?", "Encounter Captain Cook"],
        ["Do You Want to Super Size That?", "Beat the game on a Large Map."],
        ["Double KO", "Capture both Rome and Constantinople in the same game in the Fall of Rome scenario."],
        ["Dr Livingstone I presume?", "Playing as Belgium, move your Stanley Explorer to within a tile of England’s Livingstone Explorer."],
        ["Dr. Heidegger's Experiment", "Find the Fountain of Youth"],
        ["Dragon Emperor", "Win on Emperor"],
        ["Eighty-Eight Miles per Hour", "Fully Explore the Rationalism Policy Track."],
        ["Emperor Fu Manchu", "Win as Manchu"],
        ["Empire of the East", "Beat the game on any difficulty setting as Ramkhamhaeng."],
        ["Enemy Blade No More", "As Indonesia, capture an enemy capital with a Kris Swordsman with the Enemy Blade promotion."],
        ["Engineer", "Build a Wonder."],
        ["Enlightened Ruler", "Unlock all Social Policies, across any number of playthroughs."],
        ["Epic Gilgamesh", "Win as Gilgamesh in the Wonders of the Ancient World scenario."],
        ["Et tu, Brute", "Win the Fall of Rome scenario."],
        ["Everybody Wants to Rule the World", "Win a Conquest Victory using the Autocracy Ideology."],
        ["Expansionist", "Download a Mod."],
        ["Experimenter", "Play a game with a Mod."],
        ["Exterminate! Exterminate!", "Win a Domination Victory."],
        ["Far-Shooting Apollo", "Win on Emperor in the Wonders of the Ancient World scenario."],
        ["Fear the Turtle", "Win the Korean Scenario as Korea"],
        ["Fetchez la Vache!", "Build a motte and bailey improvement"],
        ["First in the Hearts of Your Countrymen", "Beat the game on any difficulty setting as Washington."],
        ["First of the Mohicans", "Beat the game on any difficulty setting as Hiawatha."],
        ["Flawless Strategy", "Beat the game on the Deity difficulty level."],
        ["Flip-Flop", "Propose to repeal an active Resolution which you had originally proposed to enact."],
        ["Flying Fortress", "Bomb an enemy city with a B-17."],
        ["Forty-Niner", "Build 1000 mines, across any number of playthroughs."],
        ["Freedom Isn't Free", "Fully Explore the Freedom Policy Track."],
        ["From Archaemennid to Safavid", "As Darius, start 5 Golden Ages in a single game."],
        ["From Russia with Love", "As Russia, kill an English Spy."],
        ["Gad Zeus!", "Found a Pantheon."],
        ["Games Without Frontiers", "Win a Diplomatic Victory using the Freedom Ideology."],
        ["Gardens of Lake Texcoco", "Build a Floating Garden in a city with a lake tile in its radius."],
        ["Genghis Khan", "Beat the Mongol scenario on the Deity difficulty level."],
        ["Gentlemen's Agreement", "Share intrigue with another player in the Empires of the Smoky Skies scenario."],
        ["Gimme Your Lunch Money!", "Bully 3000 gold from City-States across any number of playthroughs."],
        ["Give Peace a Chance", "Beat the game on any difficulty setting as Gandhi."],
        ["Glory, glory, hallelujah!", "Win the Civil War scenario playing as the Union."],
        ["Go Boldly Where No Man Has Gone Before", "Win a Space Victory."],
        ["God Is Great", "Construct 1000 Temples, across any number of playthroughs."],
        ["Going It Old School", "Beat the game on a Pangaea-type Map."],
        ["Gotta Catch 'Em All", "Beat the game on all standard map types and sizes."],
        ["Great Khan", "Beat the Mongol scenario on the King or harder difficulty level.  "],
        ["Grecian Formula", "Win as Alexander in the Wonders of the Ancient World scenario."],
        ["Greed is Good", "Have a city with the Colossus, Petra, a Caravansary, and a Harbor."],
        ["Greek Fire", "As Byzantines, sink 10 Greek ships with a Dromon."],
        ["Hands Free to Victory!", "Beat the game on any difficulty setting as Harald Bluetooth"],
        ["Hannibal’s Crossing", "As Carthage, attack a Roman Unit with an African Forest Elephant from a mountain tile."],
        ["Harder, Better, Faster, Stronger", "Upgrade a Unit."],
        ["He Threw a Car at My Head!", "Have any city ransomed by Barbarians."],
        ["Head and Shoulders Above the Rest", "Win as Samoa"],
        ["Heads Up!", "Find Easter Island in a random map game"],
        ["Herculean Effort", "Complete all International Projects in a single game as the highest contributor."],
        ["Here Ends the Noble Savage", "Raze 100 Barbarian camps, across any number of playthroughs."],
        ["Here's Looking at You, Kid", "As Morocco, airlift a civilian unit from Casablanca to Portugal's original capital."],
        ["Highway Robbery", "Plunder a Caravan Trade Route."],
        ["Holier Than Thou", "Become the dominant Religion in an opponent’s Holy City."],
        ["Holy Father", "Select the Papal Primacy Belief and Ally with 12 City-States."],
        ["Honoring the Ancestors", "Win on Deity"],
        ["Huitzilopochtli's Arrow", "Win the New World Scenario as the Aztecs."],
        ["I Can Has Nukes?", "Drop a Nuke on another Civ."],
        ["I Missed That Day in History Class", "Capture any Sassanid city as the Celts in the Fall of Rome scenario."],
        ["I Need More Elbow Room", "Beat the game on a Tiny Map."],
        ["I Prefer my Africa Scrambled", "Win the Scramble for Africa scenario as any civ on any difficulty."],
        ["I Sunk Your Imperial Capital!", "Capture Rome as the Vandals using a boat in the Fall of Rome scenario."],
        ["I'm on a Boat!", "Embark a Unit."],
        ["In Hoc Signo Vinces", "Beat the game on any difficulty as Maria I."],
        ["Indoctrinated!", "Lose dominant status in your Holy City to an opponent’s Religion."],
        ["Intelligence Network", "Share intrigue with a player who previously shared intrigue with you."],
        ["Island Hopping", "Beat the game on an Archipelago-type Map."],
        ["It Belongs in a Museum", "Have Artifacts from 10 different City-States in the Museums and Wonders in your civilization."],
        ["It satrap!", "Win as Darius I in the Wonders of the Ancient World scenario."],
        ["It's Just You and Me, Kid", "Beat the game on a Duel Map."],
        ["It's Standard Issue", "Beat the game on a Standard Map."],
        ["It's Super Effective", "Destroy an enemy unit in just one hit."],
        ["Junta for Red October", "Use a Spy to successfully stage a City-State coup."],
        ["Kamikaze Attack", "Kill an enemy unit attacking with a Japanese unit with just 1 HP remaining."],
        ["Khaaan!", "Run out of time to beat the Mongol scenario."],
        ["Khan", "Beat the Mongol scenario on any difficulty."],
        ["King of the Mountain", "Beat the game on any difficulty setting as Pachacuti."],
        ["King of the Wisent", "Beat the game on any difficulty as Casimir."],
        ["Know Thy Enemy", "Consult the Oracle 2 times in a single game in the Wonders of the Ancient World scenario."],
        ["Knowledge is Power", "As Assyria, use a Royal Library filled with a Great Work to train a unit that begins with a promotion."],
        ["Kublai Khan", "Beat the Mongol scenario on the Immortal or harder difficulty level.  "],
        ["Land Baron", "Purchase 1000 tiles, across any number of playthroughs."],
        ["Last Man Standing", "Win any Multiplayer Match."],
        ["Law of the Splintered Paddle", "Beat the game on any difficulty setting as Kamehameha."],
        ["League of Extraordinary Hoyanehs", "Win the New World Scenario as the Iroquois."],
        ["Legends of the Hidden Temple", "Fully explore the Exploration Policy track."],
        ["Lingua Franca", "Found the World Congress and remain its host for the entire game."],
        ["Lion of the North", "As Sweden, start a turn with your Great General stacked with a Hakkapelitta."],
        ["Living in Smallville", "Beat the game on a Small Map."],
        ["Longest. Name. Ever.", "Have the city of Llanfairpwllgwyngyll in your empire."],
        ["Losing My Marbles", "Extract 5 Artifacts from the territory of another major civilization."],
        ["Lux Perpetua Luceat Eis", "Fully Explore the Piety Policy Track."],
        ["Macho Picchu", "Win the New World Scenario as the Incas."],
        ["Magellan", "Prove that the world is round by uncovering a connected loop of tiles around the circumference of the world."],
        ["Marco Polo", "Be the first to explore and uncover 1000 tiles, across any number of playthroughs."],
        ["Master of the House", "Fully Explore the Tradition Policy Track."],
        ["Master of the Universe", "Beat the game on any difficulty setting with each leader."],
        ["Mehmet the Conqueror", "As the Turks, conquer Istanbul on Deity in the Into the Renaissance scenario."],
        ["Merchant King", "Trade 100 resources, across any number of playthroughs."],
        ["Merchant Prince", "Generate 200 gold per turn via Trade Routes."],
        ["Missionary Man", "Spread your Religion to an opponent with a Missionary."],
        ["Model of a Modern Major-General", "Train all Units, across any number of playthroughs."],
        ["Modern Major-General", "Win the Empires of the Smoky Skies scenario."],
        ["Money Doesn't Grow on Trees", "Fully Explore the Commerce Policy Track."],
        ["Montezuma's Revenge…", "Beat the game on any difficulty setting as Montezuma."],
        ["Moving on Up", "Earn a Unit Promotion."],
        ["My Little Pony", "As Catherine, research Horseback Riding before any other Civ."],
        ["Neighborhood Bully", "Annex a previously puppetted City-State."],
        ["Never take our freedom!", "Win as the Celts on Emperor or above in the Into the Renaissance scenario."],
        ["Ngata Chance", "Win as Tonga"],
        ["Nigerian Bank Account", "In Scramble for Africa, marry Sokoto or Bornu."],
        ["No White Flag Here", "Beat the game on any difficulty as Dido."],
        ["Nobody Expects the Spanish Inquisition", "Beat the game on any difficulty setting as Isabella."],
        ["Nobody expects...", "As Spain, use an Inquisitor to remove another Religion."],
        ["Odin's Chosen Warrior", "Win as Denmark (any difficulty)"],
        ["Odysseus the Great Tactician", "Win on King in the Wonders of the Ancient World scenario."],
        ["One Small Step", "Win a Space Victory using the Freedom Ideology."],
        ["One to Rule Them All", "Beat the game on any difficulty setting with only one city."],
        ["Ottoman Carpentry", "Win the Scramble for Africa playing as the Ottomans on Deity."],
        ["Panzer \"Shafernator\" General", "Spawn over 100 Great Generals, build an army of over 100 standing units, and beat the game 100 times."],
        ["Party in hattUSA", "Win as Muwatallis in the Wonders of the Ancient World scenario."],
        ["Paul Bunyan", "Chop down 1000 forest tiles, across any number of playthroughs."],
        ["Pax Romana Aeternum", "Win the game as Eastern or Western Rome on Deity and have all your original cities under your control in the Fall of Rome scenario."],
        ["Peace and Prosperity", "Begin a Golden Age."],
        ["Pedro's Party People", "Beat the game on any difficulty as Pedro II."],
        ["People of the Longhouse", "Build a longhouse in a city with at least 4 unchopped forests in its radius."],
        ["Pickett's Recharge", "Capture Gettysburg with a Confederate Infantry unit possessing the George Pickett promotion."],
        ["Pillage, Then Burn", "Pillage 9 Farms on the same turn"],
        ["Plate Tectonics", "Beat the game on a Continents-type Map."],
        ["Poland Can into Space", "As Poland, win a Space Victory."],
        ["Praise the Victories", "Win the Scramble for Africa playing as the Boers on Deity."],
        ["Propheteering", "Found a Religion."],
        ["Purple People Eaters", "Win as Norway (any difficulty)"],
        ["Pyramid Scheme", "Playing as France, get the Louvre to the maximum theming bonus of 16."],
        ["Queen of the Adriatic", "Beat the game on any difficulty as Enrico Dandolo."],
        ["Quite Accomplished", "Retain control of the same honourable title for the entire length of the game it is available in the Empires of the Smoky Skies scenario."],
        ["Ra's Mighty Truth", "Win as Ramesses II in the Wonders of the Ancient World scenario."],
        ["Radio Free Europe", "Adopt the Freedom Ideology and fill 10 Broadcast Towers with Great Works."],
        ["Raiders of the Lost Ark", "Have your American Archaeologist extract an Artifact from Egypt with a German Archaeologist within 2 tiles."],
        ["Raleigh's Road to Riches", "Discover El Dorado"],
        ["RAM Usage", "Research Satellites while playing as Attila on a huge map."],
        ["Rastafari Messiah", "As Ethiopia, earn 5 Great Prophets."],
        ["Reconquista Who?", "Win as the Almohads on Emperor or above in the Into the Renaissance scenario."],
        ["Red Badge of Courage", "Win the Civil War scenario on Deity."],
        ["Renaissance Man", "Win the Into the Renaissance scenario."],
        ["Rest in Gold Pieces", "Gain 1000 gold from expended Great People with the Mausoleum of Halicarnassus across any number of playthroughs"],
        ["Reverse Engineer", "Gain possession of 3 Wonders by conquering cities in a single game in the Wonders of the Ancient World scenario."],
        ["Richard the Lionheart", "As England, conquer Jerusalem on Emperor or above in the Into the Renaissance scenario."],
        ["Riddle of the Sphinx", "Rush a Wonder as Egypt with a Great Engineer."],
        ["Rising Sun", "Beat the game on any difficulty setting as Oda."],
        ["Rock the Kasbah", "Perform a Concert Tour with a Great Musician on a Moroccan Kasbah improvement."],
        ["Rocking in the Free World", "Win a Cultural Victory using the Freedom Ideology."],
        ["Ruler of the Seas", "As Elizabeth, sink and destroy 357 enemy naval units, across any number of playthroughs."],
        ["Ruler of the Twelve Colonies ", "Beat the game on a Huge Map."],
        ["Run 50 Miles and Fight a Battle", "As Zulu, have an Impi earn all of the special promotions."],
        ["Sacagawea's Legacy", "As the Shoshone, discover 5 ancient ruins with the same Shoshone Pathfinder."],
        ["Samurai Delicatessen", "Win as Japan"],
        ["Say Hello to My Little Friend", "Reach Ally Status with a City-State."],
        ["Scourge of Everyone", "Beat the game on any difficulty as Attila."],
        ["Searching for the Precious", "Find New Zealand in a random map game"],
        ["Second City", "Found a second city."],
        ["Seoul Power", "Win before 100 turns as any power"],
        ["Seriously?!?", "Have another Civ beat you to completing a Wonder 10 times."],
        ["Sheridan's Valley Campaign", "As Union, control Winchester, Front Royal, Harrisonburg, Staunton, and Lynchburg."],
        ["Siglo de Oro", "Win the New World Scenario as Spain."],
        ["Silent No More", "Beat the game on any difficulty as William of Orange."],
        ["Silk Road", "Connect to the Arabs, China, India, the Mongols, and Persia at the same time using Caravans."],
        ["Sky Admiral", "Destroy an enemy unit with a Flyer based at a Sky Fortress in the Empires of the Smoky Skies scenario."],
        ["Smooth Talking", "Use a Spy to gain influence with a City-State."],
        ["Soma Tablets for Everyone", "Reach a Happiness level of over 100 for your civ."],
        ["Standing like a Stone Wall", "Win the Civil War scenario playing as the Confederates."],
        ["Star of the North", "Beat the game on any difficulty setting as Catherine."],
        ["Sticky Fingers", "Use a Spy to steal Technology from a competitor."],
        ["Strength Through Joy", "Win a Cultural Victory using the Autocracy Ideology."],
        ["Sun Tzu's Art of War", "As Wu Zetian, earn a Great General through battle."],
        ["Supreme Khan", "Beat the Mongol scenario on the Emperor or harder difficulty level.  "],
        ["Surviving Domesday", "Win scenario on Immortal (any civ)"],
        ["Surviving Ragnarok", "Win scenario on Deity (any civ)"],
        ["Surviving the Marquesas", "Win as Hiva"],
        ["Tablet Tech Pioneer", "Beat the game on any difficulty as Ashurbanipal."],
        ["Taekwon-DOH!", "Lose as Korea"],
        ["Taking off the Training Wheels", "Beat the game on the Chieftain difficulty level."],
        ["Tea and Crumpets for Everyone", "Win the New World Scenario as England."],
        ["Team Player", "Fully Explore the Patronage Policy Track."],
        ["Tear Down this Wall!", "Force an AI player with the Order Ideology to switch to Freedom."],
        ["That's XCOM baby!", "Have your XCOM Squad go from 100 health to 0 in a single AI turn."],
        ["The African King", "Beat the game on any difficulty setting as Askia."],
        ["The Alexman", "Beat the game on the Warlord difficulty level."],
        ["The Appian Way", "Build 1000 roads, across any number of playthroughs."],
        ["The Best State of a Republic", "Win a Cultural Victory."],
        ["The Choson One", "Win as Korea"],
        ["The Explorer", "Discover 100 Natural Wonders."],
        ["The Golden Horde", "Beat the game on any difficulty setting as Genghis Khan."],
        ["The Golden Path", "Beat the game on the Emperor difficulty level."],
        ["The Great Betrayal", "As Venice, capture the Holy City of the religion that the city of Venice follows."],
        ["The Great Spirit", "Beat the game on any difficulty as Pocatello."],
        ["The Java Script", "Beat the game on any difficulty as Gajah Mada."],
        ["The Last Crusade", "Capture the city that built Petra using a Landship."],
        ["The Man Who Would Be King", "Beat the game on any difficulty setting as Alexander."],
        ["The Once and Future King", "Beat the game on the King difficulty level."],
        ["The Pen is Mightier", "Win a Diplomatic Victory."],
        ["The Rhodes Colossus", "Playing as England in Scramble for Africa, complete a railroad from Cairo to Capetown."],
        ["The Wonder Years", "Build all the Wonders, across any number of playthroughs."],
        ["The World Is a Mess, and I Just Need to Rule It", "Beat the game on the Immortal difficulty level."],
        ["The Yokes on the Mongols", "Win as Russia on Emperor or above in the Into the Renaissance scenario."],
        ["This Desert Life", "Beat the game on any difficulty as Ahmad Al ’Mansur."],
        ["This isn't Kansas", "Find Australia in a South Pacific map game"],
        ["This was their Finest Hour", "Win as Anglo-Saxon England (any difficulty)"],
        ["Thoughtful Telemachus", "Win on Prince in the Wonders of the Ancient World scenario."],
        ["Three Musketeers", "Kill a unit with a French Musketeer when two other Musketeers are providing flanking bonuses."],
        ["Time to Stitch a Tapestry", "Win as Normandy (any difficulty)"],
        ["To Stand the Test of Time", "Beat the game with all victory conditions."],
        ["Tomb Raider", "Pillage gold from an Egyptian city with a burial tomb in it."],
        ["Tout le Monde Francophone?", "Win the New World Scenario as France."],
        ["Treasure Hunter", "Discover an ancient ruin."],
        ["Turks Shmurks!", "Capture Constantinople as any enemy power in the Fall of Rome scenario."],
        ["Turtle Power", "Sink an Ironclad with a Turtle Boat"],
        ["Two Men Enter, One Man Leave", "Completely defeat another Civ and remove them from the game."],
        ["Veni, Vidi, Vici", "Beat the game on any difficulty setting as Caesar."],
        ["Video et Taceo", "Beat the game on any difficulty setting as Elizabeth."],
        ["Vivre La Revolution", "Beat the game on any difficulty setting as Napoleon."],
        ["Vote for Pedro", "As Brazil, win a Diplomatic Victory."],
        ["Wanna Be the King of the Zulus", "Beat the game on any difficulty as Shaka."],
        ["War Canoe Attack", "As Askia, conquer a city on another continent."],
        ["We are Family", "Become the dominant Religion in every Capital city on a standard-size or larger map."],
        ["We Have the Technology", "Fully explore the Tech Tree."],
        ["Whack a Mole", "Find and kill an enemy Spy."],
        ["What's Yours is Mine", "As Portugal, construct a Feitoria in a City-State that is allied to another civilization."],
        ["Where's the Biathlon?", "Enter a snow tile with the Norwegian ski infantry"],
        ["With an Iron Fist", "Fully Explore the Order Policy Track."],
        ["With Liberty and Justice for All", "Fully Explore the Liberty Policy Track."],
        ["Wonderwall", "Build 3 Wonders in the same city in the Wonders of the Ancient World scenario."],
        ["Workers of the World - Unite!", "Win a Cultural Victory using the Order Ideology."],
        ["Yoink!", "As Austria, acquire a City-State with 15 or more units through Diplomatic Marriage."],
        ["You The Conqueror", "Win scenario on Emperor (any civ)"],
        ["Yow Ming!", "Win as China"],
        ["Yuri-ka!", "Win a Space Victory using the Order Ideology."],
        ["Zeupiter", "As Rome, conquer a city with the Statue of Zeus"],
    ];

    assert.strictEqual(officialAchievements.length, 286, "sanity check on this test's own reference list");

    const dataPairs = game.achievements
        .map(a => [a.name, a.description])
        .sort((a, b) => a[0].localeCompare(b[0]));

    const expectedPairs = [...officialAchievements].sort((a, b) => a[0].localeCompare(b[0]));

    assert.deepStrictEqual(dataPairs, expectedPairs);

});
