import { test } from "node:test";
import assert from "node:assert";

import { getPlannerData } from "../utils/plannerCatalog.js";

// backend/catalog/games/civilization-vi.json - 320 real achievements sourced
// from a live ISteamUserStats/GetSchemaForGame/v2 response for appid
// 289070 (fetched through this app's own services/steamApi.js).
// All 320 ship a real, official Steam description. Civilization VI has no
// Steam-hidden achievements.
// difficulty/estimatedTime remain curatorial judgments, same convention
// as every other planner difficulty/time field in this catalog.
const civilizationVi = getPlannerData("civilization-vi");

test("getPlannerData('civilization-vi') returns real planner data with 320 curated achievements", () => {

    assert.ok(civilizationVi, "expected real planner data for civilization-vi");
    assert.ok(Array.isArray(civilizationVi.achievements));
    assert.strictEqual(civilizationVi.achievements.length, 320);

});

test("every Civilization VI achievement has a unique id from 1 to 320 and a unique apiname", () => {

    const ids = civilizationVi.achievements.map(a => a.id);
    const apinames = civilizationVi.achievements.map(a => a.apiname);

    assert.deepStrictEqual([...ids].sort((a, b) => a - b), Array.from({ length: 320 }, (_, i) => i + 1));
    assert.strictEqual(new Set(ids).size, 320);
    assert.strictEqual(new Set(apinames).size, 320);

});

test("every Civilization VI achievement has a valid difficulty (1-5), a positive estimatedTime, and non-empty name/description", () => {

    for (const achievement of civilizationVi.achievements) {

        assert.ok(
            Number.isInteger(achievement.difficulty) && achievement.difficulty >= 1 && achievement.difficulty <= 5,
            `${achievement.name} has an out-of-range difficulty: ${achievement.difficulty}`
        );

        assert.ok(
            Number.isInteger(achievement.estimatedTime) && achievement.estimatedTime > 0,
            `${achievement.name} has an invalid estimatedTime: ${achievement.estimatedTime}`
        );

        assert.ok(achievement.name?.length > 0, "achievement is missing a name");
        assert.ok(achievement.description?.length > 0, `${achievement.name} is missing a description`);
        assert.ok(achievement.apiname?.length > 0, `${achievement.name} is missing an apiname`);

    }

});

test("every one of the 320 official Civilization VI achievement name+description pairs matches the live GetSchemaForGame response", () => {

    const officialAchievements = [
        ["Game, Settler, Match", "Win a regular game at Settler difficulty or harder"],
        ["Irish Heartbeat", "Win a regular game at Chieftain difficulty or harder"],
        ["Warlording Over Others", "Win a regular game at Warlord difficulty or harder"],
        ["Machiavelli's Great Work", "Win a regular game at Prince difficulty or harder"],
        ["The Divine Right of Kings", "Win a regular game at King difficulty or harder"],
        ["Emperor's New Groove", "Win a regular game at Emperor difficulty or harder"],
        ["12 Labors of Hercules", "Win a regular game at Immortal difficulty or harder"],
        ["God-Like", "Win a regular game at Deity difficulty"],
        ["Mission to Mars", "Win a regular game with a Science victory on any difficulty with any leader"],
        ["Nirvana", "Win a regular game with a Religious victory on any difficulty with any leader"],
        ["Buying Your Blue Jeans and Listening to Your Pop Music", "Win a regular game with a Culture victory on any difficulty with any leader"],
        ["Veni, vidi, vici", "Win a regular game with a Domination victory on any difficulty with any leader"],
        ["Crusader King", "Win a regular game as Frederick Barbarossa"],
        ["Valois Dynasty", "Win a regular game as Catherine De Medici"],
        ["Daughter of Isis", "Win a regular game as Cleopatra"],
        ["Be the Change You Wish to See In the World", "Win a regular game as Gandhi"],
        ["First to Civilize", "Win a regular game as Gilgamesh"],
        ["For Sparta!!!", "Win a regular game as Gorgo"],
        ["Varangian Guard", "Win a regular game as Harald Hardrada"],
        ["Katsu!", "Win a regular game as Hojo Tokimune"],
        ["Montezuma's Revenge", "Win a regular game as Montezuma"],
        ["Mwene Kongo", "Win a regular game as Mvemba a Nzinga"],
        ["Emperor of Brazil", "Win a regular game as Pedro II"],
        ["Oratorical Skills", "Win a regular game as Pericles"],
        ["Bronze Horseman", "Win a regular game as Peter the Great"],
        ["Non Sufficit Orbis", "Win a regular game as Philip II"],
        ["Elixir of Immortality", "Win a regular game as Qin Shi Huang"],
        ["Sultan of Egypt", "Win a regular game as Saladin"],
        ["Warrior Queen", "Win a regular game as Tomyris"],
        ["Rome If You Want To", "Win a regular game as Trajan"],
        ["Let Teddy Win", "Win a regular game as Theodore Roosevelt"],
        ["I Am Amused", "Win a regular game as Victoria"],
        ["Gift From the Storm God", "Receive a Strategic Resource from Hattusa"],
        ["Legends of the Hidden Temple", "Build a Colossal Head adjacent to a Holy Site with a Temple."],
        ["Army of Cthulhu", "Levy the military of Nan Madol"],
        ["100th Anniversary", "As America make a National Park of Crater Lake and both tiles of Yosemite in one game"],
        ["Arabian Knights", "Conquer a city with a Mamluk"],
        ["Huey Tlatoani", "As Aztecs on a standard-sized map, attack an opponent while receiving a +16 Combat Strength bonus for having all of the luxuries"],
        ["2016 Ready", "Playing as Brazil, complete both Estadio Do Maracana and Christo Redentor in one city"],
        ["Crouching Tiger Hidden Cannon", "Playing as China, end a turn with 5 Crouching Tigers on Great Wall tiles"],
        ["Walk Like an Egyptian", "As Egypt build a Sphinx adjacent to the Pyramids both on Desert Floodplains"],
        ["Flight Slingulator", "Airlift a level 3 Slinger"],
        ["For Queen and Country", "Playing as England on a Huge map, have a city on every continent at the start of the turn"],
        ["Loire Valley", "Create 5 Châteaux in one city with the Wine resource."],
        ["Third Crusade", "Playing as Frederick Barbarossa, conquer the city-state of Jerusalem"],
        ["12 Olympians", "Have 12 Policy Slots as Greece"],
        ["Give Peace a Chance", "Playing as India on a Huge map, receive +35 Faith in one turn from the Satyagraha ability"],
        ["Meiji Restoration", "Playing as Japan, have a district with 6 adjacent unpillaged districts"],
        ["City of Kongo", "Playing as Kongo, have a capital city with a population of 30"],
        ["Viking Raid", "Capture a settler with a Viking Longship"],
        ["Missed That Day in History Class", "Clear nuclear contamination with a Roman Legion"],
        ["Trans-Siberian Railroad", "Playing as Russia, have a city that is at least 60 tiles away from your capital, connected by a Trade Route and road at the start of the turn."],
        ["Scythian Horse Rush", "Playing as Scythia have 10 Saka Horse Archers in your army"],
        ["Nobody Expects the Spanish Inquisition", "Launch an Inquisition as Spain"],
        ["Epic of Gilgamesh", "As Sumeria, have the first Great Work of Writing"],
        ["The Origin of Species", "Activate Darwin adjacent to the Galapagos Islands"],
        ["Oneth By Land Twoeth By Sea", "Have an Army of land Units and 2 Armadas"],
        ["Here's Looking At You Kid", "Win a regular game on a Duel Map"],
        ["Four Corners Offense", "Win a regular game on a Tiny Map"],
        ["Six Shooter", "Win a regular game on a Small Map"],
        ["Eight is Enough", "Win a regular game on a Standard Map"],
        ["Ten Commandments", "Win a regular game on a Large Map"],
        ["Dirty Dozen", "Win a regular game on a Huge Map"],
        ["Tectonic Shift", "Win a regular game on the Continents Map"],
        ["Mare Nostrum", "Win a regular game on the Inland Sea Map"],
        ["The Taste of Victory", "Win a regular game on the Island Plates Map"],
        ["Riffle and Bridge", "Win a regular game on the Shuffle Map"],
        ["Alfred Wegener's Legacy", "Win a regular game on the Pangaea Map"],
        ["Archimedes Bath", "Get 5 Tech boosts in 1 turn"],
        ["Civ 6 Civets System", "Get 5 Civic boosts in 1 turn"],
        ["Luftballons", "Use a bomber class unit to detonate a nuclear device, as long as its base and 9 Observation Balloons are located on the continent of Nena at the time of detonation."],
        ["Pizza Party!", "Activate Leonardo da Vinci in New York with Great Works from Michelangelo and Donatello -- and a sewer -- all in that city"],
        ["Seven Wonders of the Post-Apocalyptic World", "Launch a weapon of mass destruction and have it pillage seven wonders"],
        ["Repo Man", "Steal a Great Work of Art and don't get caught"],
        ["District 12", "Build every district type in one city and the Colosseum"],
        ["Land Party", "Play a multiplayer game"],
        ["Escort Service", "Put two units into a formation"],
        ["If You Build It, They Will Come", "Have 6 Improvements at one time."],
        ["Voyage of the Mayflower", "Found or conquer a city on a different continent"],
        ["Everything is Awesome!!!", "At the start of the turn have an Ecstatic city."],
        ["Investment Banking", "Have an enemy city under siege at the start of the turn"],
        ["A Case for War", "Declare a formal war"],
        ["Naming Rights", "Name a unit"],
        ["A Revolution Without Dancing", "Change your government"],
        ["Secret Service", "Have top secret access with five civilizations in one game at once."],
        ["Silver Anniversary", "Possess 6 Silver luxury resources at the start of the turn"],
        ["New Orleans Style Spanish Rice", "Become Suzerain of a City-State"],
        ["Man on the Moon", "Win a regular game with a Science victory on any difficulty with any leader with a captured Egyptian city -- having also activated Newton and Darwin"],
        ["We Are The Champions", "Win a regular game with a Religious victory with your dominant religion being Zoroastrianism and at the time of victory you are the Suzerain of Zanzibar"],
        ["Selfie", "Win a regular game with a Culture victory with your leader in the game as your opponent as well"],
        ["Island Hopping", "Win a regular game with a Domination victory on any difficulty with any leader on a Huge Island Plates map."],
        ["The Test of Time", "Win a regular game with an Ancient Era start"],
        ["After Antiquity", "Win a regular game with a Classical Era start"],
        ["Out of the Dark Ages", "Win a regular game with a Medieval Era start"],
        ["Renaissance Man", "Win a regular game with a Renaissance Era start"],
        ["Captain of Industry", "Win a regular game with an Industrial Era start"],
        ["Modern Major General", "Win a regular game with a Modern Era start"],
        ["Splitting the Atom", "Win a regular game with an Atomic Era start"],
        ["Through the Digital Age", "Win a regular game with an Information Era start"],
        ["Unique Snowflake", "Win a regular game on Fractal Map"],
        ["Even Our Castles Have Castles", "Build an Alcazar within 2 tiles of the Alhambra"],
        ["Finn MacCool's Pipe Organ", "Build a Monastery within 2 tiles of the Giant's Causeway"],
        ["What Do You Mean, \"Active Volcano?\"", "Build three Aerodromes within 2 tiles of Eyjafjallajökull"],
        ["Absolutely Nothing Rotten in the State of Denmark", "Win Vikings, Traders, and Raiders! as Canute"],
        ["More Hacksilver For Harald", "Win Vikings, Traders, and Raiders! as Harald Hardrada"],
        ["Master of the Baltic", "Win Vikings, Traders, and Raiders! as Olof Skötkonung"],
        ["God of the Sea", "Win Vikings, Traders, and Raiders! at Deity difficulty"],
        ["Armor of Faith", "Win a regular game as Jadwiga"],
        ["You Are A Terrible Person", "Playing as Poland, destroy another civilization's incomplete wonder by initiating a Culture Bomb"],
        ["Winged Hussar Mastery", "Win Jadwiga's Legacy as Stanislaw Potocki"],
        ["Always Bet On Black", "Win Jadwiga's Legacy as Mikolaj \"the Black\" Radziwill"],
        ["The Grandest of Hetmans", "Win Jadwiga's Legacy as Konstanty Ostrogski"],
        ["God-Like Legacy", "Win Jadwiga's Legacy at Deity difficulty"],
        ["A Smashing Victory", "Win a regular game as John Curtin"],
        ["Wood for Sheep", "Playing as Australia, build a Pasture over Sheep and steal an adjacent player's Lumbermill"],
        ["Revenge of the Banana Benders", "Win Outback Tycoon as Queensland"],
        ["Crow-eater Conquest", "Win Outback Tycoon as South Australia"],
        ["Gumsucker Punch", "Win Outback Tycoon as Victoria"],
        ["Sandgroper Sweep", "Win Outback Tycoon as Western Australia"],
        ["Meanwhile, in Australia", "Win Outback Tycoon at Deity difficulty"],
        ["Quite a Crowded House", "Complete an online multiplayer game of Outback Tycoon"],
        ["Midnight Oil", "Build an Oil Well on the final turn of the Outback Tycoon scenario"],
        ["Attack of the Drop Bear", "Lose a unit to the perils of Australia in the Outback Tycoon scenario"],
        ["Never Lost a Battle", "Win a regular game as Alexander"],
        ["King of the Four Corners of the World", "Win a regular game as Cyrus"],
        ["Greatest Is As Greatest Does", "Playing as Macedon, conquer a city containing both the Great Library and Great Lighthouse wonders"],
        ["Some Wine For Your Soldiers?", "Playing as Persia, conquer the original Scythian capital within 10 turns of declaring a surprise war on Scythia"],
        ["Envoy Convoy", "After building the Apadana wonder, construct 7 additional wonders in the same city"],
        ["No More Worlds To Conquer", "Win Conquests of Alexander on any difficulty"],
        ["You're the Demonstrably Greatest", "Achieve the highest possible rank in Conquests of Alexander at Deity difficulty"],
        ["He Named Them All After Himself?", "Settle four cities in Conquests of Alexander on any difficulty"],
        ["Resplendent Panoply", "Possess all of the following after conquering a city in Conquests of Alexander: Hoplite, Saka Horse Archer, Maryannu Chariot Archer, Immortal, and Varu"],
        ["I Quenched Your Thirst For Blood", "Playing as Scythia, recapture one of your founded cities from Persia"],
        ["gg nub", "Win a regular game as Amanitore"],
        ["Pyramid Scheme", "As Nubia, earn six different adjacency bonuses on a Nubian Pyramid"],
        ["Claim the Fourth Cataract", "Playing as Egypt in a regular game, conquer the original Nubian capital within 10 turns of declaring a formal war on Nubia"],
        ["The 25th Dynasty", "Playing as Nubia, liberate the original Egyptian capital in a liberation war with the capital's conqueror"],
        ["Overclocked Conviction", "After building the Jebel Barkal wonder, earn 28 Faith per turn on its tile"],
        ["More Wind for the Wind God", "Win Gifts of the Nile on any difficulty"],
        ["Total A-Nile-hilation", "Playing Gifts of the Nile as Egypt, win on Deity difficulty"],
        ["That's Some Good Kerma", "Playing Gifts of the Nile as Nubia, win on Deity difficulty"],
        ["Sea of the Bow", "Playing Gifts of the Nile as Nubia, found a coastal city on the Mediterranean Sea"],
        ["From Med to Red to the Land of the Dead", "Playing Gifts of the Nile as Egypt, conquer Irem and Punt"],
        ["Cardamom and Mangos and Elephants", "Win a regular game as Jayavarman VII"],
        ["All Beneath the Wings of Garuda", "Win a regular game as Gitarja"],
        ["What is Mind? No Matter. ", "Win the Path to Nirvana scenario on any difficulty"],
        ["What is Matter? Nevermind. ", "Win the Path to Nirvana scenario on Deity"],
        ["Wat is Love", "Build Angkor Wat and a Wat in Angkor Wat"],
        ["Thalassocratophile ", "Have 5 cities on landmasses 5 or less tiles with Indonesia"],
        ["Try To Snatch the Pebble From My Hand ", "Have a Warrior Monk with 4 Promotions"],
        ["Raid Healer", "With a Guru Heal 7 religious units with one action"],
        ["Many Signs and Wonders ", "Build all 3 Wonders in the Paths to Nirvana scenario"],
        ["Do You Have A Moment To Talk About Salvation?", "Convert 3 opposing Holy Cities in the Paths to Nirvana scenario"],
        ["uSuthu! uSuthu!", "Win a regular game as Shaka"],
        ["A Burning Splendor", "Win a regular game as Chandragupta"],
        ["A small Country, a great people, so sorely tried", "Win a regular game as Queen Wilhelmina"],
        ["Lord of All Who Live in Felt Tents", "Win a regular game as Genghis Khan"],
        ["From Peonies to Doricheon", "Win a regular game as Queen Seondeok"],
        ["Let gentle blood shew generous might", "Win a regular game as Robert the Bruce"],
        ["Radiant Deeds, Bright as Sunshine", "Win a regular game as Tamar"],
        ["Deeds of a Monarch-Scorning People", "Win a regular game as Lautaro"],
        ["Justice and Lasting Peace", "Win a regular game as Poundmaker"],
        ["Master and Commander", "Win a regular game on the Archipelago Map"],
        ["Reverse Colonialism", "As Lautaro, capture Philip II's original capital city "],
        ["Buying your Deels and Listening to Your Throat Singing", "As Genghis, win a Cultural Victory"],
        ["Triple Seven", "As Wilhelmina, have seven cities and seven Zeven de Provincien at the start of the turn"],
        ["Mulligan", "Build a Golf Course in a tile where you had previously attempted to build a Wonder, but got beaten to the Wonder by another Civ"],
        ["Adamantine Confederacy", "As Poundmaker, have an active Alliance of every type"],
        ["I Thought We'd Moved Past This Joke", "As Chandragupta, launch a nuclear weapon"],
        ["Advanced Seminar in Astrophysics", "As Seondeok, build a Spaceport district next to a Seowon"],
        ["Ibutho", "As Shaka, train a Corps of Impi using the Ikanda district"],
        ["Holy Righteous Queen Tamar", "As Tamar, have every city-state in the game following the religion you founded"],
        ["Subject Matter Expert", "Have a Governor with every promotion"],
        ["Getting the Band Back Together", "Unlock every Governor, and have them established at the same time before the game reaches the Industrial Era"],
        ["Drama Queen", "Join or be the target of 3 Emergencies in a single game"],
        ["Curse your sudden but inevitable betrayal!", "Join a Betrayal Emergency"],
        ["Blackest Queen", "As France, build an Intelligence Agency"],
        ["Bromance", "Achieve the maximum Alliance level with Gilgamesh"],
        ["Die Another Day", "Neutralize a Governor with a Spy"],
        ["Circle of Life", "Build a Fishery adjacent to the Great Barrier Reef"],
        ["Extend the Olive Branch", "Make a peace deal which includes you giving or receiving an Olives resource"],
        ["Shopping Spree", "Have 10 Shopping Malls in your civilization at the same time"],
        ["Desperate Times Call For Desperate Measures", "Assign a Dark Policy to your Government"],
        ["Frenemy", "Gain control of an Ally's city after it becomes disloyal, and choose to keep it"],
        ["Elcano's Revenge", "Be the first player to circumnavigate the world after Ferdinand Magellan has been recruited by another player"],
        ["Dark Horse", "Win the game while in a Dark Age"],
        ["Taxation Without Representation", "As England, lose a city to disloyalty which has an established Financier Governor"],
        ["Victory Belongs to the Most Persevering", "Achieve a Heroic Age"],
        ["I'm going to break the wheel", "Earn three Golden Ages in a row"],
        ["What Could Possibly Go Wrong?", "Have an improved Amber resource in a city with a Zoo and an Archaeological Museum at the start of the turn"],
        ["Metroplex", "Completely surround your Government Plaza with districts or wonders you own at the start of the turn"],
        ["Treasures of Heaven and Earth", "Win a game as Mansa Musa"],
        ["Lord of Tahuantinsuyo", "Win a game as Pachacuti"],
        ["Queen of the Byrsa", "Win a game as Dido"],
        ["Padishah Efendim", "Win a game as Suleiman The Magnificent"],
        ["Literally Playable", "Win a game as Kristina"],
        ["The Sunny Way", "Win a game as Wilfrid Laurier"],
        ["Majestrix of the Court of Love", "Win a game as Eleanor of Aquitaine"],
        ["The Laurels of Virtues and Letters", "Win a game as Matthias Corvinus"],
        ["Tu Meke", "Win a game as Kupe"],
        ["The Art of Telling Plain Truths", "Win a Diplomatic Victory"],
        ["Rivals on Ice", "Playing as Russia, conquer a city with an Ice Hockey rink"],
        ["Sid Meier's Ditchdigging Simulator", "Use two cities and the Panama Canal to make 7 contiguous land tiles passable by ships"],
        ["An Engineer's Dream", "Have a Canal, Dam, Aqueduct, Railroad, Golden Gate Bridge, and Mountain Tunnel in a city"],
        ["When Diplomacy Fails", "Have a fully upgraded Giant Death Robot capture a city"],
        ["A Man A Plan A Canal Panama", "Build the Panama Canal as Teddy Roosevelt"],
        ["Surprise Attack", "Move a military unit into an enemy's owned tile using a Mountain Tunnel (or Qhapaq Nan)"],
        ["One Tree Hill", "Have one of your Rock Band units perform a concert adjacent to a Maori Pa unique improvement"],
        ["Seahenge", "Have Stonehenge become submerged due to Coastal Flooding"],
        ["Rock God", "Have no cities following your religion then convert a city to your religion using a Rock Band unit"],
        ["Nobel-er than the Noblest", "Achieve first place in all three Nobel Prizes in the same game"],
        ["Airing Your Grievances", "Win a Diplomatic Victory Resolution and use it to reduce another player's progress toward that victory"],
        ["Peacekeeper", "As Wilfrid Laurier, successfully complete an Emergency"],
        ["Shield of Christianity", "As Hungary, have Christianity as your dominant religion and defeat a unit whose Civilization's dominant religion is not Christianity"],
        ["Po-tay-toes!", "As Pachacuti, construct a Terrace Farm that is adjacent to 2 Aqueducts and 4 Mountains"],
        ["One does not simply walk into Ngauruhoe", "As the Maori, have a Maori Toa discover the Ngauruhoe volcano"],
        ["Hajj", "As Mansa Musa, send a Trade Route to Mecca that gives the sending player at least 30 gold"],
        ["Purple Reign", "As Dido, complete the Move Capital project on 4 different continents"],
        ["Nobody's Business But the Turks", "As the Ottomans, capture another Civilization's capital and then rename it"],
        ["Smörgåsbord", "As Kristina, at the start of a turn have cities in five different terrain types (Snow, Tundra, Desert, Plains and Grassland) and have Open Air Museums in all of them"],
        ["Meet the New Boss, Same as the Old Boss", "As Eleanor, gain a city to loyalty that was owned by a different civilization with Eleanor as its leader"],
        ["Let Our Powers Combine – Wait Heart is Missing!", "Have a city with a Wind Farm, Solar Farm, Hydroelectric Dam, and Geothermal Plant"],
        ["Toward Carbon Neutrality", "Complete the Carbon Recapture project 10 times during a single game"],
        ["Future is Now", "Be the first to complete all the technologies in the Future Era in a game with 8 or more players"],
        ["And the Walls Kept Tumbling Down", "Have your Roman city lose 6 population from one Vesuvius eruption"],
        ["Real Estate Disclosures Required", "Have a district be pillaged by 3 different random events"],
        ["Eat, Drink and Be Merry", "Win the Black Death as England"],
        ["Santé Passe Richesse", "Win the Black Death as France"],
        ["Bendición", "Win the Black Death as Castile"],
        ["Gesundheit", "Win the Black Death as the Holy Roman Empire"],
        ["I'm Not Dead Yet", "Win the Black Death after turn 80"],
        ["Aggressive Strain", "Win the Black Death after conquering five cities"],
        ["Medieval Medicine", "Train 25 Plague Doctors during the Black Death scenario"],
        ["Élan", "Win War Machine as France"],
        ["Auftragstaktik", "Win War Machine as Germany"],
        ["With The Army You Have", "Win War Machine without training any units"],
        ["Vernichtungsstrategie", "As Germany, win War Machine within 25 turns"],
        ["Croix de Lorraine", "In War Machine, as France, conquer Metz within 5 turns"],
        ["Big Bertha", "In War Machine, reduce and capture a full-health city in a single turn"],
        ["Danse Macabre", "Win the Black Death scenario on Deity difficulty"],
        ["Hello Cleveland!", "Perform a Rock Concert in Cleveland"],
        ["The Test of Royale", "Win the Red Death scenario"],
        ["Do Unto Others", "Nuclear Strike another faction in the Red Death scenario"],
        ["Have Them Do Unto You", "Get nuked by another faction in the Red Death scenario"],
        ["Reinforcements Have Arrived", "Claim a Supply Drop in the Red Death scenario"],
        ["The Good Die Young", "Lose your last Civilian within the first ten turns in the Red Death scenario"],
        ["The stars are right", "Win a regular game as Lady Six Sky."],
        ["El Libertador", "Win a regular game as Simón Bolívar."],
        ["Court of Itzamna", "As the Maya found a settlement adjacent to 4 luxury resources."],
        ["To plow the sea", "As Simón Bolívar activate all the Comandante Generals across multiple games."],
        ["I'll melt with you", "Win any Victory with Apocalypse mode enabled."],
        ["The end of the world as we know it", "Be the last person standing after comets begin falling."],
        ["The accursed share", "Use a max-promotions Soothsayer to sacrifice a max-promotions GDR."],
        ["Ashes of Time", "Wanderers - Explore 30 city ruins across multiple games."],
        ["Experience Is Everything", "Preppers - Have 5 units earn 5 promotions across multiple games."],
        ["It's Alive!", "Mad Scientists - Heal 1000 health points across multiple games."],
        ["Hope Springs Eternal", "Be defeated 5 times in the Red Death scenario."],
        ["From the Outer Darkness", "Mutants - Attack a unit outside the Red Death while inside the Red Death 20 times."],
        ["Getting Pruney", "Pirates - Spend 50 turns in the water across multiple games."],
        ["U mad, bro?", "Borderlords - Trick enemy factions into triggering Grieving Gifts 5 times across multiple games."],
        ["It Hungers", "Cultists - Kill 10 units with the Undying Eye."],
        ["NERDS!", "Jocks - Use Hail Marys to wound, but not kill, 5 Civilians across multiple games."],
        ["They're coming to get you, Barbara", "Zombie Beastmasters - Spawn 30 Zombie Hordes through combat kills."],
        ["Out of Sight, Out of Mind", "Aliens - Attack while cloaked 20 times."],
        ["The Lion of Judah", "Win a regular game as Menelik II."],
        ["Battle of Adwa", "Defeat an Infantry unit whose capital is on another continent with an Oromo Cavalry."],
        ["The Mask of Baphomet", "Earn all Governor promotions for the Owls of Minerva Secret Society."],
        ["Voice of Aiwass", "Earn all Governor promotions for the Hermetic Order Secret Society."],
        ["Dead But Dreaming", "Earn all Governor promotions for the Voidsingers Secret Society."],
        ["This Blood is the Life", "Earn all Governor promotions for the Sanguine Pact Secret Society."],
        ["One Eye in One Hundred", "Win a regular game as Basil II."],
        ["Et tu, Gallia?", "Win a regular game as Ambiorix."],
        ["Rome is Where the Heart is", "As Byzantium, take the original capital of Rome while it is following your founded religion."],
        ["Crom Laughs at Your Tanks", "As Gaul, kill a Tank with a Gaesatae."],
        ["Things Fall Apart", "In Dramatic Ages Mode, lose 4 or more cities by entering a Dark Age."],
        ["The City Ever-Shining", "In Dramatic Ages Mode, enter a Golden Age with an excess 20 Era Score"],
        ["No Light Without the Dark", "In Dramatic Age Mode, as Georgia, have simultaneously a Golden and a Dark Policy active."],
        ["The Abyss is Hungry", "Dread Pirate - Sink 10 ships while using Walk the Plank across multiple games."],
        ["Naval Supremacy", "Privateer - Ensure that your patron has a naval fleet twice the size of any other colonial power."],
        ["Port in Every Storm", "Swashbuckler - Visit the tavern of 10 ports in a single game."],
        ["Love It When a Plan Comes Together", "Hoarder - Sink or capture a treasure ship while a treasure escort is locked by a chainshot."],
        ["I am a Pirate King!", "Win the Pirates scenario."],
        ["Forced Retirement", "Lose the Pirates scenario due to mutiny."],
        ["Liquid Assets", "Sink or capture a treasure ship."],
        ["Mine! Mine! Mine!", "Win the Pirates scenario using mostly Treasure Points."],
        ["I am Kind of a Big Deal", "Win the Pirates scenario using mostly Infamous Pirate Points."],
        ["I Want You to Hit Me as Hard as You Can", "Win the Pirates scenario using mostly Fightin' Points."],
        ["Babylon Rocker", "Win a regular game as Hammurabi."],
        ["Let's Do the Time Warp Again", "As Babylon, earn 5 tech boosts for techs that are at least one era later than your current era."],
        ["Sing, O Muse", "Claim every Hero across multiple games."],
        ["Clash of the Titans", "Kill an enemy Hero with your Hero."],
        ["The Brave Live Forever", "Recall a Hero 5 times in a single game."],
        ["Steel-Driving Man", "Recall a Hero after the Industrial Era."],
        ["The Dream Team", "Claim 5 Heroes in a single game."],
        ["I will not bend my back", "Win a regular game as Bà Triệu."],
        ["For he on honey-dew hath fed", "Win a regular game as Kublai Khan."],
        ["Top Hat and Monocle", "Control a 100% Monopoly on a given Luxury Resource on a Standard sized map or larger."],
        ["Jack of all Trades, Master of None", "Win a game on a Standard sized map or larger with 5 or more Industries, but no Corporations."],
        ["Robber Baron", "Control 5 Luxury Resource Monopolies at once on a Standard sized map or larger."],
        ["Limited Edition", "Hire a unique unit from a Barbarian Clan."],
        ["Finder's Fee", "Ransom 5 units from Barbarian Clans in a single game."],
        ["Frenemies", "Hire, Bribe, Incite, and Raid the same Barbarian Clan."],
        ["The Spice Must Flow", "Win a regular game as João III."],
        ["Ultramar Português", "As Portugal, have a Trading Post in cities belonging to Brazil, India, and Japan."],
        ["Re-Animator", "Control at least 20 Zombie units at the start of your turn."],
        ["Well Hello Mr. Fancypants", "Destroy a Zombie unit that has +50 or more Mutation Strength."],
        ["It's a Trap!!!", "Deal 50 or more damage to a single unit from trap damage on a single tile in one turn."],
        ["Salad Sensation", "Win a regular game as Julius Caesar"],
        ["Addressing Gettysburg", "Win a regular game as Abraham Lincoln"],
        ["The Self-Made Throne", "Win a regular game as Nzinga Mbande"],
        ["I Will Wait", "Win a regular game as Tokugawa"],
        ["Claimants of the Peacock Throne", "Win a regular game as Nader Shah"],
        ["Live Yongle Reaction", "Win a regular game as Yongle"],
        ["Mother’s Day", "Win a regular game as Wu Zetian"],
        ["Valley of Kings", "Win a regular game as Ramses II"],
        ["Dawn of a Dynasty", "Win a regular game as Sundiata Keita"],
        ["Father of Korean Literature", "Win a regular game as Sejong"],
        ["Partial Completionist", "Win a regular game as Ludwig II"],
        ["The Power Beside the Throne", "Win a regular game as Theodora"],
        ["The Triumphs of Oriana", "Win a regular game as Elizabeth I"],
    ];

    assert.strictEqual(officialAchievements.length, 320, "sanity check on this test's own reference list");

    const dataPairs = civilizationVi.achievements
        .map(a => [a.name, a.description])
        .sort((a, b) => a[0].localeCompare(b[0]));

    const expectedPairs = [...officialAchievements].sort((a, b) => a[0].localeCompare(b[0]));

    assert.deepStrictEqual(dataPairs, expectedPairs);

});
