import { test } from "node:test";
import assert from "node:assert";

import { getPlannerData } from "../utils/plannerCatalog.js";

// backend/catalog/games/company-of-heroes-2.json - 452 real achievements sourced
// from a live ISteamUserStats/GetSchemaForGame/v2 response for appid
// 231430 (fetched through this app's own services/steamApi.js).
// 449 of 452 ship a real, official Steam description, quoted
// verbatim below. The 3 hidden achievements ship no Steam
// description; their conditions here are curatorial (limited-time 2015
// event achievements, cross-checked against community guides).
// difficulty/estimatedTime/missable remain curatorial judgments.
const game = getPlannerData("company-of-heroes-2");

test("getPlannerData('company-of-heroes-2') returns real planner data with 452 curated achievements", () => {

    assert.ok(game, "expected real planner data for company-of-heroes-2");
    assert.ok(Array.isArray(game.achievements));
    assert.strictEqual(game.achievements.length, 452);

});

test("every Company of Heroes 2 achievement has a unique id from 1 to 452 and a unique apiname", () => {

    const ids = game.achievements.map(a => a.id);
    const apinames = game.achievements.map(a => a.apiname);

    assert.deepStrictEqual([...ids].sort((a, b) => a - b), Array.from({ length: 452 }, (_, i) => i + 1));
    assert.strictEqual(new Set(ids).size, 452);
    assert.strictEqual(new Set(apinames).size, 452);

});

test("every Company of Heroes 2 achievement has a valid difficulty (1-5), a positive estimatedTime, and non-empty name/description", () => {

    for (const achievement of game.achievements) {

        assert.ok(
            Number.isInteger(achievement.difficulty) && achievement.difficulty >= 1 && achievement.difficulty <= 5,
            `${achievement.name} has an out-of-range difficulty: ${achievement.difficulty}`
        );

        assert.ok(
            Number.isInteger(achievement.estimatedTime) && achievement.estimatedTime > 0,
            `${achievement.name} has an invalid estimatedTime: ${achievement.estimatedTime}`
        );

        assert.ok(achievement.name?.length > 0, "achievement is missing a name");
        assert.ok(achievement.description?.length > 0, `${achievement.name} is missing a description`);
        assert.ok(achievement.apiname?.length > 0, `${achievement.name} is missing an apiname`);

    }

});

test("every one of the 449 officially-described Company of Heroes 2 achievement name+description pairs matches the live GetSchemaForGame response", () => {

    const hiddenApinames = new Set([
        "ev_mystery_01",
        "ev_mystery_02",
        "ev_mystery_03",
    ]);

    assert.strictEqual(hiddenApinames.size, 3, "sanity check - Company of Heroes 2 has 3 hidden achievements");

    const officialAchievements = [
        ["'Pak's Quite a Punch", "Build 100 Pak40 Anti-tank Guns and kill 15 medium tanks with Pak40 Anti-tank Guns"],
        ["A Tool for Every Occasion", "Use Grenadiers' Panzerfaust ability 50 times and destroy 50 light vehicles with Grenadiers"],
        ["Annihilation over Attrition", "Play 250 Annihilate games"],
        ["Annihilator", "Win 100 annihilate games"],
        ["Anti-tank Gun Production I", "Build 60 Pak40 Anti-tank Guns, 30 Pak43 Anti-tank Guns, and 60 ZIS-3 76mm Divisional Field Guns"],
        ["Anti-Tank Gun Specialist", "Complete all Anti-Tank intelligence bulletins"],
        ["Armored and Dangerous", "Recrew 10 Soviet vehicles during the Blitzkrieg Challenge"],
        ["Armored Assassin", "Destroy 30 BM-13 Katyushas with Panther PzKpfw Vs"],
        ["Artillery Production I", "Build 60 BM-13 Katyushas and 60 Panzerwerfers"],
        ["Artillery Production II", "Build 15 ML-20 152mm Gun-Howitzer pieces and 15 leFH 18 Artillery Artillery pieces"],
        ["Artillery Specialist", "Complete all Artillery intelligence bulletins"],
        ["Assault Grenadiers", "Kill 50 enemies with a single Assault Grenadier Squad"],
        ["Assault Gun Production I", "Build 50 Sturmpanzer IVs, 10 ISU-152s, and 50 SU-85s"],
        ["Assault Gun Production II", "Build 70 SU-76s and 70 StuG IIIs"],
        ["Assault Gun Specialist", "Complete all Assault Gun intelligence bulletins"],
        ["Assault on Voronezh - Captain", "Complete the Theater of War Scenario: Assault on Voronezh on Captain difficulty"],
        ["Assault on Voronezh - Conscript", "Complete the Theater of War Scenario: Assault on Voronezh on Conscript difficulty"],
        ["Assault on Voronezh - General", "Complete the Theater of War Scenario: Assault on Voronezh on General difficulty"],
        ["Attrition", "End 25 games with a kill:death ratio greater than 2:1"],
        ["Attrition Expert", "Win 100 Victory Point games"],
        ["Attrition over Annihilation", "Play 250 Victory Point games"],
        ["Automatch Commander", "Play 25 automatch games"],
        ["Automatch Conscript", "Play 1 automatch game"],
        ["Automatch General", "Play 100 automatch games"],
        ["Automatch Lieutenant", "Play 10 automatch games"],
        ["Automatch Officer", "Play 3 automatch games"],
        ["Battle of Minsk - Captain", "Complete the Battle of Minsk on Captain difficulty"],
        ["Battle of Minsk - Conscript", "Complete the Battle of Minsk on Conscript difficulty"],
        ["Battle of Minsk - General", "Complete the Battle of Minsk on General difficulty"],
        ["Battle of Oka River - Captain", "Complete the Battle of Oka River on Captain difficulty"],
        ["Battle of Oka River - Conscript", "Complete the Battle of Oka River on Conscript difficulty"],
        ["Battle of Oka River - General", "Complete the Battle of Oka River on General difficulty"],
        ["Battle of Pripyat River - Captain", "Complete the Battle of Pripyat River on Captain difficulty"],
        ["Battle of Pripyat River - Conscript", "Complete the Battle of Pripyat River on Conscript difficulty"],
        ["Battle of Pripyat River - General", "Complete the Battle of Pripyat River on General difficulty"],
        ["Battle of the Crimea - Captain", "Complete the Battle of Crimea on Captain difficulty"],
        ["Battle of the Crimea - Conscript", "Complete the Battle of Crimea on Conscript difficulty"],
        ["Battle of the Crimea - General", "Complete the Battle of Crimea on General difficulty"],
        ["Battlefield Menace", "Build 150 Barbed Wire pieces and plant 20 Soviet TM-35 mines"],
        ["Beast Killer", "Destroy 25 Panthers PzKpfw V and 10 Tiger PzKpfw VIs with ISU-152s"],
        ["Behind Enemy Lines - Captain", "Complete Campaign Mission 11 - Behind Enemy Lines on Captain difficulty"],
        ["Behind Enemy Lines - Conscript", "Complete Campaign Mission 11 - Behind Enemy Lines on Conscript difficulty"],
        ["Behind Enemy Lines - General", "Complete Campaign Mission 11 - Behind Enemy Lines on General difficulty"],
        ["Bigger is Better", "Build 100 HM-38 120mm Mortar teams and kill 200 infantry with HM-38 120mm Mortars"],
        ["BLITZKRIEG", "Deploy 50 Mechanized Assault Groups and 50 Mechanized Grenadier Groups."],
        ["Blitzkrieg - Captain", "Complete the Blitzkrieg Challenge on Captain difficulty"],
        ["Blitzkrieg - Conscript", "Complete the Blitzkrieg Challenge on Conscript difficulty"],
        ["Blitzkrieg - General", "Complete the Blitzkrieg Challenge on General difficulty"],
        ["Blood Toll", "Win a game despite having twice as many deaths as kills"],
        ["Blow It All Up!", "Destroy 30 buildings and kill 300 infantry with Katyushas"],
        ["BOOM!", "Kill 100 vehicles with B4 howitzers."],
        ["Breaking Lines - Captain", "Complete the Theater of War Battle: Breaking Lines on Captain difficulty"],
        ["Breaking Lines - Conscript", "Complete the Theater of War Battle: Breaking Lines on Conscript difficulty"],
        ["Breaking Lines - General", "Complete the Theater of War Battle: Breaking Lines on General difficulty"],
        ["Bridge Defense - Captain", "Complete the Theater of War Challenge: Bridge on Captain difficulty"],
        ["Bridge Defense - Conscript", "Complete the Theater of War Challenge: Bridge on Conscript difficulty"],
        ["Bridge Defense - General", "Complete the Theater of War Challenge: Bridge on General difficulty"],
        ["Brigadier General", "Reached the rank of Brigadier General"],
        ["Brody Tank War - Captain", "Complete the Brody Tank War on Captain difficulty"],
        ["Brody Tank War - Conscript", "Complete the Brody Tank War on Conscript difficulty"],
        ["Brody Tank War - General", "Complete the Brody Tank War on General difficulty"],
        ["Brotherly Love (German)", "Kill 100 M1910 Maxim Heavy Machine Gun team members and 300 Conscripts with MG42 Heavy Machine Guns"],
        ["Brotherly Love (Soviet)", "Kill 100 MG42 HMG team members and 300 Grenadier squads with M1910 Maxim Heavy Machine Guns"],
        ["Burn Baby Burn", "Use the Conscripts' Molotov Cocktail ability 80 times and kill 500 enemy infantry with Conscripts"],
        ["Campaign - Captain", "Complete the Campaign on Captain difficulty"],
        ["Campaign - Conscript", "Complete the Campaign on Conscript difficulty"],
        ["Campaign - General", "Complete the Campaign on General difficulty"],
        ["Campaign Commander", "Play 25 Campaign missions"],
        ["Campaign Conscript", "Play 1 Campaign mission"],
        ["Campaign General", "Play 100 Campaign missions"],
        ["Campaign Lieutenant", "Play 10 Campaign missions"],
        ["Campaign Officer", "Play 3 Campaign missions"],
        ["Captain", "Reach the rank of Captain"],
        ["Challenging Victory", "Win 25 games with a point lead under 100"],
        ["Clean Sweep", "Clear the entire minefield in the Blitzkrieg Challenge"],
        ["Cold Weather - Captain", "Complete the Cold Weather Challenge on Captain difficulty"],
        ["Cold Weather - Conscript", "Complete the Cold Weather Challenge on Conscript difficulty"],
        ["Cold Weather - General", "Complete the Cold Weather Challenge on General difficulty"],
        ["Colonel", "Reached the rank of Colonel"],
        ["Command Economy", "Spend over 7500 resources in 15 games"],
        ["Commando Style", "Kill 15 enemies with each of 25 different Panzer Grenadier squads"],
        ["Comp-Stomp Commander", "Play 25 matches versus AI"],
        ["Comp-Stomp Conscript", "Play 1 match versus AI"],
        ["Comp-Stomp General", "Play 100 matches versus AI"],
        ["Comp-Stomp Lieutenant", "Play 10 matches versus AI"],
        ["Comp-Stomp Officer", "Play 3 matches versus AI"],
        ["Convoy - Captain", "Complete the Theater of War Challenge: Convoy on Captain difficulty"],
        ["Convoy - Conscript", "Complete the Theater of War Challenge: Convoy on Conscript difficulty"],
        ["Convoy - General", "Complete the Theater of War Challenge: Convoy on General difficulty"],
        ["Cookout", "Build 10 Campfires during the General Winter Scenario"],
        ["Corporal", "Reach the rank of Corporal"],
        ["Deadly Purpose", "Build 50 T-34/85s and destroy 10 heavy tanks with T-34/85s"],
        ["Death from Above", "Kill 600 infantry with Panzerwerfers"],
        ["Death from Afar", "Destroy 40 T-34/76 medium tanks with Elefants"],
        ["Defending the Motherland", "Kill 100 infantry units with Soviet Irregulars"],
        ["Defense of Schildkröteberg - Captain", "Complete the Defense of Schildkröteberg Challenge on Captain difficulty"],
        ["Defense of Schildkröteberg - Conscript", "Complete the Defense of Schildkröteberg Challenge on Conscript difficulty"],
        ["Defense of Schildkröteberg - General", "Complete the Defense of Schildkröteberg Challenge on General difficulty"],
        ["Delaying the Inevitable", "Play 50 games against a Soviet opponent that last longer than 45 minutes"],
        ["Destined for Destruction", "Destroy 30 T-34/76s with StuG IIIs"],
        ["Direct Indirect Fire", "Build 80 PM-41 82mm Mortar teams and use their Mortar Barrage ability 40 times"],
        ["Don't Step on the Grass", "Build 30 mine fields and plant 15 Teller AT Mines"],
        ["Elefant Frenzy", "Kill 30 enemies with each of 5 different Elefant tanks"],
        ["Encirclement at Smolensk - Captain", "Complete the Encirclement at Smolensk on Captain difficulty"],
        ["Encirclement at Smolensk - Conscript", "Complete the Encirclement at Smolensk on Conscript difficulty"],
        ["Encirclement at Smolensk - General", "Complete the Encirclement at Smolensk on General difficulty"],
        ["Even Heavy Armor Cannot Withstand Fire of this Magnitude", "Destroy 25 heavy tanks with Elefants"],
        ["Evenly Matched", "Destroy 25 T-34/76s with Panzer IVs"],
        ["Explosivist", "Use the ZIS-3 76mm Divisional Field Gun Light Artillery Barrage ability 75 times"],
        ["Faceoff at Rostov - Captain", "Complete the Faceoff at Rostov on Captain difficulty"],
        ["Faceoff at Rostov - Conscript", "Complete the Faceoff at Rostov on Conscript difficulty"],
        ["Faceoff at Rostov - General", "Complete the Faceoff at Rostov on General difficulty"],
        ["First Battle of Kharkov - Captain", "Complete the First Battle of Kharkov on Captain difficulty"],
        ["First Battle of Kharkov - Conscript", "Complete the First Battle of Kharkov on Conscript difficulty"],
        ["First Battle of Kharkov - General", "Complete the First Battle of Kharkov on General difficulty"],
        ["Flame On!", "Upgrade 60 Sdkfz 251 Halftracks with Flame Projectors"],
        ["Flanking Maneuvers", "Kill 70 HMG team members and 70 Mortar team members with Shock Troops"],
        ["Fusilier", "End 15 games with the majority of your kills from infantry (German)"],
        ["General Mud - Captain", "Complete the Theater of War Battle: General Mud on Captain difficulty"],
        ["General Mud - Conscript", "Complete the Theater of War Battle: General Mud on Conscript difficulty"],
        ["General Mud - General", "Complete the Theater of War Battle: General Mud on General difficulty"],
        ["General Winter - Captain", "Complete the General Winter Scenario on Captain difficulty"],
        ["General Winter - Conscript", "Complete the General Winter Scenario on Conscript difficulty"],
        ["General Winter - General", "Complete the General Winter Scenario on General difficulty"],
        ["German Battle Medallion", "Play as the Germans 500 times"],
        ["German Team Weapon Specialist", "End 15 games with the majority of your kills from team weapons (German)"],
        ["Gold Assassin", "Complete all objectives in the Officer Assassination Challenge"],
        ["Gold Defense", "Complete all objectives in the Winter Defense Challenge"],
        ["Gold Weather", "Complete all objectives in the Cold Weather challenge"],
        ["Goldkrieg", "Complete all objectives in the Blitzkrieg Challenge"],
        ["Halbe - Captain", "Complete Campaign Mission 13 - Halbe on Captain difficulty"],
        ["Halbe - Conscript", "Complete Campaign Mission 13 - Halbe on Conscript difficulty"],
        ["Halbe - General", "Complete Campaign Mission 13 - Halbe on General difficulty"],
        ["Halftracked", "Recrew all the abandoned German halftracks on the General Winter Scenario map"],
        ["Hard Shell", "Build 3 Panzer IV Medium Tanks during the match during the Defense of Schildkröteberg"],
        ["Heartbreaking Loss", "Lose 25 Victory Point games by reaching zero points with a 100 or less point difference"],
        ["Heavy Machine Gun Specialist", "Complete all HMG intelligence bulletins"],
        ["Heavy Rain - Captain", "Complete the Theater of War Battle: Heavy Rain on Captain difficulty"],
        ["Heavy Rain - Conscript", "Complete the Theater of War Battle: Heavy Rain on Conscript difficulty"],
        ["Heavy Rain - General", "Complete the Theater of War Battle: Heavy Rain on General difficulty"],
        ["Heavy Tank Production I", "Build 20 Tiger PzKpfw Vis, 20 IS-2s, and 40 Elefants"],
        ["Heavy Tank Specialist", "Complete all Heavy Tank intelligence bulletins"],
        ["Heavy Weapons", "Destroy 30 Sdkfz 222 Scout Cars, 15 Ostwinds, and 40 more vehicles with Guards"],
        ["Help Indeed", "Rescue all three Partizan squads in the Cold Weather challenge"],
        ["Hit the Deck!", "Kill 600 infantry with Heavy Machine Guns"],
        ["HM-38 120mm Mortar Specialist", "Destroy 15 buildings and achieve three levels of veteran status with 20 HM-38 120mm Mortars"],
        ["HMG Hero", "Kill 15 enemies with each of 10 different M1910 Maxim Heavy Machine Guns squads"],
        ["HMG Production I", "Build 80 M1910 Maxim Heavy Machine Gun teams and 80 MG42 Heavy Machine Gun teams"],
        ["Hold the Line", "Build 30 bunkers"],
        ["Human Wave", "Win a game as Soviets despite having three times as many deaths as kills"],
        ["I Need No Help", "Do not call in any reinforcements during the Brody Tank War"],
        ["In the Noose", "Destroy all the vehicles in the Soviet breakout convoy during the Encirclement at Smolensk"],
        ["Indirect but Deadly", "Destroy 200 Infantry with SU-76s and use the SU-76 Barrage ability 100 times"],
        ["Indirect Fire - Captain", "Complete the Indirect Fire Challenge on Captain difficulty"],
        ["Indirect Fire - Conscript", "Complete the Indirect Fire Challenge on Conscript difficulty"],
        ["Indirect Fire - General", "Complete the Indirect Fire Challenge on General difficulty"],
        ["Indirect Gold", "Complete all objectives in the Indirect Fire Challenge"],
        ["Infantry Annihilator", "Kill 250 Conscripts and 500 more infantry with Sturmpanzer IV \"Brummbärs\""],
        ["Infantry Production I", "Build 100 Conscripts, 100 Grenadiers,  and 60 Panzer Grenadiers"],
        ["Infantry Production II", "Build 60 Shock Troops, 60 Guard Troops, and 60 Penal Battalions"],
        ["Infantry Specialist", "Complete all Infantry intelligence bulletins"],
        ["Invulnerable", "Destroy 50 T-70s with Panther PzKpfw Vs and achieve three levels of veteran status with 25 Panther PzKpfw Vs"],
        ["IS-2 Specialist", "Build 30 IS-2 and achieve three levels of veteran status with 5 IS-2s"],
        ["It's Super Effective!", "Kill 200 Heavy Machine Gun team members and 200 Mortar team members with Sdkfz 222 Scout Cars"],
        ["Junior Lieutenant", "Reach the rank of Junior Lieutenant"],
        ["Junior Sergeant", "Reach the rank of Junior Sergeant"],
        ["Just a Scratch!", "Get a KV1 to Veterancy Rank 3."],
        ["Kalach - Captain", "Complete the Theater of War Scenario: Kalach Pincer on Captain difficulty"],
        ["Kalach - Conscript", "Complete the Theater of War Scenario: Kalach Pincer on Conscript difficulty"],
        ["Kalach - General", "Complete the Theater of War Scenario: Kalach Pincer on General difficulty"],
        ["Kharkov - Pursuit - Captain", "Complete the Theater of War Battle: Kharkov Pursuit on Captain difficulty"],
        ["Kharkov Divide - Captain", "Complete the Theater of War Battle: Kharkov Divide on Captain difficulty"],
        ["Kharkov Divide - Conscript", "Complete the Theater of War Battle: Kharkov Divide on Conscript difficulty"],
        ["Kharkov Divide - General", "Complete the Theater of War Battle: Kharkov Divide on General difficulty"],
        ["Kharkov Pursuit - Conscript", "Complete the Theater of War Battle: Kharkov Pursuit on Conscript difficulty"],
        ["Kharkov Pursuit - General", "Complete the Theater of War Battle: Kharkov Pursuit on General difficulty"],
        ["King Tiger", "Kill 50 enemies with a single Tiger PzKpfw VI"],
        ["Kinslayer", "Destroy 50 Mortar team members with GrW 34 8cm Mortars"],
        ["Knife through Butter", "Destroy 100 light vehicles with Pak40 Anti-tank Guns"],
        ["KV-8 Specialist", "Kill 300 infantry and achieve three levels of veteran status with 5 KV-8s"],
        ["Land Bridge to Leningrad - Captain", "Complete Campaign Mission 07 - Land Bridge to Leningrad on Captain difficulty"],
        ["Land Bridge to Leningrad - Conscript", "Complete Campaign Mission 07 - Land Bridge to Leningrad on Conscript difficulty"],
        ["Land Bridge to Leningrad - General", "Complete Campaign Mission 07 - Land Bridge to Leningrad on General difficulty"],
        ["Leningrad Approach - Captain", "Complete the battle: Leningrad Approach on Captain difficulty"],
        ["Leningrad Approach - Conscript", "Complete the battle: Leningrad Approach on Conscript difficulty"],
        ["Leningrad Approach - General", "Complete the battle: Leningrad Approach on General difficulty"],
        ["Lieutenant", "Reach the rank of Lieutenant"],
        ["Lieutenant Colonel", "Reached the rank of Lieutenant Colonel"],
        ["Light Snack", "Destroy 50 T-70s with Panzer IVs"],
        ["Light Vehicle Production I", "Build 50 T-70s, 50 Sdkfz 222 Scout Cars, and 50 M3A1 Scout Cars"],
        ["Light Vehicle Production II", "Build 70 M5 Halftracks and 70 Sdkfz 251 Halftracks"],
        ["Light Vehicles Specialist", "Complete all Light Vehicles intelligence bulletins"],
        ["Long Distance Combat", "Destroy 5 Elefant tanks with ML-20 152mm Gun-Howitzers"],
        ["Lublin - Captain", "Complete Campaign Mission 10 - Lublin on Captain difficulty"],
        ["Lublin - Conscript", "Complete Campaign Mission 10 - Lublin on Conscript difficulty"],
        ["Lublin - General", "Complete Campaign Mission 10 - Lublin on General difficulty"],
        ["Lucky Shot", "Destroy 25 Sdkfz 222 Scout Cars with PM-41 82mm Mortars"],
        ["M.01 - Compassion in War", "Rescue the trapped civilians"],
        ["M.01 - German Engineering", "Kill a German tank with a German AT Gun"],
        ["M.01 - Soviet Zeal", "Complete Mission 01 without calling in additional Shock Troops"],
        ["M.02 - Invaluable Resources", "Keep the Shock Troops alive throughout Mission 2"],
        ["M.02 - What's Mine is Mine", "Defend the trainyard without placing any mines on the roads"],
        ["M.03 - Hardened Armor", "Re-take the Ridge without losing a vehicle on General difficulty"],
        ["M.03 - Mtsensk Mine Field", "Place at least 10 mines before the village defense"],
        ["M.03 - Something Borrowed", "Capture at least 3 enemy weapons on the Ridge"],
        ["M.04 - Cool Efficiency", "Take all three German outposts in Mission 4 using only snipers"],
        ["M.04 - Revenge", "Destroy all 10 tanks in Mission 4"],
        ["M.05 - Help from the North", "Secure the Northern bridge in Stalingrad"],
        ["M.05 - Some Room to Breathe", "Locate and destroy the enemy howitzers in Stalingrad"],
        ["M.05 - The Silent Organs", "Complete Mission 5 without firing the Katyusha rockets"],
        ["M.06 - Get Out of the Truck!", "Destroy all the German halftracks"],
        ["M.06 - Repel and Repair", "Complete the mission with at least 50 percent HQ integrity on General difficulty "],
        ["M.06 - Scout vs. Sniper", "Kill at least 3 snipers with an M3A1 Scout Car"],
        ["M.07 - Direct Fire", "Complete the mission without capturing or deploying a Mortar"],
        ["M.07 - Point Blank Demolition", "Destroy the German strongholds from close range on General difficulty"],
        ["M.07 - Suchka Specialist", "Earn three ranks of veterancy with an SU-76"],
        ["M.08 - No Help Needed", "Complete the “Hunt” without calling in any additional troops"],
        ["M.09 - All on Your Own", "Complete Mission 9 without reestablishing radio communication"],
        ["M.09 - The Spice of Life", "Create all available types of tank in Mission 9"],
        ["M.10 - Gate Crusher", "Breach the gate without losing an ISU-152 on General difficulty"],
        ["M.10 - Glass Cannons", "Destroy an Elefant or all Pak-43s before they destroy a vehicle"],
        ["M.10 - Zero-Risk Market", "Capture the Lublin market squad without losing a soldier or vehicle"],
        ["M.11 - Armia Krajowa", "Mobilize all three types of partisan troops during the fight"],
        ["M.11 - Snipe the driver", "Snipe the driver of a moving Opel truck"],
        ["M.12 - Howitzer Hunter", "Destroy all of the German Howitzers in the city of Poznan"],
        ["M.12 - Solo Commander", "Capture both squares in Poznan before Colonel-General Kolpakchi’s army does"],
        ["M.12 - To the Rescue", "Find and rescue the Penal Battalions incarcerated in the city of Poznan"],
        ["M.13 - Halbe Massacre", "Allow no Germans to escape the encirclement"],
        ["M.13 - The Might of the Red Army", "Complete the Halbe encirclement without producing any additional units"],
        ["M.14 - Before the Winter", "Achieve victory in 60 minutes or less."],
        ["M.14 - Boots in the Streets", "Complete the mission without building any additional vehicles"],
        ["M.14 - Claimed for the Motherland", "Recrew the abandoned StuG, Brummbär and Ostwind"],
        ["M3A1 Specialist", "Achieve three levels of veteran status with 40 M3A1 Scout Cars"],
        ["Major", "Reach the rank of Major"],
        ["Major General", "Reached the rank of Major General"],
        ["Makeshift Artillery", "Kill 200 infantry with STUG III E assault guns"],
        ["Massacre", "Kill 250 HMG team members and 250 Mortar team members with Ostwinds"],
        ["Massive Destruction", "Destroy 75% of the neutral structures during the Indirect Fire Challenge"],
        ["Master Flanker", "Snipe 70 HMG Team Members and 70 Mortar Team Members"],
        ["Master Sergeant", "Reach the rank of Master Sergeant"],
        ["Medium Tank Production I", "Build 50 Panther PzKpfw Vs and 40 T-34/85s"],
        ["Medium Tank Production II", "Build 30 T-34/76s, 30 Panzer Ivs and 30 Ostwinds"],
        ["Medium Tank Specialist", "Complete all Medium Tank intelligence bulletins"],
        ["MG42 Specialist", "Achieve three levels of veteran status with 15 MG42s"],
        ["Missiles Everywhere!", "Use the BM-13 Katyusha 132mm Barrage ability 75 times and kill 30 enemies with each of 15 BM-13 Katyushas"],
        ["Mobile Bombardment", "Use the Sdkfz 250/7 Mortar Halftrack's Mortar Barrage, Smoke Barrage, and Incendiary Mortar Barrage 25 times each"],
        ["More Than Just a Personnel Carrier", "Kill 250 infantry with M5 Halftracks"],
        ["Mortar Hero", "Kill 15 enemies with each of 25 different GrW 34 8cm Mortar teams"],
        ["Mortar Production I", "Build 60 GrW 34 8cm Mortars, 60 PM-41 82mm Mortars, and 50 HM-38 120mm Mortars"],
        ["Mortar Specialist", "Complete all Mortar intelligence bulletins"],
        ["Moscow Approach - Captain", "Complete the battle: Moscow Approach on Captain difficulty"],
        ["Moscow Approach - Conscript", "Complete the battle: Moscow Approach on Conscript difficulty"],
        ["Moscow Approach - General", "Complete the battle: Moscow Approach on General difficulty"],
        ["Moscow Lines - Captain", "Complete the battle: Moscow Lines on Captain difficulty"],
        ["Moscow Lines - Conscript", "Complete the battle: Moscow Lines on Conscript difficulty"],
        ["Moscow Lines - General", "Complete the battle: Moscow Lines on General difficulty"],
        ["Multi-talented", "Kill 100 infantry and 20 vehicles with T-34/76s"],
        ["Never Know What Hit 'Em", "Kill 500 infantry with ML-20 152mm Gun-Howitzers"],
        ["Never Make an Engineer Mad", "Upgrade 100 Combat Engineers with flamethrowers and kill 200 infantry with Combat Engineers"],
        ["No Retreat No Surrender - Captain", "Complete the Theater of War Battle: No Retreat No Surrender on Captain difficulty"],
        ["No Retreat No Surrender - Conscript", "Complete the Theater of War Battle: No Retreat No Surrender on Conscript difficulty"],
        ["No Retreat No Surrender - General", "Complete the Theater of War Battle: No Retreat No Surrender on General difficulty"],
        ["No-Fly Zone", "Upgrade 60 M5 Halftracks with the M17 Quad AA package"],
        ["Not Simply Anti-Air", "Destroy 100 light vehicles with Ostwinds"],
        ["Nothing Left Standing", "Destroy 25 buildings and destroy 50 vehicles with ISU-152s"],
        ["Now That's What I Call Recon", "Kill 15 enemies with each of 20 different M3A1 Scout Cars"],
        ["Occupation - Blood in the Snow", "Rescued the wounded Commander on Occupation"],
        ["Occupation - Captain", "Complete the Theater of War Challenge: Occupation on Captain difficulty"],
        ["Occupation - Conscript", "Complete the Theater of War Challenge: Occupation on Conscript difficulty"],
        ["Occupation - General", "Complete the Theater of War Challenge: Occupation on General difficulty"],
        ["Officer Assassination - Captain", "Complete the Officer Assassination Challenge on Captain difficulty"],
        ["Officer Assassination - Conscript", "Complete the Officer Assassination Challenge on Conscript difficulty"],
        ["Officer Assassination - General", "Complete the Officer Assassination Challenge on General difficulty"],
        ["One Tank Army", "Destroy 20 Vehicles and kill 200 Infantry with IS-2s"],
        ["Oorah!", "Use the Conscripts' Oorah! Ability 100 times"],
        ["Outranged", "Destroy 50 leFH 18 Artillery Howitzer team members with ML-20 152mm Gun-Howitzer"],
        ["Outrun and Outgun", "Destroy 75 light vehicles with T-70s"],
        ["Overwhelming Might", "Win 50 games with a point lead greater than 400"],
        ["Pak43 Specialist", "Achieve three levels of veteran status with 10 Pak43 Anti-tank Guns"],
        ["Panzer Crossing - Captain", "Complete the Theater of War Battle: Panzer Crossing on Captain difficulty"],
        ["Panzer Crossing - Conscript", "Complete the Theater of War Battle: Panzer Crossing on Conscript difficulty"],
        ["Panzer Crossing - General", "Complete the Theater of War Battle: Panzer Crossing on General difficulty"],
        ["Panzer Graveyard", "Destroy 20 German tanks or assault guns during the Brody Tank War"],
        ["Panzer Grenadier Specialist", "Achieve three levels of veteran status with 20 Panzer Grenadier squads and kill 300 Conscripts with Panzer Grenadier squads"],
        ["Panzer IV Specialist", "Build 50 Panzer Ivs and achieve three levels of veteran status with 15 Panzer Ivs "],
        ["Panzer Krieg", "End 15 games with the majority of your kills from vehicles (German)"],
        ["Panzer Theft", "Recrew and repair a Panzer IV tank during the Winter Defense Challenge"],
        ["Penetrating Performance", "Destroy 75 medium tanks with ZIS-3 76mm Divisional Field Guns"],
        ["PM-41 82mm Mortar Specialist", "Achieve three levels of veteran status with 20 PM-41 82mm Mortar Teams"],
        ["Poznan Citadel - Captain", "Complete Campaign Mission 12 - Poznan Citadel on Captain difficulty"],
        ["Poznan Citadel - Conscript", "Complete Campaign Mission 12 - Poznan Citadel on Conscript difficulty"],
        ["Poznan Citadel - General", "Complete Campaign Mission 12 - Poznan Citadel on General difficulty"],
        ["Radio Silence - Captain", "Complete Campaign Mission 09 - Radio Silence on Captain difficulty"],
        ["Radio Silence - Conscript", "Complete Campaign Mission 09 - Radio Silence on Conscript difficulty"],
        ["Radio Silence - General", "Complete Campaign Mission 09 - Radio Silence on General difficulty"],
        ["Ramming Speed!", "Use the T-34/76 ramming ability 50 times"],
        ["Rapid Fire Anti-Tank", "Destroy 20 vehicles with DShK Heavy Machine Guns."],
        ["Red Dead", "Kill 20 squads of Soviet Shock Troops or Penal Battalions during Faceoff at Rostov"],
        ["Retreat at the Don - Captain", "Complete the Theater of War Battle: Retreat at the Don on Captain difficulty"],
        ["Retreat at the Don - Conscript", "Complete the Theater of War Battle: Retreat at the Don on Conscript difficulty"],
        ["Retreat at the Don - General", "Complete the Theater of War Battle: Retreat at the Don on General difficulty"],
        ["Retreat to the Donets - Captain", "Complete the Theater of War Battle: Retreat to the Donets on Captain difficulty"],
        ["Retreat to the Donets - Conscript", "Complete the Theater of War Battle: Retreat to the Donets on Conscript difficulty"],
        ["Retreat to the Donets - General", "Complete the Theater of War Battle: Retreat to the Donets on General difficulty"],
        ["Rocket Recovery", "Recrew all of the Katyusha trucks on the map during the Indirect Fire Challenge"],
        ["Rocket Siege", "Use the Panzerwerfer Rocket Barrage 30 times and build 60 Panzerwerfers"],
        ["Satchel of Trouble", "Use the Satchel Charge ability 40 times and Kill 70 Mortar teams with Penal Battalions"],
        ["Scorched Earth - Captain", "Complete Campaign Mission 02 - Scorched Earth on Captain difficulty"],
        ["Scorched Earth - Conscript", "Complete Campaign Mission 02 - Scorched Earth on Conscript difficulty"],
        ["Scorched Earth - General", "Complete Campaign Mission 02 - Scorched Earth on General difficulty"],
        ["Scrounger", "Pick up 80% of the supply caches on the map during the Officer Assassination Challenge"],
        ["Senior Captain", "Reach the rank of Senior Captain"],
        ["Senior Corporal", "Reach the rank of Senior Corporal"],
        ["Senior Lieutenant", "Reach the rank of Senior Lieutenant"],
        ["Senior Private", "Reach the rank of Senior Private"],
        ["Senior Sergeant", "Reach the rank of Senior Sergeant"],
        ["Senior Warrant Officer", "Reach the rank of Senior Warrant Officer"],
        ["Sergeant", "Reach the rank of Sergeant"],
        ["Sergeant Major", "Reach the rank of Sergeant Major"],
        ["Sharpshooter", "Use a Sniper to deliver the killing shot to five Soviet officers during the Officer Assassination Challenge"],
        ["Shooting Gallery", "Kill 500 infantry with M1910 Maxim Heavy Machine Guns"],
        ["Sibling Rivalry (German)", "Destroy 10 IS-2s with  Tiger PzKpfw VIs"],
        ["Sibling Rivalry (Soviet)", "Destroy 10 Tiger PzKpfw VIs with IS-2s"],
        ["Silence the Guns", "Destroy the Soviet Artillery positions on the central plateau in the Encirclement at Smolensk"],
        ["Sitting Ducks", "Kill 50 Mortar team memberss and 50 HMG team members with leFH 18 Artillery"],
        ["Size Doesn't Matter", "Kill 5 Tigers with M-42 AT guns"],
        ["Sniper Hero", "Kill 25 enemies with each of 15 different German Snipers"],
        ["Sniper Hunter", "Kill 50 snipers with Sdkfz 222 Scout Cars"],
        ["Someone Needs to Man those Guns!", "Deploy 200 Osttruppen squads."],
        ["Soviet Battle Medallion", "Play as the Soviets 500 times"],
        ["Soviet Infantry Specialist", "End 15 games with the majority of your kills from infantry (Soviet)"],
        ["Soviet Team Weapon Specialist", "End 15 games with the majority of your kills from team weapons (Soviet)"],
        ["Soviet Vehicle Specialist", "End 15 games with the majority of your kills from vehicles (Soviet)"],
        ["Special Ingredients", "Use MG42 Incendiary Armor Piercing rounds 100 times and destroy 30 light vehicles with MG42 Heavy Machine Guns"],
        ["Spring Rasputitsa - Bombers on Approach", "Cleared the way for bombers on Spring Rasputitsa"],
        ["Spring Rasputitsa - Captain", "Complete the Theater of War Challenge: Spring Rasputitsa on Captain difficulty"],
        ["Spring Rasputitsa - Conscript", "Complete the Theater of War Challenge: Spring Rasputitsa on Conscript difficulty"],
        ["Spring Rasputitsa - General", "Complete the Theater of War Challenge: Spring Rasputitsa on General difficulty"],
        ["Stalingrad - Captain", "Complete Campaign Mission 05 - Stalingrad on Captain difficulty"],
        ["Stalingrad - Conscript", "Complete Campaign Mission 05 - Stalingrad on Conscript difficulty"],
        ["Stalingrad - General", "Complete Campaign Mission 05 - Stalingrad on General difficulty"],
        ["Stalingrad Aftermath - Captain", "Complete Campaign Mission 06 - Stalingrad Aftermath on Captain difficulty"],
        ["Stalingrad Aftermath - Conscript", "Complete Campaign Mission 06 - Stalingrad Aftermath on Conscript difficulty"],
        ["Stalingrad Aftermath - General", "Complete Campaign Mission 06 - Stalingrad Aftermath on General difficulty"],
        ["Stalingrad Encirclement - Captain", "Complete the Theater of War Battle: Stalingrad Encirclement on Captain difficulty"],
        ["Stalingrad Encirclement - Conscript", "Complete the Theater of War Battle: Stalingrad Encirclement on Conscript difficulty"],
        ["Stalingrad Encirclement - General", "Complete the Theater of War Battle: Stalingrad Encirclement on General difficulty"],
        ["Stalingrad Rail Station - Captain", "Complete Campaign Mission 01 - Stalingrad Rail Station on Captain difficulty"],
        ["Stalingrad Rail Station - Conscript", "Complete Campaign Mission 01 - Stalingrad Rail Station on Conscript difficulty"],
        ["Stalingrad Rail Station - General", "Complete Campaign Mission 01 - Stalingrad Rail Station on General difficulty"],
        ["Stalingrad Resistance - Captain", "Complete the Theater of War Battle: Stalingrad Resistance on Captain difficulty"],
        ["Stalingrad Resistance - Conscript", "Complete the Theater of War Battle: Stalingrad Resistance on Conscript difficulty"],
        ["Stalingrad Resistance - General", "Complete the Theater of War Battle: Stalingrad Resistance on General difficulty"],
        ["Staunch Defense", "Build 10 or more bunkers in 15 games"],
        ["Stealing the Spotlight", "Kill 40 Panzer Grenadiers with Guards"],
        ["Storming the Donets - Captain", "Complete the Theater of War Battle: Storming the Donets on Captain difficulty"],
        ["Storming the Donets - Conscript", "Complete the Theater of War Battle: Storming the Donets on Conscript difficulty"],
        ["Storming the Donets - General", "Complete the Theater of War Battle: Storming the Donets on General difficulty"],
        ["StuG Lover", "Build 60 StuG IIIs and destroy 80 vehicles with StuG IIIs"],
        ["Sturmpanzer IV Specialist", "Achieve three levels of veteran status with 10 Sturmpanzer IV \"Brummbärs\"s and kill 40 enemies with the same Sturmpanzer IV \"Brummbär\""],
        ["SU-76 Specialist", "Destroy 40 Light Vehicles with SU-76s and achieve three levels of veteran status with 20 SU-76s"],
        ["Support is on the Way - Captain", "Complete Campaign Mission 03 - Support is on the Way on Captain difficulty"],
        ["Support is on the Way - Conscript", "Complete Campaign Mission 03 - Support is on the Way on Conscript difficulty"],
        ["Support is on the Way - General", "Complete Campaign Mission 03 - Support is on the Way on General difficulty"],
        ["SURPRISE!", "Destroy 20 vehicles with Partisan Tank Hunters."],
        ["Tank Destroyer", "Destroy 15 heavy tanks with SU-85s"],
        ["Tank Hunter", "Destroy 50 medium tanks and 30 heavy tanks with Panther PzKpfw Vs"],
        ["Target Practice", "Kill 300 infantry with GrW 34 8cm Mortar teams"],
        ["Tatsinskaya Raid - Captain", "Complete the Theater of War Challenge: Tatsinskaya Raid on Captain difficulty"],
        ["Tatsinskaya Raid - Conscript", "Complete the Theater of War Challenge: Tatsinskaya Raid on Conscript difficulty"],
        ["Tatsinskaya Raid - General", "Complete the Theater of War Challenge: Tatsinskaya Raid on General difficulty"],
        ["The Miraculous Winter - Captain", "Complete Campaign Mission 04 - The Miraculous Winter on Captain difficulty"],
        ["The Miraculous Winter - Conscript", "Complete Campaign Mission 04 - The Miraculous Winter on Conscript difficulty"],
        ["The Miraculous Winter - General", "Complete Campaign Mission 04 - The Miraculous Winter on General difficulty"],
        ["The Reichstag - Captain", "Complete Campaign Mission 14 - The Reichstag on Captain difficulty"],
        ["The Reichstag - Conscript", "Complete Campaign Mission 14 - The Reichstag on Conscript difficulty"],
        ["The Reichstag - General", "Complete Campaign Mission 14 - The Reichstag on General difficulty"],
        ["Theater of War - 1941 - Battles", "Complete all Theater of War Battles in 1941"],
        ["Theater of War - 1941 - Captain", "Complete all Theater of War missions in 1941 on Captain difficulty"],
        ["Theater of War - 1941 - Challenges", "Complete all Theater of War Challenges in 1941"],
        ["Theater of War - 1941 - Conscript", "Complete all Theater of War missions in 1941 on Conscript difficulty"],
        ["Theater of War - 1941 - General", "Complete all Theater of War missions in 1941 on General difficulty"],
        ["Theater of War - 1941 - Scenarios", "Complete all Theater of War Co-op Scenarios in 1941"],
        ["Theater of War - Case Blue - Captain", "Complete all Theater of War missions in Case Blue on Captain difficulty"],
        ["Theater of War - Case Blue - Conscript", "Complete all Theater of War missions in Case Blue on Conscript difficulty"],
        ["Theater of War - Case Blue - General", "Complete all Theater of War missions in Case Blue on General difficulty"],
        ["Theater of War - Southern Fronts - Captain", "Complete all Theater of War mission in Southern Fronts on Captain difficulty"],
        ["Theater of War - Southern Fronts - Conscript", "Complete all Theater of War mission in Southern Fronts on Conscript difficulty"],
        ["Theater of War - Southern Fronts - General", "Complete all Theater of War mission in Southern Fronts on General difficulty"],
        ["Theater of War - Victory at Stalingrad - Captain", "Complete all Theater of War missions in Victory at Stalingrad on Captain difficulty"],
        ["Theater of War - Victory at Stalingrad - Conscript", "Complete all Theater of War missions in Victory at Stalingrad on Conscript difficulty"],
        ["Theater of War - Victory at Stalingrad - General", "Complete all Theater of War missions in Victory at Stalingrad on General difficulty"],
        ["Theater of War Battle Commander", "Play 25 Theater of War Battles "],
        ["Theater of War Battle Conscript", "Play 1 Theater of War Battle"],
        ["Theater of War Battle General", "Play 100 Theater of War Battles "],
        ["Theater of War Battle Lieutenant", "Play 10 Theater of War Battles "],
        ["Theater of War Battle Officer", "Play 3 Theater of War Battles "],
        ["Theater of War Challenge Commander", "Play 25 Theater of War Challenges "],
        ["Theater of War Challenge Conscript", "Play 1 Theater of War Challenge"],
        ["Theater of War Challenge General", "Play 100 Theater of War Challenges"],
        ["Theater of War Challenge Lieutenant", "Play 10 Theater of War Challenges "],
        ["Theater of War Challenge Officer", "Play 3 Theater of War Challenges"],
        ["Theater of War Scenario Commander", "Play 25 Theater of War Scenarios"],
        ["Theater of War Scenario Conscript", "Play 1 Theater of War Scenario"],
        ["Theater of War Scenario General", "Play 100 Theater of War Scenarios"],
        ["Theater of War Scenario Lieutenant", "Play 10 Theater of War Scenarios"],
        ["Theater of War Scenario Officer", "Play 3 Theater of War Scenarios"],
        ["They don't Call Him Ace for Nothing!", "Kill 200 units with a single Tiger Ace."],
        ["They're Coming Out of the Woodwork!", "Deploy 50 Partisan LMG Squads, 50 Partisan SMG Squads and 50 Partisan Rifle Squads."],
        ["Tiger Ace - Captain", "Complete the Theater of War Challenge: Tiger Ace on Captain difficulty"],
        ["Tiger Ace - Conscript", "Complete the Theater of War Challenge: Tiger Ace on Conscript difficulty"],
        ["Tiger Ace - General", "Complete the Theater of War Challenge: Tiger Ace on General difficulty"],
        ["Tiger Hunting - Captain", "Complete Campaign Mission 08 - Tiger Hunting on Captain difficulty"],
        ["Tiger Hunting - Conscript", "Complete Campaign Mission 08 - Tiger Hunting on Conscript difficulty"],
        ["Tiger Hunting - General", "Complete Campaign Mission 08 - Tiger Hunting on General difficulty"],
        ["To the Front", "Call in 20 squads of Fresh Conscripts during the Winter Defense Challenge"],
        ["To the Frontlines!", "Build 50 Shock Troops and kill 300 infantry with Shock Troops"],
        ["To the Last Bullet", "Finish 500 automatch or skirmish games"],
        ["Top of the Food Chain", "Destroy 20 T-34/76s and 10 T-34/85s with Tiger PzKpfw VI tanks"],
        ["Torched", "Upgrade 30 Penal Battalions with flamethrowers and kill 300 infantry with Penal Battalions"],
        ["Total Victory", "Win 25 games with 500 or greater point lead"],
        ["Tougher Meat", "Kill 100 light vehicles with Heavy Machine Guns"],
        ["Triple Triple", "Have three squads reach triple veterancy during the Defense of Schildkröteberg"],
        ["Turtle Gold", "Complete all objectives in the Defense of Schildkröteberg"],
        ["Uncompromising", "Complete Faceoff at Rostov without the Soviets ever controlling more Victory Points than you do."],
        ["Unstoppable Force", "Build 50 Pak43 Anti-tank Guns and kill 5 IS-2 heavy tanks with Pak43s"],
        ["Up Close and Personal", "Kill 150 Anti-tank Gun team members with T-70s"],
        ["War Footing Fuel I", "Spend over 750 fuel in each of 15 games"],
        ["War Footing Fuel II", "Spend over 1000 fuel in each of 15 games"],
        ["War Footing Fuel III", "Spend over 1250 fuel in each of 15 games"],
        ["War Footing Munitions I", "Spend over 1500 munitions in each of 15 games"],
        ["War Footing Munitions II", "Spend over 2000 munitions in each of 15 games"],
        ["War Footing Munitions III", "Spend over 2500 munitions in each of 15 games"],
        ["War Games I", "Win 100 games versus one AI opponent"],
        ["War Games II", "Win 100 games versus two AI opponents"],
        ["War Games III", "Win 100 games versus three AI opponents"],
        ["War Games IV", "Win 100 games versus four AI opponents"],
        ["War Material", "Capture five team weapons or vehicles in 25 different games"],
        ["Warrant Officer", "Reach the rank of Warrant Officer"],
        ["We're Going to Need a Bigger Gun", "Get 100 kills using a KV2."],
        ["Winter Defense - Captain", "Complete the Winter Defense Challenge on Captain difficulty"],
        ["Winter Defense - Conscript", "Complete the Winter Defense Challenge on Conscript difficulty"],
        ["Winter Defense - General", "Complete the Winter Defense Challenge on General difficulty"],
        ["Winter Driver", "Recrew and fully repair a Panzer IV tank during the Cold Weather challenge"],
        ["Winter Storm - Captain", "Complete the Theater of War Battle: Winter Storm on Captain difficulty"],
        ["Winter Storm - Conscript", "Complete the Theater of War Battle: Winter Storm on Conscript difficulty"],
        ["Winter Storm - General", "Complete the Theater of War Battle: Winter Storm on General difficulty"],
        ["With Extreme Difficulty", "Destroy 5 heavy tanks with Grenadiers"],
        ["Wrong Place, Wrong Time", "Destroy 30 vehicles with leFH 18 Artillery"],
    ];

    assert.strictEqual(officialAchievements.length, 449, "sanity check on this test's own reference list");

    const dataPairs = game.achievements
        .filter(a => !hiddenApinames.has(a.apiname))
        .map(a => [a.name, a.description])
        .sort((a, b) => a[0].localeCompare(b[0]));

    const expectedPairs = [...officialAchievements].sort((a, b) => a[0].localeCompare(b[0]));

    assert.deepStrictEqual(dataPairs, expectedPairs);

});

test("the 3 hidden Company of Heroes 2 achievements each keep their real name and a non-empty curatorial description", () => {

    const names = [
        ["ev_mystery_01", "Snore, Snore, Total Bore!"],
        ["ev_mystery_02", "Romeo is Dead!"],
        ["ev_mystery_03", "Romani Ite Domum"],
    ];

    assert.strictEqual(names.length, 3, "sanity check on this test's own reference list");

    for (const [apiname, name] of names) {

        const achievement = game.achievements.find(a => a.apiname === apiname);

        assert.ok(
            achievement && achievement.name === name && achievement.description.length > 0,
            `expected ${apiname} to be named "${name}" with a non-empty curatorial description`
        );

    }

});
