import { test } from "node:test";
import assert from "node:assert";

import { getPlannerData } from "../utils/plannerCatalog.js";

// backend/catalog/games/deep-rock-galactic-survivor.json - 300 real achievements sourced
// from a live ISteamUserStats/GetSchemaForGame/v2 response for appid
// 2321470 (fetched through this app's own services/steamApi.js).
// This game has no hidden achievements: all 300 ship a real, official
// Steam description, quoted verbatim below.
// difficulty/estimatedTime/missable remain curatorial judgments.
const game = getPlannerData("deep-rock-galactic-survivor");

test("getPlannerData('deep-rock-galactic-survivor') returns real planner data with 300 curated achievements", () => {

    assert.ok(game, "expected real planner data for deep-rock-galactic-survivor");
    assert.ok(Array.isArray(game.achievements));
    assert.strictEqual(game.achievements.length, 300);

});

test("every Deep Rock Galactic: Survivor achievement has a unique id from 1 to 300 and a unique apiname", () => {

    const ids = game.achievements.map(a => a.id);
    const apinames = game.achievements.map(a => a.apiname);

    assert.deepStrictEqual([...ids].sort((a, b) => a - b), Array.from({ length: 300 }, (_, i) => i + 1));
    assert.strictEqual(new Set(ids).size, 300);
    assert.strictEqual(new Set(apinames).size, 300);

});

test("every Deep Rock Galactic: Survivor achievement has a valid difficulty (1-5), a positive estimatedTime, and non-empty name/description", () => {

    for (const achievement of game.achievements) {

        assert.ok(
            Number.isInteger(achievement.difficulty) && achievement.difficulty >= 1 && achievement.difficulty <= 5,
            `${achievement.name} has an out-of-range difficulty: ${achievement.difficulty}`
        );

        assert.ok(
            Number.isInteger(achievement.estimatedTime) && achievement.estimatedTime > 0,
            `${achievement.name} has an invalid estimatedTime: ${achievement.estimatedTime}`
        );

        assert.ok(achievement.name?.length > 0, "achievement is missing a name");
        assert.ok(achievement.description?.length > 0, `${achievement.name} is missing a description`);
        assert.ok(achievement.apiname?.length > 0, `${achievement.name} is missing an apiname`);

    }

});

test("every one of the 300 Deep Rock Galactic: Survivor achievement name+description pairs matches the live GetSchemaForGame response", () => {

    const officialAchievements = [
        ["10,000 rounds per minute", "Complete a dive with the Weapons Specialist"],
        ["A freeze is coming", "Deal 250,000 Cryo damage"],
        ["A whiff of brimstone", "Complete a dive with the Demolitionist"],
        ["Adventure awaits", "Complete a dive with the Recon"],
        ["All sides", "Have 3 'Sidearm' overclocks in a single dive"],
        ["And my axe", "Complete a dive with the Strong Armed"],
        ["Anomaly: Hazard 1", "Complete an anomaly dive at Hazard 1"],
        ["Anomaly: Hazard 2", "Complete an anomaly dive at Hazard 2"],
        ["Anomaly: Hazard 3", "Complete an anomaly dive at Hazard 3"],
        ["Anomaly: Hazard 4", "Complete an anomaly dive at Hazard 4"],
        ["Anomaly: Hazard 5", "Complete an anomaly dive at Hazard 5"],
        ["Au-fully rich", "Collect 2,000 Gold"],
        ["Axe in face!", "Destroy all rocks in one main mission stage"],
        ["Azure Weald", "Win a Azure Weald Hazard 5 dive"],
        ["Back from the brink!", "Reach max HP after having dropped below 5 HP"],
        ["Big spender", "Spend 20,000 Gold"],
        ["Blunt force trauma", "Complete a dive with 4 [KINETIC] weapons equipped"],
        ["Bomberman", "Complete a dive with 4 [EXPLOSIVE] weapons equipped"],
        ["Book of Experience", "Reach level 50 during a dive"],
        ["BOOM! Headshot", "Have +250% Crit Chance with the Sharpshooter in a single dive"],
        ["Brainstorming", "Complete a dive with the Tinkerer"],
        ["Bullseye", "Kill a Q'ronar Shellback with the Supply Pod"],
        ["Cheapskate", "Complete a dive without spending any gold or nitra"],
        ["Chemical burns", "Complete a dive with the Interrogator"],
        ["Close call", "Kill the dreadnaught while you have less than 30 HP"],
        ["Corporate Discount", "Spend 2,500 Gold"],
        ["Count em!", "Fire 150,000 projectiles in a single dive"],
        ["Cross the beams", "Complete a dive with 4 [BEAM] weapons equipped"],
        ["Crystalline Caverns", "Win a Crystalline Caverns Hazard 5 dive"],
        ["Custom rig", "Have 6 uncommon items equipped"],
        ["Deep freeze", "Complete a dive with 4 [COLD] weapons equipped"],
        ["Deep scan", "Have 5 scanner artifacts in a single dive"],
        ["Delayed gratification", "Complete a dive with 4 [LASTING] weapons equipped"],
        ["Delicious BLT", "Reach 300 Max HP"],
        ["Denied", "Kill the Dreadnought Twins before they can heal"],
        ["Dig down deep", "Unlock the Driller"],
        ["Diggy diggy hole", "Complete a dive with the Foreman"],
        ["Drill baby, drill", "Collect all the oil shale on one stage, then complete the dive"],
        ["Dwarven architecture", "Complete a dive with 4 [CONSTRUCT] weapons equipped"],
        ["Early access", "Enter the drop pod with more than 30 seconds remaining"],
        ["Elemental avatar", "Apply 5,000,000 status effect stacks as the Interrogator in a single dive"],
        ["Employee of the Month", "Complete 5 lethal operation dives"],
        ["Employee of the Week", "Complete a lethal operation dive"],
        ["Employee of the Year", "Complete 10 lethal operation dives"],
        ["Endurance: Damage I", "Deal 100,000,000 damage"],
        ["Endurance: Damage II", "Deal 250,000,000 damage"],
        ["Endurance: Damage III", "Deal 500,000,000 damage"],
        ["Endurance: Damage IV", "Deal 1,000,000,000 damage"],
        ["Endurance: Damage V", "Deal 2,000,000,000 damage"],
        ["Endurance: Dives I", "Complete 5 dives"],
        ["Endurance: Dives II", "Complete 25 dives"],
        ["Endurance: Dives III", "Complete 50 dives"],
        ["Endurance: Dives IV", "Complete 75 dives"],
        ["Endurance: Dives V", "Complete 100 dives"],
        ["Endurance: Kills I", "Kill 50,000 enemies"],
        ["Endurance: Kills II", "Kill 100,000 enemies"],
        ["Endurance: Kills III", "Kill 250,000 enemies"],
        ["Endurance: Kills IV", "Kill 500,000 enemies"],
        ["Endurance: Kills V", "Kill 1,000,000 enemies"],
        ["Endurance: Mine I", "Mine 15,000 blocks"],
        ["Endurance: Mine II", "Mine 50,000 blocks"],
        ["Endurance: Mine III", "Mine 100,000 blocks"],
        ["Endurance: Mine IV", "Mine 150,000 blocks"],
        ["Endurance: Mine V", "Mine 250,000 blocks"],
        ["Endurance: Run I", "Run 10,000 steps"],
        ["Endurance: Run II", "Run 50,000 steps"],
        ["Endurance: Run III", "Run 100,000 steps"],
        ["Endurance: Run IV", "Run 250,000 steps"],
        ["Endurance: Run V", "Run 500,000 steps"],
        ["Enjoy a relaxing stroll", "Unlock the Engineer"],
        ["Expertly tuned", "Have 6 epic items equipped"],
        ["Extreme indecision", "Perform 50 rerolls during a single dive"],
        ["Eye of the storm", "Complete a dive with unstable overclocks on both the NUK17 and the BRT7"],
        ["Fabled fittings", "Have 6 legendary items equipped"],
        ["Fastest hands on the rig", "Have +500% reload speed as the Strong Armed"],
        ["Feeling a bit sour", "Complete a dive with 3 [ACID] weapons equipped"],
        ["Feeling lucky punk?", "Get 5 luck upgrades in one dive"],
        ["Fill 'er up", "Fully fuel B0b-33"],
        ["Fleet of foot", "Complete a dive with 4 [LIGHT] weapons equipped"],
        ["Freezing hot acid", "Deal 2,500,000 Status Effect Damage in a single dive"],
        ["Fully armed and operational", "Purchase every single meta upgrade"],
        ["Fully overclocked", "Get 4 weapons to level 21 as the Tinkerer"],
        ["Get that Midas touch", "Collect 250 Gold"],
        ["Going nuclear", "Have +250% explosion radius as the Demolitionist"],
        ["Got bait?", "Kill 3 Huuli Hoarders in one dive"],
        ["Gotta stay Nitrated", "Collect 250 Nitra"],
        ["Grow fat from strength", "Have 1000 max HP as the Classic Scout"],
        ["Hangry?", "Gain 1,000 level ups"],
        ["Hollow Bough", "Win a Hollow Bough Hazard 5 dive"],
        ["Hot, hot, hot!", "Deal 250,000 Fire damage"],
        ["Hoxxes Manual", "Die 3 times"],
        ["I ain't buying it", "Complete a dive without buying anything in the shop at Hazard 3"],
        ["I solve problems", "Complete a dive with the Maintenance Worker"],
        ["It's all in the wrist", "Complete a dive with 4 [THROWABLE] weapons equipped"],
        ["It's got electrolytes", "Reach 50% move speed"],
        ["Jetty boots", "Land on 200 blocks in one dive"],
        ["Just like the old days", "Complete a Hazard 5 dive without any gear equipped"],
        ["Ka-boom!", "Complete a dive with the Heavy Gunner"],
        ["Karl, is that you?", "Have 6 fully upgraded legendary pieces of gear equipped"],
        ["Keeper of the flame", "Complete a dive with 4 [FIRE] weapons equipped"],
        ["Know no fear", "Have 300 armor as the Juggernaut"],
        ["Legendary!", "Equip a legendary item"],
        ["Light show", "Complete a dive with 4 [PLASMA] weapons equipped"],
        ["Lock and load", "Unlock the Gunner"],
        ["Lord of war", "Fire 250,000 bullets as the Weapons Specialist in a single dive"],
        ["Magma Core", "Win a Magma Core Hazard 5 dive"],
        ["Master artificer", "Fully upgrade a legendary piece of gear"],
        ["Mastery: Azure Weald", "Complete an Azure Weald mastery dive"],
        ["Mastery: Breach Cutter", "Complete a Breach Cutter weapon mastery dive"],
        ["Mastery: Burst Fire Gun", "Complete a BRT7 Burst Fire Gun weapon mastery dive"],
        ["Mastery: Coil Gun", "Complete an ArmsKore Coil Gun weapon mastery dive"],
        ["Mastery: CRSPR Flamethrower", "Complete a CRSPR Flamethrower weapon mastery dive"],
        ["Mastery: Cryo Cannon", "Complete a Cryo Cannon weapon mastery dive"],
        ["Mastery: Cryo Grenade", "Complete a Cryo Grenade weapon mastery dive"],
        ["Mastery: Cryo Guard", "Complete an Arc-Tek Cryo Guard weapon mastery dive"],
        ["Mastery: Crystalline Caverns", "Complete a Crystalline Caverns mastery dive"],
        ["Mastery: DeepCore GK2", "Complete a DeepCore GK2 weapon mastery dive"],
        ["Mastery: DeepCore PGL", "Complete a DeepCore PGL weapon mastery dive"],
        ["Mastery: Firefly Hunter Drone", "Complete a Firefly Hunter Drone weapon mastery dive"],
        ["Mastery: HE Grenade", "Complete a High Explosive Grenade weapon mastery dive"],
        ["Mastery: Heavy Autocannon", "Complete a 'Thunderhead' Heavy Autocannon weapon mastery dive at Hazard 5"],
        ["Mastery: Heavy Revolver", "Complete a 'Bulldog' Heavy Revolver weapon mastery dive"],
        ["Mastery: Hi-Volt Thunderbird", "Complete a Hi-Volt Thunderbird weapon mastery dive"],
        ["Mastery: Hollow Bough", "Complete a Hollow Bough mastery dive"],
        ["Mastery: Hurricane", "Complete a 'Hurricane' Guided Rocket System weapon mastery dive"],
        ["Mastery: Impact Axe", "Complete a Impact Axe weapon mastery dive"],
        ["Mastery: Incendiary Grenade", "Complete an Incendiary Grenade weapon mastery dive"],
        ["Mastery: Jury-Rigged Boomstick", "Complete a Jury-Rigged Boomstick weapon mastery dive"],
        ["Mastery: K1-P Viper Drone", "Complete a K1-P Viper Drone weapon mastery dive"],
        ["Mastery: Krakatoa Sentinel", "Complete a Krakatoa Sentinel weapon mastery dive"],
        ["Mastery: LMG Gun Platform", "Complete an LMG Gun Platform weapon mastery dive"],
        ["Mastery: LOK-1 Smart Rifle", "Complete a LOK-1 Smart Rifle weapon mastery dive"],
        ["Mastery: M1000", "Complete a M1000 weapon mastery dive"],
        ["Mastery: Magma Core", "Complete a Magma Core mastery dive"],
        ["Mastery: Neurotoxin Grenade", "Complete a Neurotoxin Grenade weapon mastery dive"],
        ["Mastery: Nishanka Boltshark", "Complete a Nishanka Boltshark weapon mastery dive"],
        ["Mastery: Plasma Burster", "Complete a Plasma Burster weapon mastery dive"],
        ["Mastery: Plasma Carbine", "Complete a DRAK-25 Plasma Carbine weapon mastery dive"],
        ["Mastery: Plasma Charger", "Complete an Experimental Plasma Charger weapon mastery dive"],
        ["Mastery: Powered Minigun", "Complete a 'Lead Storm' Powered Minigun weapon mastery dive at Hazard 5"],
        ["Mastery: Salt Pits", "Complete a Salt Pits mastery dive"],
        ["Mastery: Seismic Repulsor", "Complete a Seismic Repulsor weapon mastery dive"],
        ["Mastery: Shard Diffractor", "Complete a Shard Diffractor weapon mastery dive"],
        ["Mastery: Sludge Pump", "Complete a Corrosive Sludge Pump weapon mastery dive"],
        ["Mastery: Stun Sweeper", "Complete a Voltaic Stun Sweeper weapon mastery dive"],
        ["Mastery: Subata 120", "Complete a Subata 120 weapon mastery dive"],
        ["Mastery: Swarm Grenade", "Complete a Shredder Swarm Grenade weapon mastery dive"],
        ["Mastery: Tactical Leadburster", "Complete a Tactical Leadburster weapon mastery dive"],
        ["Mastery: TH-0R Bug Taser", "Complete a TH-0R Bug Taser weapon mastery dive"],
        ["Mastery: Voltaic Shock Fence", "Complete a Voltaic Shock Fence weapon mastery dive"],
        ["Mastery: Voltaic SMG", "Complete a 'Stubby' Voltaic SMG weapon mastery dive"],
        ["Mastery: Warthog Auto", "Complete a 'Warthog' Auto 210 weapon mastery dive"],
        ["Mastery: Wave Cooker", "Complete a Colette Wave Cooker weapon mastery dive"],
        ["Mastery: Zhukov NUK17", "Complete a Zhukov NUK17 weapon mastery dive"],
        ["Measure twice, shoot once", "Complete a dive with the Sharpshooter"],
        ["Mind over matter", "Complete a Hazard 4 dive without any gear equipped"],
        ["Mission Possible", "Land on the drop pod ramp 3 times using jet boots"],
        ["Modern warfare", "Complete a dive with 3 [DRONE] weapons equipped"],
        ["Multitool", "Do damage with 5 types in one dive"],
        ["No pain, no gain", "Take 2000 damage during a dive"],
        ["Now, where did I put my keys?", "Have the alien threat reach level 2 before moving B0b-33, then complete the dive"],
        ["Overclock: Breach Cutter", "Reach level 18 with the Breach Cutter"],
        ["Overclock: Burst Fire Gun", "Reach level 18 with the BRT7 Burst Fire Gun"],
        ["Overclock: Coil Gun", "Reach level 18 with the ArmsKore Coil Gun"],
        ["Overclock: CRSPR Flamethrower", "Reach level 18 with the CRSPR Flamethrower"],
        ["Overclock: Cryo Cannon", "Reach level 18 with the Cryo Cannon"],
        ["Overclock: Cryo Grenade", "Reach level 18 with the Cryo Grenade"],
        ["Overclock: Cryo Guard", "Reach level 18 with the Arc-Tek Cryo Guard"],
        ["Overclock: DeepCore GK2", "Reach level 18 with the DeepCore GK2"],
        ["Overclock: DeepCore PGL", "Reach level 18 with the DeepCore PGL"],
        ["Overclock: Firefly Hunter Drone", "Reach level 18 with the Firefly Hunter Drone"],
        ["Overclock: HE Grenade", "Reach level 18 with the High Explosive Grenade"],
        ["Overclock: Heavy Autocannon", "Reach level 18 with the 'Thunderhead' Heavy Autocannon"],
        ["Overclock: Heavy Revolver", "Reach level 18 with the 'Bulldog' Heavy Revolver"],
        ["Overclock: Hi-Volt Thunderbird", "Reach level 18 with the Hi-Volt Thunderbird"],
        ["Overclock: Hurricane", "Reach level 18 with the 'Hurricane' Guided Rocket System"],
        ["Overclock: Impact Axe", "Reach level 18 with the Impact Axe "],
        ["Overclock: Incendiary Grenade", "Reach level 18 with the Incendiary Grenade"],
        ["Overclock: Jury-Rigged Boomstick", "Reach level 18 with the Jury-Rigged Boomstick"],
        ["Overclock: K1-P Viper Drone", "Reach level 18 with the K1-P Viper Drone"],
        ["Overclock: Krakatoa Sentinel", "Reach level 18 with the Krakatoa Sentinel"],
        ["Overclock: LMG Gun Platform", "Reach level 18 with the LMG Gun Platform"],
        ["Overclock: LOK-1 Smart Rifle", "Reach level 18 with the LOK-1 Smart Rifle"],
        ["Overclock: M1000", "Reach level 18 with the M1000"],
        ["Overclock: Neurotoxin Grenade", "Reach level 18 with the Neurotoxin Grenade"],
        ["Overclock: Nishanka Boltshark", "Reach level 18 with the Nishanka Boltshark"],
        ["Overclock: Plasma Burster", "Reach level 18 with the Plasma Burster"],
        ["Overclock: Plasma Carbine", "Reach level 18 with the DRAK-25 Plasma Carbine"],
        ["Overclock: Plasma Charger", "Reach level 18 with the Experimental Plasma Charger"],
        ["Overclock: Powered Minigun", "Reach level 18 with the 'Lead Storm' Powered Minigun"],
        ["Overclock: Seismic Repulsor", "Reach level 18 with the Seismic Repulsor"],
        ["Overclock: Shard Diffractor", "Reach level 18 with the Shard Diffractor"],
        ["Overclock: Sludge Pump", "Reach level 18 with the Corrosive Sludge Pump"],
        ["Overclock: Stun Sweeper", "Reach level 18 with the Voltaic Stun Sweeper"],
        ["Overclock: Subata 120", "Reach level 18 with the Subata 120"],
        ["Overclock: Swarm Grenade", "Reach level 18 with the Shredder Swarm Grenade"],
        ["Overclock: Tactical Leadburster", "Reach level 18 with the Tactical Leadburster"],
        ["Overclock: TH-0R Bug Taser", "Reach level 18 with the TH-0R Bug Taser"],
        ["Overclock: Voltaic Shock Fence", "Reach level 18 with the Voltaic Shock Fence"],
        ["Overclock: Voltaic SMG", "Reach level 18 with the 'Stubby' Voltaic SMG"],
        ["Overclock: Warthog Auto", "Reach level 18 with the 'Warthog' Auto 210"],
        ["Overclock: Wave Cooker", "Reach level 18 with the Colette Wave Cooker "],
        ["Overclock: Zhukov NUK17", "Reach level 18 with the Zhukov NUK17"],
        ["Perfect run", "Complete a dive without taking any damage"],
        ["Perfectly balanced", "Complete a dive with 4 (or more) of your weapons at the same level"],
        ["Pillar of Society", "Kill 15,000 enemies while standing still"],
        ["Pro side wobble compensator", "Equip 10 Overclocks in a single dive"],
        ["Professional setup", "Have 6 rare items equipped"],
        ["Professionals have standards", "Complete a dive with 4 [PRECISE] weapons equipped"],
        ["Relish the pain", "Deal over 1337 damage in one attack"],
        ["Roadkill", "Drill through a lootbug with B0b-33"],
        ["Rock and Stone!", "Remember to Rock and Stone!"],
        ["Run for the hills", "Unlock the Scout"],
        ["Salt Pits", "Win a Salt Pits Hazard 5 dive"],
        ["Salvage operation", "Salvage 10 overclocks in a single dive"],
        ["Sentry goin' up", "Complete a dive with 4 [TURRET] weapons equipped"],
        ["Slick, like butter", "Dodge 100 times during a run"],
        ["Spray 'n pray", "Complete a dive with 4 [SPRAY] weapons equipped"],
        ["Sprinkle of Nitra", "Collect 2,000 Nitra"],
        ["Squint and squeeze the trigger", "Reach 75% crit chance"],
        ["Still only counts as one!", "Kill the Dreadnought without taking any damage"],
        ["Stormbringer", "Complete a dive with 4 [ELECTRICAL] weapons equipped"],
        ["Survivor squad", "Reach level 30 with all 4 classes"],
        ["Swift guns for swift hands", "Reach 75% reload speed"],
        ["That's how the cookie crumbles", "Heal 500 HP during one dive"],
        ["The dwarf with the golden bug", "Kill a golden lootbug"],
        ["The journey begins", "Complete a dive with the Classic"],
        ["The only drilldozer here is me", "Mine an entire stage before moving B0b-33, then complete the dive"],
        ["They belong in a museum", "Complete a dive without any artifacts"],
        ["They fly now?", "Bounce 100 times in one stage"],
        ["They see 'em rollin', they hatin'", "Have 3 'Tank Tracks' overclocks in a single dive"],
        ["This hurts me more", "Kill all the lootbugs in a single dive"],
        ["This is brilliant, but I like this", "Have 2 'The Favourite' overlocks in a single dive"],
        ["Tough as nails", "Complete a dive with the Juggernaut"],
        ["Tower defense", "Have 50 turrets alive at the same time"],
        ["Tried and tested", "Complete a dive with 4 [MEDIUM] weapons equipped"],
        ["True Mastery: Azure Weald", "Complete an Azure Weald mastery dive at Hazard 5"],
        ["True Mastery: Breach Cutter", "Complete a Breach Cutter weapon mastery dive at Hazard 5"],
        ["True Mastery: Burst Fire Gun", "Complete a BRT7 Burst Fire Gun weapon mastery dive at Hazard 5"],
        ["True Mastery: Coil Gun", "Complete an ArmsKore Coil Gun weapon mastery dive at Hazard 5"],
        ["True Mastery: CRSPR Flamethrower", "Complete a CRSPR Flamethrower weapon mastery dive at Hazard 5"],
        ["True Mastery: Cryo Cannon", "Complete a Cryo Cannon weapon mastery dive at Hazard 5"],
        ["True Mastery: Cryo Grenade", "Complete a Cryo Grenade weapon mastery dive at Hazard 5"],
        ["True Mastery: Cryo Guard", "Complete an Arc-Tek Cryo Guard weapon mastery dive at Hazard 5"],
        ["True Mastery: Crystalline Caverns", "Complete a Crystalline Caverns mastery dive at Hazard 5"],
        ["True Mastery: DeepCore GK2", "Complete a DeepCore GK2 weapon mastery dive at Hazard 5"],
        ["True Mastery: DeepCore PGL", "Complete a DeepCore PGL weapon mastery dive at Hazard 5"],
        ["True Mastery: Firefly Hunter Drone", "Complete a Firefly Hunter Drone weapon mastery dive at Hazard 5"],
        ["True Mastery: HE Grenade", "Complete a High Explosive Grenade weapon mastery dive at Hazard 5"],
        ["True Mastery: Heavy Autocannon", "Complete a 'Thunderhead' Heavy Autocannon weapon mastery dive at Hazard 5"],
        ["True Mastery: Heavy Revolver", "Complete a 'Bulldog' Heavy Revolver weapon mastery dive at Hazard 5"],
        ["True Mastery: Hi-Volt Thunderbird", "Complete a Hi-Volt Thunderbird weapon mastery dive at Hazard 5"],
        ["True Mastery: Hollow Bough", "Complete a Hollow Bough mastery dive at Hazard 5"],
        ["True Mastery: Hurricane", "Complete a 'Hurricane' Guided Rocket System weapon mastery dive at Hazard 5"],
        ["True Mastery: Impact Axe", "Complete a Impact Axe weapon mastery dive at Hazard 5"],
        ["True Mastery: Incendiary Grenade", "Complete an Incendiary Grenade weapon mastery dive at Hazard 5"],
        ["True Mastery: Jury-Rigged Boomstick", "Complete a Jury-Rigged Boomstick weapon mastery dive at Hazard 5"],
        ["True Mastery: K1-P Viper Drone", "Complete a K1-P Viper Drone weapon mastery dive at Hazard 5"],
        ["True Mastery: Krakatoa Sentinel", "Complete a Krakatoa Sentinel weapon mastery dive at Hazard 5"],
        ["True Mastery: LMG Gun Platform", "Complete an LMG Gun Platform weapon mastery dive at Hazard 5"],
        ["True Mastery: LOK-1 Smart Rifle", "Complete a LOK-1 Smart Rifle weapon mastery dive at Hazard 5"],
        ["True Mastery: M1000", "Complete a M1000 weapon mastery dive at Hazard 5"],
        ["True Mastery: Magma Core", "Complete a Magma Core mastery dive at Hazard 5"],
        ["True Mastery: Neurotoxin Grenade", "Complete a Neurotoxin Grenade weapon mastery dive at Hazard 5"],
        ["True Mastery: Nishanka Boltshark", "Complete a Nishanka Boltshark weapon mastery dive at Hazard 5"],
        ["True Mastery: Plasma Burster", "Complete a Plasma Burster weapon mastery dive at Hazard 5"],
        ["True Mastery: Plasma Carbine", "Complete a DRAK-25 Plasma Carbine weapon mastery dive at Hazard 5"],
        ["True Mastery: Plasma Charger", "Complete an Experimental Plasma Charger weapon mastery dive at Hazard 5"],
        ["True Mastery: Powered Minigun", "Complete a 'Lead Storm' Powered Minigun weapon mastery dive at Hazard 5"],
        ["True Mastery: Salt Pits", "Complete a Salt Pits mastery dive at Hazard 5"],
        ["True Mastery: Seismic Repulsor", "Complete a Seismic Repulsor weapon mastery dive at Hazard 5"],
        ["True Mastery: Shard Diffractor", "Complete a Shard Diffractor weapon mastery dive at Hazard 5"],
        ["True Mastery: Sludge Pump", "Complete a Corrosive Sludge Pump weapon mastery dive at Hazard 5"],
        ["True Mastery: Stun Sweeper", "Complete a Voltaic Stun Sweeper weapon mastery dive at Hazard 5"],
        ["True Mastery: Subata 120", "Complete a Subata 120 weapon mastery dive at Hazard 5"],
        ["True Mastery: Swarm Grenade", "Complete a Shredder Swarm Grenade weapon mastery dive at Hazard 5"],
        ["True Mastery: Tactical Leadburster", "Complete a Tactical Leadburster weapon mastery dive at Hazard 5"],
        ["True Mastery: TH-0R Bug Taser", "Complete a TH-0R Bug Taser weapon mastery dive at Hazard 5"],
        ["True Mastery: Voltaic Shock Fence", "Complete a Voltaic Shock Fence weapon mastery dive at Hazard 5"],
        ["True Mastery: Voltaic SMG", "Complete a 'Stubby' Voltaic SMG weapon mastery dive at Hazard 5"],
        ["True Mastery: Warthog Auto", "Complete a 'Warthog' Auto 210 weapon mastery dive at Hazard 5"],
        ["True Mastery: Wave Cooker", "Complete a Colette Wave Cooker weapon mastery dive at Hazard 5"],
        ["True Mastery: Zhukov NUK17", "Complete a Zhukov NUK17 weapon mastery dive at Hazard 5"],
        ["Truly epic", "Equip an epic item"],
        ["Underclocked", "Complete a dive without any overclocks"],
        ["Underpromise, overdeliver", "Complete a dive with all of your weapons at level 1"],
        ["Unreasonable uptime", "Have a 30 second lifetime on one weapon with the Maintenance Worker"],
        ["Vanguard: Hazard 3", "Complete a vanguard contract dive at Hazard 3"],
        ["Vanguard: Hazard 4", "Complete a vanguard contract dive at Hazard 4"],
        ["Vanguard: Hazard 5", "Complete a vanguard contract dive at Hazard 5"],
        ["Walk without rhythm", "Deploy 30 seismic repulsor turrets at the same time with the Heavy Gunner"],
        ["We're keeping this one", "Fully upgrade a piece of gear"],
        ["Weight of fire", "Complete a dive with 4 [PROJECTILE] weapons equipped"],
        ["What's in the box!?", "Gain 10 mastery levels"],
        ["Who touched my gun!?", "Complete a dive with 4 [HEAVY] weapons equipped"],
        ["Why so Salty?", "Reach 50 armor"],
        ["With fire and blood", "Deal 10,000,000 fire damage as the Foreman in a single dive"],
        ["Works 100% of the time", "Collect 25 magnets"],
        ["You're locked in here with me", "Survive in 1 stage for 10 minutes as the Recon"],
        ["Zone of control", "Complete a dive with 3 [AREA] weapons equipped"],
    ];

    assert.strictEqual(officialAchievements.length, 300, "sanity check on this test's own reference list");

    const dataPairs = game.achievements
        .map(a => [a.name, a.description])
        .sort((a, b) => a[0].localeCompare(b[0]));

    assert.deepStrictEqual(dataPairs, [...officialAchievements].sort((a, b) => a[0].localeCompare(b[0])));

});
