import { test } from "node:test";
import assert from "node:assert";

import { getPlannerData } from "../utils/plannerCatalog.js";

// backend/catalog/games/europa-universalis-4.json - 373 real achievements sourced
// from a live ISteamUserStats/GetSchemaForGame/v2 response for appid
// 236850 (fetched through this app's own services/steamApi.js).
// This game has no hidden achievements: all 373 ship a real, official
// Steam description, quoted verbatim below.
// difficulty/estimatedTime/missable remain curatorial judgments.
const game = getPlannerData("europa-universalis-4");

test("getPlannerData('europa-universalis-4') returns real planner data with 373 curated achievements", () => {

    assert.ok(game, "expected real planner data for europa-universalis-4");
    assert.ok(Array.isArray(game.achievements));
    assert.strictEqual(game.achievements.length, 373);

});

test("every Europa Universalis IV achievement has a unique id from 1 to 373 and a unique apiname", () => {

    const ids = game.achievements.map(a => a.id);
    const apinames = game.achievements.map(a => a.apiname);

    assert.deepStrictEqual([...ids].sort((a, b) => a - b), Array.from({ length: 373 }, (_, i) => i + 1));
    assert.strictEqual(new Set(ids).size, 373);
    assert.strictEqual(new Set(apinames).size, 373);

});

test("every Europa Universalis IV achievement has a valid difficulty (1-5), a positive estimatedTime, and non-empty name/description", () => {

    for (const achievement of game.achievements) {

        assert.ok(
            Number.isInteger(achievement.difficulty) && achievement.difficulty >= 1 && achievement.difficulty <= 5,
            `${achievement.name} has an out-of-range difficulty: ${achievement.difficulty}`
        );

        assert.ok(
            Number.isInteger(achievement.estimatedTime) && achievement.estimatedTime > 0,
            `${achievement.name} has an invalid estimatedTime: ${achievement.estimatedTime}`
        );

        assert.ok(achievement.name?.length > 0, "achievement is missing a name");
        assert.ok(achievement.description?.length > 0, `${achievement.name} is missing a description`);
        assert.ok(achievement.apiname?.length > 0, `${achievement.name} is missing an apiname`);

    }

});

test("every one of the 373 Europa Universalis IV achievement name+description pairs matches the live GetSchemaForGame response", () => {

    const officialAchievements = [
        ["A Blessed Nation", "As a Coptic Nation, gain all 5 Blessings."],
        ["A Decent Reserve", "Have a maximum manpower of at least 1 million."],
        ["A Fine Goosestep", "Form Prussia and have at least 125% Discipline."],
        ["A Golden Empire", "Enact a Golden Age as an Empire."],
        ["A Hero’s Welcome", "Starting as Karaman, form the Sultanate of Rum"],
        ["A Kaiser not just in name", "Form the Holy Roman Empire."],
        ["A Manchurian Candidate", "Start as one of the Jurchen tribes and form Qing."],
        ["A Pile of Gold", "Own 10 provinces which produce gold."],
        ["A Protected Market", "Have 100% Mercantilism."],
        ["A Sun God", "Form Inca, embrace all Institutions and own all of South America as core provinces."],
        ["A tale of two Families", "Starting as Vijayanagar or Bahmanis conquer the other’s capital and have them not exist."],
        ["AAA Credit", "As a Great Power, take on over 1,000 ducats of another nation’s debt."],
        ["Absolutely", "Gain 100 Absolutism."],
        ["Abu Bakr II’s Ambition", "Start as Mali and have 4 Colonial Subjects in South America."],
        ["Academical", "As Athens, own 50 universities."],
        ["AEIOU", "Complete the Austrian mission tree."],
        ["African Power", "Own and have cores on all provinces in Africa as Kongo."],
        ["Aggressive Expander", "Own 200 provinces."],
        ["Albania or Iberia", "As Albania, own or have a subject own Iberia and the Caucasus."],
        ["All belongs to Mother Russia", "Start as a country of Russian culture and form Russia."],
        ["All Blue", "As Portugal, all of Europe is owned by you or blue European countries that exist in 1444."],
        ["All That's Thine Shall Be Mine", "As a Greedy ruler, take all of a nation’s ducats in a peace deal."],
        ["All Your Trade Are Belong to Us", "Have the highest trade power in Genoa, Venice and English Channel while having an income of at least 300 ducats per month."],
        ["Almost Prussian Blue", "Starting as the Livonian Order, form Livonia and own the territory of the North German Confederation as core provinces."],
        ["An early Reich", "Form Germany."],
        ["An Industrial Evolution", "As Great Britain, own all of England as core provinces and have at least 25 development in each province there."],
        ["An Unlikely Candidate", "Starting as Mzab, Touggourt or Djerid, reform Al-Andalus."],
        ["Anglophile", "Complete all English and British missions."],
        ["Arabian Coffee", "Form Arabia and be the nation producing the most coffee in the world."],
        ["Around the World in 80 Years", "Starting as a Custom Nation of up to 400 points in the British Region, own New York, San Francisco, Suez, Bombay, Calcutta, Hong Kong and Yokohama by 1524.11.11."],
        ["Assembly Instructions Needed", "Form Scandinavia and revoke the privilegia of the Holy Roman Empire while being the Emperor."],
        ["At every continent", "Own one province on each continent."],
        ["Atwix Legacy", "Have 10 personal unions at the same time."],
        ["Auld Alliance Reversed", "As Scotland, have France as a vassal (do not form Great Britain)."],
        ["Australia-Hungary", "Starting as an Australian tribe unite Australia and subjugate Hungary."],
        ["Avar Khaganate", "Achieve Empire rank and conquer Hungary as Avaria."],
        ["Azur semé de lis or", "Get all the French Cores as France."],
        ["Baa Baa Black Sheep", "As Qara Qoyunlu become the leading producer of wool."],
        ["Baborg", "As the Mughals, assimilate at least 12 culture groups."],
        ["Back in Control", "Form Yuan and be the only nation holding land in China"],
        ["Back to the Piast", "As Mazovia, Glogow or Opole, form the nation of Poland."],
        ["Baltic Crusader", "As Teutonic Order or Livonian Order, own all of Russia as core provinces and convert it to Catholic."],
        ["Barbarossa", "As a Maghrebi nation, have 500 light ships privateering at the same time."],
        ["Basileus", "As Byzantium, restore the borders of the Eastern Roman Empire in the Balkans and Anatolia."],
        ["Basque in Glory", "Starting as Navarra, ensure that most of Iberia is Basque culture before the Age of Absolutism."],
        ["Bengal Tiger", "Start as Bengal and own Samarkand as a core province."],
        ["Better than Napoleon", "As France, own Vienna, Berlin and Moscow as core provinces."],
        ["Big Blue Blob", "As France, hold 100 European core provinces before 1500."],
        ["Black Jack", "Have at least 21 different subjects with 5 cities each and without any subject having 50% or more Liberty Desire. Trade Companies do not count."],
        ["Bleed Them Dry", "Have 10 different War Reparations being paid to you at the same time."],
        ["Blockader", "Blockade at least 10 ports of one enemy."],
        ["Blood for the Sky God!", "As a Tengri nation, have Nahuatl as your syncretic faith."],
        ["Breadbasket of the World", "As the Mamluks, export grain to every continent at least once."],
        ["Breaking the Yoke", "As Ryazan, own Saratov, Crimea and Kazan while being independent"],
        ["Brentry", "Starting as England, form the Angevin Kingdom and enact all the Acts of Crown parliamentary issues."],
        ["Brick by Brick", "Starting as Denmark, enact the Unified Kalmar Monarchy government reform and own the entire Scandinavian region as your cores."],
        ["Bright Spark", "Have 50 Innovativeness."],
        ["Brothers in Arms", "Win a war as a secondary participant."],
        ["Bunte Kuh", "As Hamburg, trade in both Gems and Livestock."],
        ["Carthago Delenda Est", "As an Italian culture nation, make sure entire Tunis Area is at 100 devastation."],
        ["Center of Attention", "Own both a Protestant and a Reformed Center of Reformation."],
        ["Cherrypicking", "Conscript a 3 star general from a Daimyo Subject."],
        ["Chop Chop", "With only one Monarch, have six different Consorts."],
        ["Choson One", "As Korea, own or have a subject own all Shinto, Confucian and Buddhist provinces in the world."],
        ["Cities of Cibola", "As a Nation that has Pueblo as primary culture, own at least 7 provinces with 10 development each."],
        ["City of Cities", "Own a core province with at least 60 development."],
        ["Cold War", "Win a war without fighting a single battle."],
        ["Colonial Management", "Have 3 colonial governors that were directly appointed by you at the same time."],
        ["Combined Arms", "Have both an Admiral and a General with a trait."],
        ["Consulate of the Sea", "As Aragon conquer all Mediterranean Centers of Trade."],
        ["Copium Wars ", "Starting and playing as Ming, own the Britain region."],
        ["Core-fu", "Force a nation to revoke 5 cores in one peace deal as Corfu."],
        ["Cotton Kandy", "As Kandy be production leader in Cotton."],
        ["Cowardly Tactics", "Have a fort and a supply depot in a mountainous province producing livestock."],
        ["Crossing the Finnish Line", "Release and play as Finland in 1444 and have a direct land connection to the Cape while your capital is in Nyland/Uusimaa."],
        ["Czechs and Balances", "Starting as Bohemia, grant at least two privileges to each estate while having at least 50% Crown Land."],
        ["Dar al-Islam", "Unify Islam under your rule."],
        ["David the Builder", "As Georgia have no free building slots in any owned province."],
        ["Defender of the Faith", "Become Defender of the Faith."],
        ["Definitely the Sultan of Rum", "Own and have cores on Rome, Moscow and Istanbul as Ottomans or Rum."],
        ["Desert Power", "Starting as an Arabian Tribe, have the Oasis privilege enacted, and more than 1000 development in the Arabian Region."],
        ["Die Please Die", "Have a ruler with 1 or lower in all three categories who is over the age of 70."],
        ["Disciples of Enlightenment", "Starting as Dai Viet, have 10 nations follow the Mahayana Faith by 1500."],
        ["Doge Coins", "Starting as Venice, become the Economic Hegemon."],
        ["Don’t be Cilli", "Starting as Cilli, form another nation."],
        ["Double the Love", "Start with no unions and get two at the same time."],
        ["Dovmont's Own", "Starting as Pskov, have 100 standing Streltsy units"],
        ["Down Under", "Have a colony in Australia."],
        ["Dracula's Revenge", "Start as Wallachia or Moldavia, form Romania and own or have a subject own all of the Balkans."],
        ["Dude, Where's my Boat?", "Capture 20 boats with the Boarding Naval Doctrine."],
        ["Early-Modern Warfare", "Have 100 regiments at 100% Army Drill."],
        ["Eat your Greens", "Control all Grasslands in Asia as Kale before the age of Absolutism."],
        ["Electable!", "Become an elector in the HRE as a country which does not start as elector."],
        ["Emperor of Hindustan", "Starting as Delhi, Restore their Empire's borders."],
        ["Empire of Mann", "As Mann, conquer all Islands in the world."],
        ["Even Better than Piet Heyn", "Gain over 100 gold from privateering a single treasure fleet."],
        ["Everything's Coming Up Mulhouse", "Starting as Mulhouse, become Emperor of the HRE and completely decentralize the Empire."],
        ["Factionalism", " Have 3 different estates in your country with at least 70% influence each."],
        ["Fanatic Collectivist", "Own all Institution Origin provinces."],
        ["Fine Financials", "Own Eight level 3 Centres of Trade."],
        ["First Come, First Serve", "Starting as a Western technology custom nation in North America or South America with no more than 200 points, unite the two continents."],
        ["For Odin!", "Starting as a Norse custom nation with no more than 200 points and a maximum of 5 provinces, own & core Scandinavia and the British Isles and convert it all to Norse."],
        ["For the Emperor!", "Form Prussia or Germany, have the Empire government rank and 40.000 Marines raised at the same time."],
        ["For the Glory", "Diplo-annex a vassal."],
        ["Foremost Servitor of Jagannath", "Start as Orissa and own or have a subject own all tropical wood provinces."],
        ["Forever Golden", "Complete the Spanish Mission Tree."],
        ["Forgive me, for I have Sindh", "Become Christian as Sindh."],
        ["Foul Mouthed", "Scornfully insult 10 nations that border you."],
        ["Four For Trade", "Form four Trade Companies and get bonus merchants from all of them."],
        ["From Frankfurt to the Andes", "Starting as Frankfurt, form Jerusalem, and then form the Inca while owning Mallorca."],
        ["From Humble Origins", "Starting as a custom nation with no more than 50 points, have at least 2000 total development."],
        ["Frozen Assets", "Start as Novgorod and control 90% of the trade power in the White Sea trade node while it is the highest valued trade node in the world."],
        ["Fugger Banking", "As Augsburg, subsidize 3 Great Powers 20% of their income while having less than 20 provinces."],
        ["Full House", "Have 3 Vassals and 2 Marches at the same time."],
        ["Ganges Khan", "Start as Tribal nation in India and become a Steppe Horde."],
        ["Gentle Persuasion", "Have a Siege Specialist general win a siege in a province with a fort."],
        ["Georgia on my Mind", "Fully own all three Georgias."],
        ["Get out of my swamp!", "As the Netherlands, own all of the Low Countries and have 50% or more Fort Defense."],
        ["Global Hegemony", "Reach 100% Strength as any type of Hegemon."],
        ["God Tier", "Become a Tier 5 Defender of the Faith as a nation that is neither Catholic nor Sunni."],
        ["Gold Rush", "Reform the Golden Horde before 1500."],
        ["Golden Horn", "As a Somali nation, fully own the Horn of Africa region and have a monthly gold income of at least 10 ducats."],
        ["Golden Wind", "As Air, make 50 ducats profit per month and have 50% of your income made through gold provinces."],
        ["Good King René", "Start as Provence, form the Kingdom of Jerusalem."],
        ["Gothic Invasion", "Start as Theodoro and conquer all Germanic culture provinces in Europe."],
        ["Grand Coalition", "Join a coalition of more than 5 nations."],
        ["Grand Duchy", "Starting as a Duchy, have 1000 development without upgrading your government rank."],
        ["Great Moravia", "Restore the Great Moravian borders as Nitra or Moravia."],
        ["Great Perm", "As Perm, own or have a subject own the Russian, Siberian, Scandinavian, Canadian, Hudson Bay and Cascadian Regions."],
        ["Guarantor of Peace", "Guarantee the Independence of France, The Ottoman Empire and Russia."],
        ["Hanukkah Mutapa", "Starting as Mutapa, convert to Judaism and celebrate a festival."],
        ["Hard Bargaining", "As Defender of a Muslim Faith, propagate your religion in The Moluccas through trade to convert 5 provinces."],
        ["Hessian Mercenaries", "As Hesse, have at least 50 regiments of mercenaries and no loans."],
        ["Hoarder", "As a Fetishist nation, have 13 available Cults."],
        ["Holiest Roman Empire", "As either the Papal States or the Emperor, have the Papal States as an Elector while the HRE is officially Catholic."],
        ["Holy Horder", "Starting as the Teutonic Order, form the Mongol Empire while have the Holy Horde government reform enacted."],
        ["Holy Trinity", "As the Papacy, own Jerusalem and have Livonian Order, Teutonic Order and The Knights as Marches."],
        ["Home and Away", "As Wales, hold Cardiff, Dublin, Edinburgh, Rome, Paris and London."],
        ["I don't like sand", "Have the most development while owning no province with terrain other than desert or coastal desert."],
        ["I’ll graze my horse here.. And here…", "As a Horde, own over 200 provinces producing grain."],
        ["Ideas Guy", "Starting as a custom nation with the full 800 points but no more than 3 total development, have a monthly income of at least 500 ducats."],
        ["Imperio español", "As Spain have Mexico, Panama, Havana, Cuzco in colonial Nations under you."],
        ["Imposter Syndrome", "As Sus, have three countries hostile to you (less than 0 opinion) after they discovered your spy."],
        ["In the Name of the Father", "As an Orthodox country, have 100 Patriarch Authority."],
        ["Industrial Powerhouse", "Have 10 furnaces built in your nation."],
        ["Inner Turmoil", "Starting as The Isles, own 20 provinces by 1500, none of which are on Islands."],
        ["Isn't this the way to India?", "Discover the Americas as Castile or Spain."],
        ["It's all about luck", "Win a battle against a great leader, without a leader."],
        ["It's all about the money", "Accumulate 3000 gold."],
        ["It's all coming together", "Complete the Incan mission tree (Sunset invasion missions excluded)."],
        ["It's All Greek To Me", " Form Greece and own and have cores on Zeta, Thatta, Lamba, and Roh"],
        ["Italian Ambition", "Form Italy."],
        ["Je maintiendrai", "Form the Netherlands as a minor nation starting with Dutch culture."],
        ["Jihad", "As Najd, own 500 Sunni provinces."],
        ["Just a Little Patience", "Play a campaign from 1444 until 1820."],
        ["Just Resting In My Account", "Corrupt the officials in a Rival country."],
        ["Keep the Flame Burning", "As a Zoroastrian nation, own all Religious Centers and Monument Baku Ateshgah on tier 3."],
        ["KHAAAAAAN", "Restore the Mongol Empire before the Age of Absolutism."],
        ["King of Jerusalem", "Form the Kingdom of Jerusalem as Cyprus or The Knights."],
        ["King of Kings", "Complete the Persian mission tree."],
        ["Kingdom of God", "Starting as the Papal State, become the Kingdom of God"],
        ["Kinslayer", "As Tver, Yaroslavl, Ryazan, Beloozero, Rostov or Odoyev, eliminate all other Rurikovich nations without changing your ruling dynasty."],
        ["Kirishitan Japan", "Start as a Japanese Daimyo, convert yourself and all of Japan to Christianity."],
        ["Knights of the Caribbean", "Starting as the Knights, own the Caribbean and every island in the Mediterranean. (Colonies are NOT allowed)"],
        ["Komnenoi Empire", "As Trebizond, have the Empire government rank."],
        ["Kow-Tow", "As Ming, have a subject from each religion group."],
        ["Krabater", "Form the nation of Croatia and station a unit of cavalry in Stockholm."],
        ["Kuban Cigars", "As Kuba, own or have a subject own Havana and be the world’s leading producer of Tobacco."],
        ["Kushite Restoration", "As a Nubian culture nation, own or have a non-Tributary subject own the entire Egyptian region."],
        ["Land of Eastern Jade", "Own a core province in the Mexico region as a Buddhist country."],
        ["Laughingstock", "Own the provinces of Haha, Hehe and Lolland"],
        ["Lazarus", "As Serbia, own the entire Balkans as core provinces."],
        ["Legacy of Saint George", "As Georgia, have Genoa, Aragon, England, and Trier as vassals, while controlling Wales."],
        ["Lessons of Hemmingstedt", "As Dithmarschen, hold the provinces of Sjaelland and Holland while Denmark do not exist"],
        ["Let It Go!", "Starting as Norway, have your capital in the Canada region while not owning any province in Scandinavia and not playing as a released subject."],
        ["Liberty or Death", "Start as USA in 1776 bookmark and own all your cores while being at peace."],
        ["Lion of the North", "Start as Sweden and lead the Protestant League to victory against the Emperor."],
        ["Live Long and Prosper", "Have 30 states with prosperity at the same time as you have a 70 year old ruler."],
        ["Luck of the Irish", "Own and have cores on the British Isles as an Irish nation."],
        ["Lucky Lucca", "As Lucca, own Lucknow!"],
        ["Made in Japan", "Embrace \"manufactories\" institution as Japan by 1655."],
        ["Magellan’s Voyage", "Make the first circumnavigation."],
        ["Maharana Pratap", "Start as Mewar and field an army of 20 Rajput regiments."],
        ["Mansa Musa", "As Mali, give 10k ducats away to another great power without having a single loan or being bankrupt."],
        ["Mare Nostrum", "Restore the Roman Empire and own the entire Mediterranean and Black Sea coast lines."],
        ["Market Control", "Be trade leader of seven different goods."],
        ["Marshy March", "Have a march with at least two marsh provinces."],
        ["Mary of Lotharingia", "Starting as Burgundy, form Lotharingia and have a female ruler named Marie."],
        ["Mass Production", "Starting as Odoyev, own one of every manufactory"],
        ["Master of India", "Own and have cores on all of India as a European nation."],
        ["Mayapahit?", "Starting as any Mayan country, form Maya and own or have a subject own the island of Java."],
        ["Mehmet's Ambition", "Starting as The Ottomans, own or have Core Eyalets own all the provinces required to form the Roman Empire before 1500."],
        ["Meissner Porcelain", "As Saxony, own or have a subject own all Chinaware provinces in the world."],
        ["Mets Hayk", "Starting as Karabakh, own, core, and convert to Coptic the borders of Great Armenia."],
        ["Mewar Never Changes", "Complete the Mewar Mission Tree."],
        ["Multiculturalism", "Have 4 different Cultures and 4 different religions represented in your court."],
        ["My armies are invincible!", "Gain at least 7.0 land morale."],
        ["My True Friend", "Go to war in support of a rebel faction and win, enforcing their demands."],
        ["Napoleon’s Ambition", "As Revolutionary France, spread the Revolution to 10 countries."],
        ["Narcissism", "Name a general after yourself and lead your army to victory."],
        ["Neither Holy, Nor German", "Have 7 Free Cities in the Empire, none of which is of a Germanic culture."],
        ["Networking", "Have 100 point spy networks in 3 Rival nations."],
        ["Never say Nevers", "As Nevers, own the entire France region as core provinces."],
        ["New, New Deli", "As Deli, have your capital in the Delhi province."],
        ["No Country for Old Tercios", "As Spain have Reformed Tercios, 33 Tercio Units, and control 3 Great Power capitals at the same time"],
        ["No Pirates in my Caribbean", "Own or have a subject own the entire Caribbean."],
        ["No Trail of Tears", "Own and have cores on the Thirteen Colonies as Cherokee with all institutions embraced."],
        ["Nobody wants to die", "Own Timbuktu as Songhai"],
        ["Norwegian Wood", "Own or have a subject own all naval supplies provinces as Norway."],
        ["Not just Pizza", "Become a Great Power as Naples."],
        ["Not so sad a state...", "As Portugal, have a colony in Brazil and in Africa."],
        ["On the Edge of Madness", "As Aztecs, reach 95 Doom, then go 20 years without Doom hitting 100."],
        ["On the Rhodes Again", "Starting as The Knights, conquer and core Constantinople, Jerusalem and Antioch."],
        ["One Faith", "Have all non-wasteland land provinces in the world be of your religion."],
        ["One Family to Rule them All", "Have your dynasty on 8 thrones at the same time. Client states do not count."],
        ["One King to Rule!", "As Poland, become an absolutist monarchy, abolishing the Sejm."],
        ["One nation to rule them all", "As Saruhan, have at least 9 loyal vassals with at least 100 development each."],
        ["One Night in Paris", "Start as England, own and have a core on Paris (do not form another country unless it's Great Britain or the Angevin Kingdom)."],
        ["Østindisk Kompagni Te", "As Denmark establish Trade company and have at least 10% Tea market share."],
        ["Over a Thousand!", "Own 1001 provinces directly."],
        ["Pandya Empire", "Starting as Madurai, conquer the Pandya Territories."],
        ["Parisian Pasha", "Assign Pasha to Paris."],
        ["Philippine Tiger", "As Cebu, recreate the Chola Empire."],
        ["Pick Your Poison", "As Kaffa, develop in Cafa while a subject of yours owns it."],
        ["Pirate Bay of Janjira", "Have more than 50% Privateering power in the Gujarat trade node"],
        ["Poland can into space", "As Poland, reach the maximum level in all technologies (32)."],
        ["Populists in Government", "Switch government type through government reforms."],
        ["Prester John", "Starting as Ethiopia, own and have cores on Alexandria, Antioch and Constantinople as a Coptic country."],
        ["Protect the Secret", "As Yemen, prevent any European Nation from owning a Coffee-producing province in the Old World until 1700."],
        ["Purify the Temple", "Starting as Riga, enact the Salvific Plutocracy government reform and raid the heretic church of Rome."],
        ["Pyramid of Skulls", "As a Steppe Horde, raze a province with at least 30 development."],
        ["Qing of China", "Become Chinese Emperor as Qing and own all of China."],
        ["Queen of Conquest", "Conquer land while in a Queen Regency."],
        ["Queen of Mercury", "As Kilwa, own and have cores on Zanzibar and Bombay (Thana)."],
        ["Quizquiz Pro Quo", "As Quizquiz, have your capital in the Anjou province."],
        ["Rags and Riches", "Have the highest income in the world while neither owning nor starting with a province with a development level higher than 10."],
        ["Raja of the Rajput Reich", "Conquer all of Germany as Nagaur."],
        ["Redecorating", "Starting as an Orthodox Nation, Consecrate Metropolitan in Roma"],
        ["Rekindling the Flames", "Starting as a Zoroastrian custom nation with no more than 200 points and a maximum of 5 provinces, rekindle the royal fires."],
        ["Relentless Push East", "Starting as a Russian nation, By 1600 own the East Siberian Coastline"],
        ["Respected", "Have 100 prestige, 100 legitimacy and three stability."],
        ["Restore the Pentarchy", "Starting as Byzantium, own Rome, Constantinople, Alexandria, Antioch, and Jerusalem while being Orthodox."],
        ["Rise of the White Sheep", "As Aq Qoyunlu, own Tabriz and have Qara Qoyunlu not exist by 1478."],
        ["Royal Authority", "Install a union through a succession war."],
        ["Rozwi Empire", "Starting as Butua, conquer Mutapa (Zimbabwe and Lower Zambezi areas)."],
        ["Ruina Imperii", "Dismantle the Holy Roman Empire."],
        ["Sailor Mon", "As Pegu, have at least 100,000 sailors."],
        ["Sakoku Law", "Go full isolationist in 6 Incidents."],
        ["Saladin's Legacy", "Playing as Hisn Kayfa, reforge the Ayyubid Empire."],
        ["Seriously?!", "Kill 10,000 men in one battle."],
        ["Shahanshah", "Start as Ardabil and form Persia or Eranshahr."],
        ["Shemot is Not", "As a Jewish nation, convert all of Egypt to Jewish while having the Jewish Community Aspect active."],
        ["Sikh Pun", "Convert to Sikhism and form the nation of Punjab."],
        ["Sinaasappel!", "Get Orangists in power with 100% Republican Tradition, and owning a province in China."],
        ["Sleepless in Seattle", "Own 10 Coffee producing provinces, and have your capital in Salish."],
        ["Sons of Carthage", "As Tunisia, own and have cores on Sicily, Sardinia, the Balearic Islands, the coast of Algiers and the southern coast of Spain."],
        ["Spaghetti Western", "Starting as Bologna, become Mexico or Texas."],
        ["Spain is the Emperor", "Become the Emperor of the Holy Roman Empire as Spain."],
        ["Spanish Fly", "Starting as Offaly, secure a Personal Union over an Iberian nation."],
        ["Spice Girls", "Having a female ruler, have active trading bonuses for Cloves, Spices, Salt and Sugar."],
        ["Stardust Crusaders", "As Japan have the Land of the Christian Sun reform while Palestine and Cairo are Christian under us."],
        ["Stern des Südens", "Form Bavaria starting as München and have your Subject Bremen own Werder."],
        ["Stiff Upper Lippe", "As Lippe, own all of the British Isles."],
        ["Strait Talk", "As Hormuz, have at least 10 diplomatic reputation"],
        ["Subsidize my Love", "Subsidize 3 different allies at least 50% of their monthly income without running a deficit."],
        ["Sun Invasion", "As the Madyas, own and have cores on Tepeacac, Mexico, Tullucan and Huastec."],
        ["Sunset Invasion", "Own and have cores on Lisbon, Madrid, Paris, London, Amsterdam and Rome as the Aztecs."],
        ["Super Trooper", "Starting as Sweden, enact the Allotment System government reform, have 80 regiments of Carolean raised at the same time with at least +40% infantry combat ability."],
        ["Surfing USA", "Form the USA as Hawaii."],
        ["Swahili Persuasion", "As Kilwa, convert all of the Moluccas and Indonesia."],
        ["Sweden is not overpowered!", "Own and have cores on the entire Baltic coastline as Sweden."],
        ["Sweet Harmony", "Harmonize 7 religions as Confucian."],
        ["Sweet Home Qaraqorum", "As the Mughals assimilate Mongolian culture."],
        ["Switzerlake", "Own 99 provinces as Switzerland while owning no ports."],
        ["Sworn Fealty", "Starting as an Arabian Tribal Federation, unite Arabia and have maximum Tribal Allegiance."],
        ["Take that, von Habsburgs!", "Starting as Hungary, own all of Austria as core provinces."],
        ["Tatarstan", "As Kazan or Nogai, own all Tatar culture group lands."],
        ["Tear Down This Wall", "Use Artillery Barrage on Berlin."],
        ["Terra Mariana", "As Riga, own or have a subject own the Baltic region."],
        ["That is mine!", "Conquer a province."],
        ["That's a Grand Army", "Build up your army to your country's maximum army forcelimit."],
        ["That's a Grand Navy", "Build up your navy to your country's maximum navy forcelimit."],
        ["That's a Silk Road", "Own or have a subject own all provinces in the world producing silk."],
        ["That's No Mon", "As Pegu, own at least 50 provinces that are not of the Mon culture."],
        ["The 52 Garhs", "As Garhwal own and maintain 52 forts without going into debt"],
        ["The Animal Kingdom", "As Manipur, unite the Bengal region and convert it to Animism."],
        ["The Bohemians", "As Bohemia, own Dublin as a core province."],
        ["The Buddhists Strike Back", "As Kotte or Kandy, own all of India and convert it to Theravada Buddhism."],
        ["The Burgundian Conquest", "As Burgundy, own the Low Countries region as core provinces and have France and Austria as your subjects."],
        ["The Chrysanthemum Throne", "Unite Japan as a Daimyo."],
        ["The Coin is Stronger than the Sword", "Charter Company from an Indian nation."],
        ["The Continuation of Diplomacy", "Successfully use Threaten War to gain a province from another nation."],
        ["The Eagle flies alone", "Starting as Hisn Kayfa, reach a forcelimit of 500k."],
        ["The Emperors new clothes", "Overthrow Austria and become the Emperor of the Holy Roman Empire."],
        ["The Fezzan Corridors", "As Fezzan, control at least 90% of the trade power in Tunis, Katsina, Safi and Timbuktu."],
        ["The First Toungoo Empire", "As Taungu, unite the Burman culture group by 1500."],
        ["The Five Colonies", "Have five colonial nations."],
        ["The Freest Man in the World", "Ensure that no colonized province in the world produces slaves while having the War Against the World Doctrine government reform enacted."],
        ["The Grand Armada", "Have 500 heavy ships and no loans."],
        ["The Great Khan", "Starting as Mongolia or Great Horde, own or have a subject own the Chinese, Russian and Persian regions."],
        ["The Hungarian Games", "Starting as Hungary, win 23 battles with the Black Army against at least 12 different countries."],
        ["The Iron Price", "Restore the Danelaw region to Danish rule, and make it Danish culture."],
        ["The Last Crusade", "Starting as Byzantium, control Venezia, and make sure that the country Venice doesn't exist."],
        ["The League of Mayapan", "Starting as Huastec, form Maya."],
        ["The Levant Turnabout", "As the Mamluks, have 100 Army Professionalism and annex the Ottomans."],
        ["The Navigator", "As Portugal, own provinces in Africa, India and Indonesia before 1500."],
        ["The Ostenders", "As Austria or AH have the District and Military Administration investments in the West Bengal area."],
        ["The pen is mightier than the sword", "Have three unions at the same time as Austria or Austria-Hungary."],
        ["The Pheasant Strut", "As Gorkha form Nepal and defeat Prussia with at least 100,000 Prussian casualties in a war (both have to be primary targets of war)."],
        ["The Power of Three", "Own a Crown Colony, a Self-Governing Colony and a Private Enterprise."],
        ["The Prince of Egypt", "Starting as Florence, form Egypt."],
        ["The Princess is in this Castle", "As a country that does not start with a female heir, have a female heir while having a Castle in your capital (more advanced fort buildings do not count)."],
        ["The Re-Reconquista", "As Granada, form Andalusia and reconquer all of Iberia."],
        ["The Reapers", "Starting as Aragon, be a Peasant Republic and have Madrid and Paris owned by any Peasant Republic."],
        ["The Rising Sun", "Own and have cores on all of Japan as a European nation."],
        ["The Six Nations", "Form a Federation of at least six nations as the Iroquois."],
        ["The Spice Must Flow", "Form the nation of Malaya."],
        ["The Sudanese Expedition", "Starting as Morocco, conquer the Niger and Sahel Regions."],
        ["The Sun Never Sets on the Indian Empire", "Form Hindustan or Bharat and own or have a subject own Cape, London, Hong Kong (Canton) and Ottawa (Kichessipirini)."],
        ["The Third Way", "Start as an Ibadi nation and eliminate all rival schools of Islam (do not convert to another religion)."],
        ["The Three Mountains", "Own or have a subject own the entire world as Ryukyu."],
        ["The Uncommonwealth", "As Lithuania, become The Commonwealth."],
        ["The White Company", "Join a war on the other side of someone to whom you have rented condottieri."],
        ["The White Elephant", "As Ayutthaya, own all of Indochina and Burma as core provinces."],
        ["The Zoro-Austrians", "Starting as Austria, convert to Zoroastrianism, and complete the Persian Zoroastrian missions."],
        ["There Khan only be one!", "Starting as a Steppe Horde, ensure there exists no other horde than you on the world."],
        ["These Banners need a Saga", "Starting as a Jurchen nation, have 100 regiments of Banners raised at the same time."],
        ["This is fine", "Have at least +10 Global Unrest and be in a winning coalition war, which was targeted against you."],
        ["This is My Faith", "Convert to Protestantism and unlock 3 Aspects of Faith."],
        ["This is Persia!", "Form Persia or Eranshahr, and own Egypt, Anatolia and Greece as core provinces."],
        ["This navy can take it all", "Gain at least 7.0 naval morale."],
        ["This Revolution Was Crushed", "In a war against the target of the Revolution, control their capital and have at least 99% war score."],
        ["Three Trivial Tributary Tribes", "Have 3 Tribal States as Tributaries."],
        ["Tiger of Mysore", "Starting as Mysore, Conquer the Deccan and Coromandel Regions."],
        ["Time Bandit", "Successfully steal a map from another nation."],
        ["Timurizz", "Starting as the Timurids, have 75 prestige, and 5 allies with 100 Trust and 150 opinion "],
        ["To the Bone", "As Bone, use pillage capital at least 7 times."],
        ["Total Control", "Own 100 or more provinces with no local autonomy or unrest."],
        ["Trade Hegemon", "Starting as any European country, conquer and have cores on Aden, Hormoz and Malacca."],
        ["Traditional Player", "More than 90 percent Naval and Army Tradition."],
        ["Triple the Rome", "As Russia, be the Emperor of China and the HRE."],
        ["Trophy Hunter", "Capture an enemy flagship."],
        ["True Catholic", "Control three Cardinals."],
        ["True Heir of Timur", "Starting as a Timurid subject, form the Mughals and conquer India by 1550."],
        ["Truly Divine Ruler", "Get a 5/5/5 Ruler or higher."],
        ["Truly Good Maaaaa-tch", "Starting as either Aq Qoyunlu or Qara Qoyunlu, have a royal marriage and an alliance with Ramazan."],
        ["Trustworthy", "Have five allies with 100 trust towards you each."],
        ["Turkish Delight", "Start as Candar and own 20 Sugar provinces between you and your subjects."],
        ["Turn the Table", "As a colony, break free and vassalize your former overlord without forming any other nation."],
        ["Turning the Tide", "Start as a Steppe Horde in 1444 and embrace all institutions."],
        ["Turtles all the way down", "As Korea get 135% Ship Durability."],
        ["Ultimate Military", "As Songhai, have Prussia and Nepal as marches!"],
        ["Until death do us apart", "Secure a Royal Marriage with another country."],
        ["Vasa or Wettin?", "Get a ruler of your dynasty on the throne of Poland or the Commonwealth while they are an elective monarchy."],
        ["Venetian Sea", "Have a 75% Trade share in both the Alexandria and Constantinople nodes as Venice, owning less than 10 cities."],
        ["Veritas Vincit", "Starting as Bohemia, make Hussite the official faith of the Empire and become the Emperor."],
        ["Victorian Three", "As Busoga, Buganda or Karagwe, reach administrative, diplomatic and military technology level 32."],
        ["Victorious!", "Win a war."],
        ["Viva la Revolución!", "Have rebels you support in another country enforce their demands."],
        ["Voltaire's Nightmare", "Have at least 100 countries in the HRE."],
        ["Voting Streak", "Successfully pass 11 issues in a row in Parliament."],
        ["We bled for this", "Win a war with at least one million dead on both sides."],
        ["Where Am I?", "As a New World native with Random New World active, explore the entire New World."],
        ["Where are the penguins?", "As a Malagasy country, unite Madagascar and hold all the most southern provinces of the world."],
        ["Where the heart is", "As Dahomey, force all non-Fetishist nations out of Niger and Sahel by 1500."],
        ["Why is the Rûm gone!?", "As Asturias, establish an Order in Rum."],
        ["Winged Hussars", "Have Winged Hussars as your active unit with more than +50% cavalry combat ability."],
        ["With a little help..", "As Ragusa, lead a Trade League of at least 5 nations and guarantee the Ottomans’ independence."],
        ["Wonderful", "Own 8 different monuments on tier 3."],
        ["World Conqueror", "Own or have a subject own the entire world."],
        ["World Discoverer", "Discover all non-wasteland land provinces."],
        ["Yarr Harr a Pirate's Life For Me", "Choose to play as New Providence and conquer all of Caribbeans."],
        ["You Get A New Home, And You Get A New Home", "Expel 5 different minorities to your colonies."],
    ];

    assert.strictEqual(officialAchievements.length, 373, "sanity check on this test's own reference list");

    const dataPairs = game.achievements
        .map(a => [a.name, a.description])
        .sort((a, b) => a[0].localeCompare(b[0]));

    assert.deepStrictEqual(dataPairs, [...officialAchievements].sort((a, b) => a[0].localeCompare(b[0])));

});
