import { test } from "node:test";
import assert from "node:assert";

import { getPlannerData } from "../utils/plannerCatalog.js";

// backend/catalog/games/gotham-city-impostors.json - 412 real achievements sourced
// from a live ISteamUserStats/GetSchemaForGame/v2 response for appid
// 206210 (fetched through this app's own services/steamApi.js). None are
// hidden; every description is Steam's own real text.
// difficulty/estimatedTime/missable remain curatorial judgments.
const game = getPlannerData("gotham-city-impostors");

test("getPlannerData('gotham-city-impostors') returns real planner data with 412 curated achievements", () => {

    assert.ok(game, "expected real planner data for gotham-city-impostors");
    assert.ok(Array.isArray(game.achievements));
    assert.strictEqual(game.achievements.length, 412);

});

test("every Gotham City Impostors achievement has a unique id from 1 to 412 and a unique apiname", () => {

    const ids = game.achievements.map(a => a.id);
    const apinames = game.achievements.map(a => a.apiname);

    assert.deepStrictEqual([...ids].sort((a, b) => a - b), Array.from({ length: 412 }, (_, i) => i + 1));
    assert.strictEqual(new Set(ids).size, 412);
    assert.strictEqual(new Set(apinames).size, 412);

});

test("every Gotham City Impostors achievement has a valid difficulty (1-5), a positive estimatedTime, and non-empty name/description", () => {

    for (const achievement of game.achievements) {

        assert.ok(
            Number.isInteger(achievement.difficulty) && achievement.difficulty >= 1 && achievement.difficulty <= 5,
            `${achievement.name} has an out-of-range difficulty: ${achievement.difficulty}`
        );

        assert.ok(
            Number.isInteger(achievement.estimatedTime) && achievement.estimatedTime > 0,
            `${achievement.name} has an invalid estimatedTime: ${achievement.estimatedTime}`
        );

        assert.ok(achievement.name?.length > 0, "achievement is missing a name");
        assert.ok(achievement.description?.length > 0, `${achievement.name} is missing a description`);
        assert.ok(achievement.apiname?.length > 0, `${achievement.name} is missing an apiname`);

    }

});

test("every one of the 412 Gotham City Impostors achievement name+description pairs matches the catalog data", () => {

    const officialAchievements = [
        ["Airspace Denier Expert", "Complete all Airspace Denier Feats."],
        ["All Gassed Up", "Hold all three Gasblasters for a full minute."],
        ["All Hooked Up", "Attach the Battery 25 times."],
        ["Angry Hedgehog", "Use the Angry Hedgehog Rampage 25 times."],
        ["Ankle Biter", "Catch 250 enemies with a Bear Trap."],
        ["Anti-Armor Specialist", "Kill 250 enemies that are wearing Body Armor."],
        ["Antisocial", "Accrue 50000 bonus XP by using the 'Antisocial' Psychological Profile."],
        ["Anxious", "Accrue 50000 bonus XP by using the 'Anxious' Psychological Profile."],
        ["Assists Awarded", "Earn a Kill Assist 50000 times."],
        ["Avalanche!", "Stomp kill a frozen enemy."],
        ["Axe You Later", "Kill 3 enemies with a Hatchet after you die."],
        ["Battery Collector", "Pick up a dropped Battery 25 times."],
        ["Bear Trap Expert", "Complete all Bear Trap Feats."],
        ["Bear-Stalker - Rainbow Attack!", "Get 5000 kills with the Bear-Stalker."],
        ["Bear-Stalker B.O. Sniffer Pro", "Get 100 kills using the B.O. Sniffer Mod for the Bear-Stalker."],
        ["Bear-Stalker Headshot Pro", "Kill 375 enemies with headshots using the Bear-Stalker."],
        ["Bear-Stalker Master", "Complete all Bear-Stalker Feats."],
        ["Bear-Stalker Pro", "Get 750 kills with the Bear-Stalker."],
        ["BFF", "Revive 3 teammates in a single round."],
        ["Bipolar", "Accrue 50000 bonus XP by using the 'Bipolar' Psychological Profile."],
        ["Bloody Rampage", "Kill 25 enemies during Kill Crazy Rampage."],
        ["Blow Hard", "Hit multiple enemies with a single Conch Shell blast 15 times."],
        ["Blow Me Down", "Kill 25 enemies with a blast from the Conch Shell."],
        ["Boarding Party - Rainbow Attack!", "Kill 2000 Enemies with the Boarding Party."],
        ["Boarding Party Damage Pro", "Inflict 18000 Damage with the Boarding Party."],
        ["Boarding Party Kills Pro", "Kill 375 Enemies with the Boarding Party."],
        ["Boarding Party Master", "Complete all Boarding Party Feats."],
        ["Body Armor Expert", "Complete All Body Armor Feats."],
        ["Body Dysmorphic", "Accrue 50000 bonus XP by using the 'Body Dysmorphic' Psychological Profile."],
        ["Bogey Down ", "Win 1 mid-air Dive Bomb duels."],
        ["Bombardier - Rainbow Attack!", "Get 5000 kills with the Bombardier."],
        ["Bombardier Master", "Complete all Bombardier Feats."],
        ["Bombardier Mortar Pro", "Get 50 kills using Mortar Ammo for the Bombardier."],
        ["Bombardier Multi Pro", "Kill multiple enemies with a single Bombardier explosion 50 times."],
        ["Bombardier Pro", "Get 750 kills with the Bombardier."],
        ["Boomerang Expert", "Complete all Boomerang Feats."],
        ["Boomerwrangler", "Successfully daze 50 enemies with the Boomerang."],
        ["Bountiful Harvest", "In Bounty Hunter, appear in the end-match lineup 25 times."],
        ["Bounty Hunter", "Complete all Bounty Hunter Feats."],
        ["Bounty Winner", "Complete 50 matches of Bounty Hunter."],
        ["Buccaneer - Rainbow Attack!", "Get 5000 kills with the Buccaneer."],
        ["Buccaneer 4x Scope Lens Pro", "Get 50 kills using the 4x Scope Lens Mod for the Buccaneer."],
        ["Buccaneer B.O. Sniffer Pro", "Get 50 kills using the B.O. Sniffer Mod for the Buccaneer."],
        ["Buccaneer Headshot Pro", "Kill 375 enemies with headshots using the Buccaneer."],
        ["Buccaneer Master", "Complete all Buccaneer Feats."],
        ["Buccaneer Muzzle Break Pro", "Get 50 kills using the Muzzle Break Mod for the Buccaneer."],
        ["Buccaneer Pro", "Get 750 kills with the Buccaneer."],
        ["Buccaneer Silencer Pro", "Get 50 kills using the Silencer Mod for the Buccaneer."],
        ["Bullet Sponge", "Absorb 250000 damage with the Body Armor."],
        ["Bunnyhop Boycott", "Play 2 entire rounds without ever using the jump button."],
        ["Burly Elite", "Complete all Burly Body Type Feats."],
        ["Burly Hunter", "Kill 250 Burly enemies."],
        ["Buzzsaw", "Kill 3 enemies in 2 seconds or less with the Falcon Blade."],
        ["Care Package Expert", "Complete all Care Package Feats."],
        ["Carrier Killer", "Kill an enemy carrying the Battery 150 times."],
        ["Chaperone - Rainbow Attack!", "Get 5000 kills with the Chaperone."],
        ["Chaperone B.O. Sniffer Pro", "Get 50 kills using the B.O. Sniffer Mod for the Chaperone."],
        ["Chaperone Close Kills Pro", "Get 375 kills at a range of 4 meters or less while using the Chaperone."],
        ["Chaperone Expanded Drum Pro", "Get 50 kills using the Expanded Drum Mod for the Chaperone."],
        ["Chaperone Master", "Complete all Chaperone Feats."],
        ["Chaperone Muzzle Break Pro", "Get 50 kills using the Muzzle Break Mod for the Chaperone."],
        ["Chaperone Penetrator Pro", "Kill 25 armored enemies using the Penetrator Ammo Mod for the Chaperone."],
        ["Chaperone Pro", "Get 750 kills with the Chaperone."],
        ["Chaperone Reflex Sight Pro", "Get 50 kills using the Reflex Sight Mod for the Chaperone."],
        ["Cleaned Up My Axe", "Retrieve 50 thrown Hatchets."],
        ["Close Call", "Detach the Battery with less than 30 seconds left until machine activation."],
        ["Codependent", "Accrue 50000 bonus XP by using the 'Codependent' Psychological Profile."],
        ["Conch Honker", "Hit 250 enemies with a Conch Shell blast."],
        ["Conch Shell Expert", "Complete all Conch Shell Feats."],
        ["Crackshot", "Kill 2 enemies with the same bullet while using The Marshal or the Buccaneer."],
        ["Cross-Country Cloaker", "Travel 7 kilometers while invisible."],
        ["Customizer", "Unlock any locked loadout or costume item."],
        ["Cut 'Em Down", "Kill a Grappling Enemy 30 times."],
        ["Cutthroat (Burly)", "Knife-kill 80 enemies while using the Burly Body Type."],
        ["Cutthroat (Mighty)", "Knife-kill 100 enemies while using the Mighty Body Type."],
        ["Cutthroat (Nimble)", "Knife-kill 40 enemies while using the Nimble Body Type."],
        ["Cutthroat (Speedy)", "Knife-kill 20 enemies while using the Burly Body Type."],
        ["Cutthroat (Tough)", "Knife-kill 60 enemies while using the Tough Body Type."],
        ["Damage Dealt", "Deal 25000000 damage points."],
        ["Damage Eater (Burly)", "Absorb 1200 points of damage without dying while using the Burly Body Type."],
        ["Damage Eater (Mighty)", "Absorb 1400 points of damage without dying while using the Mighty Body Type."],
        ["Damage Eater (Nimble)", "Absorb 700 points of damage without dying while using the Nimble Body Type."],
        ["Damage Eater (Speedy)", "Absorb 500 points of damage without dying while using the Speedy Body Type."],
        ["Damage Eater (Tough)", "Absorb 900 points of damage without dying while using the Tough Body Type."],
        ["Dare to Care", "Deploy 250 Care Packages."],
        ["Dawn Patrol - Rainbow Attack!", "Get 5000 kills with the Dawn Patrol."],
        ["Dawn Patrol B.O. Sniffer Pro", "Get 50 kills using the B.O. Sniffer Mod for the Dawn Patrol."],
        ["Dawn Patrol Extended Magazines Pro", "Get 50 kills using the Extended Magazines Mod for the Dawn Patrol."],
        ["Dawn Patrol Headshot Pro", "Kill 375 enemies with headshots using the Dawn Patrol."],
        ["Dawn Patrol Master", "Complete all Dawn Patrol Feats."],
        ["Dawn Patrol Muzzle Break Pro", "Get 50 kills using the Muzzle Break Mod for the Dawn Patrol."],
        ["Dawn Patrol Penetrator Pro", "Kill 25 armored enemies using the Penetrator Ammo Mod for the Dawn Patrol."],
        ["Dawn Patrol Pro", "Get 750 kills with the Dawn Patrol."],
        ["Dawn Patrol Red Dot Sight Pro", "Get 50 kills using the Red Dot Sight Mod for the Dawn Patrol."],
        ["Dawn Patrol Reflex Sight Pro", "Get 50 kills using the Reflex Sight Mod for the Dawn Patrol."],
        ["Dawn Patrol Silencer Pro", "Get 50 kills using the Silencer Mod for the Dawn Patrol."],
        ["Daze of Glory", "Kill 7 enemies while dazed."],
        ["Death on Wheels", "Get 250 kills while Rollerskating."],
        ["Death Racer", "Use the Death Racer Rampage 25 times."],
        ["Death Racer Rally", "Travel 5 kilometers during Death Racer Rampage."],
        ["Death-Dealer (Burly)", "Kill 1000 enemies while using the Burly Body Type."],
        ["Death-Dealer (Mighty)", "Kill 1000 enemies while using the Mighty Body Type."],
        ["Death-Dealer (Nimble)", "Kill 1000 enemies while using the Nimble Body Type."],
        ["Death-Dealer (Speedy)", "Kill 1000 enemies while using the Speedy Body Type."],
        ["Death-Dealer (Tough)", "Kill 1000 enemies while using the Tough Body Type."],
        ["Deep Freezer - Rainbow Attack!", "Inflict 1250000 Damage with the Deep Freezer."],
        ["Deep Freezer B.O. Sniffer Pro ", "Inflict 10000 Damage using the B.O. Sniffer Mod for the Deep Freezer."],
        ["Deep Freezer Extended Magazines Pro ", "Inflict 10000 Damage using the Extended Magazines Mod for the Deep Freezer."],
        ["Deep Freezer Master", "Complete all Deep Freezer Feats"],
        ["Deep Freezer Pro", "Inflict 50000 Damage with the Deep Freezer."],
        ["Delighted with Deathmatch ", "Complete All Team Deathmatch Feats."],
        ["Desperado - Rainbow Attack!", "Get 5000 kills with the Desperado."],
        ["Desperado B.O. Sniffer Pro", "Get 50 kills using the B.O. Sniffer Mod for the Desperado."],
        ["Desperado Extended Magazines Pro", "Get 50 kills using the Extended Magazines Mod for the Desperado."],
        ["Desperado Headshot Pro", "Kill 375 enemies with headshots using the Desperado."],
        ["Desperado Master", "Complete all Desperado Feats."],
        ["Desperado Muzzle Break Pro", "Get 50 kills using the Muzzle Break Mod for the Desperado."],
        ["Desperado Penetrator Pro", "Kill 25 armored enemies using the Penetrator Ammo Mod for the Desperado."],
        ["Desperado Pro", "Get 750 kills with the Desperado."],
        ["Desperado Red Dot Sight Pro", "Get 50 kills using the Red Dot Sight Mod for the Desperado."],
        ["Desperado Reflex Sight Pro", "Get 50 kills using the Reflex Sight Mod for the Desperado."],
        ["Desperado Silencer Pro", "Get 50 kills using the Silencer Mod for the Desperado."],
        ["Distance Traveled", "Travel 21000 kilometers (Multiplayer Only)."],
        ["Dive Bomb Denial", "Thwart 7 Dive Bomb attacks."],
        ["Dive Bomber", "Kill 75 enemies by Dive Bombing."],
        ["Dizzy Beyond Death", "Damage 3 enemies with a Boomerang impact after you die."],
        ["Doctor Knows Best", "Complete all Basic Health Feats."],
        ["Eagle Eye", "Use the Eagle Eye Rampage 50 times."],
        ["Earthquake", "Kill 3 enemies with a single dive bomb attack."],
        ["Eat My Dust", "In Psych Warfare, finish a match with double the score of the player in second place."],
        ["Effusive Enabler", "Have 100000 health or ammo replenished by your Care Package."],
        ["Enemies Killed", "Kill 64000 enemies."],
        ["Enemy Bounty ", "Collect 100 enemy tokens."],
        ["Energy Drink Expert", "Complete All Energy Drink feats."],
        ["Equalogist", "Kill everyone on the opposite team 25 times."],
        ["Experience Earned", "Earn 10000000 Experience Points."],
        ["Fading Star", "Kill 1 enemies with the Shuriken after you die."],
        ["Falcon Blade - Rainbow Attack!", "Get 3750 kills with the Falcon Blade."],
        ["Falcon Blade Block Pro", "Block 3750 attacks with the Falcon Blade."],
        ["Falcon Blade Kill Pro", "Get 750 kills with the Falcon Blade."],
        ["Falcon Blade Master", "Complete all Falcon Blade Feats."],
        ["Fear the Nemesaurus", "Become a Nemesis 50 times."],
        ["Felt That Welt", "Kill 7 enemies with a Boomerang impact."],
        ["Feverish Fumigator", "Capture 250 Gasblasters."],
        ["Final Surprise", "Kill 5 enemies with your Trap-in-the-Box after you die."],
        ["Flyswatter", "Kill 60 Jetpacking Enemies."],
        ["Frequent Flier", "Glide 70 total kilometers."],
        ["Friendly Bounty", "Retrieve 100 teammate tokens."],
        ["Fumigation's Most Wanted", "In Fumigation, appear in the end-match lineup 25 times."],
        ["Fumigator of the Year", "Complete all Fumigation Feats."],
        ["Gadget Phobia", "Complete all Gadgeteer Kills Feats."],
        ["Gas Guardian", "Defend 250 Gasblasters."],
        ["Gas Guzzler", "Hold any single Gasblaster for five consecutive minutes."],
        ["Gas Master", "In Fumigation, finish a match in first place 10 times."],
        ["Gatekeeper - Rainbow Attack!", "Get 5000 kills with the Gatekeeper."],
        ["Gatekeeper B.O. Sniffer Pro", "Get 50 kills using the B.O. Sniffer Mod for the Gatekeeper."],
        ["Gatekeeper Extended Magazines Pro", "Get 50 kills using the Extended Magazines Mod for the Gatekeeper."],
        ["Gatekeeper Headshot Pro", "Kill 375 enemies with headshots using the Gatekeeper."],
        ["Gatekeeper Master", "Complete all Gatekeeper Feats."],
        ["Gatekeeper Muzzle Break Pro", "Get 50 kills using the Muzzle Break Mod for the Gatekeeper."],
        ["Gatekeeper Penetrator Pro", "Kill 25 armored enemies using the Penetrator Ammo Mod for the Gatekeeper."],
        ["Gatekeeper Pro", "Get 750 kills with the Gatekeeper."],
        ["Gatekeeper Red Dot Sight Pro", "Get 50 kills using the Red Dot Sight Mod for the Gatekeeper."],
        ["Gatekeeper Reflex Sight Pro", "Get 50 kills using the Reflex Sight Mod for the Gatekeeper."],
        ["Gatekeeper Silencer Pro", "Get 50 kills using the Silencer Mod for the Gatekeeper."],
        ["Glider Rig Expert", "Complete all Glider Rig Feats."],
        ["Glory Hog", "In Team Deathmatch, finish a match with double the score of the player in second place."],
        ["Gnome Fly Zone", "Deploy 250 Airspace Deniers."],
        ["Gnome Syndrome", "Damage 100 Enemies with the Airspace Denier."],
        ["Gone Grappling", "Kill a grappling enemy with the grapple gun."],
        ["Grapple Gun Expert", "Complete all Grapple Gun Feats."],
        ["Grapple Gunned", "Kill 25 enemies with a Grapple Gun impact."],
        ["Gun Runner", "Use the Gun Runner Rampage 25 times."],
        ["Gun Runner Marathon", "Travel 5 kilometers during Gun Runner Rampage."],
        ["Gun Runner Supreme", "Complete all Gun Runner Feats."],
        ["Hang-Time Hero", "Stay aloft for 60 seconds without landing."],
        ["Hardy Hedgehog", "Take 10000 damage during Angry Hedgehog Rampage."],
        ["Hatchet Expert", "Complete all Hatchet Feats."],
        ["Head Hunter", "In Bounty Hunter, finish a match in first place 10 times."],
        ["Headshots", "Kill 32000 enemies with headshots."],
        ["Headshots Survived", "Survive 25000 headshots."],
        ["Hedgehog Hero", "Complete all Angry Hedgehog Feats."],
        ["Hero of the Hour", "In Fumigation, finish a match with double the score of the player in second place."],
        ["Histrionic", "Accrue 50000 bonus XP by using the 'Histrionic' Psychological Profile."],
        ["Home Run", "Kill two enemies with a single knife attack."],
        ["Huntsman - Rainbow Attack!", "Get 5000 kills with the Huntsman."],
        ["Huntsman B.O. Sniffer Pro", "Get 50 kills using the B.O. Sniffer Mod for the Huntsman."],
        ["Huntsman Extended Magazines Pro", "Get 50 kills using the Extended Magazines Mod for the Huntsman."],
        ["Huntsman Headshot Pro", "Kill 375 enemies with headshots using the Huntsman."],
        ["Huntsman Master", "Complete all Huntsman Feats."],
        ["Huntsman Muzzle Break Pro", "Get 50 kills using the Muzzle Break Mod for the Huntsman."],
        ["Huntsman Penetrator Pro", "Kill 25 armored enemies using the Penetrator Ammo Mod for the Huntsman."],
        ["Huntsman Pro", "Get 750 kills with the Huntsman."],
        ["Huntsman Red Dot Sight Pro", "Get 50 kills using the Red Dot Sight Mod for the Huntsman."],
        ["Huntsman Reflex Sight Pro", "Get 50 kills using the Reflex Sight Mod for the Huntsman."],
        ["Huntsman Silencer Pro", "Get 50 kills using the Silencer Mod for the Huntsman."],
        ["Ice and Dice", "Shatter 50 Frozen Enemies with your Knife."],
        ["Impact Grenade Expert", "Complete all Impact Grenade feats."],
        ["Inflated Insoles Expert", "Complete all Inflated Insoles Feats."],
        ["Initiated", "Complete the Initiation mission."],
        ["Insole Addict", "Use the Inflated Insoles 1000 times."],
        ["Insoles to Injury", "Kill 250 enemies while Double-Jumping."],
        ["Invincible", "Get a 20 Kill Streak."],
        ["Invisible Ambusher", "Kill 100 enemies within 5 seconds of becoming visible."],
        ["Jackhammer - Rainbow Attack!", "Get 5000 kills with the Jackhammer."],
        ["Jackhammer B.O. Sniffer Pro", "Get 50 kills using the B.O. Sniffer Mod for the Jackhammer."],
        ["Jackhammer Extended Magazines Pro", "Get 50 kills using the Extended Magazines Mod for the Jackhammer."],
        ["Jackhammer Headshot Pro", "Kill 375 enemies with headshots using the Jackhammer."],
        ["Jackhammer Master", "Complete all Jackhammer Feats."],
        ["Jackhammer Muzzle Break Pro", "Get 50 kills using the Muzzle Break Mod for the Jackhammer."],
        ["Jackhammer Penetrator Pro", "Kill 25 armored enemies using the Penetrator Ammo Mod for the Jackhammer."],
        ["Jackhammer Pro", "Get 750 kills with the Jackhammer."],
        ["Jackhammer Red Dot Sight Pro", "Get 50 kills using the Red Dot Sight Mod for the Jackhammer."],
        ["Jackhammer Reflex Sight Pro", "Get 50 kills using the Reflex Sight Mod for the Jackhammer."],
        ["Jetpack Attackaroo", "Kill 250 enemies while the Jetpack is active."],
        ["Jetpack Expert", "Complete all Jetpack Feats."],
        ["Just Axein'", "Kill 100 enemies with the Hatchet."],
        ["Just Try to Stop Me", "Get a 5 Kill Streak."],
        ["Kill Crazy", "Use the Kill Crazy Rampage 25 Times."],
        ["Kingmaker - Rainbow Attack!", "Get 5000 kills with the Kingmaker."],
        ["Kingmaker Extended Magazines Pro", "Kill 50 using the Extended Magazines mod for the Kingmaker."],
        ["Kingmaker Full Auto Pro", "Kill 50 using the Full Auto mod for the Kingmaker."],
        ["Kingmaker Headshot Pro", "Get 375 headshots with the Kingmaker."],
        ["Kingmaker Jacketed Hollow Point Pro", "Kill 50 using the Jacketed Hollow Point Ammo mod for the Kingmaker."],
        ["Kingmaker Kill Pro", "Get 750 kills with the Kingmaker."],
        ["Kingmaker Master", "Complete all Kingmaker Feats."],
        ["Kingmaker Muzzle Break Pro", "Kill 50 using the Muzzle Break mod for the Kingmaker."],
        ["Kingmaker Penetrator Pro", "Kill 25 using the Penetrator Ammo mod for the Kingmaker."],
        ["Kingmaker Reflex Sight Pro", "Kill 50 using the Reflex Sight mod for the Kingmaker."],
        ["Kingmaker Silencer Pro", "Kill 50 using the Silencer mod for the Kingmaker."],
        ["Kleptomaniacal", "Accrue 50000 bonus XP by using the 'Kleptomaniacal' Psychological Profile."],
        ["Knife Backstab Pro", "Get 30 backstab kills."],
        ["Knife Kill Pro", "Get 375 kills with the Knife."],
        ["Knife Master", "Complete all Knife Feats."],
        ["Lambs to the Slaughter", "Complete all Basic Kill Feats."],
        ["Lasting Impact", "Kill 3 enemies with an Impact Grenade after you die."],
        ["Laughter is the Worst Medicine", "Successfully release enough Joker Gas to cause a Fumigation Defeat for the Bats 25 times."],
        ["Legendary Master", "Complete all Legendary Feats."],
        ["Let It Glide", "Glide 1 kilometer without landing."],
        ["Lineup Finishes", "Finish in the top 3 lineup 500 times."],
        ["Major Impact", "Kill 100 enemies with the Impact Grenade."],
        ["Masochistic", "Accrue 50000 bonus XP by using the 'Masochistic' Psychological Profile."],
        ["Matches Completed", "Play 10000 matches to completion."],
        ["Matches Won", "Win 5000 matches."],
        ["Mercy Killer", "Kill 100 enemies caught in a Bear Trap."],
        ["Mighty Elite", "Complete all Mighty Body Type Feats."],
        ["Mighty Hunter", "Kill 250 Mighty enemies."],
        ["Motion Sensor Expert", "Complete all Motion Sensor Feats."],
        ["Motion Tracker", "Tag 500 Enemies with Motion Sensors."],
        ["Motivation Celebration", "Heal 750 Life in ten seconds."],
        ["Motivation Elation", "Heal 500 Life in ten seconds."],
        ["Motivation Sensation", "Heal 1000 Life in ten seconds."],
        ["Motivator - Rainbow Attack!", "Heal 5000000 Life with the Motivator."],
        ["Motivator Master", "Complete all Motivator Feats."],
        ["Motivatory Motivation", "Heal 750000 Life with the Motivator."],
        ["Multiple Impacts", "Kill multiple enemies with a single Impact Grenade 7 times."],
        ["MVP Finishes", "Finish in first place 250 times."],
        ["Narcissistic", "Accrue  240 Costume Coins by using the 'Narcissistic' Psychological Profile."],
        ["Nary a Nemesis", "Play 10 rounds without anyone becoming your Nemesis."],
        ["Nemesaurus", "Become the Nemesis of 2 players in the same match."],
        ["Nemesaurus Prime", "Become the Nemesis of 4 players in the same match."],
        ["Nemesaurus Rex", "Become the Nemesis of 3 players in the same match."],
        ["Nimble Elite", "Complete all Nimble Body Type Feats."],
        ["Nimble Hunter", "Kill 250 Nimble enemies."],
        ["Ninja Smoke Bomb Expert", "Complete all Ninja Smoke Bomb Feats."],
        ["No Body Left Behind", "Complete all Body Type Kill Feats."],
        ["No Man Left Behind", "Revive 25 teammates."],
        ["Opportunist", "Kill 100 enemies dazed by a Boomerang."],
        ["Panic Survivor", "Survive 25 enemy Brainwashing Events."],
        ["Paranoid", "Accrue 50000 bonus XP by using the 'Paranoid' Psychological Profile."],
        ["Partisan - Rainbow Attack!", "Get 5000 kills with the Partisan."],
        ["Partisan B.O. Sniffer Pro", "Get 50 kills using the B.O. Sniffer Mod for the Partisan."],
        ["Partisan Extended Magazines Pro", "Get 50 kills using the Extended Magazines Mod for the Partisan."],
        ["Partisan Headshot Pro", "Kill 375 enemies with headshots using the Partisan."],
        ["Partisan Master", "Complete all Partisan Feats."],
        ["Partisan Muzzle Break Pro", "Get 50 kills using the Muzzle Break Mod for the Partisan."],
        ["Partisan Penetrator Pro", "Kill 25 armored enemies using the Penetrator Ammo Mod for the Partisan."],
        ["Partisan Pro", "Get 750 kills with the Partisan."],
        ["Partisan Red Dot Sight Pro", "Get 50 kills using the Red Dot Sight Mod for the Partisan."],
        ["Partisan Reflex Sight Pro", "Get 50 kills using the Reflex Sight Mod for the Partisan."],
        ["Partisan Silencer Pro", "Get 50 kills using the Silencer Mod for the Partisan."],
        ["Party Daze", "Successfully daze multiple enemies with a single Boomerang 7 times."],
        ["Passive Aggresive", "Accrue 50000 bonus XP by using the 'Passive Aggresive' Psychological Profile."],
        ["Persuader - Rainbow Attack!", "Get 5000 kills with the Persuader."],
        ["Persuader B.O. Sniffer Pro", "Get 50 kills using the B.O. Sniffer Mod for the Persuader."],
        ["Persuader Close Kills Pro", "Get 375 kills at a range of 4 meters or less while using the Persuader."],
        ["Persuader Extended Magazines Pro", "Get 50 kills using the Extended Magazines Mod for the Persuader."],
        ["Persuader Master", "Complete all Persuader Feats."],
        ["Persuader Muzzle Break Pro", "Get 50 kills using the Muzzle Break Mod for the Persuader."],
        ["Persuader Penetrator Pro", "Kill 25 armored enemies using the Penetrator Ammo Mod for the Persuader."],
        ["Persuader Pro", "Get 750 kills with the Persuader."],
        ["Persuader Reflex Sight Pro", "Get 30 kills using the Reflex Sight Mod for the Persuader."],
        ["Photogenic", "In Team Deathmatch, appear in the end-match lineup 25 times."],
        ["Pipe Bomb Bonk", "Kill 7 enemies with a direct hit from a Pipe Bomb."],
        ["Pipe Bomb Expert", "Complete all Pipe Bomb feats."],
        ["Pipe Bomb Multi-Kill", "Kill multiple enemies with a single Pipe Bomb 25 times."],
        ["Plausible Deniability", "Inflict 25000 Damage with the Toxic Gas."],
        ["Pop a Squat", "Kill 50 enemies while crouched."],
        ["Pop Goes Your Face", "Kill 250 enemies with your Trap-in-the-Box."],
        ["Postmortem Piper", "Kill 5 enemies with a Pipe Bomb after you die."],
        ["Powder Keg", "Use the Powder Keg Rampage 25 Times."],
        ["Powder Keg Vengeance", "Kill 25 enemies during Powder Keg Rampage."],
        ["Prestigious", "Accept your first Promotion."],
        ["Propaganda Minister", "In Psych Warfare, finish a match in first place 10 times."],
        ["Propaganda Posterboy", "In Psych Warfare, appear in the end-match lineup 25 times."],
        ["Propagandist", "Complete all Psych Warfare Feats."],
        ["Psychological Shutout", "Win a game of Psych Warfare without the other team ever scoring."],
        ["Psychotic", "Kill 3 enemies with the panic slap attack."],
        ["Radiology", "Tag 5 enemies within 3 seconds using the targeting goggles."],
        ["Ramp It Up", "Jump a Skate Ramp 75 times."],
        ["Rampage is all the Rage", "Complete all Kill Crazy Rampage Feats."],
        ["Rampicide", "Kill 7 enemies while jumping a Skate Ramp on Rollerskates."],
        ["Ready to Blow", "Complete all Powder Keg Feats."],
        ["Rodent Removal", "Kill 10 Bats in one life."],
        ["Roller Patroller", "Travel 100 kilometers on Roller Skates."],
        ["Rollerskates Expert", "Complete all Rollerskate Feats."],
        ["Rush Hour", "Sprint for 60 seconds straight."],
        ["Sadistic", "Accrue 50000 bonus XP by using the 'Sadistic' Psychological Profile."],
        ["Second Sight", "Kill an enemy who is using the Ninja Smoke Bomb 30 times."],
        ["Second Wind", "Use an Energy Drink when you have 10 health or less 30 times."],
        ["Sensor Dispenser", "Deploy 250 Motion Sensors."],
        ["Shooting Fish in a Barrel", "Kill 25 Demoralized enemies in Psych Warfare."],
        ["Shower of Gold", "Earn 60 gold medals in Challenge mode."],
        ["Shredder - Rainbow Attack!", "Get 5000 kills with the Shredder."],
        ["Shredder B.O. Sniffer Pro", "Get 50 kills using the B.O. Sniffer Mod for the Shredder."],
        ["Shredder Extended Magazines Pro", "Get 50 kills using the Extended Magazines Mod for the Shredder."],
        ["Shredder Headshot Pro", "Kill 375 enemies with headshots using the Shredder."],
        ["Shredder Master", "Complete all Shredder Feats."],
        ["Shredder Muzzle Break Pro", "Get 50 kills using the Muzzle Break Mod for the Shredder."],
        ["Shredder Penetrator Pro", "Kill 25 armored enemies using the Penetrator Ammo Mod for the Shredder."],
        ["Shredder Pro", "Get 750 kills with the Shredder."],
        ["Shredder Red Dot Sight Pro", "Get 50 kills using the Red Dot Sight Mod for the Shredder."],
        ["Shredder Reflex Sight Pro", "Get 50 kills using the Reflex Sight Mod for the Shredder."],
        ["Shuck and Jive", "Complete all Movement Feats."],
        ["Shuriken Expert", "Complete all Shuriken Feats."],
        ["Skeet Shooting", "Kill a Skate-Jumping enemy in mid-air 7 times."],
        ["Skunk Ninja", "Deploy 250 Toxic Gas."],
        ["Sky is Falling", "Kill 7 enemies by dropping onto them with the Jetpack."],
        ["Slap Happy", "Kill 25 enemies with Panic Slap attacks while demoralized in Psych Warfare."],
        ["Smog Alert", "Win a Fumigation game on Ace Chemical, Amusement Mile, Crime Alley, Gotham Power and The Docks."],
        ["Speedy Elite", "Complete all Speedy Body Type Feats."],
        ["Speedy Hunter", "Kill 250 Speedy enemies."],
        ["Spreading the Word", "Win a Psych Warfare game on Ace Chemical, Amusement Mile, Crime Alley, Gotham Power and The Docks."],
        ["Spring Boot Squash", "Kill 30 enemies by landing on them with Spring Boots."],
        ["Spring Boots Expert", "Complete all Spring Boot Feats."],
        ["Springs Have Sprung", "Use the Spring Boots 1000 times."],
        ["Star Shower", "Hit 3 enemies with a single Shuriken volley."],
        ["Star Struck", "Kill 50 enemies with the Shuriken."],
        ["Star Struck Multi", "Kill 2 enemies with a single Shuriken volley."],
        ["Strung Along", "Grapple 50 total kilometers."],
        ["Sugar Rush", "Heal yourself 250 times with the Energy Drink."],
        ["Surprise Party", "Kill multiple enemies with your single Trap-in-the-Box 25 times."],
        ["Surprise!", "Kill 3 or more enemies with a single Trap-in-the-Box blast."],
        ["Survivalist (Burly)", "Avoid death for an entire match while only using the Burly Body Type."],
        ["Survivalist (Mighty)", "Avoid death for an entire match while only using the Mighty Body Type."],
        ["Survivalist (Nimble)", "Avoid death for an entire match while only using the Nimble Body Type."],
        ["Survivalist (Speedy)", "Avoid death for an entire match while only using the Speedy Body Type."],
        ["Survivalist (Tough)", "Avoid death for an entire match while only using the Tough Body Type."],
        ["Sweet Revenge", "Kill your Nemesis 10 times."],
        ["Target Hunter", "Kill 250 enemies that are tagged by Targeting Goggles."],
        ["Target Painter", "Tag 500 enemies with the Targeting Goggles."],
        ["Targeting Goggles Expert", "Complete all Targeting Goggles Feats."],
        ["Team Damage Healed", "Heal 2500000 points of damage."],
        ["Team Oriented", "Complete 50 matches of Team Deathmatch."],
        ["Thanks for Playing!", "Finish one match of Gotham City Impostors."],
        ["The Marshal - Rainbow Attack!", "Get 5000 kills with The Marshal."],
        ["The Marshal 4x Scope Lens Pro", "Get 50 kills using the 4x Scope Lens Mod for The Marshal."],
        ["The Marshal B.O. Sniffer Pro", "Get 50 kills using the B.O. Sniffer Mod for The Marshal."],
        ["The Marshal Extended Magazines Pro", "Get 50 kills using the Extended Magazines Mod for The Marshal."],
        ["The Marshal Headshot Pro", "Kill 375 enemies with headshots using The Marshal."],
        ["The Marshal Master", "Complete all The Marshal Feats."],
        ["The Marshal Muzzle Break Pro", "Get 50 kills using the Muzzle Break Mod for The Marshal."],
        ["The Marshal Pro", "Get 750 kills with The Marshal."],
        ["The Marshal Silencer Pro", "Get 50 kills using the Silencer Mod for The Marshal."],
        ["The Pwny Express", "Kill everyone on the enemy team in under 5 seconds."],
        ["Thrustasaurus", "Travel 30 total kilometers while the Jetpack is active."],
        ["Thunder Dragon - Rainbow Attack!", "Get 5000 kills with the Thunder Dragon."],
        ["Thunder Dragon Master", "Complete all Thunder Dragon Feats."],
        ["Thunder Dragon Missiles Pro", "Get 100 kills using the Missiles for the Thunder Dragon."],
        ["Thunder Dragon Multi-Kill Pro", "Kill multiple enemies with a single rocket 50 times."],
        ["Thunder Dragon Pro", "Get 750 kills with the Thunder Dragon."],
        ["Timber!", "Kill a grappling enemy with a hatchet."],
        ["Time Played", "Play Gotham City Impostors for 2000 total hours (Multiplayer Only)."],
        ["Time Well Spent", "Complete 50 matches of Psych Warfare."],
        ["Timed to Die", "Kill 250 enemies with the Pipe Bomb."],
        ["Total Victory", "Win each game mode in Ace Chemical, Amusement Mile, Crime Alley, Gotham Power and The Docks."],
        ["Tough as Nails", "Use the Tough As Nails Rampage 25 times."],
        ["Tough Elite", "Complete all Tough Body Type Feats."],
        ["Tough Enough", "Take 10000 damage during Tough as Nails Rampage."],
        ["Tough Hunter", "Kill 250 Tough enemies."],
        ["Toxic Gas Expert", "Complete all Toxic Gas Feats."],
        ["Trap-in-the-Box Expert", "Complete all Trap-in-the-Box feats."],
        ["Turning the Tide", "Turn the tables in Fumigation when the enemy team's victory is imminent."],
        ["Tyrannical", "Accrue 50000 bonus XP by using the 'Tyrannical' Psychological Profile."],
        ["Ultimate Death Racer", "Complete all Death Racer Feats."],
        ["Unplugger", "Detach the Battery 25 times."],
        ["Unstoppable", "Get a 10 Kill Streak."],
        ["Urban Unrest", "Win a Team Deathmatch game on Ace Chemical, Amusement Mile, Crime Alley, Gotham Power and The Docks."],
        ["Very Tough Stuff", "Complete all Tough as Nails Feats."],
        ["When Bats Attack", "Successfully release enough Bat Pheromones to cause a Fumigation Defeat for the Jokerz 25 times."],
        ["Where's the 'I' in 'Team'?", "In Team Deathmatch, finish a match in first place 10 times."],
        ["Where's the Fire?", "Sprint 25 kilometers."],
        ["Who's Laughing Now?", "Kill 10 Jokerz in one life."],
        ["Wide and Far", "Win a Bounty Hunter game on Ace Chemical, Amusement Mile, Crime Alley, Gotham Power, The Docks, 25th Floor and East End."],
        ["Witch Doctor - Rainbow Attack!", "Get 3750 kills with the Witch Doctor."],
        ["Witch Doctor Damage Pro", "Cause 100000 damage with the Witch Doctor."],
        ["Witch Doctor Deflective Charge Pro", "Get 45 kills using the Deflective Charge Mod for the Witch Doctor."],
        ["Witch Doctor Kills Pro", "Kill 375 enemies with the Witch Doctor."],
        ["Witch Doctor Master", "Complete all Witch Doctor Feats."],
        ["Wolf Pack", "Use the Wolf Pack Rampage 50 times."],
        ["Yay Me!", "In Bounty Hunter, finish a match with double the score of the player in second place."],
        ["Your Worst Nightmare", "Complete all Basic Nemesis Feats."],
    ];

    assert.strictEqual(officialAchievements.length, 412, "sanity check on this test's own reference list");

    const dataPairs = game.achievements
        .map(a => [a.name, a.description])
        .sort((a, b) => a[0].localeCompare(b[0]));

    assert.deepStrictEqual(dataPairs, [...officialAchievements].sort((a, b) => a[0].localeCompare(b[0])));

});
