import { test } from "node:test";
import assert from "node:assert";

import { getPlannerData } from "../utils/plannerCatalog.js";

// backend/catalog/games/halo-the-master-chief-collection.json - 700 real achievements sourced
// from a live ISteamUserStats/GetSchemaForGame/v2 response for appid
// 976730 (fetched through this app's own services/steamApi.js). None are
// hidden; every description is Steam's own real text.
// difficulty/estimatedTime/missable remain curatorial judgments.
const game = getPlannerData("halo-the-master-chief-collection");

test("getPlannerData('halo-the-master-chief-collection') returns real planner data with 700 curated achievements", () => {

    assert.ok(game, "expected real planner data for halo-the-master-chief-collection");
    assert.ok(Array.isArray(game.achievements));
    assert.strictEqual(game.achievements.length, 700);

});

test("every Halo: The Master Chief Collection achievement has a unique id from 1 to 700 and a unique apiname", () => {

    const ids = game.achievements.map(a => a.id);
    const apinames = game.achievements.map(a => a.apiname);

    assert.deepStrictEqual([...ids].sort((a, b) => a - b), Array.from({ length: 700 }, (_, i) => i + 1));
    assert.strictEqual(new Set(ids).size, 700);
    assert.strictEqual(new Set(apinames).size, 700);

});

test("every Halo: The Master Chief Collection achievement has a valid difficulty (1-5), a positive estimatedTime, and non-empty name/description", () => {

    for (const achievement of game.achievements) {

        assert.ok(
            Number.isInteger(achievement.difficulty) && achievement.difficulty >= 1 && achievement.difficulty <= 5,
            `${achievement.name} has an out-of-range difficulty: ${achievement.difficulty}`
        );

        assert.ok(
            Number.isInteger(achievement.estimatedTime) && achievement.estimatedTime > 0,
            `${achievement.name} has an invalid estimatedTime: ${achievement.estimatedTime}`
        );

        assert.ok(achievement.name?.length > 0, "achievement is missing a name");
        assert.ok(achievement.description?.length > 0, `${achievement.name} is missing a description`);
        assert.ok(achievement.apiname?.length > 0, `${achievement.name} is missing an apiname`);

    }

});

test("every one of the 700 Halo: The Master Chief Collection achievement name+description pairs matches the catalog data", () => {

    const officialAchievements = [
        ["\"BLAM\" Said The Lady!", "H3: ODST: Swap Dare's pistol for a Rocket Launcher on Coastal Highway."],
        ["10 Minutes Too Early", "Halo 2: In The Oracle, find the holo-drone before the Heretic Leader activates it."],
        ["343 Guilty Spark", "Halo CE: Complete 343 Guilty Spark."],
        ["A Crate of Medals", "Collect 3,000 campaign or playlist medals."],
        ["A Day To Remember", "Halo CE: Play Halo: CE on the 15th of any month."],
        ["A Few Trinkets", "Collect 5,000 campaign or playlist medals."],
        ["A Fine Choice", "Halo CE: Complete a Halo: CE playlist."],
        ["A Heap of Medals", "Collect 4,000 campaign or playlist medals."],
        ["A Long Time Ago", "Halo 4: Play a game of Halo 4 on the 6th of any month."],
        ["A Monument To All Your Sins", "Halo: Reach: Complete every level of the game on Legendary difficulty, by yourself."],
        ["A Pile of Medals", "Collect 2,000 campaign or playlist medals."],
        ["A Pleasant Trip", "H3: ODST: Beat the par time on ONI Alpha Site."],
        ["A Preference for Pain", "Halo 3: Complete the Halo 3 LASO Campaign playlist."],
        ["Adventurer", "H3: ODST: Find the 22nd Audio Log."],
        ["Aficiando", "Halo 3: Complete three Halo 3 playlists."],
        ["Aim for the Head", "Earn a total of 2,500 Headshot medals in multiplayer."],
        ["Airborne", "Halo CE: Launch a Warthog for at least 5 seconds and have it splatter an enemy."],
        ["All According to Plan...", "Halo CE: Kill the first group of enemies on The Truth and Reconciliation without being detected."],
        ["All Ears", "H3: ODST: Find the 15th Audio Log."],
        ["All Out of Bubblegum", "Collect 1,000 campaign or playlist medals."],
        ["All You Can Eat", "Halo CE: Beat the par time on The Maw."],
        ["An Artist's Canvas", "H3: ODST: Beat the par time on Kizingo Blvd."],
        ["An Ear Full", "H3: ODST: Find the 2nd Audio Log."],
        ["And So It Begins...", "Halo 2: Collect the Master Chief toy in Delta Halo."],
        ["Animal Habitat", "Halo 2: Spot the hippo on the walls of Headlong in classic multiplayer."],
        ["Annual", "Halo 3: Complete Halo on 4-player Legendary co-op, with Iron Skull, and everyone in Ghosts."],
        ["Arcade Owner", "Halo 2: Beat the par score on every Halo 2 level."],
        ["Archivist", "H3: ODST: Find the 26th Audio Log."],
        ["Are We There Yet?", "Halo 2: Beat the par time on The Great Journey."],
        ["Arrival", "Halo CE: Activate Terminal 1 on The Pillar of Autumn."],
        ["Artifact", "Halo 4: Complete all chapters in Spartan Ops Episode 2."],
        ["Askar", "Halo 3: Beat the par score on The Storm."],
        ["Assault", "Halo 3: Complete The Storm."],
        ["Assault on the Control Room", "Halo CE: Complete Assault on the Control Room."],
        ["Assembled the Majority", "Halo: Reach: Find Data Pad 18 on The Pillar Of Autumn on Legendary difficulty"],
        ["Assembly Skull", "Halo 3: Find the hidden Skull on the Assembly multiplayer map."],
        ["Attentive", "H3: ODST: Find the 18th Audio Log."],
        ["Audiophile", "H3: ODST: Find the 30th Audio Log."],
        ["Auditor", "H3: ODST: Find the 7th Audio Log."],
        ["Babbling Dead", "Halo 3: Activate Terminal 6 on The Covenant."],
        ["Back At It", "Halo 2: Play a game of Halo 2 Anniversary on the 9th of any month."],
        ["Back for More", "Halo 2: Complete the LASO campaign playlist."],
        ["Back In The Day", "Halo CE: Play a CTF custom game on Blood Gulch with 4 players. Tri-tip optional."],
        ["Bake That Cake", "Halo: Reach: Beat the par score on Tip of the Spear."],
        ["Balaho's Most Wanted", "Kill 100 Grunts."],
        ["Battle Hardened", "Win 250 multiplayer games."],
        ["Beachhead", "Halo CE: Storm The Silent Cartographer beach with no Marine casualties on Heroic or Legendary."],
        ["Bearly Contained", "Halo CE: Activate Terminal 6 on 343 Guilty Spark."],
        ["Because It Wasn't Hard Enough", "Halo: Reach: Complete a Legendary campaign mission with 3 or more skulls enabled (Scoring Only)."],
        ["Before and After", "Halo CE: Complete every level of the game having seen it in both classic and remastered mode."],
        ["Before the Fire", "Halo 3: Activate Terminal 3 on The Ark."],
        ["Begins with a Single Step", "Halo 3: On Tsavo Highway, complete the level without entering a vehicle."],
        ["Believe in a Hero", "Halo CE: Complete every level of the game on Heroic difficulty."],
        ["Betcha can't stick it...", "Halo 2: Stick a Plasma Grenade to a Stealth Elite on Outskirts."],
        ["Better With Age", "Halo 3: Beat the par score on every Halo 3 level."],
        ["Big Green Style", "Halo 2: Complete every level of the game on Easy difficulty."],
        ["Big Time Gamer", "Complete 400 missions or multiplayer games."],
        ["Bill Past Due", "H3: ODST: Beat the par time on Tayari Plaza."],
        ["Bip! Bap! BAM!", "H3: ODST: Earn a Triple Kill medal with the pistol on any level."],
        ["Birth of a Spartan", "Halo CE: Complete every level of the game on Normal difficulty."],
        ["Bite The Hand", "Kill a 343 developer in matchmaking or someone who has this achievement."],
        ["Bits and Pieces", "H3: ODST: Destroy 5 Phantoms on NMPD HQ."],
        ["BLASTacular!", "Halo 2A MP: Destroyed all the Halo 2 Anniversary Multiplayer BLAST soda cans."],
        ["Bloodhound", "H3: ODST: Find the 4th clue unraveling the mystery."],
        ["Bloody Thirsty!", "Halo 2A MP: Found and destroyed the BLAST soda can on Bloodline."],
        ["Blown Out of the Sky", "Halo 2A MP: Blow up the Banshee or Hornet in flight while piloted, with the Rocket Launcher."],
        ["Bomb Squad", "Halo 2: Beat the par score on Cairo Station."],
        ["Bombing Run", "Halo 2A MP: In Assault, take, plant, and score from the bomb spawn without dying or dropping it."],
        ["Bonus Level", "Complete 200 missions or multiplayer games."],
        ["Boot Camp Hero", "Halo 3: Complete a Halo 3 playlist."],
        ["Boundless", "Halo 2: Beat the par score on Delta Halo."],
        ["Brainpan", "Halo 3: Find all the hidden multiplayer Skulls."],
        ["Bro Hammer", "Complete any co-op level on Legendary difficulty."],
        ["Bros to the Close", "Halo 4: Complete Infinity without one preventable Marine death on Heroic or Legendary."],
        ["Brovershield", "Complete any co-op level on Heroic difficulty."],
        ["Cairo Station", "Halo 2: Complete Cairo Station."],
        ["Can't Get Enough", "Complete 300 missions or multiplayer games."],
        ["Can't Keep Him Down", "Halo 3: Fight alongside and listen to The Man. The Legend. Chips Dubbo."],
        ["Can't Put It Down", "Complete 150 missions or multiplayer games."],
        ["Can't Stop Here, This is Brute Country", "H3: ODST: Beat par time on all Halo 3: ODST levels."],
        ["Canonical Conundrum", "Halo: Reach: Find all Data Pads."],
        ["Capacious Cartography", "Halo: Reach: Create a custom map using Forge World."],
        ["Catch 'Em Napping", "H3: ODST: Kill 5 sleeping Grunts on Mombasa Streets."],
        ["Catch This", "Earn a total of 500 Grenade Kill or Plasma Kill medals in matchmade games."],
        ["Catching On", "H3: ODST: Find the 28th Audio Log."],
        ["Catherine", "Halo 4: Complete all chapters in Spartan Ops Episode 3."],
        ["Cavalier", "Halo 3: Beat the par score on Tsavo Highway."],
        ["Charted", "Halo CE: Beat the par score on The Silent Cartographer."],
        ["Charum Hakkor", "Halo 4: Activate Terminal 3 on Infinity."],
        ["Checking Out Your Options", "Halo CE: Complete a match on at least 4 unique game types."],
        ["Checkmate", "Kill 100 Watchers."],
        ["Chest of Gold", "Halo 4: Complete a Halo 4 playlist."],
        ["Chesty Puller Starter Kit", "Collect 7,000 campaign or playlist medals."],
        ["Chief, Smash!", "Halo 4: Kill 3 Crawlers in one hit with the Gravity Hammer on Midnight."],
        ["Chieftain of the Brutes", "Halo 2: Collect the Tartarus toy in Quarantine Zone."],
        ["Chol Von's Not Gonna Like This", "Halo: Reach: Kill 1000 Skirmishers."],
        ["Circuit Breaker", "Halo CE: Beat the par score on 343 Guilty Spark."],
        ["Citadel Skull", "Halo 3: Find the hidden Skull on the Citadel multiplayer map."],
        ["Classic", "H3: ODST: Finish any level solo on Legendary, with no shots fired or grenades thrown."],
        ["Classic Completion", "Halo: Reach: Complete Exodus without using any armor abilities."],
        ["Cleansing", "Halo 3: Complete Floodgate."],
        ["Clear and Present Danger", "Halo: Reach: Pad on the run."],
        ["Close Quarters Combat", "Halo CE: Complete The Truth and Reconciliation with at least four rounds left in your Sniper Rifle."],
        ["Coastal Highway", "H3: ODST: Complete Coastal Highway."],
        ["Cold as Ice", "Halo 2A MP: On Lockdown, kill an opponent with the hanging ice."],
        ["Cold Fusion", "Halo 2A MP: Kill an opponent by detonating a Fusion Coil."],
        ["Collection Eligibility Confirmed", "Halo: Reach: See, he IS in the game!"],
        ["Committed", "Complete 350 missions or multiplayer games."],
        ["Commuter", "Halo 2: Complete Metropolis without entering a vehicle on Heroic or Legendary."],
        ["Composer", "Halo 4: Complete Composer."],
        ["Confused Callouts", "Halo: Reach: Trigger a humorous callout on your HUD's position indicator."],
        ["Connoisseur", "Halo 2: Complete three Halo 2 playlists."],
        ["Considerate", "H3: ODST: Find the 24th Audio Log."],
        ["Consumption Junction", "Halo CE: Beat the par score on The Maw."],
        ["Contender", "Win 50 multiplayer games."],
        ["Cool Story Bro", "Halo 3: Listen to the story of the Final Grunt."],
        ["Countdown", "Halo 4: Beat the par time on Midnight."],
        ["Counter-Sniped", "Halo 2A MP: With a Sniper Rifle or Beam Rifle kill an enemy that was zoomed in."],
        ["Cowardly Grunt", "Halo 2: Listen to the Cowardly Grunt's woes."],
        ["Cryptum", "Halo 4: Activate Terminal 7 on Midnight."],
        ["Curious", "Halo 2: Activate Terminal 1 on Cairo Station."],
        ["Curious Composition", "Halo: Reach: Find Data Pad 16 on New Alexandria on Legendary difficulty"],
        ["Dambuster", "Halo 3: Beat the par time on Floodgate."],
        ["Dankey Kang", "Kill 1000 Brutes."],
        ["Dark Fortress", "Halo 4: Beat the par score on Requiem."],
        ["Data Hive", "H3: ODST: Complete Data Hive."],
        ["Dawn", "Halo 4: Complete Dawn."],
        ["Dear Diary...", "Halo CE: Activate all Halo: CE Terminals."],
        ["Decorated Warrior", "Halo 2A MP: Get awarded at least 10 different medals in one multiplayer game."],
        ["Deference of Darkness", "H3: ODST: Complete any level without activating VISR mode."],
        ["Déjà Vu", "H3: ODST: Complete Coastal Highway on 4-player Legendary co-op, with Iron, and no 'Hog or Scorpion."],
        ["Delicious Brains", "Kill 100 Flood."],
        ["Delighted", "Halo 2: Activate Terminal 9 on Quarantine Zone."],
        ["Delta Halo", "Halo 2: Complete Delta Halo."],
        ["Demon", "Halo 2: Complete any campaign level without dying on Normal or harder."],
        ["Departure", "Halo 4: Complete all chapters in Spartan Ops Episode 1."],
        ["Destination Vacation", "Halo 2: View one of the seasonal signs on Zanzibar in classic multiplayer."],
        ["Determined", "Halo 2: Activate Terminal 8 on Sacred Icon."],
        ["Devastating", "Halo 3: Complete all Halo 3 Legendary campaign missions in under 3 hours."],
        ["Devotee", "Halo 4: Complete three Halo 4 playlists."],
        ["Did Somebody Say...", "Halo CE: Beat par time on all Halo: CE levels."],
        ["Did You Major in Marine Bio?", "Halo: Reach: Encounter the hidden marines on Exodus."],
        ["Didact's Hand", "Halo 4: Complete all chapters in Spartan Ops Episode 4."],
        ["Didn't Like This Ship Anyways", "Halo CE: Beat the par time on The Pillar of Autumn."],
        ["Digging up the Past", "Halo 4: Access the Master Chief's records on Dawn."],
        ["Digital Destinies", "Halo: Reach: Find Data Pad 9 on The Pillar Of Autumn"],
        ["Dim Mak", "Earn a total of 250 Beat Down medals in multiplayer."],
        ["Dirge of Madrigal", "Halo 3: Trigger the hidden music cue in Halo 3."],
        ["Dirty Bird", "Halo 2: Fly the Heretic Banshee."],
        ["Do Tell", "H3: ODST: Find the 4th Audio Log."],
        ["Do You Remember When We Met", "H3: ODST: Play a game of Halo 3: ODST on the 22nd of any month."],
        ["Does Whatever a Spartan Can?", "H3: ODST: Destroy a Wraith…with your bare hands."],
        ["Dogcatcher", "Kill 1000 Crawlers."],
        ["Domination", "Earn a total of 100 Legendary medals in matchmade games."],
        ["Don't Hangar Around", "Halo 2: Beat the par time on Cairo Station."],
        ["Don't Make a Girl a Promise", "Halo 2: Collect the Cortana toy in Gravemind."],
        ["Don't Strain Your Metaphors", "H3: ODST: Beat the par score on Uplift Reserve."],
        ["Double Down", "Halo 2A MP: In Anniversary multiplayer, receive 2 or more Double Kill medals."],
        ["Double Time!", "H3: ODST: Beat the par time on Coastal Highway."],
        ["Double Trouble", "Earn a total of 250 Double Kill medals in matchmade games."],
        ["Dust And Echoes", "Halo: Reach: Complete New Alexandria."],
        ["E E E", "Halo 2: View both signs in the level Metropolis."],
        ["Ear Bender", "H3: ODST: Find the 16th Audio Log."],
        ["Easy As One Two Three", "Halo 4: Beat the par time on all Halo 4 levels."],
        ["Easy to Overlook", "Halo: Reach: Access hidden UNSC radio chatter."],
        ["Eavesdropping", "H3: ODST: Find the 6th Audio Log."],
        ["Elder Signs", "Halo 3: View 2 different sigils on Valhalla."],
        ["Emergency Shutdown", "Halo 4: Beat the par score on Shutdown."],
        ["Eminent Domain", "Halo 2A MP: In Territories, control any 3 Territories simultaneously for 30 seconds."],
        ["Enamored", "Halo 2: Activate Terminal 7 on Regret."],
        ["Enchanted", "Halo 2: Activate Terminal 6 on Delta Halo."],
        ["Enemies Everywhere!", "Halo: Reach: Complete a Firefight set on Normal or Harder."],
        ["Examiner", "Halo 2: Activate Terminal 3 on Metropolis."],
        ["Excellent Taste", "Halo CE: Complete three Halo: CE playlists."],
        ["Exodus", "Halo 4: Complete all chapters in Spartan Ops Episode 10."],
        ["Expendable", "Halo 4: Complete all chapters in Spartan Ops Episode 8."],
        ["Explore the Floor", "Halo 4: Trick or force a Hunter to fall to its demise on Shutdown on Heroic or Legendary."],
        ["Exterminator", "Halo 3: Beat the par score on Floodgate."],
        ["Fascinated", "Halo 2: Activate Terminal 5 on The Oracle."],
        ["Fast and Low", "H3: ODST: Splatter 7 enemies with a Banshee on Kikowani Station."],
        ["Fast Fall", "Halo: Reach: Beat par time on all Halo: Reach levels."],
        ["Feeling Charitable", "Halo 2: Beat the par time on High Charity."],
        ["Feet Don't Fail Me Now", "H3: ODST: Beat the par time on Kikowani Station."],
        ["Feet Firmly Planted", "Halo CE: Complete a level without jumping."],
        ["Feet First", "Halo 4: Complete all Spartan Ops chapters."],
        ["Finished the Fight", "Halo 3: Complete every level of the game on Legendary difficulty."],
        ["Firefly", "H3: ODST: Kill a Drone with a flame grenade on Data Hive."],
        ["First In, Last Out", "H3: ODST: Complete every level of the game on Heroic difficulty."],
        ["First Stop: Anywhere But Here!", "H3: ODST: Beat the par time on NMPD HQ."],
        ["Fists of Fury", "Halo 2: Beat the par score on Regret."],
        ["Flaming Ninja Anniversary", "Halo 2A MP: Kill an opponent that has the Ninja Redux achievement in Anniversary matchmaking."],
        ["Flipyap", "Halo 3: Listen to the tale of a young Grunt named Flipyap."],
        ["Flood", "Halo 4: Activate Terminal 4 on Reclaimer."],
        ["Floor It!", "H3: ODST: Beat the par time on Uplift Reserve."],
        ["Fly, You Fools!", "Halo: Reach: Find the hidden Banshees on The Package."],
        ["Flyover Country", "Halo CE: Beat the par time on Halo."],
        ["Foe Hammer", "Kill 5,000 enemies or players."],
        ["Folks Need Heroes…", "Halo: Reach: Complete every level of the game on Heroic difficulty."],
        ["Force of Will", "Halo 2: Beat the par time on Gravemind."],
        ["Forerunner", "Halo 4: Complete Forerunner."],
        ["Forged in Fire", "Win 100 multiplayer games."],
        ["Forza in the Fall", "Halo: Reach: Flip the switches to become a Reach Racer!"],
        ["Fowl Hunt", "H3: ODST: Kill 3 Jetpack Brutes with a shotgun on Oni Alpha Site."],
        ["Frequent Flyer Miles", "Halo 2: Beat the par score on The Great Journey."],
        ["Front Page News", "Halo: Reach: Find me in the club."],
        ["Game Breaker", "Halo: Reach: Kill 10 enemies while using a Jetpack."],
        ["Game Master", "Created and saved 5 Custom Game types."],
        ["Game On", "Complete 50 missions or multiplayer games."],
        ["Gate Your Thirst!", "Halo 2A MP: Found and destroyed the BLAST soda can on Stonetown."],
        ["Generous Tipper", "Halo: Reach: Beat the par time on Tip of the Spear."],
        ["Get A Load", "H3: ODST: Find the 13th Audio Log."],
        ["Get Me Out of Here!", "Halo CE: Ride in a Pelican for several seconds on the level 343 Guilty Spark."],
        ["Giant Hula Hoop", "Halo CE: Beat the par score on Halo."],
        ["Gimme That", "Halo 4: Beat the par time on Reclaimer."],
        ["Give Heed", "H3: ODST: Find the 12th Audio Log."],
        ["Give Him the Stick", "Halo 4: Take out both Hunters using only the Sticky Detonator on Composer."],
        ["Go Ape Shiv", "Halo 2: Kill an enraged, berserk Brute using melee."],
        ["Go, Chief! Gun It!", "Halo 3: Beat the par time on Halo."],
        ["Goat Roped", "Halo CE: Halo CE: Complete all Halo: CE Legendary campaign missions in under 3 hours."],
        ["Gods Must Be Strong", "Halo: Reach: Complete every level of the game on Legendary difficulty."],
        ["Going Bananas", "Kill 100 Brutes."],
        ["Going International", "Halo 4: Complete a match on at least 8 different multiplayer maps."],
        ["Going Nowhere Fast", "Halo 2: Beat par time on all Halo 2 levels."],
        ["GOOOAAAAALLLL!", "Halo 2: Shoot the soccer ball in the level Metropolis."],
        ["Grand Theft Halo", "Halo 2A MP: In one match, steal a total of 5 occupied vehicles from opponents."],
        ["Gravemind", "Halo 2: Complete Gravemind."],
        ["Greenhorn", "Halo CE: Complete every level of the game on Easy difficulty."],
        ["Gruntageddon", "Kill 1000 Grunts."],
        ["Guerilla", "Halo 3: Beat the par score on Sierra 117."],
        ["Guided Tour", "Halo 2: Beat the par score on Sacred Icon."],
        ["Gumshoe", "H3: ODST: Find the 3rd clue unraveling the mystery."],
        ["Gunslinger", "Halo 4: Beat the par score on Dawn."],
        ["Halo", "Halo CE: Complete Halo."],
        ["Hang Onto My Words", "H3: ODST: Find the 11th Audio Log."],
        ["Haplorrhini", "Halo 3: Find a lonely missing link."],
        ["Hazard Pay", "Halo 4: Complete all Spartan Ops chapters on Heroic difficulty."],
        ["HBOrg Special", "Halo: Reach: Party with the DJ Brute."],
        ["He Never Gets Me Anything", "Halo 2: Complete Delta Halo without entering a vehicle on Heroic or Legendary."],
        ["He's Running a Marathon...", "Halo 2: Spot the developer in the opening cutscene of Gravemind on Legendary in Classic Mode."],
        ["He's Unstoppable", "Halo CE: Complete any level on Heroic difficulty or higher without taking health damage."],
        ["Head Banging", "Halo 4: Beat the par score on Composer."],
        ["Headhunter", "Halo CE: Find and claim all Skulls in Halo: CE."],
        ["Heading to his Destiny", "Halo 3: Destined for greatness."],
        ["Headstrong", "Halo CE: Beat the par score on Keyes."],
        ["Hear Me Out", "H3: ODST: Find the 5th Audio Log."],
        ["Herald of the Reclamation", "Complete all campaigns on Easy difficulty."],
        ["Heresy Will Not Stay My Feet", "Halo 2: Beat the par score on The Arbiter."],
        ["Heretic Skull", "Halo 3: Find the hidden Skull on the Heretic multiplayer map."],
        ["Hero", "Halo 2: Complete every level of the game on Heroic difficulty."],
        ["Hey, You Dropped This", "Halo: Reach: Find Data Pad on 1 Winter Contingency"],
        ["HI BEN", "Halo 2: Oh, hi!"],
        ["High Altitude Thirst!", "Halo 2A MP: Found and destroyed the BLAST soda can on Zenith."],
        ["High Charity", "Halo 2: Complete High Charity."],
        ["Highway Robbery", "Halo 3: Beat the par time on Tsavo Highway."],
        ["Hippo Hero", "Halo 3: Who DARED to discard this brave animal?"],
        ["Hit The Beach", "Halo CE: Beat the par time on The Silent Cartographer."],
        ["Hitchhikers May Be Escaping Convicts", "Halo CE: Activate Terminal 5 on Assault on the Control Room."],
        ["Holdout", "Halo 3: Complete Crow's Nest."],
        ["Hot Zone", "Halo 2: Beat the par time on Quarantine Zone."],
        ["How Did I Lose All My Fingers?", "Halo: Reach: Beat the par score on The Package."],
        ["How Pedestrian", "Halo CE: Complete Halo without entering a vehicle."],
        ["Hunters Hunted", "Kill 50 Hunters."],
        ["I Dabble in Slaying", "Complete one cross-game playlist."],
        ["I Didn't Train To Be A Pilot", "Halo: Reach: Kill 3 of the anti-aircraft batteries during New Alexandria."],
        ["I Got This", "Complete 100 missions or multiplayer games."],
        ["I Like Crazy", "Halo 2: Collect the Rampant Cortana toy in High Charity."],
        ["I Love My Job", "H3: ODST: Beat the par score on ONI Alpha Site."],
        ["I Need a Hero", "Halo 4: Complete every level of the game on Heroic difficulty."],
        ["I Need A Weapon", "Halo: Reach: Complete Nightfall."],
        ["I Regret Nothing", "Halo 2: Beat the par time on Regret."],
        ["I Was Wondering What Would Break First", "Kill 100 Knights."],
        ["I'm Sorry, Dave", "Halo: Reach: Find the hidden binary signature."],
        ["Icarus", "Halo 4: Complete all Spartan Ops chapters on Legendary difficulty."],
        ["Ice In Your Veins", "Halo: Reach: Beat the par score on Winter Contingency."],
        ["Idle Hands", "Halo CE: Activate Terminal 4 on The Silent Cartographer."],
        ["In It To Win It", "Win 200 multiplayer games."],
        ["Infinity", "Halo 4: Complete Infinity."],
        ["Info Dump", "Halo: Reach: Find Data Pad 6 on Exodus"],
        ["Inquisitive", "Halo 2: Activate Terminal 2 on Outskirts."],
        ["Insomnia", "Halo: Reach: Beat the par score on Long Night of Solace."],
        ["Inspector", "Halo 2: Activate Terminal 4 on The Arbiter."],
        ["Interloper", "Halo 4: Beat the par time on Requiem."],
        ["Into The Howling Dark", "Halo: Reach: Complete Exodus."],
        ["Inundation", "Halo 3: Activate Terminal 2 on The Ark."],
        ["Invaders Repelled", "Halo 2A MP: In King of the Hill, kill 5 opponents within your controlled hill."],
        ["Invasion", "Halo 4: Complete all chapters in Spartan Ops Episode 7."],
        ["Investigator", "H3: ODST: Find the 2nd clue to unraveling the mystery."],
        ["It Was Inevitable", "Halo CE: Beat the par score on Two Betrayals."],
        ["Jorge Can't Have All the Big Guns", "Halo: Reach: Use a Pelican turret."],
        ["Jungle Warfare", "Halo 4: Beat the par score on Infinity."],
        ["Junior Detective", "H3: ODST: Find the 1st clue to unraveling the mystery."],
        ["Just A Taste", "Collect 500 campaign or playlist medals."],
        ["Just Browsing", "Halo 3: Complete a match on at least 4 different game types in multiplayer."],
        ["Just Getting Started", "Kill 100 enemies or players."],
        ["Just Like Storming a Castle", "Halo: Reach: Beat the par time on ONI: Sword Base."],
        ["Just Sayin...I Ain't Dead", "H3: ODST: Complete any level without dying on Heroic or Legendary."],
        ["Justice", "Halo 4: Activate Terminal 6 on Composer."],
        ["Keep It Clean", "Halo: Reach: Kill 7 Moa during Winter Contingency."],
        ["Keep Your Foot on the Pedrogas", "Halo: Reach: Complete all Halo: Reach Legendary campaign missions in under 3 hours."],
        ["Key", "Halo 4: Complete all chapters in Spartan Ops Episode 9."],
        ["Keyes", "Halo CE: Complete Keyes."],
        ["Kikowani Station", "H3: ODST: Complete Kikowani Station."],
        ["Kilotons of Fun", "Halo CE: Activate Terminal 10 on The Maw."],
        ["King of the Crows", "Halo 3: Beat the par score on Crow's Nest."],
        ["Kizingo Boulevard", "H3: ODST: Complete Kizingo Blvd."],
        ["Knight in White Assassination", "Halo 4: Assassinate a Knight in any Spartan Ops mission."],
        ["Knightbane", "Kill 1000 Knights."],
        ["Knights", "Halo 4: Activate Terminal 5 on Shutdown."],
        ["Knowledgable", "Halo 2: Activate Terminal 10 on Gravemind."],
        ["Landfall", "Halo 3: Complete Sierra 117."],
        ["LASO Master", "Complete each individual game specific LASO playlist for every Halo game."],
        ["Last Stand", "Halo 3: Complete The Covenant."],
        ["Leave It Where It Lay", "Halo CE: Complete Two Betrayals on Legendary difficulty without picking up a new weapon."],
        ["Leave None Alive", "Halo 2: Beat the par score on The Oracle."],
        ["Left Behind", "Halo: Reach: Achieve a score of 30,000 points on Lone Wolf."],
        ["Legend", "Complete all campaigns on Legendary difficulty."],
        ["Legend Slayer", "Halo 2A MP: Kill an opponent that has the Legendary Anniversary achievement."],
        ["Legendary Anniversary", "Halo 2: Complete every level of the game on Legendary difficulty."],
        ["Librarian's Gift", "Halo 4: Complete every level of the game on Easy difficulty."],
        ["Librarian's Pet", "Halo 4: Beat the par score on Reclaimer."],
        ["Life Story", "Complete the Master Chief Saga playlist."],
        ["Lightning in a Bottle", "Halo CE: Beat the par time on 343 Guilty Spark."],
        ["Lightning Strike", "Halo 3: Beat the par time on The Storm."],
        ["Like a Broken Record", "H3: ODST: Find a legendary hidden music cue."],
        ["Like a Fine Wine", "Halo CE: Complete the Halo: CE LASO Campaign playlist."],
        ["Like Peanut Butter and Chocolate", "Halo 2: Complete a level in co-op on Heroic or Legendary with the Masterblaster Skull active."],
        ["Listener", "H3: ODST: Find the 1st Audio Log."],
        ["Living Legend", "Halo CE: Complete every level of the game on Legendary difficulty."],
        ["Lone Wolf Legend", "Halo 4: Complete every level of the game on Legendary difficulty, by yourself."],
        ["Long Time Fan", "Complete 450 missions or multiplayer games."],
        ["Longshore Skull", "Halo 3: Find the hidden Skull on the Longshore multilayer map."],
        ["Look Out for the Little Guys", "Halo CE: Complete Two Betrayals on Legendary difficulty without killing any Grunts."],
        ["Lord of Admirals", "Halo 4: Activate Terminal 2 on Forerunner."],
        ["Lore Master", "Activate all terminals."],
        ["Madrigal Debut", "Halo CE: Trigger a hidden music cue in Halo: CE."],
        ["Magic Touch", "H3: ODST: Beat the par score on Data Hive."],
        ["Making History", "Halo 3: Beat the par time on Cortana."],
        ["Man on the Moon", "Halo 3: He's watching you."],
        ["Master Forger", "Created and saved 5 Custom Maps in Forge."],
        ["Mean Streets of New Mombasa", "H3: ODST: Complete every level of the game on Legendary difficulty."],
        ["Medal Completionist", "Collect 10,000 campaign or playlist medals."],
        ["Medal Master Chief", "Collect 8,000 campaign or playlist medals."],
        ["Meddling and Madness", "Halo: Reach: Find Data Pad 13 on Tip Of The Spear on Legendary difficulty"],
        ["Meeting of the (Artificial) Minds", "Halo: Reach: Find Data Pad 3 on Nightfall"],
        ["Megg", "Halo CE: It's a sign."],
        ["Memento Mori", "Halo 4: Complete all chapters in Spartan Ops Episode 5."],
        ["Memories", "Halo CE: Activate Terminal 8 on Two Betrayals."],
        ["Metropolis", "Halo 2: Complete Metropolis."],
        ["Midnight", "Halo 4: Complete Midnight."],
        ["Milk Carton", "Halo 3: Find the poster of the missing man."],
        ["Mind Games", "Halo CE: Activate Terminal 9 on Keyes."],
        ["Mind the Gap", "Halo 3: 4 vehicles, 1 gap on Legendary using Cowbell, Catch, Thunderstorm, Mythic, and Tough Luck."],
        ["Mind the Skill Gap", "Halo: Reach: Observe the logo of a buttoned-up mining company."],
        ["Minority Report", "Halo: Reach: Find Data Pad 5 on Long Night Of Solace"],
        ["Missing Link", "Halo 3: Watching. Waiting. Plotting."],
        ["Monitored", "H3: ODST: Find the 10th Audio Log."],
        ["Monopolized", "Halo 2: Complete all Halo 2 Legendary campaign missions in under 3 hours."],
        ["Monumental Thirst!", "H2A: Found and destroyed the BLAST soda can on Remnant.."],
        ["Moon's Out, Goons Out", "Halo: Reach: Beat the par score on Nightfall."],
        ["Mortardom", "Halo 4: On Reclaimer, use a Wraith to kill at least four enemy Wraiths on Heroic or Legendary."],
        ["Multiplayer Champion", "Win 500 multiplayer games."],
        ["MVP", "Halo 2A MP: Finished as the top player on the winning team in a matchmade game."],
        ["My Buddy Chips", "Halo CE: Fight alongside Chips Dubbo and listen to his words of wisdom."],
        ["My Work is Done", "Halo 2: Collect the Librarian toy in Uprising."],
        ["Mystery Achievement", "Inscrutable. Mysterious."],
        ["Nagato Makes Moving Easy", "H3: ODST: Complete all Halo 3: ODST Legendary campaign missions in under 3 hours."],
        ["Naked Tyrant", "Halo 4: Complete the Halo 4 LASO Campaign playlist."],
        ["Naughty Naughty", "Kill 10 Engineers."],
        ["Needs More Whammy Bar", "Halo 2: Complete the level Regret with the Prophet Birthday Skull activated."],
        ["Negative, Ghostrider", "Halo: Reach: Get a Skullamanjaro in a matchmade Headhunter game."],
        ["New Ways to Save a Buck", "Halo: Reach: Hear a familiar voice on New Alexandria."],
        ["NEXT!", "H3: ODST: Complete a Halo 3: ODST playlist."],
        ["Nice Work Dawg!", "Earn a total of 2,500 Assist medals in multiplayer."],
        ["Nine Lives Are a Myth", "Halo: Reach: Beat the par score on New Alexandria."],
        ["Ninja Redux", "Halo 2A MP: Kill 5 people with melee from behind in Anniversary matchmaking."],
        ["NMPD HQ", "H3: ODST: Complete NMPD HQ."],
        ["No Easy Way Out", "Halo 4: Survive Spartan Miller (Ep.5 Ch.1) of Spartan Ops on Heroic or Legendary."],
        ["No Man's Land", "Halo 2: Beat the par time on Uprising."],
        ["No One Left Behind", "Halo 4: Save at least one Marine on Hacksaw (Ep.2 Ch.3) of Spartan Ops on Heroic or Legendary."],
        ["No Pain, No Gain", "Complete 1 mission with the LASO playlist skulls enabled."],
        ["No Picnic", "Halo: Reach: Observe a grizzly scene on New Alexandria."],
        ["No Smoking", "Halo CE: Disapprovingly look at Captain Keyes' abandoned pipe."],
        ["No Stone Unturned", "Halo 3: Activate all Halo 3 Terminals."],
        ["No-Fly Zone", "Halo CE: Destroy three of the four Banshees on Halo during a single play-through."],
        ["Now Just You Gúta Minute", "Halo: Reach: Beat the par time on Nightfall."],
        ["Objective Secured", "Halo 2: Beat the par score on Outskirts."],
        ["Observant", "H3: ODST: Find the 20th Audio Log."],
        ["Obsessed", "Halo 2: Activate Terminal 13 on The Great Journey."],
        ["Of Patience and Partiality", "Halo: Reach: Find Data Pad 15 on Exodus on Legendary difficulty"],
        ["Official Business", "Halo 2: Beat the par score on Gravemind."],
        ["Oh, These Baubles?", "Collect 6,000 campaign or playlist medals."],
        ["On Your Toes", "H3: ODST: Find the 25th Audio Log."],
        ["One Final Firefight", "Halo: Reach: Achieve a score of 150,000 points on Lone Wolf."],
        ["One For the Record Books", "Halo: Reach: Beat the par time on New Alexandria."],
        ["One Got Away", "H3: ODST: View the missing link."],
        ["One Way Ride", "H3: ODST: Complete any level without using a health pack on Heroic or Legendary."],
        ["ONI Alpha Site", "H3: ODST: Complete ONI Alpha Site."],
        ["Operation Completion", "Halo 4: Complete a Spartan Ops mission."],
        ["Oracle", "Halo 2: Complete The Oracle."],
        ["Orbital Skull", "Halo 3: Find the hidden Skull on the Orbital multiplayer map."],
        ["Orpheus", "Halo 3: Beat the par score on Cortana."],
        ["Ouroboros", "Halo 4: Beat the par time on Infinity."],
        ["Outskirts", "Halo 2: Complete Outskirts."],
        ["Overachiever", "Halo CE: Beat the par score on all Halo: CE levels."],
        ["Overheard", "H3: ODST: Find the 8th Audio Log."],
        ["Overshields are for Sissies", "Halo CE: Complete the level The Pillar of Autumn on Legendary without picking up an overshield."],
        ["Overtaken By Events", "H3: ODST: Beat the par time on Data Hive."],
        ["Pacifist", "Halo CE: Finish The Silent Cartographer without shooting, grenades, melee, dying or restarting."],
        ["Paper Trail", "Halo: Reach: Find Data Pad 7 on New Alexandria"],
        ["Parting the Sea", "Halo: Reach: Beat the par score on Exodus."],
        ["Party Pooper", "Earn a total of 250 Killjoy medals in matchmade games."],
        ["Pest Control", "Kill 100 Crawlers."],
        ["Phantom Hunter", "Halo 3: Destroy 3 total Phantoms on The Covenant."],
        ["Piece of Cake", "Halo 4: Beat the par time on Dawn."],
        ["Pillar of Autumn", "Halo CE: Complete The Pillar of Autumn."],
        ["Pillar of Awesome", "Halo CE: Beat the par score on The Pillar of Autumn."],
        ["Pineapple Express", "H3: ODST: Kill 4 enemies with a single plasma or frag grenade."],
        ["Planting A Flag", "Earn a total of 250 CTF Mode Specific medals in matchmade games."],
        ["Play Us a Sad Song, Claude", "Halo: Reach: Listen to a hidden music cue."],
        ["Plugged In", "H3: ODST: Find the 17th Audio Log."],
        ["Pour It On", "H3: ODST: Beat the par score on NMPD HQ."],
        ["Power Play", "Halo 2A MP: On Warlord, get 5 active camouflage power ups in a single game."],
        ["Precious Cargo", "Halo: Reach: Beat the par score on The Pillar of Autumn."],
        ["Primate", "Halo 3: Find your first missing links."],
        ["Private Eye", "H3: ODST: Find the 5th clue unraveling the mystery."],
        ["Prophet's Bane", "Halo 3: Complete every level of the game on Normal difficulty."],
        ["Protocol Dictates Action", "Halo: Reach: Complete ONI: Sword Base."],
        ["Put Up Your Dukes", "Halo 2A MP: Get 25 melee kills in multiplayer."],
        ["Pyrrhic Solution", "Halo 2: Collect the Didact toy in The Great Journey."],
        ["Quarantine Zone", "Halo 2: Complete Quarantine Zone."],
        ["Quick Trigger Finger", "Win 450 multiplayer games."],
        ["Quicker Than Reading the Book", "Halo: Reach: Beat the par time on Exodus."],
        ["Quis custodiet ipsos custodes?", "Halo CE: Activate Terminal 7 on The Library."],
        ["Raging in the Dark", "Halo 4: Beat the par time on Forerunner."],
        ["Rampant Speculation", "Halo: Reach: Find Data Pad 4 on Tip Of The Spear"],
        ["Ranger", "Halo 3: Beat the par score on The Ark."],
        ["Reach Has Been Good to Me", "Halo: Reach: Complete a Halo: Reach playlist."],
        ["Read Halsey's Journal", "Halo: Reach: Find Data Pad 2 on ONI: Sword Base"],
        ["Reading Room", "Halo CE: Beat the par score on The Library."],
        ["Reclaimer", "Halo 4: Complete Reclaimer."],
        ["Record Store Owner", "H3: ODST: Find all 30 Audio Logs."],
        ["Red vs. Blue", "Halo 2A MP: Win 10 matches on Bloodline in multiplayer."],
        ["Reed the Strategy", "Halo 2: Beat the par time on The Oracle."],
        ["Refuge", "Halo 3: Complete The Ark."],
        ["Regret", "Halo 2: Complete Regret."],
        ["Regrettable Turn of Events", "Halo 2: Collect the Prophet of Regret toy in Regret."],
        ["Remember Reach", "Halo: Reach: Play a game of Halo: Reach on the 14th of any month."],
        ["Remove the Bishops From the Board", "Kill 1000 Watchers."],
        ["Requiem", "Halo 4: Complete Requiem."],
        ["Requiescat in Pace", "Halo: Reach: Complete 10 assassinations on enemy players."],
        ["Return", "Halo 3: Complete Halo."],
        ["Reviewer", "Halo 2: Activate Terminal 12 on High Charity."],
        ["Rex Sword", "Halo 2: Grab the energy sword on the level Outskirts."],
        ["Ripple Fire", "Halo 2: Beat the par score on Metropolis."],
        ["Rising Waters", "Halo 3: Activate Terminal 1 on The Ark."],
        ["Roadkill Rampage", "Halo 2A MP: In Anniversary matchmaking, earn a total of 100 Splatter medals."],
        ["Rock and Coil Hit Back", "Halo 2A MP: In Anniversary matchmaking, earn a total of 100 Environmentalist medals."],
        ["Rooftop Runner", "Halo 2: Beat the par time on Outskirts."],
        ["Rookie", "H3: ODST: Complete every level of the game on Easy difficulty."],
        ["Roses vs Violets", "Halo 4: Why are you even here?"],
        ["Rule Your Thirst!", "Halo 2A MP: Found and destroyed the BLAST soda can on Warlord."],
        ["Run and Gunned", "Halo: Reach: Headshot 10 enemies while they are sprinting."],
        ["Sabre Metrics", "Halo: Reach: Beat the par time on Long Night of Solace."],
        ["Sacred Icon", "Halo 2: Complete Sacred Icon."],
        ["Sacrifice", "Halo CE: Activate Terminal 2 on Halo."],
        ["Safety Not Guaranteed", "H3: ODST: Complete a Halo 3: ODST LASO Campaign playlist."],
        ["Sample Plate", "Complete three cross-game playlists."],
        ["Sandbox Skull", "Halo 3: Find the hidden Skull on the Sandbox multiplayer map."],
        ["Saturday Morning Cartoon", "H3: ODST: Is there a toy inside?"],
        ["Scarab Lord", "Halo 2: Acquire the Scarab Gun."],
        ["Scarab Slide", "Halo 3: Beat the par time on The Covenant."],
        ["Scattered", "Halo 4: Complete all chapters in Spartan Ops Episode 6."],
        ["Scavenger Hunt", "Kill 1000 Jackals."],
        ["Scholar", "Halo 2: Activate Terminal 11 on Uprising."],
        ["Scorched Earth", "Halo 2: Beat the par score on High Charity."],
        ["Scout", "H3: ODST: Find the 21st Audio Log."],
        ["Scurty Bump", "Halo CE: Beat the par time on Keyes."],
        ["Seconds", "Halo 2: Complete a Halo 2 playlist."],
        ["Secret Agent", "H3: ODST: Find the 6th clue unraveling the mystery."],
        ["Send Me Out... With A Bang", "Halo: Reach: Complete The Pillar of Autumn."],
        ["Shadow of Sundered Star", "Halo 4: Beat the par score on Forerunner."],
        ["Sharpshooter", "Win 150 multiplayer games."],
        ["Shields Up!", "Halo 2A MP: On Zenith, personally activate the center energy shield 3 times in one matchmade game."],
        ["Shiny...", "H3: ODST: Pilot a Banshee on Kizingo Boulevard."],
        ["Shook the Hornet's Nest", "Halo 2A MP: Get 30 kills with the Hornet in multiplayer."],
        ["Shoot and Scoot", "H3: ODST: Complete NMPD HQ without firing the Sniper Rifle on Heroic or Legendary."],
        ["Shut. Down. Everything.", "Halo 4: Beat the par time on Shutdown."],
        ["Shutdown", "Halo 4: Complete Shutdown."],
        ["Sid Graffiti", "Halo 2: Spot the Sid graffiti on the walls of Coagulation in classic multiplayer."],
        ["Siege of Ivory Tower", "Halo 2: Listen to a hidden music cue in Halo 2."],
        ["Sightseeing", "Halo CE: Complete a match on at least 8 different classic multiplayer maps."],
        ["Silent but Deadly", "Halo 2: Kill 7 opponents from behind in a row without being spotted."],
        ["Silent Shepherds", "Halo: Reach: Find Data Pad 17 on The Package on Legendary difficulty"],
        ["Six Pedals, Four Directions", "Halo 2: Drive a Scorpion while playing as the Arbiter."],
        ["Skeet Shooter", "Halo 2A MP: Killed 15 opponents that were airborne from a Man Cannon."],
        ["Skulltaker Halo 2: Anger", "Halo 2: Find and claim the Anger Skull on Legendary."],
        ["Skulltaker Halo 2: Assassins", "Halo 2: Find and claim the Assassins Skull on Legendary."],
        ["Skulltaker Halo 2: Black Eye", "Halo 2: Find and claim the Black Eye Skull on Legendary."],
        ["Skulltaker Halo 2: Blind", "Halo 2: Find and claim the Blind Skull."],
        ["Skulltaker Halo 2: Catch", "Halo 2: Find and claim the Catch Skull on Legendary."],
        ["Skulltaker Halo 2: Envy", "Halo 2: Find and claim the Envy Skull on Legendary."],
        ["Skulltaker Halo 2: Famine", "Halo 2: Find and claim the Famine Skull on Legendary."],
        ["Skulltaker Halo 2: Ghost", "Halo 2: Find and claim the Ghost Skull on Legendary."],
        ["Skulltaker Halo 2: Grunt Birthday Party", "Halo 2: Find and claim the Grunt Birthday Party Skull on Legendary."],
        ["Skulltaker Halo 2: Iron", "Halo 2: Find and claim the Iron Skull on Legendary."],
        ["Skulltaker Halo 2: IWHBYD", "Halo 2: Find and claim the IWHBYD Skull on Legendary."],
        ["Skulltaker Halo 2: Mythic", "Halo 2: Find and claim the Mythic Skull on Legendary."],
        ["Skulltaker Halo 2: Sputnik", "Halo 2: Find and claim the Sputnik Skull on Legendary."],
        ["Skulltaker Halo 2: That's Just…Wrong", "Halo 2: Find and claim the That's Just...Wrong Skull on Legendary."],
        ["Skulltaker Halo 2: Thunderstorm", "Halo 2: Find and claim the Thunderstorm Skull on Legendary."],
        ["Skulltaker Halo 3: Black Eye", "Halo 3: Find and claim the Black Eye Skull on Normal or harder."],
        ["Skulltaker Halo 3: Blind", "Halo 3: Find and claim the Blind Skull on Normal or harder."],
        ["Skulltaker Halo 3: Catch", "Halo 3: Find and claim the Catch Skull on Normal or harder."],
        ["Skulltaker Halo 3: Cowbell", "Halo 3: Find and claim the Cowbell Skull on Normal or harder."],
        ["Skulltaker Halo 3: Famine", "Halo 3: Find and claim the Famine Skull on Normal or harder."],
        ["Skulltaker Halo 3: Fog", "Halo 3: Find and claim the Fog Skull on Normal or harder."],
        ["Skulltaker Halo 3: Grunt Birthday Party", "Halo 3: Find and claim the Grunt Birthday Party Skull on Normal or harder."],
        ["Skulltaker Halo 3: Iron", "Halo 3: Find and claim the Iron Skull on Normal or harder."],
        ["Skulltaker Halo 3: IWHBYD", "Halo 3: Find and claim the IWHBYD Skull on Normal or harder."],
        ["Skulltaker Halo 3: Mythic", "Halo 3: Find and claim the Mythic Skull on Normal or harder."],
        ["Skulltaker Halo 3: Thunderstorm", "Halo 3: Find and claim the Thunderstorm Skull on Normal or harder."],
        ["Skulltaker Halo 3: Tilt", "Halo 3: Find and claim the Tilt Skull on Normal or harder."],
        ["Skulltaker Halo 3: Tough Luck", "Halo 3: Find and claim the Tough Luck Skull on Normal or harder."],
        ["Skulltaker Halo: CE: Bandana", "Halo CE: Find and claim the Bandanna skull in remastered mode."],
        ["Skulltaker Halo: CE: Black Eye", "Halo CE: Find and claim the Black Eye skull in remastered mode."],
        ["Skulltaker Halo: CE: Boom", "Halo CE: Find and claim the Boom skull in remastered mode."],
        ["Skulltaker Halo: CE: Eye Patch", "Halo CE: Find and claim the Eye Patch skull in remastered mode."],
        ["Skulltaker Halo: CE: Famine", "Halo CE: Find and claim the Famine skull in remastered mode."],
        ["Skulltaker Halo: CE: Fog", "Halo CE: Find and claim the Fog skull in remastered mode."],
        ["Skulltaker Halo: CE: Foreign", "Halo CE: Find and claim the Foreign skull in remastered mode."],
        ["Skulltaker Halo: CE: Grunt Birthday Party", "Halo CE: Find and claim the Grunt Birthday Party skull in remastered mode."],
        ["Skulltaker Halo: CE: Iron", "Halo CE: Find and claim the Iron skull in remastered mode."],
        ["Skulltaker Halo: CE: Malfunction", "Halo CE: Find and claim the Malfunction skull in remastered mode."],
        ["Skulltaker Halo: CE: Mythic", "Halo CE: Find and claim the Mythic skull in remastered mode."],
        ["Skulltaker Halo: CE: Pinata", "Halo CE: Find and claim the Pinata skull in remastered mode."],
        ["Skulltaker Halo: CE: Recession", "Halo CE: Find and claim the Recession skull in remastered mode."],
        ["Skunked", "Halo: Reach: Won a matchmade game of Invasion in the 1st phase."],
        ["Smooth Operator", "Halo 4: Complete all Spartan Ops chapters solo on Legendary difficulty."],
        ["Snoop Troop", "H3: ODST: Find the 14th Audio Log."],
        ["So You Don't Want the Tank?", "Halo 2: Beat the par time on Delta Halo."],
        ["Son of a Gun", "H3: ODST: Beat the par score on Kizingo Blvd."],
        ["Sounds Familiar", "Halo 3: This stuff is your history!"],
        ["Speed Demon", "Halo 3: Beat the par time on all Halo 3 levels."],
        ["Speeding Ticket", "Halo 2: Beat the par time on Metropolis."],
        ["Speedy Delivery", "Halo: Reach: Beat the par time on The Package."],
        ["Speedy One One Seven", "Halo 3: Beat the par time on Sierra 117."],
        ["Splinters", "Halo CE: Activate Terminal 3 on The Truth and Reconciliation."],
        ["Spoilsport", "Kill 100 Jackals."],
        ["Spotter", "H3: ODST: Find the 23rd Audio Log."],
        ["Spree Master", "Earn a total of 100 Killing Spree medals in matchmade games."],
        ["Squid Jackpot!", "H3: ODST: Beat the par score on Kikowani Station."],
        ["Standard Operating Brocedure", "Complete any co-op level on Normal difficulty."],
        ["Starved For Shields", "Halo 2: Complete a level with only the Streaking Skull active on Heroic or Legendary."],
        ["Stayin' Alive", "Halo 2A MP: In Juggernaut, survive as the Juggernaut for 30 seconds."],
        ["Steady Aim", "Win 400 multiplayer games."],
        ["Stick With It...A Little Longer", "Play a multiplayer or co-op game at least 3 months after your first game."],
        ["Still Sharp", "Halo: Reach: Beat the par score on ONI: Sword Base."],
        ["Striking Fear in Their Hearts", "Win 350 multiplayer games."],
        ["Strong, Silent Type", "H3: ODST: Assassinate 3 Brutes in a row on Data Hive."],
        ["Survey Says...", "H3: ODST: Beat the par score on Tayari Plaza."],
        ["Swift and Shallow", "Halo: Reach: Hijack a Banshee during the Reach Campaign."],
        ["Sword and Shield", "Halo 3: Activate Terminal 7 on Halo."],
        ["Symphony of Pain", "Halo 4: Beat the par time on Composer."],
        ["T-Rex", "Halo CE: Find the hidden Rex sign on The Maw."],
        ["T'vaoan Terminator", "Halo: Reach: Kill 100 Skirmishers."],
        ["Tank Beats Everything", "Halo: Reach: Finish The Package on Legendary with the Scorpion intact."],
        ["Taste Test", "Halo 4: Complete a match on at least 4 different game types in multiplayer."],
        ["Tayari Plaza", "H3: ODST: Complete Tayari Plaza."],
        ["Tempered Blade", "Win 10 multiplayer games."],
        ["Term of Enlistment", "Halo 4: Complete all Spartan Ops chapters on Normal difficulty."],
        ["Terminal Conditions", "Halo: Reach: Find Data Pad 8 on The Package"],
        ["Terminal Velocity", "Halo 2: Beat the par time on Sacred Icon."],
        ["Terminus", "Halo 4: Activate all Halo 4 Terminals."],
        ["Thanks A Killion", "Kill 20,000 enemies or players."],
        ["That Just Happened", "Halo CE: Complete The Library on Heroic or Legendary difficulty without dying."],
        ["The Answer is Simple", "Halo: Reach: Find Data Pad 14 on Long Night Of Solace on Legendary Difficulty"],
        ["The Arbiter", "Halo 2: Complete The Arbiter."],
        ["THE Chips Dubbo?", "Halo 2: Fight alongside the legendary Chips Dubbo and listen to his words."],
        ["The Coin's Fault", "Halo 3: Activate Cortana's Terminal on Cortana."],
        ["The Doctor Is In", "Halo 2: Beat the par score on Quarantine Zone."],
        ["The Good, The Bad, and The Dead", "Collect 9,000 campaign or playlist medals."],
        ["The Goose is Loose", "Halo 2A MP: Get 25 kills with the Gungoose in multiplayer."],
        ["The Great Journey", "Halo 2: Complete The Great Journey."],
        ["The Guardians Are Coming", "Get killed by the Guardians."],
        ["The Humble Beginnings of Wiljax Brantley", "Halo: Reach: Now that's a value meal."],
        ["The Hype Is Real", "Halo 2: Beat the par score on Uprising."],
        ["The Key", "Halo 3: Complete Cortana."],
        ["The Legend of 117", "Halo 4: Complete every level of the game on Legendary difficulty."],
        ["The Library", "Halo CE: Complete The Library."],
        ["The Long Haul", "Complete 500 missions or multiplayer games."],
        ["The Marine Corps Gives Its Regards", "H3: ODST: Beat par score on all Halo 3: ODST levels."],
        ["The Maw", "Halo CE: Complete The Maw."],
        ["The One Percent", "Kill 100 Elites."],
        ["The Return of Megg", "Halo 2: She's not picking up."],
        ["The Road", "Halo 3: Complete Tsavo Highway."],
        ["The Silent Cartographer", "Halo CE: Complete The Silent Cartographer."],
        ["The Soldier We Need You To Be", "Halo: Reach: Complete every level of the game on Normal difficulty."],
        ["The True King", "Earn a total of 250 KOTH Mode Specific medals in matchmade games."],
        ["The Will of the Prophets", "Halo 2: Collect the Arbiter toy in Sacred Icon."],
        ["Thermopylae", "Win 300 multiplayer games."],
        ["They've Always Been Faster", "Halo: Reach: Clear Winter Contingency without setting foot in a drivable vehicle."],
        ["Third Time's A Charm", "Halo 3: Play a game of Halo 3 on the 25th of any month."],
        ["Thirst Locked Down!", "Halo 2A MP: Found and destroyed the BLAST soda can on Lockdown."],
        ["Thirsty Grunt", "Halo CE: Listen to the Thirsty Grunt talk about his eating habits."],
        ["This is my Rifle, This is my Gun", "Halo 4: Carry a UNSC weapon all the way through Forerunner on Heroic or Legendary."],
        ["This is Not the Greatest Lab in the World…", "Halo: Reach: Find your way into Halsey's Lab on The Package."],
        ["This Is Not Your Grave", "Halo: Reach: Complete The Package."],
        ["This Oliphant Has No Brakes", "H3: ODST: Beat the par score on Coastal Highway."],
        ["This Side Up", "Halo CE: Complete the Warthog ride of The Maw without being forcibly ejected from your vehicle."],
        ["Those Left Behind", "H3: ODST: Finish Tayari Plaza with at least one Marine still breathing."],
        ["Throne of Bones", "Find and claim all the campaign skulls in Halo:CE, Halo 2, and Halo 3."],
        ["Tighten Up The Graphics", "Halo 2: Complete every level of Halo 2 having seen it in both classic and remastered mode."],
        ["Time Shift", "Halo 3: Beat the par time on Crow's Nest."],
        ["Tipping Point", "Halo 3: Activate Terminal 4 on The Covenant."],
        ["TLDR", "Halo CE: Beat the par time on The Library."],
        ["To War", "Halo: Reach: Complete Tip of the Spear."],
        ["Top Gungoose", "Halo 2A MP: Get a kill with the Gungoose while airborne."],
        ["Torchbearer", "Halo 3: Beat the par score on Halo."],
        ["Tour of Duty", "Halo 2A MP: Complete a game in every one of the 6 updated Anniversary MP maps."],
        ["Tourist", "Halo 2: Complete a match on at least 8 different classic multiplayer maps."],
        ["Toybox", "Halo 2: Collect all eight Halo toys."],
        ["Training Wheels", "Halo 3: Complete every level of the game on Easy difficulty."],
        ["Trifecta", "H3: ODST: Complete three Halo 3: ODST playlists."],
        ["Triple Threat", "Halo 2A MP: In Ricochet, pass once, score once, and kill at least one enemy in the same match."],
        ["Trophy Collector", "Halo 2: Find and claim all Skulls in Halo 2."],
        ["Truth and Reconciliation", "Halo CE: Complete The Truth and Reconciliation."],
        ["Tuned In", "H3: ODST: Find the 3rd Audio Log."],
        ["Two Betrayals", "Halo CE: Complete Two Betrayals."],
        ["Two Corpses In One Grave", "Halo: Reach: Kill 2 vehicles at once with the Target Locator during ONI: Sword Base."],
        ["Two Places, Same Time", "H3: ODST: I've got my eye on you, Marine."],
        ["Tying Up Loose Ends", "Halo CE: Kill every Elite on the level Keyes on Heroic or Legendary difficulty."],
        ["Unreliable Narrator", "Halo: Reach: Find Data Pad 10 on Winter Contingency on Legendary difficulty"],
        ["Unsolved Mysteries", "Halo: Reach: Find Data Pad 12 on Nightfall on Legendary difficulty"],
        ["Unto Dust", "Halo 3: Activate Terminal 5 on The Covenant."],
        ["Up All Night", "Complete 250 missions or multiplayer games."],
        ["Uplift Reserve", "H3: ODST: Complete Uplift Reserve."],
        ["Uprising", "Halo 2: Complete Uprising."],
        ["Urban Warfare Badge", "H3: ODST: Complete every level of the game on Normal difficulty."],
        ["Vandalized", "H3: ODST: Face it."],
        ["Vanguard", "Halo 3: Beat the par score on The Covenant."],
        ["Veteran", "Complete all campaigns on Normal difficulty."],
        ["Vetro Strike", "Halo CE: Beat the par score on Assault on the Control Room."],
        ["Wait, How'd the Ship Get Down Here?", "Halo: Reach: Beat the par time on The Pillar of Autumn."],
        ["Wake Up Buttercup", "Halo: Reach: Destroy the Corvette's engines & escort in under 3 minutes during Long Night of Solace "],
        ["Wake Up, John", "Halo 4: Complete every level of the game on Normal difficulty."],
        ["Walk It Off", "Halo CE: Complete The Pillar of Autumn on Legendary without picking up a health kit."],
        ["Walking Encyclopedia", "Halo 2: Activate all Halo 2 Terminals."],
        ["War", "Halo 4: Activate Terminal 1 on Requiem."],
        ["War Hero", "Complete all campaigns on Heroic difficulty."],
        ["Warden", "Halo 2 MP: In Classic or Anniversary matchmaking, stop the killing spree of another player."],
        ["Warrior", "Halo 2: Complete every level of the game on Normal difficulty."],
        ["Watchful", "H3: ODST: Find the 19th Audio Log."],
        ["Waypoint", "Halo 3: Beat the par time on The Ark."],
        ["We'll Be Back", "Halo: Reach: Beat the par score on every Halo: Reach level."],
        ["We're Gonna Need a Bigger Ship", "Halo: Reach: Fly both the Pelican and Phantom on New Alexandria."],
        ["We're Just Getting Started", "Halo: Reach: Complete Winter Contingency."],
        ["Welcome to Reach", "Halo: Reach: Complete every level of the game on Easy difficulty."],
        ["Well...Maybe One or Two", "Kill 25 Engineers."],
        ["Were It So Easy", "Kill 1000 Elites."],
        ["Wetwork", "Halo 2A MP: On Shrine in CTF, activate the enemy base waterfall and, before it stops, grab the flag."],
        ["What About Bob?", "Halo: Reach: Find and eliminate one of the hidden Ranger Commander Elites."],
        ["What About Those Tanks?", "H3: ODST: Destroy 7 Wraiths on Oni Alpha Site."],
        ["What Does It All Mean?", "Halo: Reach: Find Data Pad 11 on ONI: Sword Base on Legendary difficulty"],
        ["What Power Outage?", "Halo 4: Complete The Cauldron Base of Spartan Ops without losing a generator on Heroic or Legendary."],
        ["Where Am I?", "Complete 10 missions or multiplayer games."],
        ["Whispers Across the Galaxy", "Halo 3: View the communique from Mendicant Bias."],
        ["Whistle Stop Tour", "Halo CE: Beat the par time on Two Betrayals."],
        ["Who Needs Red Flag?", "Halo: Reach: Complete three Halo: Reach playlists."],
        ["Who Needs Them?", "Halo 3: On The Ark, complete the level without entering a vehicle on Legendary."],
        ["Why Am I Here?", "Halo 2: View this hidden message on the classic Beaver Creek map."],
        ["Why Do This To Yourself?", "Halo: Reach: Complete the Halo: Reach LASO Campaign playlist."],
        ["Why So Serious", "Halo 2: View the smiling face in the classic multiplayer map Coagulation."],
        ["Window Shopping", "Halo 2: Complete a match on at least 4 different game types in classic multiplayer."],
        ["Winter Urgency", "Halo: Reach: Beat the par time on Winter Contingency."],
        ["Wiretapping", "H3: ODST: Find the 9th Audio Log."],
        ["Wisening Up", "H3: ODST: Find the 29th Audio Log."],
        ["Witch Doctor", "Halo 3: Find and claim all Skulls in Halo 3."],
        ["Witching Hour", "Halo 4: Beat the par score on Midnight."],
        ["With Your Shield or On It", "Halo 3: Complete every level of the game on Heroic difficulty."],
        ["Workers' Compensation", "Halo: Reach: Splatter an enemy using the forklift."],
        ["World Traveler", "Halo 3: Complete a match on at least 8 different multiplayer maps."],
        ["Worship Your Thirst!", "Halo 2A MP: Found and destroyed the BLAST soda can on Shrine."],
        ["Would It've Killed You To Take The Elevator", "Halo CE: Beat the par time on Assault on the Control Room."],
        ["Wraith Hunter", "Halo CE: Destroy four Wraith tanks in Assault on the Control Room with the Scorpion tank."],
        ["Wyrmslayer", "Kill 250 Hunters."],
        ["Xenophobia", "H3: ODST: Complete any level without using Covenant weapons."],
        ["Yes No You Decide", "Halo: Reach: Find Data Pad 19 on Lone Wolf on Legendary difficulty"],
        ["YOLO Strats", "Halo 2: Beat the par time on The Arbiter."],
        ["You Are The Weapon", "Halo CE: Kill a Hunter with one pistol round."],
        ["You Can't Handle the Truth", "Halo CE: Beat the par time on The Truth and Reconciliation."],
        ["You Flew Pretty Good", "Halo: Reach: Complete Long Night of Solace."],
        ["You Had it Coming", "Halo 4: Beat the par score on every Halo 4 level."],
        ["You Really Can't Handle the Truth", "Halo CE: Beat the par score on The Truth and Reconciliation."],
        ["You're Joking", "Halo 4: Complete all Halo 4 Legendary campaign missions in under 3 hours."],
        ["You're No Chips", "Halo 4: What do Marines know about sticks?"],
        ["Your Attention Please", "H3: ODST: Find the 27th Audio Log."],
        ["Your Heresy Will Stay Your Feet", "Halo: Reach: Kill the Elite Zealot before he can escape during Tip of the Spear."],
        ["Your Journey Begins", "Complete a campaign mission or a match of multiplayer."],
        ["Zealot", "Halo 2A MP: In Anniversary matchmaking, win 10 games as an Elite."],
        ["Zombie Repeller", "Kill 1000 Flood."],
    ];

    assert.strictEqual(officialAchievements.length, 700, "sanity check on this test's own reference list");

    const dataPairs = game.achievements
        .map(a => [a.name, a.description])
        .sort((a, b) => a[0].localeCompare(b[0]));

    assert.deepStrictEqual(dataPairs, [...officialAchievements].sort((a, b) => a[0].localeCompare(b[0])));

});
