import { test } from "node:test";
import assert from "node:assert";

import { getPlannerData } from "../utils/plannerCatalog.js";

// backend/catalog/games/killing-floor-2.json - 307 real achievements sourced
// from a live ISteamUserStats/GetSchemaForGame/v2 response for appid
// 232090 (fetched through this app's own services/steamApi.js).
// This game has no hidden achievements: all 307 ship a real, official
// Steam description, quoted verbatim below.
// difficulty/estimatedTime/missable remain curatorial judgments.
const game = getPlannerData("killing-floor-2");

test("getPlannerData('killing-floor-2') returns real planner data with 307 curated achievements", () => {

    assert.ok(game, "expected real planner data for killing-floor-2");
    assert.ok(Array.isArray(game.achievements));
    assert.strictEqual(game.achievements.length, 307);

});

test("every Killing Floor 2 achievement has a unique id from 1 to 307 and a unique apiname", () => {

    const ids = game.achievements.map(a => a.id);
    const apinames = game.achievements.map(a => a.apiname);

    assert.deepStrictEqual([...ids].sort((a, b) => a - b), Array.from({ length: 307 }, (_, i) => i + 1));
    assert.strictEqual(new Set(ids).size, 307);
    assert.strictEqual(new Set(apinames).size, 307);

});

test("every Killing Floor 2 achievement has a valid difficulty (1-5), a positive estimatedTime, and non-empty name/description", () => {

    for (const achievement of game.achievements) {

        assert.ok(
            Number.isInteger(achievement.difficulty) && achievement.difficulty >= 1 && achievement.difficulty <= 5,
            `${achievement.name} has an out-of-range difficulty: ${achievement.difficulty}`
        );

        assert.ok(
            Number.isInteger(achievement.estimatedTime) && achievement.estimatedTime > 0,
            `${achievement.name} has an invalid estimatedTime: ${achievement.estimatedTime}`
        );

        assert.ok(achievement.name?.length > 0, "achievement is missing a name");
        assert.ok(achievement.description?.length > 0, `${achievement.name} is missing a description`);
        assert.ok(achievement.apiname?.length > 0, `${achievement.name} is missing an apiname`);

    }

});

test("every one of the 307 Killing Floor 2 achievement name+description pairs matches the catalog data", () => {

    const officialAchievements = [
        ["A British Hell on Earth", "Complete Hellmark Station on Survival Hell On Earth Difficulty"],
        ["A Deadly Carol", "Complete Santa's Workshop on Survival Suicidal Difficulty"],
        ["A Light In The Darkness", "Complete Catacombs on Survival Normal difficulty"],
        ["A Little Turbulence", "Complete Airship on Survival Normal difficulty"],
        ["A Spark to Light the Way", "Complete Power Core on Survival Normal difficulty"],
        ["A Special Deal", "Destroy 10 Dosh Necklaces in Shopping Spree"],
        ["A Whupping", "Beat Krampus Lair on Suicidal"],
        ["A World Under Glass", "Collect all the items (Snowglobes) on Krampus Lair"],
        ["Absolution", "Complete Elysium on Survival Hell On Earth Difficulty"],
        ["ALAN!!!!!!", "Collect all the volley balls on Zed Landing"],
        ["All Hope abandon, Ye Who Enter Here", "Complete Infernal Realms on Survival Hell On Earth difficulty"],
        ["All This Science I Don't Understand", "Destroy 10 Steam Batteries on Steam Fortress"],
        ["An Explosive Ending", "Complete Nuked on Objective Hard or higher Difficulty"],
        ["Arc Action", "Beat Burning Paris on Hell on Earth"],
        ["Bastille Brawl", "Beat Burning Paris on Suicidal"],
        ["Benefactor", "Give 1000 Dosh to Another Player During a Multiplayer Match"],
        ["Big Brother is Watching You", "Complete Dystopia 2029 on Survival Hell On Earth Difficulty"],
        ["Biotics Bling", "Collect all the items on Biotics Lab"],
        ["Black Forest Babies", "Collect all the items on Black Forest"],
        ["Blown Out", "Complete Zed Landing on Survival Hell On Earth difficulty"],
        ["Bolting through the Core", "Complete Power Core on Survival Hard difficulty"],
        ["Bow Movement", "Complete Evacuation Point on Survival Suicidal difficulty"],
        ["Bundle of Switches", "Beat Krampus Lair on Hard"],
        ["Burning Out the Fuse", "Complete Steam Fortress on Objective Normal Difficulty"],
        ["But what if we added Gas?", "Complete The Descent on Survival Hard difficulty"],
        ["Bye bye Volter", "Complete Castle Volter on Survival, Hard or higher Difficulty"],
        ["Cackling Crazy", "Complete Ashwood Asylum on Survival Hard or higher Difficulty"],
        ["Can't Be Contained", "Collect All the Items on Containment Station"],
        ["Can't Make an Omelette Without Killing a Few People", "Complete Hostile Grounds on Survival Hard difficulty"],
        ["Carried off to the Underworld", "Complete Krampus Lair on Survival Hell On Earth difficulty"],
        ["Castle Crashers", "Complete Monster Ball on Survival Normal difficulty"],
        ["Catacombs Cash", "Collect all the items on Catacombs"],
        ["Cleanup On Aisle 3", "Complete Shopping Spree on Survival Normal Difficulty"],
        ["Close-out", "Complete Zed Landing on Survival Suicidal difficulty"],
        ["Code Dead", "Complete DieSector wave 25 on Endless Suicidal difficulty"],
        ["Controlled Environment", "Beat Biotics Lab on Hell on Earth"],
        ["Cookies and Milk", "Complete Santa's Workshop on Survival Normal Difficulty"],
        ["Crash Course", "Complete Crash on Survival Hell On Earth Difficulty"],
        ["Cult of Personality", "Collect 10 Hans Volter Dolls in Castle Volter"],
        ["Dam You're Good!", "Complete Spillway on Survival Hell On Earth Difficulty"],
        ["Dance on the Gore Floor", "Complete Monster Ball on Survival Suicidal difficulty"],
        ["Dangerous Waves", "Complete Rig on Survival Hard or higher Difficulty"],
        ["Darkness Dolls", "Collect all the items on Farmhouse"],
        ["Data Deliverier ", "Complete Zed Landing on Objective Hard Difficulty"],
        ["Davy Crockett", "Collect all the items on Nuked"],
        ["Dead Silence", "Kill a Siren Before She Screams"],
        ["Deadly Fishbowl", "Complete Subduction on Survival Hell On Earth Difficulty"],
        ["Death's Door", "Unlock the Alchemist Room in Monster Ball"],
        ["Deliverance", "Complete Elysium on Survival Hard or higher Difficulty"],
        ["Die Volter", "Kill Dr. Hans Volter For the First Time"],
        ["Don't Panic", "Complete Containment Station on Survival Hard difficulty"],
        ["Droning On", "Complete Zed Landing on Objective Normal Difficulty"],
        ["End of the Line", "Defeat the Matriarch on any difficulty. "],
        ["Experimental Progress...", "Complete Biolapse on Hard or higher Difficulty"],
        ["Experimental Success!", "Complete Biolapse on Hell On Earth Difficulty"],
        ["Fatal Exception", "Complete DieSector wave 25 on Endless Hell On Earth difficulty"],
        ["Fear Is For The Zeds, My Little Lord", "Beat Outpost on Hell on Earth"],
        ["Firing Range Master", "Complete Desolation on Survival Hell On Earth Difficulty"],
        ["Flying Unfriendly Skies", "Complete Airship on Survival Hard difficulty"],
        ["Forgotten Knowledge", "Find all collectibles on Netherhold"],
        ["From Here to Eternity", "Complete wave 15 on Endless Hard or higher difficulty on Elysium"],
        ["Frozen Assets", "Complete Outpost on Objective Suicidal Difficulty"],
        ["Fun Near the Sun", "Complete Lockdown on Survival Hard difficulty"],
        ["Fun Size? What is Fun Size?", "Beat Nightmare on Suicidal"],
        ["Give Up and Go Mad Now", "Complete Containment Station on Survival Suicidal difficulty"],
        ["Giving the Cold Shoulder", "Complete Outpost on Objective Hard Difficulty"],
        ["Gnarly", "Complete Zed Landing on Survival Hard difficulty"],
        ["Hack and Slash", "Kill Your First Scrake"],
        ["Hans Off the Merchandise", "Collect all the items on The Descent"],
        ["Hard Berserker", "Beat Any One Map as Berserker on Hard Difficulty"],
        ["Hard Commando", "Complete any map as a Commando on Survival Hard difficulty"],
        ["Hard Demolition", "Complete any map as a Demolitionist on Survival Hard difficulty"],
        ["Hard Firebug", "Complete any map as a Firebug on Survival Hard difficulty"],
        ["Hard Gunslinger", "Complete any map as a Gunslinger on Survival Hard difficulty"],
        ["Hard Medic", "Beat Any One Map as Medic on Hard Difficulty"],
        ["Hard Sharpshooter", "Beat Any One Map as Sharpshooter on Hard Difficulty"],
        ["Hard Support", "Complete any map as a Support on Survival Hard difficulty"],
        ["Hard Survivalist ", "Complete any map as a Survivalist on Survival Hard difficulty"],
        ["Hard SWAT", "Beat Any One Map as SWAT on Hard Difficulty"],
        ["Hell is Just a Frame of Mind", "Complete Infernal Realms on Survival Suicidal difficulty"],
        ["Hell is Other People", "Beat Infernal Realms on Normal"],
        ["Hellish Berserker", "Beat Any One Map as Berserker on Hell on Earth Difficulty"],
        ["Hellish Commando", "Complete any map as a Commando on Survival Hell On Earth difficulty"],
        ["Hellish Demolition", "Complete any map as a Demolitionist on Survival Hell On Earth difficulty"],
        ["Hellish Firebug", "Complete any map as a Firebug on Survival Hell On Earth difficulty"],
        ["Hellish Gunslinger", "Complete any map as a Gunslinger on Survival Hell On Earth difficulty"],
        ["Hellish Medic", "Beat Any One Map as Medic on Hell on Earth Difficulty"],
        ["Hellish Sharpshooter", "Complete any map as a Sharpshooter on Survival Hell On Earth difficulty"],
        ["Hellish Support", "Complete any map as a Support on Survival Hell On Earth difficulty"],
        ["Hellish Survivalist", "Complete any map as a Survivalist on Survival Hell On Earth difficulty"],
        ["Hellish SWAT", "Beat Any One Map as SWAT on Hell On Earth Difficulty"],
        ["Hidden Globes", "Destroy 10 Snow Globes in Carillon Hamlet"],
        ["High as a Kite", "Complete Steam Fortress on Objective Suicidal Difficulty"],
        ["High Voltage", "Complete Power Core on Survival Suicidal difficulty"],
        ["Hold Out", "Weld a Door to 100%"],
        ["Horzine Rail Express", "Complete Carillon Hamlet on Survival Hell On Earth Difficulty"],
        ["Houston, We Don't Have a Problem", "Complete Lockdown on Survival Hell On Earth difficulty"],
        ["How Bout Some Gas?", "Complete The Descent on Survival Normal difficulty"],
        ["How I Learned to Love the Bomb", "Complete Nuked on Survival Hell On Earth difficulty"],
        ["I Got a Rock", "Beat Nightmare on Normal"],
        ["I Got Your Back", "Heal a Teammate With the Syringe"],
        ["I Have the Power!", "Complete Power Core on Survival Hell On Earth difficulty"],
        ["I was trained by the best. British Intel.", "Beat Prison on Hell on Earth"],
        ["I'll Dopple Bock", "Complete Black Forest on Survival Suicidal difficulty"],
        ["If You Are Going Through Hell, Keep Going", "Complete Infernal Realms on Survival Hard difficulty"],
        ["Ignorance is Strength", "Complete Dystopia 2029 on Survival Hard or higher Difficulty"],
        ["In too Deep", "Complete Subduction on Survival Hard or Higher Difficulty"],
        ["Infernal Relics", "Collect all the Items in Infernal Realms"],
        ["Inside the Oblivion Maze", "Complete Netherhold on Survival Hard or higher Difficulty"],
        ["Into the Mouth of Hell", "Complete Hellmark Station on Survival Hard or higher Difficulty"],
        ["Island Isolation", "Complete Zed Landing on Objective Suicidal Difficulty"],
        ["It's a Bloody World After All", "Complete Tragic Kingdom on Survival Normal difficulty"],
        ["It's aD.A.R.able", "Collect all the items (D.A.R. Bobbleheads) on DieSector"],
        ["It's All Downstream From Here", "Complete Spillway on Survival Normal Difficulty"],
        ["It's Cold as Hell", "Complete Steam Fortress on Objective Hell On Earth Difficulty"],
        ["It's Only a Flesh Wound", "Kill Your First Fleshpound"],
        ["It's Snow Good. ", "Complete Outpost on Objective Normal Difficulty"],
        ["Just Like the Simulations", "Complete Desolation on Survival Hard or higher Difficulty"],
        ["Just Visiting", "Beat Volter Manor on Normal"],
        ["Kein Bier Vor Vier", "Complete Black Forest on Survival Hell On Earth difficulty"],
        ["Killer Korn", "Complete Black Forest on Survival Normal difficulty"],
        ["Killing in the Evening", "Complete Carillon Hamlet on Survival Hard or higher Difficulty"],
        ["Laboratory Matricide", "Complete Biotics Lab on Objective Hell On Earth Difficulty"],
        ["Lager Me Up", "Complete Black Forest on Survival Hard difficulty"],
        ["Let's Try Some Gas", "Complete The Descent on Survival Suicidal difficulty"],
        ["Letting the Demons Out", "Collect all the items (skulls) on Nightmare"],
        ["Like Tears in Rain", "Find all the Collectibles on Dystopia 2029"],
        ["Like what, kill him again?", "Beat Prison on Suicidal"],
        ["Limited Contact", "Beat Biotics Lab on Hard"],
        ["Lord of the Manor", "Complete Volter Manor on Survival Hell On Earth difficulty"],
        ["Lost Goods", "Collect 10 Snow Globes in Crash"],
        ["Manor Money", "Collect all the items on Volter Manor"],
        ["Marine Research", "Collect 10 Holographic Projectors in Rig"],
        ["Medieval Threats", "Complete Barmwich Town on Survival Hard or higher Difficulty"],
        ["Mercenaries get paid", "Beat Prison on Hard"],
        ["Mile High Dead Club", "Complete Airship on Survival Hell On Earth difficulty"],
        ["Mind the Gap", "Complete Hostile Grounds on Survival Normal difficulty"],
        ["Mind Your Manor", "Beat Volter Manor on Hard"],
        ["Money Down the Drain", "Destroy 10 Dosh Necklaces in Spillway"],
        ["Money Mania", "Destroy 10 red skulls on Ashwood Asylum"],
        ["Mr. Perky 10", "Reach Level 10 on Any Perk"],
        ["Mr. Perky 15", "Reach Level 15 on Any Perk"],
        ["Mr. Perky 20", "Reach Level 20 on Any Perk"],
        ["Mr. Perky 25", "Reach Level 25 on Any Perk"],
        ["Mr. Perky 5", "Reach Level 5 on Any Perk"],
        ["Never Got the Hang of Thursdays", "Complete Containment Station on Survival Normal difficulty"],
        ["Nightmare’s over", "Complete Castle Volter on Survival Hell On Earth Difficulty"],
        ["Nobel Prize for Destruction", "Destroy 10 gold trophies on Biolapse"],
        ["Non Compos Mentis", "Complete Ashwood Asylum on Survival Hell On Earth Difficulty"],
        ["Normal Berserker", "Beat Any One Map as Berserker on Normal Difficulty"],
        ["Normal Commando", "Complete any map as a Commando on Survival Normal difficulty"],
        ["Normal Demolition", "Complete any map as a Demolitionist on Survival Normal difficulty"],
        ["Normal Firebug", "Complete any map as a Firebug on Survival Normal difficulty"],
        ["Normal Gunslinger", "Complete any map as a Gunslinger on Survival Normal difficulty"],
        ["Normal Medic", "Beat Any One Map as Medic on Normal Difficulty"],
        ["Normal Sharpshooter", "Beat Any One Map as Sharpshooter on Normal Difficulty"],
        ["Normal Support", "Complete any map as a Support on Survival Normal difficulty"],
        ["Normal Survivalist", "Beat Any One Map as Survivalist on Normal Difficulty"],
        ["Normal SWAT", "Complete any map as a SWAT on Survival Normal difficulty"],
        ["Not Night Lamps", "Collect 10 Glowing Skulls in Barmwich Town"],
        ["Old Skull", "Destroy 10 Demon Skulls on Hellmark Station"],
        ["Oleaginous Old Ones", "Find all the Collectibles on Sanitarium "],
        ["One Giant Leap for Mankind", "Complete Moonbase on Survival Hell On Earth Difficulty"],
        ["One Small Step for Man", "Complete Moonbase on Survival Hard or higher Difficulty"],
        ["Open For Testing", "Beat Biotics Lab on Normal"],
        ["Outpost Offerings", "Collect all the items on Outpost"],
        ["Overflow Controlled", "Complete Spillway on Survival Suicidal Difficulty"],
        ["Paris Plunder", "Collect all the items on Burning Paris"],
        ["Party Hard!", "Complete Monster Ball on Survival Hard difficulty"],
        ["Peace is Our Profession", "Complete Nuked on Survival Suicidal difficulty"],
        ["Perilous Prison", "Collect all the items on Prison"],
        ["Perked Up", "Reach Level 25 in all Perks"],
        ["Plow the Field", "Beat Farmhouse on Normal Difficulty"],
        ["Point Paper", "Collect all the items on Evacuation Point"],
        ["Powered by Steam", "Collect all the items (Steam Cells) on Airship"],
        ["Projections from the Deep", "Collect 10 Holographic Projectors in Subduction"],
        ["Quick on the Trigger", "Kill the Patriarch Before He Has a Chance to Heal"],
        ["Reach Level 10 Berserker", "Reach Level 10 Berserker"],
        ["Reach Level 10 Commando", "Reach Level 10 Commando"],
        ["Reach Level 10 Demolitionist", "Reach Level 10 Demolitionist"],
        ["Reach Level 10 Firebug", "Reach Level 10 Firebug"],
        ["Reach Level 10 Gunslinger", "Reach Level 10 Gunslinger"],
        ["Reach Level 10 Medic", "Reach Level 10 Medic"],
        ["Reach Level 10 Sharpshooter", "Reach Level 10 Sharpshooter"],
        ["Reach Level 10 Support", "Reach Level 10 Support"],
        ["Reach Level 10 Survivalist", "Reach Level 10 Survivalist"],
        ["Reach Level 10 SWAT", "Reach Level 10 SWAT"],
        ["Reach Level 15 Berserker", "Reach Level 15 Berserker"],
        ["Reach Level 15 Commando", "Reach Level 15 Commando"],
        ["Reach Level 15 Demolitionist", "Reach Level 15 Demolitionist"],
        ["Reach Level 15 Firebug", "Reach Level 15 Firebug"],
        ["Reach Level 15 Gunslinger", "Reach Level 15 Gunslinger"],
        ["Reach Level 15 Medic", "Reach Level 15 Medic"],
        ["Reach Level 15 Sharpshooter", "Reach Level 15 Sharpshooter"],
        ["Reach Level 15 Support", "Reach Level 15 Support"],
        ["Reach Level 15 Survivalist", "Reach Level 15 Survivalist"],
        ["Reach Level 15 SWAT", "Reach Level 15 SWAT"],
        ["Reach Level 20 Berserker", "Reach Level 20 Berserker"],
        ["Reach Level 20 Commando", "Reach Level 20 Commando"],
        ["Reach Level 20 Demolitionist", "Reach Level 20 Demolitionist"],
        ["Reach Level 20 Firebug", "Reach Level 20 Firebug"],
        ["Reach Level 20 Gunslinger", "Reach Level 20 Gunslinger"],
        ["Reach Level 20 Medic", "Reach Level 20 Medic"],
        ["Reach Level 20 Sharpshooter", "Reach Level 20 Sharpshooter"],
        ["Reach Level 20 Support", "Reach Level 20 Support"],
        ["Reach Level 20 Survivalist", "Reach Level 20 Survivalist"],
        ["Reach Level 20 SWAT", "Reach Level 20 SWAT"],
        ["Reach Level 25 Berserker", "Reach Level 25 Berserker"],
        ["Reach Level 25 Commando", "Reach Level 25 Commando"],
        ["Reach Level 25 Demolitionist", "Reach Level 25 Demolitionist"],
        ["Reach Level 25 Firebug", "Reach Level 25 Firebug"],
        ["Reach Level 25 Gunslinger", "Reach Level 25 Gunslinger"],
        ["Reach Level 25 Medic", "Reach Level 25 Medic"],
        ["Reach Level 25 Sharpshooter", "Reach Level 25 Sharpshooter"],
        ["Reach Level 25 Support", "Reach Level 25 Support"],
        ["Reach Level 25 Survivalist", "Reach Level 25 Survivalist"],
        ["Reach Level 25 SWAT", "Reach Level 25 SWAT"],
        ["Reach Level 5 Berserker", "Reach Level 5 Berserker"],
        ["Reach Level 5 Commando", "Reach Level 5 Commando"],
        ["Reach Level 5 Demolitionist", "Reach Level 5 Demolitionist"],
        ["Reach Level 5 Firebug", "Reach Level 5 Firebug"],
        ["Reach Level 5 Gunslinger", "Reach Level 5 Gunslinger"],
        ["Reach Level 5 Medic", "Reach Level 5 Medic"],
        ["Reach Level 5 Sharpshooter", "Reach Level 5 Sharpshooter"],
        ["Reach Level 5 Support", "Reach Level 5 Support"],
        ["Reach Level 5 Survivalist", "Reach Level 5 Survivalist"],
        ["Reach Level 5 SWAT", "Reach Level 5 SWAT"],
        ["Reap what you Sow", "Beat Farmhouse on Hell on Earth Difficulty"],
        ["Red Friday", "Complete Shopping Spree on Survival Hell On Earth Difficulty"],
        ["Rest In Pieces", "Complete Monster Ball on Survival Hell on Earth difficulty"],
        ["Restricted Access", "Beat Biotics Lab on Suicidal"],
        ["Savings to Die For", "Complete Shopping Spree on Survival Suicidal Difficulty"],
        ["School's Out Forever", "Complete the Training Floor"],
        ["Science Finds A Way", "Complete Biotics Lab on Objective Hard or higher Difficulty"],
        ["Sea of Zeds", "Complete Rig on Survival Hell On Earth Difficulty"],
        ["Seas The Day", "Complete Evacuation Point on Survival Hell On Earth difficulty"],
        ["Seine Skirmish", "Complete Burning Paris on Survival Hard difficulty"],
        ["Settling In", "Beat Volter Manor on Suicidal"],
        ["Shocking Discovery!", "Collect all the items (Batteries) on Lockdown"],
        ["Shoot One Get Two Free", "Complete Shopping Spree on Survival Hard Difficulty"],
        ["Slaying with Santa", "Complete Santa's Workshop on Survival Hard Difficulty"],
        ["So Long and Thanks for All the Zeds", "Complete Containment Station on Survival Hell On Earth difficulty"],
        ["Soar, Gore, and More", "Complete Airship on Survival Suicidal difficulty"],
        ["Someone Call a Chopper?", "Complete Zed Landing on Objective Hell On Earth Difficulty"],
        ["Sow the Seed", "Beat Farmhouse on Hard Difficulty"],
        ["Space Race", "Complete Lockdown on Survival Suicidal difficulty"],
        ["Spooky Scary Skeletons", "Destroy 10 Glowing Skulls in Monster Ball"],
        ["Station Stabilization", "Complete Lockdown on Survival Normal difficulty"],
        ["Stocking Full of Coal", "Beat Krampus Lair on Normal"],
        ["Suicidal Berserker", "Beat Any One Map as Berserker on Suicidal Difficulty"],
        ["Suicidal Commando", "Complete any map as a Commando on Survival Suicidal difficulty"],
        ["Suicidal Demolition", "Complete any map as a Demolitionist on Survival Suicidal difficulty"],
        ["Suicidal Firebug", "Complete any map as a Firebug on Survival Suicidal difficulty"],
        ["Suicidal Gunslinger", "Complete any map as a Gunslinger on Survival Suicidal difficulty"],
        ["Suicidal Medic", "Beat Any One Map as Medic on Suicidal Difficulty"],
        ["Suicidal Sharpshooter", "Complete any map as a Sharpshooter on Survival Suicidal difficulty"],
        ["Suicidal Support", "Complete any map as a Support on Survival Suicidal difficulty"],
        ["Suicidal Survivalist", "Complete any map as a Survivalist on Survival Suicidal difficulty"],
        ["Suicidal SWAT", "Beat Any One Map as SWAT on Suicidal Difficulty"],
        ["Surfs Up", "Complete Zed Landing on Survival Normal difficulty"],
        ["Surge Breaker", "Collect all the items (Batteries) on Power Core"],
        ["Test Trials", "Complete DieSector wave 25 on Endless Hard difficulty"],
        ["That's enough gas....", "Complete The Descent on Survival Hell On Earth difficulty"],
        ["The Abyss Stares Back at You", "Complete Netherhold on Survival Hell On Earth Difficulty"],
        ["The Dark Side of the Moon", "Find all collectibles on Moonbase"],
        ["The Goriest Place on Earth", "Complete Tragic Kingdom on Survival Hard difficulty"],
        ["The House the Zed Built", "Complete Tragic Kingdom on Survival Suicidal difficulty"],
        ["The Mineshaft Gap", "Complete Nuked on Survival Hard difficulty"],
        ["The Oldest and Strongest Emotion", "Complete Sanitarium on Hard or higher Difficulty"],
        ["The Shield Doors Must Be Closed", "Beat Outpost on Suicidal"],
        ["The Snow Must Go On", "Complete Outpost on Objective Hell On Earth Difficulty"],
        ["The Suite Life", "Complete Evacuation Point on Survival Normal difficulty"],
        ["The War Room", "Complete Nuked on Survival Normal difficulty"],
        ["The Wonderful World of Merchandising", "Collect all the items on The Tragic Kingdom"],
        ["The World On Fire", "Complete Nuked on Objective Hell On Earth Difficulty"],
        ["There Is No I in Team, But There Is an I in Pie", "Complete Hostile Grounds on Survival Suicidal difficulty"],
        ["They Shall Not Pass", "Complete Catacombs on Survival Hell On Earth difficulty"],
        ["This Is A Tomb, Theirs", "Complete Catacombs on Survival Suicidal difficulty"],
        ["This Is No Mine", "Complete Catacombs on Survival Hard difficulty"],
        ["This Is What Happens When You Meet A Zed In The Alps", "Beat Outpost on Hard"],
        ["Touchdown Brings Me Down", "Complete Steam Fortress on Objective Hard Difficulty"],
        ["Tower Tussle", "Complete Burning Paris on Survival Normal difficulty"],
        ["Training Simulation", "Complete DieSector wave 25 on Endless Normal difficulty"],
        ["Trainwreck", "Complete Crash on Survival Hard or higher Difficulty"],
        ["Unsinkable II", "Complete Evacuation Point on Survival Hard difficulty"],
        ["Victory! Full Size Candy Bar!", "Beat Nightmare on Hell on Earth"],
        ["VS Human Win", "Win a VS Survival Round Playing as the Humans"],
        ["VS Zed Win", "Win a VS Survival Round Playing as the Zeds"],
        ["Walked into the wrong room", "Beat Prison on Normal"],
        ["Water the Crops", "Beat Farmhouse on Suicidal Difficulty"],
        ["Where Nightmares Come True", "Complete Tragic Kingdom on Survival Hell On Earth difficulty"],
        ["Who Died and Made You #*%$&@ King of the Zombies?", "Complete Hostile Grounds on Survival Hell On Earth difficulty"],
        ["Win 1", "Win 1 Multiplayer Match"],
        ["Win 10", "Win 10 Multiplayer Matches"],
        ["Win 25", "Win 25 Multiplayer Matches"],
        ["Win Hard", "Win Any Match on Hard Difficulty"],
        ["Win Hell on Earth", "Win Any Match on Hell on Earth Difficulty"],
        ["Win Suicidal", "Win Any Match on Suicidal Difficulty"],
        ["With Strange Aeons Even Death May Die", "Complete Sanitarium on Hell On Earth Difficulty"],
        ["You are my Only Hope", "Collect 10 Holographic projectors on Desolation"],
        ["You Can't Fight In Here, This Is The Control Room", "Beat Outpost on Normal"],
        ["You're On The Badass List", "Complete Santa's Workshop on Survival Hell On Earth Difficulty"],
        ["You've Got Red on You", "Collect All the Items on Hostile Grounds"],
        ["Yuck, Candy Corn", "Beat Nightmare on Hard"],
        ["Yule Shoot Your Eye Out", "Destroy 10 Snow Globes in Santa's Workshop"],
        ["Zeds Are In Town", "Complete Barmwich Town on Survival Hell On Earth Difficulty"],
        ["Zeds Be Dam", "Complete Spillway on Survival Hard Difficulty"],
    ];

    assert.strictEqual(officialAchievements.length, 307, "sanity check on this test's own reference list");

    const dataPairs = game.achievements
        .map(a => [a.name, a.description])
        .sort((a, b) => a[0].localeCompare(b[0]));

    assert.deepStrictEqual(dataPairs, [...officialAchievements].sort((a, b) => a[0].localeCompare(b[0])));

});
