import { test } from "node:test";
import assert from "node:assert";

import { getPlannerData } from "../utils/plannerCatalog.js";

// backend/catalog/games/killing-floor.json - 285 real achievements sourced
// from a live ISteamUserStats/GetSchemaForGame/v2 response for appid
// 1250 (fetched through this app's own services/steamApi.js). None are
// hidden; every description is Steam's own real text.
// difficulty/estimatedTime/missable remain curatorial judgments.
const game = getPlannerData("killing-floor");

test("getPlannerData('killing-floor') returns real planner data with 285 curated achievements", () => {

    assert.ok(game, "expected real planner data for killing-floor");
    assert.ok(Array.isArray(game.achievements));
    assert.strictEqual(game.achievements.length, 285);

});

test("every Killing Floor achievement has a unique id from 1 to 285 and a unique apiname", () => {

    const ids = game.achievements.map(a => a.id);
    const apinames = game.achievements.map(a => a.apiname);

    assert.deepStrictEqual([...ids].sort((a, b) => a - b), Array.from({ length: 285 }, (_, i) => i + 1));
    assert.strictEqual(new Set(ids).size, 285);
    assert.strictEqual(new Set(apinames).size, 285);

});

test("every Killing Floor achievement has a valid difficulty (1-5), a positive estimatedTime, and non-empty name/description", () => {

    for (const achievement of game.achievements) {

        assert.ok(
            Number.isInteger(achievement.difficulty) && achievement.difficulty >= 1 && achievement.difficulty <= 5,
            `${achievement.name} has an out-of-range difficulty: ${achievement.difficulty}`
        );

        assert.ok(
            Number.isInteger(achievement.estimatedTime) && achievement.estimatedTime > 0,
            `${achievement.name} has an invalid estimatedTime: ${achievement.estimatedTime}`
        );

        assert.ok(achievement.name?.length > 0, "achievement is missing a name");
        assert.ok(achievement.description?.length > 0, `${achievement.name} is missing a description`);
        assert.ok(achievement.apiname?.length > 0, `${achievement.name} is missing an apiname`);

    }

});

test("every one of the 285 Killing Floor achievement name+description pairs matches the catalog data", () => {

    const officialAchievements = [
        ["3 Ring Circus", "Win a Long Game on Abusement Park on Suicidal Difficulty."],
        ["777", "Win Fuel on the first try"],
        ["A Bit Barmy", "Win a Long Game on Bedlam, on Normal Difficulty."],
        ["A Bloody Christmas Carol", "Kill 15 XMas Clots, 5 xmas Stalkers, 5 XMas Crawlers, 1 XMas Siren and 1 XMas Bloat."],
        ["Advanced Omega Wave Resonance Explorer", "Beat Steamland on Hell on Earth Difficulty"],
        ["Agnosia", "Beat Forgotten on Hard Difficulty"],
        ["All shook up", "Destroy all (15) Snow Globes"],
        ["Alligator Farmer", "Win a Long Game on Farm on Suicidal Difficulty."],
        ["Alpha Wave Osteooxidation Activator", "Beat Steamland in Objective Mode on Suicidal Difficulty"],
        ["Amnesia", "Beat Forgotten on Suicidal Difficulty"],
        ["Amusing Death", "Beat Moonbase on Suicidal Difficulty"],
        ["And Back to School", "Complete a Long Game on all 3 Summer 2009 maps on Suicidal Difficulty."],
        ["Anti Freeze", "Beat Ice Cave on Hell on Earth Difficulty"],
        ["Arcade Gamer", "[2013 Summer] Complete the Pop the Clot, the Strong Man and the Grenade Toss games"],
        ["Assault Flayer Ordinance", "Push a scrake back with the direct fire from a Hunting Shotgun or alt fire from the Multi-Chamber ZED Thrower"],
        ["Assistant Homicide", "Kill 2 Circus Stalkers with a Melee weapon to the back in one wave."],
        ["Astro Buffer Afficiando", "Beat Steamland on Normal Difficulty"],
        ["Attempting Re-entry", "Beat Moonbase on Hard Difficulty"],
        ["Back to Work", "[2010 Xmas] Kill 20 Christmas Clots in one wave."],
        ["Bad Santa", "Unlock 10 of the 13 Christmas Achievements along with any Christmas Map achievement."],
        ["Bear King of the Dark Forest", "Win a Long Game on Wyre, on Suicidal Difficulty."],
        ["Bitter Irony", "Kill 2 Scrakes with a Chainsaw in a Single Wave."],
        ["Blinding Big Brother", "Destroy all 30 Cameras"],
        ["Bloody Yanks", "Kill 1 specimen ONLY while expending a full M4 Assault Rifle magazine"],
        ["Blooper Reel", "Turn 500 Zeds into Giblets using the M79."],
        ["Boss from Hell", "Win a Long Game on Offices on Hell on Earth Difficulty."],
        ["Brain Fart", "Beat Forgotten on Normal Difficulty"],
        ["British Superiority", "Kill a zed each with both the Bullpup and FN-Fal"],
        ["Burned out", "Beat Clandestine on Suicidal Difficulty"],
        ["Burning Irony", "Kill 15 Husks with the Husk Cannon"],
        ["Burning up the Midway", "Kill 10 Circus Clots with a Fire-based weapon."],
        ["Burst Pipe", "Win a Long Game on Waterworks on Hard Difficulty."],
        ["Business Class", "Beat Transit on Suicidal Difficulty"],
        ["But It's All Red!", "Collect all 16 Z.E.D. Gun pieces"],
        ["Can't Catch Me!", "[2010 Xmas] Kill 2 Christmas Gorefasts with a Melee weapon from behind in one wave."],
        ["Careful Spender", "Kill 4 Specimens with a Single Shot from a Hunting Shotgun."],
        ["Carving The Jack O' Lantern", "Decapitate a burning Halloween specimen in Bedlam"],
        ["Cattle Class", "Beat Transit on Normal Difficulty"],
        ["Cattle Farmer", "Win a Long Game on Farm on Hard Difficulty."],
        ["Cave of Wonder", "Beat ThrillsChills on Normal Difficulty"],
        ["Cavern of Pain", "Beat ThrillsChills on Hard Difficulty"],
        ["Cerberus", "Beat Hell on Suicidal Difficulty"],
        ["Chicken Farmer", "Win a Long Game on Farm on Normal Difficulty."],
        ["Claw Machine Master", "Attach the crane hook within 125 seconds"],
        ["Clearing Clown Alley", "Kill 5 Circus Bloats in one game."],
        ["Combat Medic", "Kill a zed that has injured a player (M7A3 rifle)"],
        ["Comet", "Win a Long Game on Icebreaker on Hell on Earth Difficulty."],
        ["Commit-ed for life", "Win a Long Game on Bedlam on Hell on Earth Difficulty."],
        ["Complete Barking", "Win a Long Game on Bedlam, on Suicidal Difficulty."],
        ["Cracked the Nutcracker!", "[2010 Xmas] Land the killing blow on a Christmas Fleshpound with a Knife."],
        ["Crane Operator", "Beat Fright Yard in Objective Mode on Suicidal Difficulty"],
        ["Creepy Crawlies", "Kill 15 Hillbilly Crawlers in 1 game with the Tommy Gun or MKb42"],
        ["Crushed Ice", "Win a Long Game on Icebreaker on Hard Difficulty."],
        ["Day-trip", "Beat Transit in Objective Mode on Normal Difficulty"],
        ["Daytrip", "Win a Long Game on Mountain Pass on Normal Difficulty."],
        ["Dear Departed", "Win a Long Game on Departed on Hell on Earth Difficulty."],
        ["Death", "Beat Hell on Normal Difficulty"],
        ["Death To The Mad Scientist", "Defeat the Patriarch on Suicidal."],
        ["Deck the Halls with Buckets o' Blood", "[2010 Xmas] Kill 3 Christmas Zeds in 1 ZED time chain with a Melee weapon."],
        ["Dementia", "Beat Forgotten on Hell on Earth Difficulty"],
        ["Demon Farmer", "Win a Long Game on Farm on Hell on Earth Difficulty."],
        ["Demonic King of the Manor", "Win a Long Game on Manor on Hell on Earth Difficulty."],
        ["Demonic Road", "Beat Hellride on Suicidal Difficulty"],
        ["Departure Gallery", "Win a Long Game on Departed on Normal Difficulty."],
        ["Departure Gate", "Win a Long Game on Departed on Suicidal Difficulty."],
        ["Departure Lounge", "Win a Long Game on Departed on Hard Difficulty."],
        ["Devil Cake", "Complete all new map achievements on Hell On Earth Difficulty."],
        ["Devil's Co-pilot", "Beat Hellride on Hell on Earth Difficulty"],
        ["Diablo Steel Man", "Win a Long Game on Foundry on Hell on Earth Difficulty."],
        ["Dignity for the Dead", "Kill 10 Specimens Feeding on Dead Teammates Corpses."],
        ["Doctor WHO??", "Transit - Get all Objective achievements AND beat KFO Transit on Hard or above to unlock Dr Rachel Clamely."],
        ["Dog and Pony Show", "Win a Long Game on Abusement Park on Hard Difficulty."],
        ["Dot of Doom", "Get 25 headshots in a row with the EBR while using the Laser Sight."],
        ["Duke of the Manor", "Win a Long Game on Manor on Hard Difficulty."],
        ["Economy Comfort", "Beat Transit on Hard Difficulty"],
        ["Eggnog Anyone?", "[2010 Xmas] Get covered in Christmas Bloat Bile and live for 10 seconds on Hard, Suicidal, or Hell on Earth."],
        ["Elephant Gun", "Land the killing blow on a Circus Fleshpound with a Pistol."],
        ["Emperor of the Manor", "Win a Long Game on Manor on Suicidal Difficulty."],
        ["Ex-scientist", "Collect all the bile without a contamination"],
        ["Experimenticenticide", "Kill 100 Specimens."],
        ["Experimentilottacide", "Kill 10,000 Specimens."],
        ["Experimentimillicide", "Kill 1,000 Specimens."],
        ["Explosion of Love", "Heal yourself plus 5 other players with one grenade"],
        ["Explosive Personality", "As Demolitions, kill 1000 Specimens with the Pipebomb."],
        ["Extended Motion Protector", "[2013 Summer] Protect the Ringmaster during the escort mission so that he does not get hit more than 15 times"],
        ["Fascist Dietitian", "Kill 200 Bloats."],
        ["Feeling Lucky?", "Kill a specimen with every shot from your Revolver for one magazine"],
        ["Fending off Mrs. Claws", "[2010 Xmas] Kill 3 Christmas Stalkers with a Lever Action Rifle without reloading."],
        ["Fiery Personality", "Set 3 Hillbilly Gorefasts on fire with the Flare Pistol or Trench Gun"],
        ["Finish Him", "Hit a Scrake with the M203 Rifle grenade to kill him"],
        ["Fire and Forget", "Kill a Halloween Fleshpound and Scrake in the same explosion with the Seal Squeal Harpoon Bomber or the LAW"],
        ["First Class", "Beat Transit on Hell on Earth Difficulty"],
        ["First Cousins", "Beat Hillbilly Horror on Hell on Earth Difficulty"],
        ["First Cousins (Once Removed)", "Beat Hillbilly Horror on Suicidal Difficulty"],
        ["Flaming Hell, That was Close", "As Firebug, kill the Husk with the Flamethrower before he hurts anyone."],
        ["Flea Circus", "Win a Long Game on Abusement Park on Normal Difficulty."],
        ["Floodgate to Hell", "Win a Long Game on Waterworks on Hell on Earth Difficulty."],
        ["Fork Lift Operator", "Beat Fright Yard in Objective Mode on Normal Difficulty"],
        ["Fractional Neutron Activator", "Beat Steamland on Suicidal Difficulty"],
        ["Fruit Cake", "Complete all new map achievements on Suicidal Difficulty."],
        ["Fugly ", "Kill one of each type of zed in one round (HSG Shotgun) "],
        ["Full Charge", "Have 5 Breaker Boxes 100% repaired at the same time"],
        ["Game Over, Man!", "Have 20 Zeds you slowed with the Z.E.D. gun killed"],
        ["Gang Crew", "Beat Fright Yard on Hard Difficulty"],
        ["Getting Chunky", "Obliterate 10 Zeds at once with the Pipe Bomb."],
        ["Gimli That Axe!", "Get the Not-a-war-hammer Achievement in Dwarfs!?"],
        ["Gimme a Plaster!", "Win a Long Game on Hospital Horrors on Normal Difficulty."],
        ["Golden 3 Crown Note", "Get all 3 gold bars without the carriers taking damage while they have them"],
        ["Golden Potato", "Get into GLaDOS' core on Aperture."],
        ["Gone Camping", "Win a Long Game on Mountain Pass on Hard Difficulty."],
        ["Gone clubbing", "Beat Clandestine on Normal Difficulty"],
        ["Gone Mental", "Win a Long Game on Bedlam, on Hard Difficulty."],
        ["Grandma got Eaten by a Reindeer", "Win a Long Game on Santa's Evil Lair on Hell on Earth Difficulty."],
        ["Grim Reaper", "Get the 6 Special Halloween Achievements plus 1 Hillbilly Horror Map Achievement to unlock the Grim Reaper"],
        ["Grotto of Terror", "Beat ThrillsChills on Suicidal Difficulty"],
        ["Guardian Assault Protector", "Protect the ringmaster during the defense mission so that he does not get hit more than 15 times"],
        ["Hangover from Hell", "Beat Clandestine on Hell Difficulty"],
        ["Hard Boss", "Win a Long Game on Offices on Hard Difficulty."],
        ["Hard Pub Crawl", "Win a Long Game on West London on Hard Difficulty."],
        ["Have my axe", "Kill 30 Fleshpounds with the Dwarfs!? axe with back attacks"],
        ["Healing Touch", "Heal 200 teammates with the MP7's medication dart."],
        ["Hellish Pub Crawl", "Win a Long Game on West London on Hell on Earth Difficulty."],
        ["Here is to us", "Beat Moonbase on Normal Difficulty"],
        ["Hide and go Puke", "[2013 Summer] Destroy all the Pukey the Clown dolls"],
        ["Highlander", "Kill a Scrake, a Fleshpound, and the Patriarch with the Claymore Sword within one map"],
        ["Highway to Heaven", "Beat Hellride on Normal Difficulty"],
        ["Historical Remnants", "Kill 6 Zeds with one magazine on an MKb42, without reloading"],
        ["Hollow of Horror", "Beat ThrillsChills on Hell Difficulty"],
        ["Home Brewer", "Beat Siren's Belch on Normal Difficulty"],
        ["Homer's Heroes", "Kill 100 Sirens."],
        ["Hot Cross Fun", "Kill 25 Burning Specimens with a Crossbow."],
        ["I Am Become Death", "Kill 5 Hillbilly Zeds in 10 seconds with the Scythe or Axe"],
        ["I Like To Watch", "Aquire 5 Minutes of \"Zed-Time\"."],
        ["I love ze Healing not ze Hurting", "Heal others for 3000 points of health with the MP5 SMG"],
        ["I'm Dreaming of a Red Christmas", "Win a Long Game on Santa's Evil Lair on Suicidal Difficulty."],
        ["I'm Dying Here!", "Win a Long Game on Hospital Horrors on Suicidal Difficulty."],
        ["I'm Making a Note Here, Huge Success", "Win a Long Game on Aperture on Hell on Earth Difficulty."],
        ["Ice Cube", "Win a Long Game on Icebreaker on Normal Difficulty."],
        ["Iceberg", "Win a Long Game on Icebreaker on Suicidal Difficulty."],
        ["It's Not Easy Being Greasy", "Cause a Specimen to Die by Luring them into Bloat Acid."],
        ["It's What's Inside That Counts", "Turn 500 Specimens into Giblets."],
        ["Italian Meat Pasta", "Kill 12 zeds with a full magazine from the Combat Shotgun"],
        ["Juggling Act", "Drop 5 different Tier 2 weapons in one wave."],
        ["Keep Those Sneakers Off the Floor!", "Kill 20 Stalkers with Explosives."],
        ["Killer Junior", "Kill 20 crawlers in mid-air with the M79."],
        ["King", "Beat Stronghold on Hell on Earth Difficulty"],
        ["King Minos", "Beat Hell on Hard Difficulty"],
        ["Lab Assistant", "Win a Long Game on Biotics Lab on Hard Difficulty."],
        ["Lab Cleaner", "Win a Long Game on Biotics Lab on Normal Difficulty."],
        ["Lab Professor", "Win a Long Game on Biotics Lab on Suicidal Difficulty."],
        ["Let Them Burn", "Get 1000 points of burn damage with the MAC-10."],
        ["Lifting a Dumbell", "Kill a Circus Husk with a LAW."],
        ["Long weekend", "Beat Transit in Objective Mode on Hard Difficulty"],
        ["Long, Hot Summer", "Complete a Long Game on all 3 Summer 2009 maps on Normal Difficulty."],
        ["Longshoreman", "Beat Fright Yard on Normal Difficulty"],
        ["Lord of the Manor", "Win a Long Game on Manor on Normal Difficulty."],
        ["Lucifer", "Beat Hell on Hell on Earth Difficulty"],
        ["Mad Boss", "Win a Long Game on Offices on Suicidal Difficulty."],
        ["Man of Steel", "Win a Long Game on Foundry, on Suicidal Difficulty."],
        ["Master Brewer", "Beat Siren's Belch on Suicidal Difficulty"],
        ["Master Surgeon", "As a Medic, Kill 8 Specimens using a Knife in a Single Wave."],
        ["Meet Your Maker!", "Kill 1000 Hillbilly Zeds"],
        ["Merry Friggin Christmas", "[2010 Xmas] Kill the Christmas Patriarch."],
        ["Merry Men", "Kill the Patriarch when everyone is ONLY using Crossbows."],
        ["Micro Brewer", "Beat Siren's Belch on Hard Difficulty"],
        ["Missed Connection", "Win a Long Game on Filth's Cross on Hard Difficulty."],
        ["Modified Psychoacceleration Achiever", "Beat Steamland on Hard Difficulty"],
        ["Most Bang for the Buck", "Kill 10 Halloween zeds in explosions using the Seeker 6 or the M32 within 5 seconds"],
        ["Mountaineer", "Win a Long Game on Mountain Pass on Suicidal Difficulty."],
        ["Moved to Paris!", "Beat Transit in Objective Mode on Hell on Earth Difficulty"],
        ["Mr. Perky", "Get All of your Perks up to Level 5."],
        ["Mrs. Punkd", "Get 4 of 6 of the 2013 Summer Event in-game level Achievements, one Standard and one Objective Mode map completion Achievement, plus the Punk'd Achievement to unlock Steampunk Mrs. Foster"],
        ["Multi-pass", "Transit - Pick up the door key"],
        ["Nail'd!", "Kill 4 Stalkers in a game with the Vlad9000 Nailgun"],
        ["Neighborhood Watch", "Win a Long Game on Suburbia on Normal Difficulty."],
        ["Nitro Boost!", "Transit - Get the Nitro to the Objective in 135 seconds or less"],
        ["No Time for Love, Dr. Jones", "Win a short round on KF-Hell playing as or with Harchier Spebbington"],
        ["Not Dead Yet!", "Win a Long Game on Hospital Horrors on Hell on Earth Difficulty."],
        ["Not So Silent Night", "[2010 Xmas] Kill a Christmas Siren with an undetonated LAW rocket."],
        ["Oktoberfest Master", "Collect all the Beer Steins"],
        ["On the Rocks", "Beat Ice Cave on Suicidal Difficulty"],
        ["On Top of the Big Top", "Win a Long Game on Abusement Park on Hell on Earth Difficulty."],
        ["One Giant Leap (Back) for Mankind", "Beat Moonbase on Hell on Earth Difficulty"],
        ["One Small Step for Man", "Kill 500 Zeds with the Schneidzekk Medic Gun while you are falling"],
        ["Oscillating Hydrogen Transition Achiever", "Beat Steamland in Objective Mode on Hard Difficulty"],
        ["Park Ranger", "Win a Long Game on Mountain Pass on Hell on Earth Difficulty."],
        ["Peasant", "Beat Stronghold on Normal Difficulty"],
        ["Philanthropist", "Give 1,000 Pounds to Teammates who have 50% of Your Cash or Less."],
        ["Piece of Cake", "Complete all new map achievements on Normal Difficulty."],
        ["Pile Up", "Win a Long Game on Filth's Cross on Hell on Earth Difficulty."],
        ["Pound Cake", "Complete all new map achievements on Hard Difficulty."],
        ["Pound This", "Kill 100 Fleshpounds with the AA12."],
        ["Pressure Failure", "Win a Long Game on Waterworks on Suicidal Difficulty."],
        ["Prince", "Beat Stronghold on Suicidal Difficulty"],
        ["Private Security", "Win a Long Game on Suburbia on Hard Difficulty."],
        ["Pub Crawl", "Win a Long Game on West London on Normal Difficulty."],
        ["Punk'd", "Unlock 10 of the 13 Circus Achievements along with any Abusement Park achievement."],
        ["Quarter Pounder With Ease", "Turn 5 Fleshpounds into Giblets."],
        ["Raccoon King of the Dark Forest", "Win a Long Game on Wyre, on Hard Difficulty."],
        ["Rack 'em up", "Beat Clandestine on Hard Difficulty"],
        ["Random Axe of Kindness", "Kill 15 Specimens with a Fire Axe in a Single Wave."],
        ["Rich Evil Uncle", "Collect all the Treasure Bags"],
        ["Ringmaster", "Kill the \"Ring Leader\" (Circus Patriarch)"],
        ["Rippin' It Up", "Kill a Hillbilly Husk and another Hillbilly Zed in the same shot with the Buzzsaw Bow or M99"],
        ["Rudolph, the Bloody Nosed Reindeer", "[2010 Xmas] Kill a Christmas Crawler with a Crossbow."],
        ["Rule The Roost", "Get all 6 achievements and unlock Commando Chicken"],
        ["Running Late", "Win a Long Game on Filth's Cross on Normal Difficulty."],
        ["SCAR'd", "Kill 1000 Specimens with the SCAR."],
        ["Science Got Done", "Win a Long Game on Aperture on Normal Difficulty."],
        ["Science Hater", "Transit - Destroy all the DNA vials"],
        ["Scientist from Hell", "Win a Long Game on Biotics Lab on Hell on Earth Difficulty."],
        ["Second Cousins", "Beat Hillbilly Horror on Hard Difficulty"],
        ["Seeing Double", "Kill 5 Circus Crawlers with a Bullpup in one wave."],
        ["Self Medicator", "In Co-op Mode, Use Syringe on Yourself 100 Times."],
        ["Serious vacation", "Beat Transit in Objective Mode on Suicidal Difficulty"],
        ["Shipping Magnate", "Beat Fright Yard in Objective Mode on Hell on Earth Difficulty"],
        ["Silent Night, Evil Night", "Win a Long Game on Santa's Evil Lair on Hard Difficulty."],
        ["Simplified Force Adhesion Afficianado", "Beat Steamland in Objective Mode on Normal Difficulty"],
        ["Single-Load Doom Bombardier", "Kill a ZED with a direct (unexploded) shot from the Orca Bomb Propeller or the M-79/M32"],
        ["Single-shot Equalizer", "Kill 4 different types of Zeds with headshots with 4 shots from the Long Musket or the M14 without reloading"],
        ["Skull Cracker", "Clandestine - Destroy 30 skulls"],
        ["Slight Drip", "Win a Long Game on Waterworks on Normal Difficulty."],
        ["Small Hands", "Kill 3 Circus Clots in a wave with the Lever Action Rifle."],
        ["Snow Cone", "Beat Ice Cave on Normal Difficulty"],
        ["Social Outburst", "Kill 8 Specimens with One Grenade."],
        ["Soul Collector", "Free the souls of the 25 Gnomes hidden on Hillbilly Horror in 1 game"],
        ["Sparkling in the Twilight", "Kill The Vampire Patriarch Ringmaster in Bedlam"],
        ["Sparring with a Master", "Kill a Circus Gorefast with a Melee weapon."],
        ["Spec Ops ", "Kill 12 clots with one magazine without reloading (MK23)"],
        ["Squire", "Beat Stronghold on Hard Difficulty"],
        ["Squirrel King of the Dark Forest", "Win a Long Game on Wyre, on Normal Difficulty."],
        ["Stay Frosty", "Beat Ice Cave on Hard Difficulty"],
        ["Steel Worker", "Win a Long Game on Foundry, on Hard Difficulty."],
        ["Stevedore", "Beat Fright Yard on Suicidal Difficulty"],
        ["Still Alive", "Win a Long Game on Aperture on Hard Difficulty."],
        ["Straight Rush", "Kill the Patriarch Before he has a Chance to Heal."],
        ["Stuck in Limbo", "Beat Hellride on Hard Difficulty"],
        ["Suicidal Pub Crawl", "Win a Long Game on West London on Suicidal Difficulty."],
        ["Summer of 2009", "Complete a Long Game on all 3 Summer 2009 maps on Hard Difficulty."],
        ["SWAT", "Win a Long Game on Suburbia on Hell on Earth Difficulty."],
        ["Tachyon Cytoneutralization Explorer", "Beat Steamland in Objective Mode on Hell on Earth Difficulty"],
        ["Taking Down the Big Top", "Kill 4 Circus Zeds in 1 ZED time chain with a Melee weapon."],
        ["That Bloody Well Hurts!", "Win a Long Game on Hospital Horrors on Hard Difficulty."],
        ["That's not Santa!", "[2010 Xmas] Kill 3 Christmas Bloats with the Bullpup in one wave."],
        ["The Big Hunt", "Kill a Circus Scrake with a Crossbow."],
        ["The Big One", "Kill 2 scrakes with one shot (M99)"],
        ["The Boss", "Win a Long Game on Offices on Normal Difficulty."],
        ["The Completely Suicidal War", "Complete a Long Game on all 5 Core Maps on Suicidal Difficulty."],
        ["The Hard War", "Complete a Long Game on all 5 Core Maps on Hard Difficulty."],
        ["The L.A.W. That Broke The Camel's Back", "Deliver the Killing Blow to the Patriarch with a L.A.W. Rocket."],
        ["The Long War", "Complete a Long Game on all 5 Core Maps on Normal Difficulty."],
        ["The Scene is Zed", "Kill 250 Halloween Specimens in Bedlam"],
        ["Thin-Ice Pirouette", "Complete 10 Waves when the Rest of your Team has Died."],
        ["Third Cousins", "Beat Hillbilly Horror on Normal Difficulty"],
        ["This is a Triumph", "Win a Long Game on Aperture on Suicidal Difficulty."],
        ["This is No Ordinary Rabbit!", "Kill 25 Halloween Scrakes in Bedlam"],
        ["Tin Man", "Win a Long Game on Foundry, on Normal Difficulty."],
        ["Tis Better to Give than to Receive", "[2010 Xmas] Drop 3 Tier 3 weapons for others (with which they kill at least one Christmas Zed)."],
        ["Toasted Jack Frost", "[2010 Xmas] Kill the Christmas Scrake with a Fire-based weapon."],
        ["Too Close For Comfort", "Finish off a Fleshpound using a Melee Attack."],
        ["Totally Metal", "Transit - Kill 250 Zeds before completing the welding objective"],
        ["Train Wreck", "Win a Long Game on Filth's Cross on Suicidal Difficulty."],
        ["Trappist Monk", "Beat Siren's Belch on Hell on Earth Difficulty"],
        ["Trench Warfare", "Set a total of 200 Zeds on fire with the Trench Gun in Hillbilly Horror"],
        ["Trick, not Treat", "Kill 5 Halloween Specimens with any gun without reloading"],
        ["Truck Driver", "Beat Fright Yard in Objective Mode on Hard Difficulty"],
        ["Turbo Executioner", "Kill 5 zeds in ZED time without reloading with Dr. T's LDS or Bullpup"],
        ["Uber Tuber", "Expensive but delicious! Brought to you by Dr. Dougley and Lord Ned."],
        ["Under The Weather", "Use Bile or the Flamethrower to kill one of each Halloween Zed"],
        ["Vigilante", "Win a Long Game on Suburbia on Suicidal Difficulty."],
        ["Walking in  A Winter Horror Land", "Win a Long Game on Santa's Evil Lair on Normal Difficulty."],
        ["Warehouse Foreman", "Win a Long Game on Crash on Suicidal Difficulty."],
        ["Warehouse Forklift Operator", "Win a Long Game on Crash on Hard Difficulty."],
        ["Warehouse Janitor", "Win a Long Game on Crash on Normal Difficulty."],
        ["Warehouse Manager", "Win a Long Game on Crash on Hell on Earth Difficulty."],
        ["Waste Disposal", "Win a Long Game on Biohazard on Normal Difficulty."],
        ["Waste Land", "Win a Long Game on Biohazard on Hard Difficulty."],
        ["Waste of Space", "Win a Long Game on Biohazard on Suicidal Difficulty."],
        ["Wasted", "Win a Long Game on Biohazard on Hell on Earth Difficulty."],
        ["We Have Ourselves a Cowboy", "Hold dual 9mm, dual hand cannons and Dual Revolvers"],
        ["Wharfinger", "Beat Fright Yard on Hell on Earth Difficulty"],
        ["Who Brings a Gun to a Snow Ball Fight?", "[2010 Xmas] Kill a Christmas Husk with any Pistol."],
        ["Windjammer Enthusiast", "Survive 10 seconds after being screamed at by a Circus Siren on Hard or above."],
        ["Wolf King of the Dark Forest", "Win a Long Game on Wyre on Hell on Earth Difficulty."],
        ["Zed October", "Win a Long Bedlam Match During the Halloween Event on Hard"],
    ];

    assert.strictEqual(officialAchievements.length, 285, "sanity check on this test's own reference list");

    const dataPairs = game.achievements
        .map(a => [a.name, a.description])
        .sort((a, b) => a[0].localeCompare(b[0]));

    assert.deepStrictEqual(dataPairs, [...officialAchievements].sort((a, b) => a[0].localeCompare(b[0])));

});
