import { test } from "node:test";
import assert from "node:assert";

import { getPlannerData } from "../utils/plannerCatalog.js";

// backend/catalog/games/men-of-war-assault-squad-2.json - 415 real achievements sourced
// from a live ISteamUserStats/GetSchemaForGame/v2 response for appid
// 244450 (fetched through this app's own services/steamApi.js). None are
// hidden; every description is Steam's own real text.
// Many displayNames repeat across difficulties/DLC missions; only apinames are unique.
// difficulty/estimatedTime/missable remain curatorial judgments.
const game = getPlannerData("men-of-war-assault-squad-2");

test("getPlannerData('men-of-war-assault-squad-2') returns real planner data with 415 curated achievements", () => {

    assert.ok(game, "expected real planner data for men-of-war-assault-squad-2");
    assert.ok(Array.isArray(game.achievements));
    assert.strictEqual(game.achievements.length, 415);

});

test("every Men of War: Assault Squad 2 achievement has a unique id from 1 to 415 and a unique apiname", () => {

    const ids = game.achievements.map(a => a.id);
    const apinames = game.achievements.map(a => a.apiname);

    assert.deepStrictEqual([...ids].sort((a, b) => a - b), Array.from({ length: 415 }, (_, i) => i + 1));
    assert.strictEqual(new Set(ids).size, 415);
    assert.strictEqual(new Set(apinames).size, 415);

});

test("every Men of War: Assault Squad 2 achievement has a valid difficulty (1-5), a positive estimatedTime, and non-empty name/description", () => {

    for (const achievement of game.achievements) {

        assert.ok(
            Number.isInteger(achievement.difficulty) && achievement.difficulty >= 1 && achievement.difficulty <= 5,
            `${achievement.name} has an out-of-range difficulty: ${achievement.difficulty}`
        );

        assert.ok(
            Number.isInteger(achievement.estimatedTime) && achievement.estimatedTime > 0,
            `${achievement.name} has an invalid estimatedTime: ${achievement.estimatedTime}`
        );

        assert.ok(achievement.name?.length > 0, "achievement is missing a name");
        assert.ok(achievement.description?.length > 0, `${achievement.name} is missing a description`);
        assert.ok(achievement.apiname?.length > 0, `${achievement.name} is missing an apiname`);

    }

});

test("every one of the 415 Men of War: Assault Squad 2 achievement name+description pairs matches the catalog data", () => {

    const officialAchievements = [
        ["101st Airborne", "Call-in 101st Airborne in Skirmish."],
        ["15.000 XP", "Collect 15.000 XP as USA."],
        ["15.000 XP", "Collect 15.000 XP as Germany."],
        ["15.000 XP", "Collect 15.000 XP as Commonwealth."],
        ["15.000 XP", "Collect 15.000 XP as Soviet Union."],
        ["15.000 XP", "Collect 15.000 XP as Japan."],
        ["2.000 XP", "Collect 2.000 XP as USA."],
        ["2.000 XP", "Collect 2.000 XP as Germany."],
        ["2.000 XP", "Collect 2.000 XP as Commonwealth."],
        ["2.000 XP", "Collect 2.000 XP as Soviet Union."],
        ["2.000 XP", "Collect 2.000 XP as Japan."],
        ["200mm Type 4", "Call-in a 200mm Type 4 in Skirmish."],
        ["203mm B-4M", "Call-in a 203mm B-4M in Skirmish."],
        ["5.000 XP", "Collect 5.000 XP as USA."],
        ["5.000 XP", "Collect 5.000 XP as Germany."],
        ["5.000 XP", "Collect 5.000 XP as Commonwealth."],
        ["5.000 XP", "Collect 5.000 XP as Soviet Union."],
        ["5.000 XP", "Collect 5.000 XP as Japan."],
        ["50.000 XP", "Collect 50.000 XP as USA."],
        ["50.000 XP", "Collect 50.000 XP as Germany."],
        ["50.000 XP", "Collect 50.000 XP as Commonwealth."],
        ["50.000 XP", "Collect 50.000 XP as Soviet Union."],
        ["50.000 XP", "Collect 50.000 XP as Japan."],
        ["500 XP", "Collect 500 XP as USA."],
        ["500 XP", "Collect 500 XP as Germany."],
        ["500 XP", "Collect 500 XP as Commonwealth."],
        ["500 XP", "Collect 500 XP as Soviet Union."],
        ["500 XP", "Collect 500 XP as Japan."],
        ["Ace of Aces", "Destroy the enemy tank ace in 3rd person tank Skirmish!"],
        ["Ace of Aces", "Destroy the enemy tank ace in 3rd person tank Skirmish!"],
        ["Ace of Aces", "Destroy the enemy tank ace in 3rd person tank Skirmish!"],
        ["Ace of Aces", "Destroy the enemy tank ace in 3rd person tank Skirmish!"],
        ["Ace of Aces", "Destroy the enemy tank ace in 3rd person tank Skirmish!"],
        ["Ambush", "Ambush the Japanese reinforcments in introduction."],
        ["ANZAC", "Call-in ANZAC in defense Skirmish."],
        ["Artillery Strike", "Call-in an Artillery Strike in Skirmish."],
        ["Banzai", "Call-in Banzai in Skirmish."],
        ["Baptism of Fire", "Repell the enemy attack in first Skirmish."],
        ["Baptism of Fire", "Repell the enemy attack in first Skirmish."],
        ["Baptism of Fire", "Repell the enemy attack in first Skirmish."],
        ["Baptism of Fire", "Repell the enemy attack in first Skirmish."],
        ["Baptism of Fire", "Repell the enemy attack in first Skirmish."],
        ["Beachhead", "Clean the beach of enemies in introduction."],
        ["Behind Enemy Lines", "Destroy the enemy artillery emplacement in sniper Skirmish."],
        ["Behind Enemy Lines", "Destroy the enemy artillery emplacement in sniper Skirmish."],
        ["Behind Enemy Lines", "Destroy the enemy artillery emplacement in sniper Skirmish."],
        ["Behind Enemy Lines", "Destroy the enemy artillery emplacement in sniper Skirmish."],
        ["Behind Enemy Lines", "Destroy the enemy artillery emplacement in sniper Skirmish."],
        ["Brandenburger", "Call-in German Brandenburger in defense Skirmish."],
        ["British Radio Operator", "Call-in a British Radio Operator in defense Skirmish."],
        ["Chi-Ha 57", "Call-in a Chi-ha 57 in stealth Skirmish."],
        ["Commandos", "Call-in Commandos in Skirmish."],
        ["Commonwealth mission 1 - easy", "Complete the first British mission on easy."],
        ["Commonwealth mission 1 - hard", "Complete the first British mission on hard."],
        ["Commonwealth mission 1 - heroic", "Complete the first British mission on heroic."],
        ["Commonwealth mission 1 - normal", "Complete the first British mission on normal."],
        ["Commonwealth mission 10 - easy", "Complete the tenth British mission on easy."],
        ["Commonwealth mission 10 - hard", "Complete the tenth British mission on hard."],
        ["Commonwealth mission 10 - heroic", "Complete the tenth British mission on heroic."],
        ["Commonwealth mission 10 - normal", "Complete the tenth British mission on normal."],
        ["Commonwealth mission 2 - easy", "Complete the second British mission on easy."],
        ["Commonwealth mission 2 - hard", "Complete the second British mission on hard."],
        ["Commonwealth mission 2 - heroic", "Complete the second British mission on heroic."],
        ["Commonwealth mission 2 - normal", "Complete the second British mission on normal."],
        ["Commonwealth mission 3 - easy", "Complete the third British mission on easy."],
        ["Commonwealth mission 3 - hard", "Complete the third British mission on hard."],
        ["Commonwealth mission 3 - heroic", "Complete the third British mission on heroic."],
        ["Commonwealth mission 3 - normal", "Complete the third British mission on normal."],
        ["Commonwealth mission 4 - easy", "Complete the fourth British mission on easy."],
        ["Commonwealth mission 4 - hard", "Complete the fourth British mission on hard."],
        ["Commonwealth mission 4 - heroic", "Complete the fourth British mission on heroic."],
        ["Commonwealth mission 4 - normal", "Complete the third British mission on normal."],
        ["Commonwealth mission 5 - hard", "Complete the fifth British mission on hard."],
        ["Commonwealth mission 5 - heroic", "Complete the fifth British mission on heroic."],
        ["Commonwealth mission 5 - normal", "Complete the fifth British mission on normal."],
        ["Commonwealth mission 6 - easy", "Complete the sixth British mission on easy."],
        ["Commonwealth mission 6 - heroic", "Complete the sixth British mission on heroic."],
        ["Commonwealth mission 6 - normal", "Complete the sixth British mission on normal."],
        ["Commonwealth mission 7 - easy", "Complete the seventh British mission on easy."],
        ["Commonwealth mission 7 - hard", "Complete the seventh British mission on hard."],
        ["Commonwealth mission 7 - heroic", "Complete the seventh British mission on heroic."],
        ["Commonwealth mission 7 - normal", "Complete the seventh British mission on normal."],
        ["Commonwealth mission 8 - easy", "Complete the eighth British mission on easy."],
        ["Commonwealth mission 8 - hard", "Complete the eighth British mission on hard."],
        ["Commonwealth mission 8 - heroic", "Complete the eighth British mission on heroic."],
        ["Commonwealth mission 8 - normal", "Complete the eighth British mission on normal."],
        ["Commonwealth mission 9 - easy", "Complete the ninth British mission on easy."],
        ["Commonwealth mission 9 - hard", "Complete the ninth British mission on hard."],
        ["Commonwealth mission 9 - heroic", "Complete the ninth British mission on heroic."],
        ["Commonwealth mission 9 - normal", "Complete the ninth British mission on normal."],
        ["Commonwealth misson 5 - easy", "Complete the fifth British mission on easy."],
        ["Commonwealth misson 6 - hard", "Complete the sixth British mission on hard."],
        ["Completionist", "Fulfill the second bonus objective in airborne Skirmish!"],
        ["Completionist", "Fulfill the second bonus objective in airborne Skirmish!"],
        ["Completionist", "Fulfill the second bonus objective in airborne Skirmish!"],
        ["Completionist", "Fulfill the second bonus objective in airborne Skirmish!"],
        ["Completionist", "Fulfill the second bonus objective in airborne Skirmish!"],
        ["Conquerer", "Conquer all strategic points and set-up a new field HQ in first Skirmish."],
        ["Conquerer", "Conquer all strategic points and set-up a new field HQ in first Skirmish."],
        ["Conquerer", "Conquer all strategic points and set-up a new field HQ in first Skirmish."],
        ["Conquerer", "Conquer all strategic points and set-up a new field HQ in first Skirmish."],
        ["Conquerer", "Conquer all strategic points and set-up a new field HQ in first Skirmish."],
        ["Fireworks", "Burn down the enemy fuel depot in 3rd person tank Skirmish!"],
        ["Fireworks", "Burn down the enemy fuel depot in 3rd person tank Skirmish!"],
        ["Fireworks", "Burn down the enemy fuel depot in 3rd person tank Skirmish!"],
        ["Fireworks", "Burn down the enemy fuel depot in 3rd person tank Skirmish!"],
        ["Fireworks", "Burn down the enemy fuel depot in 3rd person tank Skirmish!"],
        ["Five Star General", "Reward for owning the Digital Deluxe edition!"],
        ["For the Motherland", "Call-in Charge in Skirmish."],
        ["Fortification", "Capture the Japanese fortification in introduction."],
        ["German Radio Operator", "Call-in a German Radio Operator in defense Skirmish."],
        ["Germany mission 1 easy", "Complete the first German mission on easy."],
        ["Germany mission 1 hard", "Complete the first German mission on hard."],
        ["Germany mission 1 heroic", "Complete the first German mission on heroic."],
        ["Germany mission 1 normal", "Complete the first German mission on normal."],
        ["Germany mission 10 - easy", "Complete the tenth German mission on easy."],
        ["Germany mission 10 - hard", "Complete the tenth German mission on hard."],
        ["Germany mission 10 - heroic", "Complete the tenth German mission on heroic."],
        ["Germany mission 10 - normal", "Complete the tenth German mission on normal."],
        ["Germany mission 2 - easy", "Complete the second German mission on easy."],
        ["Germany mission 2 - hard", "Complete the second German mission on hard."],
        ["Germany mission 2 - heroic", "Complete the second German mission on heroic."],
        ["Germany mission 2 - normal", "Complete the second German mission on normal."],
        ["Germany mission 3 - easy", "Complete the third German mission on easy."],
        ["Germany mission 3 - hard", "Complete the third German mission on hard."],
        ["Germany mission 3 - heroic", "Complete the third German mission on heroic."],
        ["Germany mission 3 - normal", "Complete the third German mission on normal."],
        ["Germany mission 4 - easy", "Complete the fourth German mission on easy."],
        ["Germany mission 4 - hard", "Complete the fourth German mission on hard."],
        ["Germany mission 4 - heroic", "Complete the fourth German mission on heroic."],
        ["Germany mission 4 - normal", "Complete the fourth German mission on normal."],
        ["Germany mission 5 - easy", "Complete the fifth German mission on easy."],
        ["Germany mission 5 - hard", "Complete the fifth German mission on hard."],
        ["Germany mission 5 - heroic", "Complete the fifth German mission on heroic."],
        ["Germany mission 5 - normal", "Complete the fifth German mission on normal."],
        ["Germany mission 6 - easy", "Complete the sixth German mission on easy."],
        ["Germany mission 6 - hard", "Complete the sixth German mission on hard."],
        ["Germany mission 6 - heroic", "Complete the sixth German mission on heroic."],
        ["Germany mission 6 - normal", "Complete the sixth German mission on normal."],
        ["Germany mission 7 - easy", "Complete the seventh German mission on easy."],
        ["Germany mission 7 - hard", "Complete the seventh German mission on hard."],
        ["Germany mission 7 - heroic", "Complete the seventh German mission on heroic."],
        ["Germany mission 7 - normal", "Complete the seventh German mission on normal."],
        ["Germany mission 8 - easy", "Complete the eighth German mission on easy."],
        ["Germany mission 8 - heroic", "Complete the eighth German mission on heroic."],
        ["Germany mission 9 - easy", "Complete the ninth German mission on easy."],
        ["Germany mission 9 - hard", "Complete the ninth German mission on hard."],
        ["Germany mission 9 - heroic", "Complete the ninth German mission on heroic."],
        ["Germany mission 9 - normal", "Complete the ninth German mission on normal."],
        ["Germany misson 8 - hard", "Complete the eighth German mission on hard."],
        ["Germany misson 8 - normal", "Complete the eighth German mission on normal."],
        ["Goliath", "Call-in a Goliath in Skirmish."],
        ["Guards Rifle", "Call-in Guards Rifle in defense Skirmish."],
        ["High Value Target", "Take out the commanding officer in stealth Skirmish."],
        ["High Value Target", "Take out the commanding officer in stealth Skirmish."],
        ["High Value Target", "Take out the commanding officer in stealth Skirmish."],
        ["High Value Target", "Take out the commanding officer in stealth Skirmish."],
        ["High Value Target", "Take out the commanding officer in stealth Skirmish."],
        ["Ho-Ri 2", "Call-in a Ho-Ri 2 in tank defense Skirmish."],
        ["Introduction - easy", "Complete the introduction on easy difficulty."],
        ["Introduction - hard", "Complete the introduction on hard difficulty."],
        ["Introduction - heroic", "Complete the introduction on heroic difficulty."],
        ["Introduction - normal", "Complete the introduction on normal difficulty."],
        ["Japanese Empire mission 1 - easy", "Complete the first Japanese mission on easy."],
        ["Japanese Empire mission 1 - hard", "Complete the first Japanese mission on hard."],
        ["Japanese Empire mission 1 - heroic", "Complete the first Japanese mission on heroic."],
        ["Japanese Empire mission 1 - normal", "Complete the first Japanese mission on normal."],
        ["Japanese Empire mission 10 - easy", "Complete the tenth Japanese mission on easy."],
        ["Japanese Empire mission 10 - hard", "Complete the tenth Japanese mission on hard."],
        ["Japanese Empire mission 10 - heroic", "Complete the tenth Japanese mission on heroic."],
        ["Japanese Empire mission 10 - normal", "Complete the tenth Japanese mission on normal."],
        ["Japanese Empire mission 2 - easy", "Complete the second Japanese mission on easy."],
        ["Japanese Empire mission 2 - hard", "Complete the second Japanese mission on hard"],
        ["Japanese Empire mission 2 - heroic", "Complete the second Japanese mission on heroic."],
        ["Japanese Empire mission 2 - normal", "Complete the second Japanese mission on normal."],
        ["Japanese Empire mission 3 - easy", "Complete the third Japanese mission on easy."],
        ["Japanese Empire mission 3 - hard", "Complete the third Japanese mission on hard."],
        ["Japanese Empire mission 3 - heroic", "Complete the third Japanese mission on heroic."],
        ["Japanese Empire mission 3 - normal", "Complete the third Japanese mission on normal."],
        ["Japanese Empire mission 4 - easy", "Complete the fourth Japanese mission on easy."],
        ["Japanese Empire mission 4 - hard", "Complete the fourth Japanese mission on hard."],
        ["Japanese Empire mission 4 - heroic", "Complete the fourth Japanese mission on heroic."],
        ["Japanese Empire mission 4 - normal", "Complete the fourth Japanese mission on normal."],
        ["Japanese Empire mission 5 - easy", "Complete the fifth Japanese mission on easy."],
        ["Japanese Empire mission 5 - hard", "Complete the fifth Japanese mission on hard."],
        ["Japanese Empire mission 5 - heroic", "Complete the fifth Japanese mission on heroic."],
        ["Japanese Empire mission 5 - normal", "Complete the fifth Japanese mission on normal."],
        ["Japanese Empire mission 6 - easy", "Complete the sixth Japanese mission on easy."],
        ["Japanese Empire mission 6 - hard", "Complete the sixth Japanese mission on hard."],
        ["Japanese Empire mission 6 - heroic", "Complete the sixth Japanese mission on heroic."],
        ["Japanese Empire mission 6 - normal", "Complete the sixth Japanese mission on normal."],
        ["Japanese Empire mission 7 - easy", "Complete the seventh Japanese mission on easy."],
        ["Japanese Empire mission 7 - hard", "Complete the seventh Japanese mission on hard."],
        ["Japanese Empire mission 7 - heroic", "Complete the seventh Japanese mission on heroic."],
        ["Japanese Empire mission 7 - normal", "Complete the seventh Japanese mission on normal."],
        ["Japanese Empire mission 8 - easy", "Complete the eighth Japanese mission on easy."],
        ["Japanese Empire mission 8 - hard", "Complete the eighth Japanese mission on hard."],
        ["Japanese Empire mission 8 - heroic", "Complete the eighth Japanese mission on heroic."],
        ["Japanese Empire mission 8 - normal", "Complete the eighth Japanese mission on normal."],
        ["Japanese Empire mission 9 - easy", "Complete the ninth Japanese mission on easy."],
        ["Japanese Empire mission 9 - hard", "Complete the ninth Japanese mission on hard."],
        ["Japanese Empire mission 9 - heroic", "Complete the ninth Japanese mission on heroic."],
        ["Japanese Empire mission 9 - normal", "Complete the ninth Japanese mission on normal."],
        ["Japanese Radio Operator", "Call-in a Japanese Radio Operator in defense Skirmish."],
        ["Kamikaze", "Call-in Kamikaze in defense Skirmish."],
        ["King Tiger", "Call-in a King Tiger in tank defense Skirmish."],
        ["M5A1 Stuart", "Call-in a M5A1 Stuart in stealth Skirmish."],
        ["Master Tanker", "Fight your way through the enemy lines with your M4A3E2(76) Jumbo!"],
        ["Master Tanker", "Fight your way through the enemy lines with your M26 Pershing!"],
        ["Master Tanker", "Fight your way through the enemy lines with your M26E4 Super Pershing"],
        ["Master Tanker", "Fight your way through the enemy lines with your PzKpfw V Panther!"],
        ["Master Tanker", "Fight your way through the enemy lines with your Jagdpanther!"],
        ["Master Tanker", "Fight your way through the enemy lines with your Veteran Tiger!"],
        ["Master Tanker", "Fight your way through the enemy lines with your Comet I (A34)!"],
        ["Master Tanker", "Fight your way through the enemy lines with your M4A4 Firefly!"],
        ["Master Tanker", "Fight your way through the enemy lines with your Mk. VII Churchill!"],
        ["Master Tanker", "Fight your way through the enemy lines with your SU-100!"],
        ["Master Tanker", "Fight your way through the enemy lines with your KV-85!"],
        ["Master Tanker", "Fight your way through the enemy lines with your IS-2!"],
        ["Master Tanker", "Fight your way through the enemy lines with your Chi-To!"],
        ["Master Tanker", "Fight your way through the enemy lines with your Chi-Ri!"],
        ["Master Tanker", "Fight your way through the enemy lines with your Ho-Ri I!"],
        ["Mechanic", "Repair the friendly knocked out tank in first Skirmish."],
        ["Mechanic", "Repair the friendly knocked out tank in first Skirmish."],
        ["Mechanic", "Repair the friendly knocked out tank in first Skirmish."],
        ["Mechanic", "Repair the friendly knocked out tank in first Skirmish."],
        ["Mechanic", "Repair the friendly knocked out tank in first Skirmish."],
        ["Mk. VII Tetrach", "Call-in a Mk. VII Tetrach in stealth Skirmish."],
        ["Mk.VII Churchill", "Call-in a Mk.VII Churchill in tank defense Skirmish."],
        ["Origins - Germany mission 1 - easy", "Mercury"],
        ["Origins - Germany mission 1 - hard", "Mercury"],
        ["Origins - Germany mission 1 - heroic", "Mercury"],
        ["Origins - Germany mission 1 - normal", "Mercury"],
        ["Origins - Germany mission 2 - easy", "Scorching Sands"],
        ["Origins - Germany mission 2 - hard", "Scorching Sands"],
        ["Origins - Germany mission 2 - heroic", "Scorching Sands"],
        ["Origins - Germany mission 2 - normal", "Scorching Sands"],
        ["Origins - Germany mission 3 - easy", "Desert Stronghold"],
        ["Origins - Germany mission 3 - hard", "Desert Stronghold"],
        ["Origins - Germany mission 3 - heroic", "Desert Stronghold"],
        ["Origins - Germany mission 3 - normal", "Desert Stronghold"],
        ["Origins - Germany mission 4 - easy", "On the way to Tunis"],
        ["Origins - Germany mission 4 - hard", "On the way to Tunis"],
        ["Origins - Germany mission 4 - heroic", "On the way to Tunis"],
        ["Origins - Germany mission 4 - normal", "On the way to Tunis"],
        ["Origins - Germany mission 5 - easy", "Borg's Last Fight"],
        ["Origins - Germany mission 5 - hard", "Borg's Last Fight"],
        ["Origins - Germany mission 5 - heroic", "Borg's Last Fight"],
        ["Origins - Germany mission 5 - normal", "Borg's Last Fight"],
        ["Origins - Soviet Union mission 1 - easy", "Baptism by Fire"],
        ["Origins - Soviet Union mission 1 - hard", "Baptism by Fire"],
        ["Origins - Soviet Union mission 1 - heroic", "Baptism by Fire"],
        ["Origins - Soviet Union mission 1 - normal", "Baptism by Fire"],
        ["Origins - Soviet Union mission 2 - easy", "Evacuation"],
        ["Origins - Soviet Union mission 2 - hard", "Evacuation"],
        ["Origins - Soviet Union mission 2 - heroic", "Evacuation"],
        ["Origins - Soviet Union mission 2 - normal", "Evacuation"],
        ["Origins - Soviet Union mission 3 - easy", "P.O.W."],
        ["Origins - Soviet Union mission 3 - hard", "P.O.W."],
        ["Origins - Soviet Union mission 3 - heroic", "P.O.W."],
        ["Origins - Soviet Union mission 3 - normal", "P.O.W."],
        ["Origins - Soviet Union mission 4 - easy", "Moscow is Behind Us!"],
        ["Origins - Soviet Union mission 4 - hard", "Moscow is Behind Us!"],
        ["Origins - Soviet Union mission 4 - heroic", "Moscow is Behind Us!"],
        ["Origins - Soviet Union mission 4 - normal", "Moscow is Behind Us!"],
        ["Origins - Soviet Union mission 5 - easy", "The Penal Unit"],
        ["Origins - Soviet Union mission 5 - hard", "The Penal Unit"],
        ["Origins - Soviet Union mission 5 - heroic", "The Penal Unit"],
        ["Origins - Soviet Union mission 5 - normal", "The Penal Unit"],
        ["Origins - Soviet Union mission 6 - easy", "The Last Stand"],
        ["Origins - Soviet Union mission 6 - hard", "The Last Stand"],
        ["Origins - Soviet Union mission 6 - heroic", "The Last Stand"],
        ["Origins - Soviet Union mission 6 - normal", "The Last Stand"],
        ["Origins - Soviet Union mission 7 - easy", "Behind Enemy Lines"],
        ["Origins - Soviet Union mission 7 - hard", "Behind Enemy Lines"],
        ["Origins - Soviet Union mission 7 - heroic", "Behind Enemy Lines"],
        ["Origins - Soviet Union mission 7 - normal", "Behind Enemy Lines"],
        ["Origins - Soviet Union mission 8 - easy", "Chasing Shadows"],
        ["Origins - Soviet Union mission 8 - hard", "Chasing Shadows"],
        ["Origins - Soviet Union mission 8 - heroic", "Chasing Shadows"],
        ["Origins - Soviet Union mission 8 - normal", "Chasing Shadows"],
        ["Origins - Soviet Union mission 9 - easy", "The Flying Dutchman"],
        ["Origins - Soviet Union mission 9 - hard", "The Flying Dutchman"],
        ["Origins - Soviet Union mission 9 - heroic", "The Flying Dutchman"],
        ["Origins - Soviet Union mission 9 - normal", "The Flying Dutchman"],
        ["Origins - USA mission 1 - easy", "Arsenal"],
        ["Origins - USA mission 1 - hard", "Arsenal"],
        ["Origins - USA mission 1 - heroic", "Arsenal"],
        ["Origins - USA mission 1 - normal", "Arsenal"],
        ["Origins - USA mission 2 - easy", "Armistice"],
        ["Origins - USA mission 2 - hard", "Armistice"],
        ["Origins - USA mission 2 - heroic", "Armistice"],
        ["Origins - USA mission 2 - normal", "Armistice"],
        ["Origins - USA mission 3 - easy", "Meeting the Enemy"],
        ["Origins - USA mission 3 - hard", "Meeting the Enemy"],
        ["Origins - USA mission 3 - heroic", "Meeting the Enemy"],
        ["Origins - USA mission 3 - normal", "Meeting the Enemy"],
        ["Origins - USA mission 4 - easy", "Disaster in Tunisia"],
        ["Origins - USA mission 4 - hard", "Disaster in Tunisia"],
        ["Origins - USA mission 4 - heroic", "Disaster in Tunisia"],
        ["Origins - USA mission 4 - normal", "Disaster in Tunisia"],
        ["Origins - USA mission 5 - easy", "Turning Point"],
        ["Origins - USA mission 5 - hard", "Turning Point"],
        ["Origins - USA mission 5 - heroic", "Turning Point"],
        ["Origins - USA mission 5 - normal", "Turning Point"],
        ["P51 Airstrike", "Call-in a P51 Airstrike in Skirmish."],
        ["PzKpfw II Luchs", "Call-in a PzKpfw II Luchs in stealth Skirmish."],
        ["Road Block", "Clear the road block in introduction."],
        ["Saviour", "Repair and recover the secret allied tank in tank defense Skirmish."],
        ["Saviour", "Repair and recover the secret allied tank in tank defense Skirmish."],
        ["Saviour", "Repair and recover the secret allied tank in tank defense Skirmish."],
        ["Saviour", "Repair and recover the secret allied tank in tank defense Skirmish."],
        ["Saviour", "Repair and recover the secret allied tank in tank defense Skirmish."],
        ["Silent Hunter", "Kill all enemy snipers or armor without any reinforcements in sniper Skirmish."],
        ["Silent Hunter", "Kill all enemy snipers or armor without any reinforcements in sniper Skirmish."],
        ["Silent Hunter", "Kill all enemy snipers or armor without any reinforcements in sniper Skirmish."],
        ["Silent Hunter", "Kill all enemy snipers or armor without any reinforcements in sniper Skirmish."],
        ["Silent Hunter", "Kill all enemy snipers or armor without any reinforcements in sniper Skirmish."],
        ["Soviet Radio Operator", "Call-in a Soviet Radio Operator in defense Skirmish."],
        ["Soviet Union mission 1 - easy", "Complete the first Soviet mission on easy."],
        ["Soviet Union mission 1 - hard", "Complete the first Soviet mission on hard."],
        ["Soviet Union mission 1 - heroic", "Complete the first Soviet mission on heroic."],
        ["Soviet Union mission 1 - normal", "Complete the first Soviet mission on normal."],
        ["Soviet Union mission 10 - easy", "Complete the tenth Soviet mission on easy."],
        ["Soviet Union mission 10 - hard", "Complete the tenth Soviet mission on hard."],
        ["Soviet Union mission 10 - heroic", "Complete the tenth Soviet mission on heroic."],
        ["Soviet Union mission 10 - normal", "Complete the tenth Soviet mission on normal."],
        ["Soviet Union mission 2 - easy", "Complete the second Soviet mission on easy."],
        ["Soviet Union mission 2 - hard", "Complete the second Soviet mission on hard."],
        ["Soviet Union mission 2 - heroic", "Complete the second Soviet mission on heroic."],
        ["Soviet Union mission 2 - normal", "Complete the second Soviet mission on normal."],
        ["Soviet Union mission 3 - easy", "Complete the third Soviet mission on easy."],
        ["Soviet Union mission 3 - hard", "Complete the third Soviet mission on hard."],
        ["Soviet Union mission 3 - heroic", "Complete the third Soviet mission on heroic."],
        ["Soviet Union mission 3 - normal", "Complete the third Soviet mission on normal."],
        ["Soviet Union mission 4 - easy", "Complete the fourth Soviet mission on easy."],
        ["Soviet Union mission 4 - hard", "Complete the fourth Soviet mission on hard."],
        ["Soviet Union mission 4 - heroic", "Complete the fourth Soviet mission on heroic."],
        ["Soviet Union mission 4 - normal", "Complete the fourth Soviet mission on normal."],
        ["Soviet Union mission 5 - easy", "Complete the fifth Soviet mission on easy."],
        ["Soviet Union mission 5 - hard", "Complete the fifth Soviet mission on hard."],
        ["Soviet Union mission 5 - heroic", "Complete the fifth Soviet mission on heroic."],
        ["Soviet Union mission 5 - normal", "Complete the fifth Soviet mission on normal."],
        ["Soviet Union mission 6 - easy", "Complete the sixth Soviet mission on easy."],
        ["Soviet Union mission 6 - hard", "Complete the sixth Soviet mission on hard."],
        ["Soviet Union mission 6 - heroic", "Complete the sixth Soviet mission on heroic."],
        ["Soviet Union mission 6 - normal", "Complete the sixth Soviet mission on normal."],
        ["Soviet Union mission 7 - easy", "Complete the seventh Soviet mission on easy."],
        ["Soviet Union mission 7 - hard", "Complete the seventh Soviet mission on hard."],
        ["Soviet Union mission 7 - heroic", "Complete the seventh Soviet mission on heroic."],
        ["Soviet Union mission 7 - normal", "Complete the seventh Soviet mission on normal."],
        ["Soviet Union mission 8 - easy", "Complete the eighth Soviet mission on easy."],
        ["Soviet Union mission 8 - hard", "Complete the eighth Soviet mission on hard."],
        ["Soviet Union mission 8 - heroic", "Complete the eighth Soviet mission on heroic."],
        ["Soviet Union mission 8 - normal", "Complete the eighth Soviet mission on normal."],
        ["Soviet Union mission 9 - easy", "Complete the ninth Soviet mission on easy."],
        ["Soviet Union mission 9 - hard", "Complete the ninth Soviet mission on hard."],
        ["Soviet Union mission 9 - heroic", "Complete the ninth Soviet mission on heroic."],
        ["Soviet Union mission 9 - normal", "Complete the ninth Soviet mission on normal."],
        ["Spearhead", "Break through the enemy defenses in first Skirmish."],
        ["Spearhead", "Break through the enemy defenses in first Skirmish."],
        ["Spearhead", "Break through the enemy defenses in first Skirmish."],
        ["Spearhead", "Break through the enemy defenses in first Skirmish."],
        ["Spearhead", "Break through the enemy defenses in first Skirmish."],
        ["Stealth", "Destroy the bonus objective without alerting the enemy in airborne Skirmish!"],
        ["Stealth", "Destroy the bonus objective without alerting the enemy in airborne Skirmish!"],
        ["Stealth", "Destroy the bonus objective without alerting the enemy in airborne Skirmish!"],
        ["Stealth", "Destroy the bonus objective without alerting the enemy in airborne Skirmish!"],
        ["Stealth", "Destroy the bonus objective without alerting the enemy in airborne Skirmish!"],
        ["SU-100", "Call-in a SU-100 in tank defense Skirmish."],
        ["Super Pershing", "Call-in a Super Pershing in tank defense Skirmish."],
        ["T-70", "Call-in a T-70 in stealth Skirmish."],
        ["U.S. Marines", "Call-in U.S. Marines in defense Skirmish."],
        ["U.S. Radio Operator", "Call-in an American Radio Operator in defense Skirmish."],
        ["USA mission 1 - easy", "Complete the first US mission on easy."],
        ["USA mission 1 - hard", "Complete the first US mission on hard."],
        ["USA mission 1 - heroic", "Complete the first US mission on heroic."],
        ["USA mission 1 - normal", "Complete the first US mission on normal."],
        ["USA mission 10 - easy", "Complete the tenth US mission on easy."],
        ["USA mission 10 - hard", "Complete the tenth US mission on hard."],
        ["USA mission 10 - heroic", "Complete the tenth US mission on heroic."],
        ["USA mission 10 - normal", "Complete the tenth US mission on normal."],
        ["USA mission 2 - easy", "Complete the second US mission on easy."],
        ["USA mission 2 - hard", "Complete the second US mission on hard."],
        ["USA mission 2 - heroic", "Complete the second US mission on heroic."],
        ["USA mission 2 - normal", "Complete the second US mission on normal."],
        ["USA mission 3 - easy", "Complete the third US mission on easy."],
        ["USA mission 3 - hard", "Complete the third US mission on hard."],
        ["USA mission 3 - heroic", "Complete the third US mission on heroic."],
        ["USA mission 3 - normal", "Complete the third US mission on normal."],
        ["USA mission 4 - easy", "Complete the fourth US mission on easy."],
        ["USA mission 4 - hard", "Complete the fourth US mission on hard."],
        ["USA mission 4 - heroic", "Complete the fourth US mission on heroic."],
        ["USA mission 4 - normal", "Complete the fourth US mission on normal."],
        ["USA mission 5 - easy", "Complete the fifth US mission on easy."],
        ["USA mission 5 - hard", "Complete the fifth US mission on hard."],
        ["USA mission 5 - heroic", "Complete the fifth US mission on heroic."],
        ["USA mission 5 - normal", "Complete the fifth US mission on normal."],
        ["USA mission 6 - easy", "Complete the sixth US mission on easy."],
        ["USA mission 6 - hard", "Complete the sixth US mission on hard."],
        ["USA mission 6 - heroic", "Complete the sixth US mission on heroic."],
        ["USA mission 6 - normal", "Complete the sixth US mission on normal."],
        ["USA mission 7 - easy", "Complete the seventh US mission on easy."],
        ["USA mission 7 - hard", "Complete the seventh US mission on hard."],
        ["USA mission 7 - heroic", "Complete the seventh US mission on heroic."],
        ["USA mission 7 - normal", "Complete the seventh US mission on normal."],
        ["USA mission 8 - easy", "Complete the eighth US mission on easy."],
        ["USA mission 8 - hard", "Complete the eighth US mission on hard."],
        ["USA mission 8 - heroic", "Complete the eighth US mission on heroic."],
        ["USA mission 8 - normal", "Complete the eighth US mission on normal."],
        ["USA mission 9 - easy", "Complete the ninth US mission on easy."],
        ["USA mission 9 - hard", "Complete the ninth US mission on hard."],
        ["USA mission 9 - heroic", "Complete the ninth US mission on heroic."],
        ["USA mission 9 - normal", "Complete the ninth US mission on normal."],
        ["Veteran Tiger", "Call-in a Veteran Tiger in Skirmish."],
    ];

    assert.strictEqual(officialAchievements.length, 415, "sanity check on this test's own reference list");

    const dataPairs = game.achievements
        .map(a => [a.name, a.description])
        .sort((a, b) => a[0].localeCompare(b[0]));

    assert.deepStrictEqual(dataPairs, [...officialAchievements].sort((a, b) => a[0].localeCompare(b[0])));

});
