import { test } from "node:test";
import assert from "node:assert";

import { getPlannerData } from "../utils/plannerCatalog.js";

// backend/catalog/games/northgard.json - 289 real achievements sourced
// from a live ISteamUserStats/GetSchemaForGame/v2 response for appid
// 466560 (fetched through this app's own services/steamApi.js). None are hidden; every achievement's description is Steam's own real
// text, quoted verbatim.
// difficulty/estimatedTime/missable remain curatorial judgments.
const game = getPlannerData("northgard");

test("getPlannerData('northgard') returns real planner data with 289 curated achievements", () => {

    assert.ok(game, "expected real planner data for northgard");
    assert.ok(Array.isArray(game.achievements));
    assert.strictEqual(game.achievements.length, 289);

});

test("every Northgard achievement has a unique id from 1 to 289 and a unique apiname", () => {

    const ids = game.achievements.map(a => a.id);
    const apinames = game.achievements.map(a => a.apiname);

    assert.deepStrictEqual([...ids].sort((a, b) => a - b), Array.from({ length: 289 }, (_, i) => i + 1));
    assert.strictEqual(new Set(ids).size, 289);
    assert.strictEqual(new Set(apinames).size, 289);

});

test("every Northgard achievement has a valid difficulty (1-5), a positive estimatedTime, and non-empty name/description", () => {

    for (const achievement of game.achievements) {

        assert.ok(
            Number.isInteger(achievement.difficulty) && achievement.difficulty >= 1 && achievement.difficulty <= 5,
            `${achievement.name} has an out-of-range difficulty: ${achievement.difficulty}`
        );

        assert.ok(
            Number.isInteger(achievement.estimatedTime) && achievement.estimatedTime > 0,
            `${achievement.name} has an invalid estimatedTime: ${achievement.estimatedTime}`
        );

        assert.ok(achievement.name?.length > 0, "achievement is missing a name");
        assert.ok(achievement.description?.length > 0, `${achievement.name} is missing a description`);
        assert.ok(achievement.apiname?.length > 0, `${achievement.name} is missing an apiname`);

    }

});

test("every one of the 289 Northgard achievement name+description pairs matches the catalog data", () => {

    const officialAchievements = [
        ["7 Wonders", "Play a game where 7 different Relics are built."],
        ["A \"Small\" Delivery", "Build the Relic of Naglfar"],
        ["A Meal fit for a King", "Win by cooking the Banquet of Valhöll."],
        ["A wild Viking appears!", "Attack an enemy in Landvidi"],
        ["Aggressive Negotiations", "Win with the Clan of the Squirrel"],
        ["Aggressor", "Win with the clan of the Wolf [not in Story Mode]"],
        ["Airdropped supplies", "Leave 200 resources or more in loot pouches to be collected by your allies in a single game"],
        ["Another shrubbery!", "Clear Naströnd 5 times"],
        ["Arma-get-out", "Complete each of the bonus objectives in the first chapter of Cross of Vidar"],
        ["Bear Conqueror", "Finish a Conquest with the clan of the Bear"],
        ["Bear Hunter", "Kill 3 bears in a single game"],
        ["Bear Master", "Get 50 Victories with the Clan of the Bear [not in Story Mode]"],
        ["Berserk", "Hire the Berserker"],
        ["Bifröst Explorer", "Finish a run of Bifröst in Classic or Challenge mode."],
        ["Bifröst Survivor", "Finish a run of Bifröst in Challenge mode."],
        ["Bifröst Ultimate Explorer", "Finish a run of Bifröst in Classic or Challenge mode with each clan."],
        ["Big Fish", "Have 10 fishermen at the same time"],
        ["Bird Enthousiast", "Heal Vedrfolnir once"],
        ["Bird Lover", "Heal Vedrfolnir 10 times"],
        ["Blood Taste", "Win with the Clan of the Dragon"],
        ["Boar Conqueror", "Finish a Conquest with the clan of the Boar"],
        ["Boar Master", "Get 50 Victories with the Clan of the Boar [not in Story Mode]"],
        ["Builder", "Win with the Clan of the Horse"],
        ["Building a what?!", "Collect 10 Stones and 10 Iron in a single game without building a mine"],
        ["Call of the Wild", "Build the Relic of the Clan of the Owl"],
        ["Can I go home now ?", "Overwork the same worker 5 times."],
        ["Chapter 1 - Exodus", "Complete the first chapter of Rig's Saga"],
        ["Chapter 10 - Fimbulvinter", "Complete the tenth chapter of Rig's Saga"],
        ["Chapter 11 - Bifrost", "Complete the eleventh chapter of Rig's Saga"],
        ["Chapter 2 - Foothold", "Complete the second chapter of Rig's Saga"],
        ["Chapter 3 - Settlement", "Complete the third chapter of Rig's Saga"],
        ["Chapter 4 - Trade War", "Complete the fourth chapter of Rig's Saga"],
        ["Chapter 5 - Punitive Expedition", "Complete the fifth chapter of Rig's Saga"],
        ["Chapter 6 - Intervention", "Complete the sixth chapter of Rig's Saga"],
        ["Chapter 7 - Jötunnheim", "Complete the seventh chapter of Rig's Saga"],
        ["Chapter 8 - Contest", "Complete the eighth chapter of Rig's Saga"],
        ["Chapter 9 - Tremors", "Complete the ninth chapter of Rig's Saga"],
        ["Child of Ragnarök", "Win with the Clan of the Hounds"],
        ["Clean Slate", "Eliminate 3 different neutral factions in a single game"],
        ["Conqueror", "Complete Rig's Saga in Hard difficulty (or above)"],
        ["Conqueror Expert", "Unlock level 4 of the Legion Path"],
        ["Contact with Thor", "Colonize the Thor Wrath tile once"],
        ["Cross Roads", "Complete the second chapter of Cross of Vidar"],
        ["Cultural Assimilation", "Win a Lore Victory with the Kingdom of the Stoat, assigning your Monks only to Viking Artifacts"],
        ["Dances with wolves", "Gather 1000 food by killing wolves with the Clan of the Wolf in one game"],
        ["Day of the Tentacle", "Win with the Clan of the Kraken"],
        ["Deer Hunter", "Control 4 Hunter's Lodge at the same time"],
        ["Destruction Derby", "Destroy 4 different buildings with the Ram ability in one game."],
        ["Devious", "Win with the Clan of the Snake"],
        ["Do NOT Step on its Tail", "Build the Relic of Mask of Gullinbursti"],
        ["Do you have a moment to talk about our Lord and Savior?", "Carry a Relic into enemy territory"],
        ["Do you want to build a snowman?", "Build a snowman during the Winter Festival event"],
        ["Domination", "Finish at least 6 Conquests with different clans"],
        ["Don't kick the eagles' nest", "Blind 6 enemies or more in a single fight"],
        ["Dragon Conqueror", "Finish a Conquest with the clan of the Dragon"],
        ["Dragon Master", "Get 50 Victories with Clan of the Dragon"],
        ["Dragonslayer", "Kill the Wyvern"],
        ["Eagle Conqueror", "Finish a Conquest with the clan of the Eagle"],
        ["Eagle Master", "Achieve 50 Victories with the Clan of the Eagle"],
        ["Educated Colonization", "Spend 1000 Lore in colonization in one game"],
        ["Emperor", "Finish a Conquest in Hard difficulty"],
        ["Enter At Your Own Risk", "Build 6 defensive buildings or more in a single zone."],
        ["Everything has a price", "Build the Relic of the Clan of the Turtle"],
        ["Everything the light touches", "Control 5 forts or more"],
        ["Expansionist", "Control 15 territories"],
        ["Explorer", "Explore a ruin"],
        ["Extreme Junction", "Complete the ninth chapter of Cross of Vidar"],
        ["Faithbook", "Build the Codex Aureus"],
        ["Fenrir? More like Fen RIP", "Complete each of the bonus objectives in the tenth chapter of Cross of Vidar"],
        ["Final Cross", "Complete the tenth chapter of Cross of Vidar"],
        ["Finders keepers", "Explore a ruin or shipwreck on a zone next to an enemy territory"],
        ["For a Few More Krowns", "Have 3000+ krowns"],
        ["Foreign Legion", "Assemble an army composed of 10 different types of units or more."],
        ["Fresh Sea Air", "Win a game without colonizing any non coastal zone with the Clan of the Kraken"],
        ["Friend of the Jötnar", "Unlock the Giant's Warchief"],
        ["Gardening", "Clear Naströnd for the first time"],
        ["Gaul Trap", "Complete each of the bonus objectives in the ninth chapter of Cross of Vidar"],
        ["Goat Conqueror", "Finish a Conquest with the clan of the Goat"],
        ["Goat Master", "Get 50 Victories with the Clan of the Goat [not in Story Mode]"],
        ["Godfred of Frise", "Complete Cross of Vidar in Hard difficulty (or above)"],
        ["Grave Raider", "Explore 10 Ancient Graves"],
        ["Great Defense", "Control 5 upgraded towers lvl 2"],
        ["Great Explorer", "Explore every zone of Northgard"],
        ["Great Merchant", "Achieve a Trade Victory [not in Story Mode]"],
        ["Guardian", "Kill 5 Valkyries in a single game"],
        ["Guardian Expert", "Unlock level 4 of the Guardian Path"],
        ["Guess who's back? (everyone)", "Revive 20 or more units at once"],
        ["Hammer Time", "Build the Relic of Mjöllnir"],
        ["Hanging out with friends", "Have 6 warchiefs in one of your zones."],
        ["Hard Celtzer", "Complete each of the bonus objectives in the seventh chapter of Cross of Vidar"],
        ["High King Rank", "Achieve 500 victories with any clan [not in Story Mode]"],
        ["Hippogriff Conqueror", "Finish a Conquest with the clan of the Hippogriff"],
        ["Hippogriff Master", "Achieve 50 Victories with the Clan of the Hippogriff"],
        ["Horse Conqueror", "Finish a Conquest with the clan of the Horse"],
        ["Horse Master", "Get 50 Victories with Clan of the Horse"],
        ["Hostile takeover", "Eliminate an enemy clan or faction, then claim their main zone with one of your caravan."],
        ["Hot water", "Colonize 1 geyser tile"],
        ["Hounds Conqueror", "Finish a Conquest with the clan of the Hounds"],
        ["Hounds Master", "Achieve 50 Victories with the Clan of the Hounds"],
        ["How Do You Like it Now?!", "Attack a Wolf Den and kill a wolf with a Wolfskin in wolf form."],
        ["I came, I saw, I conquered.", "Win each one of the different battles"],
        ["I need more RAM!", "Build the Relic of the Clan of the Ox"],
        ["I saw some lights", "Colonize a zone with a Ceremonial Bonfire during the \"Ceremonial Bonfire\" event"],
        ["I See You", "Win with the Clan of the Owl"],
        ["I see you !", "Reveal an enemy Townhall with Brundr or Kaelinn"],
        ["I.O.U", "In a single realm of Bifröst, collect 1200 or more of a single resource from the shared pool."],
        ["I’m a Generous God", "Gift 1,000 resources in one game"],
        ["Idavoll Explorer", "Escape the realm of Idavoll."],
        ["If I can't have them no one can", "Eliminate 5 neutral factions after they were befriended by another clan."],
        ["Improvised Carpentry", "Win a game without ever building a Woodcutter's Lodge."],
        ["In your face", "Win a competitive event in which all clans have participated"],
        ["Iron Miner", "Mine 60 Iron in a single game"],
        ["It's a trap!", "Build the Relic of the Clan of the Lynx"],
        ["It's a Wonderful Life", "Keep your happiness over 12 for a whole year"],
        ["It's about the journey...", "Reach a +30% production bonus on a caravan."],
        ["It's just a scratch...", "Use the Cleanse ability for the first time"],
        ["Jarl Rank", "Achieve 100 victories with any clan [not in Story Mode]"],
        ["Joan’s Arc", "Complete each of the bonus objectives in the fifth chapter of Cross of Vidar"],
        ["Just a little help for my friends", "Win a game having shared all the meals you prepare with all your teammates"],
        ["Just Want to Watch the World Burn", "Build the Relic of the Clan of the Rat"],
        ["King of Northgard", "Achieve a Fame Victory [not in Story Mode]"],
        ["King Rank", "Achieve 250 victories with any clan [not in Story Mode]"],
        ["Knowledge is a Fruit", "Build the Relic of Jörmunr"],
        ["Knowledge is Power", "Gain access to the Lore Tree of 7 other clans in a single game."],
        ["Kobold Wipe Out", "Destroy a Kobold camp"],
        ["Kobolds and Friends", "Trade with the Kobolds"],
        ["Kraken Conqueror", "Finish a Conquest with the clan of the Kraken"],
        ["Kraken Master", "Achieve 50 Victories with the Clan of the Kraken"],
        ["Legendary Guardian", "Kill 10 Valkyries in a single game"],
        ["Let me borrow this...", "Steal a knowledge for the first time using Mimirsbrunn"],
        ["Let Them Be Stronger", "Build the Relic of Dainsleif & Tyrfing"],
        ["Life is Over-Rated", "Kill a Jötunn with a Draconic Jötunn"],
        ["Lion Conqueror", "Finish a Conquest with the clan of the Lion"],
        ["Lion Master", "Achieve 50 Victories with the Clan of the Lion"],
        ["Live and Let Live", "Win a game with every started neutral faction alive and not befriended by anyone"],
        ["Lord of Cinder", "Keep the Purification Pyres burning for 12 months without interruption."],
        ["Lord of Lords", "Win with the Clan of the Stoat"],
        ["Lore Seeker", "Build a Carved Stone next to the Relic of the Gods"],
        ["Lynx Conqueror", "Finish the Conquest with the clan of the Lynx"],
        ["Lynx Master", "Achieve 50 Victories with the Clan of the Lynx"],
        ["Mass purification", "Heal 8 sick units with a single Cleanse"],
        ["Megastore", "Have 10 Merchants working in the same zone."],
        ["Merchant", "Win with the clan of the Raven [not in Story Mode]"],
        ["Midas was an amateur", "Build the Altar of Volvinius"],
        ["Midgard Explorer", "Escape the realm of Midgard."],
        ["Mimirsbruh", "Steal a knowledge 5 times using Mimirsbrunn"],
        ["Monk is not dead", "Build the relic of the clan of the Lion"],
        ["Muspelheim Explorer", "Escape the realm of Muspelheim."],
        ["My Little Neutral: Friendship is Magic", "Befriend 3 different neutral factions in a single game [Not in Story Mode]"],
        ["Myr'Killer", "Destroy a Myrkalfar Camp"],
        ["Myrkalfar & Co.", "Befriend the Myrkalfar"],
        ["Namsborg", "Complete the fourth chapter of Cross of Vidar"],
        ["Natural Reserve", "Have more than 10 natural resources in your territory  in a single game."],
        ["Nature's Wonders", "Have 12 menders in your territory"],
        ["Nidavellir Explorer", "Escape the realm of Nidavellir."],
        ["Niflheim Explorer", "Escape the realm of Niflheim."],
        ["No Place Like Mine", "Win a game by mining exclusively outside your territory."],
        ["Noblesse Oblige", "Complete each of the bonus objectives in the sixth chapter of Cross of Vidar"],
        ["Norse God", "Achieve 1000 victories with any clan [not in Story Mode]"],
        ["Northern SPA", "Colonize 10 geyser tiles"],
        ["Not a poney, yet not a bird", "Win with the Clan of the Hippogriff"],
        ["Nothing personal", "Launch a regular and a Giant Mercenary raid on the same player"],
        ["Now you know how that Feels", "Attack Woodcutters with the Guardian of Realms in a single game."],
        ["Operation Neptune", "Complete the seventh chapter of Cross of Vidar"],
        ["Overcooked", "Wound a Giant boar with a Mjöllnir's Thunder"],
        ["Owl Conqueror", "Finish a Conquest with the clan of the Owl"],
        ["Owl Master", "Achieve 50 Victories with the Clan of the Owl"],
        ["Ox Conqueror", "Finish a Conquest with the clan of the Ox"],
        ["Ox Master", "Get 50 Victories with Clan of the Ox"],
        ["Paladin and the forty fiefs", "Complete the third chapter of Cross of Vidar"],
        ["Pandora's Box", "Build the Relic of the Clan of the Eagle"],
        ["Paris Syndrome", "Complete the sixth chapter of Cross of Vidar"],
        ["Perfectionist", "Finish all battles of a Conquest"],
        ["PlayWithFire", "Build the Holy Fire Relic"],
        ["Plowshares to Swords", "Turn a Farmer into a Warrior"],
        ["Poltergeist", "In Landvidi, attack an enemy with Ghost warriors"],
        ["Pope Culture", "Complete each of the bonus objectives in the third chapter of Cross of Vidar"],
        ["Power to the People", "Enter an enemy territory with an army composed of 20 Sentries or more"],
        ["Pride of the Kraken", "Build the Edda of Vor"],
        ["Proud", "Win with the clan of the Stag [not in Story Mode]"],
        ["Purge", "Kill 20 Draugar in a single game"],
        ["Ragenold of Nantes", "Complete Cross of Vidar in Normal difficulty (or above)"],
        ["Ragnarok", "Win a Ragnarok game"],
        ["Raider", "Build 3 Harbors in a single game"],
        ["Rat Conqueror", "Finish a Conquest with the clan of the Rat"],
        ["Rat Master", "Achieve 50 Victories with the Clan of the Rat"],
        ["Raven Conqueror", "Finish a Conquest with the clan of the Raven"],
        ["Raven Master", "Get 50 Victories with the Clan of the Raven [not in Story Mode]"],
        ["Recluse", "Win with the Clan of the Boar [not in Story Mode]"],
        ["Rig's brigade grabs Briga", "Complete each of the bonus objectives in the second chapter of Cross of Vidar"],
        ["Rock Smasher", "Kill 10 Rock Golems"],
        ["Rock Solid Statement", "Deal 200 damage in a single catapult shot."],
        ["Rocks are the solution", "Build the Relic of the Clan of the Hippogriff"],
        ["Rollo of Rouen", "Complete Cross of Vidar in Extreme difficulty"],
        ["Rollolo", "Complete all of the bonus objectives in every chapter of Cross of Vidar"],
        ["Scholar", "Have 6 active Runestone or Carved Stones"],
        ["Secrets of Bifrost", "Complete each of the bonus objectives of the eleventh chapter of Rig's Saga"],
        ["Secrets of Contest", "Complete each of the bonus objectives of the eighth chapter of Rig's Saga"],
        ["Secrets of Exodus", "Complete each of the bonus objectives of the first chapter of Rig's Saga"],
        ["Secrets of Fimbulvinter", "Complete each of the bonus objectives of the tenth chapter of Rig's Saga"],
        ["Secrets of Foothold", "Complete each of the bonus objectives of the second chapter of Rig's Saga"],
        ["Secrets of Intervention", "Complete each of the bonus objectives of the sixth chapter of Rig's Saga"],
        ["Secrets of Jötunnheim", "Complete each of the bonus objectives of the seventh chapter of Rig's Saga"],
        ["Secrets of Punitive Expedition", "Complete each of the bonus objectives of the fifth chapter of Rig's Saga"],
        ["Secrets of Rig's Saga", "Complete all the bonus objectives in every chapters of Rig's Saga"],
        ["Secrets of Settlement", "Complete each of the bonus objectives of the third chapter of Rig's Saga"],
        ["Secrets of Trade War", "Complete each of the bonus objectives of the fourth chapter of Rig's Saga"],
        ["Secrets of Tremors", "Complete each of the bonus objectives of the ninth chapter of Rig's Saga"],
        ["Serf's Up", "Complete each of the bonus objectives in the fourth chapter of Cross of Vidar"],
        ["Sheep Master", "Have 8 sheeps in Sheepfolds"],
        ["Slaughterhouse", "Slaughter 8 Sheep in a single game"],
        ["Small but sturdy", "Win a game, having a territory counting 4 zones or less."],
        ["Snake Conqueror", "Finish a Conquest with the clan of the Snake"],
        ["Snake Master", "Get 50 Victories with Clan of the Snake"],
        ["Solid as a Rock", "Win with the Clan of the Turtle"],
        ["Sovereign", "Finish a Conquest in Extreme difficulty"],
        ["Spread Your Wings", "Win with the Clan of the Eagle"],
        ["Spygame", "Send a scout to spy on 3 different clan's Townhall  in a single game"],
        ["Squalid Living", "Build a House in a swamp"],
        ["Squirrel Conqueror", "Finish a Conquest with the clan of the Squirrel"],
        ["Squirrel Master", "Achieve 50 Victories with the Clan of the Squirrel"],
        ["Stag Conqueror", "Finish a Conquest with the clan of the Stag"],
        ["Stag Master", "Get 50 Victories with Clan of the Stag [not in Story Mode]"],
        ["Stalwart", "Win with the clan of the Bear [not in Story Mode]"],
        ["Stoat Conqueror", "Finish a Conquest with the clan of the Stoat"],
        ["Stoat Master", "Achieve 50 Victories with the Clan of the Stoat"],
        ["Stone Miner", "Mine 150 Stone in a single game"],
        ["Storyteller", "Have 5 active Skalds at the same time"],
        ["Survivor", "Win with the clan of the Goat [not in Story Mode]"],
        ["Tactician Expert", "Unlock level 4 of the Leadership Path"],
        ["Tear of the Earth", "Use Scorched Earth on an enemy tile"],
        ["Thane Rank", "Achieve 50 victories with any clan [not in Story Mode]"],
        ["That still only counts as one", "Kill 3 enemy Dwarven Operatives in a single game"],
        ["The Benefits of Dark Magic", "Build the Relic of Skull of Hrungnir"],
        ["The Blade of Orléans", "Complete the fifth chapter of Cross of Vidar"],
        ["The cat's out of the bag", "Win with the Clan of the Lynx"],
        ["The End", "Complete Rig's Saga in Normal difficulty (or above)"],
        ["The Explorer", "Have the whole map explored before the year 803 in a Medium or Large map"],
        ["The Great Cauldron", "Build the Relic of Eldhrumnir"],
        ["The Last Resort", "Release Oskoreia at the highest level of threat"],
        ["The Lion Queen", "Win with the Clan of the Lion"],
        ["The little shop of Gifts", "Give at least 6 Knowledges to other clans in a single game."],
        ["The Long Game", "Reach the year 810"],
        ["The Melting Stones", "Completely mine 5 Molten Rocks"],
        ["The Mystic", "Win by taking control of Yggdrasil [not in Story Mode]"],
        ["The Old Guard", "Win by Unleashing the Realms' power."],
        ["The Poacher Game", "Buy 500 Hunting Trophies in one game"],
        ["The Protector", "Win by guarding the Gate of Helheim [not in Story Mode]"],
        ["The Rat King", "Win with the Clan of the Rat"],
        ["The Root of our Clan", "Build the Relic of the Clan of the Squirrel"],
        ["The Smith", "Win by forging the Sword of Odin [not in Story Mode]"],
        ["The Sword in the stone", "Complete the eigth chapter of Cross of Vidar"],
        ["The Taste of Blood", "Build the Relic of Horn of Managarm"],
        ["The Tortoise and the heir", "Complete each of the bonus objectives in the eigth chapter of Cross of Vidar"],
        ["The Twelve Peers", "Raise an army comprised of at least 12 paladins"],
        ["The Value of Friendship", "Gains more than 500 Kröwns selling relationship."],
        ["The Wall", "Have 7 Defense Towers in your territory"],
        ["The Wise", "Achieve a Wisdom Victory [not in Story Mode]"],
        ["The Wonder Collector", "Capture an enemy Relic"],
        ["This is Mine Now", "Build the Relic of Hlidskjalf"],
        ["This is not Over Compensation", "Build the Relic of Scabbard of Gram"],
        ["This isn't even my final form!", "Find 6 Legendary items in one game"],
        ["Thor Fanatic", "Colonize the Thor Wrath Tile 10 times"],
        ["Through Helheim and back", "Complete Rig's Saga in Extreme difficulty"],
        ["Toughskin Siblings", "Save a Boarskin from sacrificing themself using Blood Sacrifice, with the Death Deceiver ability of a Bearskin."],
        ["Trader", "Have 3 active trade route in a single game"],
        ["Try Not to Break This One", "Build the Relic of Gefjun's Jar"],
        ["Turtle Conqueror", "Finish a Conquest with the clan of the Turtle"],
        ["Turtle Master", "Achieve 50 Victories with the Clan of the Turtle"],
        ["Twilight of the Gods", "Complete the first chapter of Cross of Vidar"],
        ["Unleash the Beast", "Build the Relic of the Clan of the Hounds"],
        ["UNLIMITED FLOWER!", "Control a territory of at least 10 Eldritch zones."],
        ["Unstoppable Force", "Win with the Clan of the Ox"],
        ["Uprising", "Endure a Thrall uprising"],
        ["Valhalla's Vanguard", "Have a Varangian guard benefit from all military forges."],
        ["Victorious Squid", "Witness a boat sunk by the mighty Kraken"],
        ["Warchief Rank", "Achieve 25 victories with any clan [not in Story Mode]"],
        ["Warlord", "Achieve a Domination Victory [not in Story Mode]"],
        ["Warrior Rank", "Achieve 10 victories with any clan [not in Story Mode]"],
        ["What is better than 1 Giant Champion ?", "Unlock 2 Giants' Champion in 1 game"],
        ["Where is Your God Now?", "Forge Mjolnir as the Kingdom of the Stoat"],
        ["Who needs houses?", "Win a game with the clan of the Ox without reaching max population"],
        ["Why so Serious", "Build the Relic of Gungnir"],
        ["Wolf Conqueror", "Finish a Conquest with the clan of the Wolf"],
        ["Wolf Hunter", "Kill 20 Wolves in a single game"],
        ["Wolf Master", "Get 50 Victories with the Clan of the Wolf [not in Story Mode]"],
        ["Wonder Builder", "Build 2 relics in the same game"],
        ["You Will Fight For Me", "Enslave a Jotunn, a Kobold or a Myrkalf"],
        ["You're Welcome!", "Collect and share a Levy providing at least 3 different bonuses at their maximum value"],
    ];

    assert.strictEqual(officialAchievements.length, 289, "sanity check on this test's own reference list");

    const dataPairs = game.achievements
        .map(a => [a.name, a.description])
        .sort((a, b) => a[0].localeCompare(b[0]));

    assert.deepStrictEqual(dataPairs, [...officialAchievements].sort((a, b) => a[0].localeCompare(b[0])));

});
