import { test } from "node:test";
import assert from "node:assert";

import { getPlannerData } from "../utils/plannerCatalog.js";

// backend/catalog/games/team-fortress-2.json - 520 real achievements sourced
// from a live ISteamUserStats/GetSchemaForGame/v2 response for appid
// 440 (fetched through this app's own services/steamApi.js).
// This game has no hidden achievements: all 520 ship a real, official
// Steam description, quoted verbatim below.
// difficulty/estimatedTime/missable remain curatorial judgments, the same
// convention as every other planner difficulty/time field in this catalog.
const game = getPlannerData("team-fortress-2");

test("getPlannerData('team-fortress-2') returns real planner data with 520 curated achievements", () => {

    assert.ok(game, "expected real planner data for team-fortress-2");
    assert.ok(Array.isArray(game.achievements));
    assert.strictEqual(game.achievements.length, 520);

});

test("every Team Fortress 2 achievement has a unique id from 1 to 520 and a unique apiname", () => {

    const ids = game.achievements.map(a => a.id);
    const apinames = game.achievements.map(a => a.apiname);

    assert.deepStrictEqual([...ids].sort((a, b) => a - b), Array.from({ length: 520 }, (_, i) => i + 1));
    assert.strictEqual(new Set(ids).size, 520);
    assert.strictEqual(new Set(apinames).size, 520);

});

test("every Team Fortress 2 achievement has a valid difficulty (1-5), a positive estimatedTime, and non-empty name/description", () => {

    for (const achievement of game.achievements) {

        assert.ok(
            Number.isInteger(achievement.difficulty) && achievement.difficulty >= 1 && achievement.difficulty <= 5,
            `${achievement.name} has an out-of-range difficulty: ${achievement.difficulty}`
        );

        assert.ok(
            Number.isInteger(achievement.estimatedTime) && achievement.estimatedTime > 0,
            `${achievement.name} has an invalid estimatedTime: ${achievement.estimatedTime}`
        );

        assert.ok(achievement.name?.length > 0, "achievement is missing a name");
        assert.ok(achievement.description?.length > 0, `${achievement.name} is missing a description`);
        assert.ok(achievement.apiname?.length > 0, `${achievement.name} is missing an apiname`);

    }

});

test("every one of the 520 Team Fortress 2 achievement name+description pairs matches the live GetSchemaForGame response", () => {

    const officialAchievements = [
        [".executioner", "In a single wave, kill 15 bomb-carrying robots in a row before they level up."],
        ["(Not So) Lonely Are the Brave", "Keep a Heavy healed with your dispenser while he gains 5 kills."],
        ["0wn the Means of Production", "Remove 20 stickybombs by killing the Demomen who produced them."],
        ["A Bygone Century", "Pit 100 robots in Rottenburg."],
        ["A Cut Above", "Kill a gun-wielding Spy with your knife."],
        ["A Fresh Pair of Eyes", "Dominate a player using the Pyrovision Goggles and earn your own pair!"],
        ["A Lovely Vacation Spot", "Get to Skull Island and claim your reward!"],
        ["A Year to Remember", "Get 2004 lifetime kills."],
        ["Agent Provocateur", "Backstab your Steam Community friends 10 times."],
        ["Ain't Got Time to Bleed", "Kill 3 players with the Equalizer in a single life without being healed."],
        ["Air Raid", "Kill 3 players during the same parachute deploy."],
        ["Arsonist", "Destroy 50 Engineer buildings."],
        ["Artful Dodger", "Dodge 1000 damage in a single life using your Bonk! Atomic Punch."],
        ["Attack o' Lantern", "Cause the deaths of 5 players by exploding nearby pumpkin bombs."],
        ["Attention Getter", "Ignite 100 enemies with the flare gun."],
        ["Australian Rules", "Dominate an enemy Sniper."],
        ["Autoclave", "Assist in burning 5 enemies with a single ÜberCharge on a Pyro."],
        ["Autopsy Report", "Provide an enemy with a freezecam shot of you taunting above their ragdoll."],
        ["Back 2 Back", "While using the Back Scatter, kill a Heavy/Medic pair within 20 seconds of each other."],
        ["Back in Business", "While using the Back Scatter, kill 20 spies from behind."],
        ["Backdraft Dodger", "Kill a Pyro who has airblasted one of your rockets in the last 10 seconds."],
        ["Balance of Power", "Win a round in which the enemy team has attempted to capture your final control point."],
        ["Balls-E", "Destroy the tank during the final seconds of the bomb being deployed."],
        ["Bank On It", "As a Sniper collect $500 in a mission without running over the currency packs."],
        ["Banner of Brothers", "Buff 5 Steam friends at once with the Buff Banner."],
        ["Baptism by Fire", "Force 10 burning enemies to jump into water."],
        ["BarbeQueQ", "Cause a dominated player to leave the server."],
        ["Batter Up", "Perform 1000 double jumps."],
        ["Batting the Doctor", "Kill a Medic that is ready to deploy an ÜberCharge."],
        ["Battle Rustler", "Teleport 100 team members into battle."],
        ["Be Efficient", "Get 3 kills with the Sniper Rifle without missing a shot."],
        ["Be Polite", "Provide an enemy with a freezecam shot of you doffing your hat."],
        ["Beanball", "Stun a Scout with their own ball."],
        ["Beat Me Up, Scotty", "Use a critical swing with the Eyelander to kill 5 enemy players."],
        ["Beaux and Arrows", "Kill a Heavy & Medic pair with the bow."],
        ["Bedside Manner", "Be healing a teammate as he achieves an achievement of his own."],
        ["Belittled Beleaguer", "Kill an opposing player that has your intelligence while holding theirs."],
        ["Best Case Scenario", "Kill 6 enemies carrying the Australium during the same round."],
        ["Best Little Slaughterhouse in Texas", "Rack up 5000 kills with your sentry guns."],
        ["BFF²", "Have 2 BEST FRIENDS at the same time."],
        ["Big Pharma", "Assist a Heavy in killing 10 enemies, where neither of you die."],
        ["Blast Assist", "Assist in exploding 5 enemies with a single ÜberCharge on a Soldier."],
        ["Blind Fire", "Destroy an Engineer building that you can't see with a direct hit from your Grenade Launcher."],
        ["Block the Plate", "Block 50 point captures."],
        ["Blockbuster", "Achieve 100,000 YouTube™ views for your movie."],
        ["Bloody Merry", "Provide an enemy player with a freezecam of your smiling face."],
        ["Blunt Trauma", "Assist in punching 2 enemies with a single ÜberCharge on a Heavy."],
        ["Bomb Squaddie", "Destroy 10 stickybombs with the shotgun in a single life."],
        ["Bombs Away!", "Kill 3 people with the Air Strike during a single rocket jump."],
        ["Borscht Belt", "Kill 10 Heavies with The K.G.B."],
        ["Bot-Buster", "Kill 5 robots in a single explosion from detonating a sentry buster."],
        ["Brainspotting", "Decapitate 50 enemy players."],
        ["Bravehurt", "Kill 25 players defending a capture point or cart."],
        ["Breaking Morant", "Kill 10 Snipers with a sentry gun under control of your Wrangler."],
        ["Brotherhood of Steel", "Complete a mission with 5 people on your Friends List."],
        ["Brothers in Harms", "Kill 10 enemies while assisting or being assisted by another Soldier."],
        ["Brushback", "Stun 50 enemies while they are capturing a point or pushing the cart."],
        ["Building Block", "Have a sentry shielded by the Wrangler absorb 500 damage without being destroyed."],
        ["Built to Last", "Help a single building tank over 2000 damage without being destroyed."],
        ["Burn Notice", "Survive 30 seconds after being ignited while cloaked."],
        ["Burn Ward", "Ignite 3 Medics that are ready to deploy an ÜberCharge."],
        ["Caber Toss", "Bounce an enemy into the air and kill them before they land."],
        ["Camp Fire", "Kill 3 enemies in a row, all within the same area."],
        ["Candy Coroner", "Collect 20 Halloween pumpkins from dead players to unlock a hat."],
        ["Cap Trap", "Kill an enemy who is capturing a control point with a critical hit."],
        ["Cap-ogee", "Win a round with at least 5 teammates on the elevator."],
        ["Carnival of Carnage: Arms Reduction", "Kill 15 enemies while under the effect of Merasmus's melee-only curse."],
        ["Carnival of Carnage: Bumper Crop", "Kill 30 enemies by bumping their bumper cars off the tracks."],
        ["Carnival of Carnage: Bumper to Bumper to Bumper", "Win each of the 3 bumper car games to earn a bonus Halloween Gift Cauldron."],
        ["Carnival of Carnage: Hat Trick", "Score 3 goals in bumper car soccer."],
        ["Carnival of Carnage: ReinKartnation", "Respawn 30 ghost teammates during bumper car games."],
        ["Carnival of Carnage: Step Right Up", "Earn 4 of the Carnival of Carnage achievements."],
        ["Carnival of Carnage: Up All Night To Get Ducky", "Collect 250 ducks."],
        ["Caught Napping", "Kill 50 enemies from behind with the Force-A-Nature."],
        ["Chain Reaction", "Get 3 kills within 6 seconds using the Demoman charge."],
        ["Chief of Staff", "Accumulate 1 million total heal points."],
        ["Chippin' In", "As a team, pit 10 robots in a single wave in Mannhattan."],
        ["Circle the Wagons", "Repair 50,000 damage to friendly buildings constructed by other players."],
        ["Claim Jumper", "Capture a control point within 12 seconds after exiting a teleporter."],
        ["Class Struggle", "Work with a friendly Medic to kill an enemy Heavy & Medic pair."],
        ["Classassin", "Get one or more kills as all nine classes in one round."],
        ["Clearcutter", "Kill 6 people with your axe in one life."],
        ["Clockwork Carnage", "Destroy two tanks within 5 seconds of each other."],
        ["Clockwork Conqueror", "Destroy a tank within 20 seconds of its arrival."],
        ["Closer", "Destroy 3 teleporter entrances."],
        ["Combined Fire", "Use your shotgun to finish off 20 players you've ignited."],
        ["Come in from the Cold", "Get a Revenge kill with a backstab."],
        ["Communist Mani-Fisto", "Kill an enemy with a critical punch."],
        ["Conga Line", "Do the Conga with 10 or more players at the same time."],
        ["Consolation Prize", "Get backstabbed 50 times."],
        ["Constructus Interruptus", "Kill an Engineer who is working on a sentry gun."],
        ["Consultation", "Assist a fellow Medic in killing 3 enemies in a single life."],
        ["Controlled Burn", "Ignite 50 enemies capturing one of your control points."],
        ["Cooking the Books", "Ignite 5 enemies carrying your intelligence."],
        ["Costume Contest", "Kill a Spy disguised as your current class."],
        ["Counter Espionage", "Backstab a disguised Spy."],
        ["Crasher Crusher", "Play an advanced wave in Rottenburg without the bomb entering the town."],
        ["Crime and Punishment", "Kill 10 enemies carrying your intelligence."],
        ["Crock Block", "Survive a direct hit from a critical rocket."],
        ["Crockets Are Such B.S.", "Shoot two non-boosted crit rockets in a row."],
        ["Cry Some Moor!", "Destroy 50 buildings."],
        ["Ctrl + Assault + Delete", "Destroy a sentry buster before it reaches its target."],
        ["Dance Dance Immolation", "Kill 3 enemies while they're taunting."],
        ["Dazed and Defused", "Stun 50 robots while upgraded with rocket specialist."],
        ["De-sentry-lized", "Destroy 3 Engineer sentry guns."],
        ["Dead Heat", "Kill an enemy in the same second that he kills you."],
        ["Dead Heat", "Play through a back-and-forth battle for 15 control point captures."],
        ["Dead Reckoning", "Kill an enemy with an arrow while you're dead."],
        ["Death from Above", "Rocket jump and kill 2 enemies before you land."],
        ["Death from Below", "Kill 10 opponents who are airborne with the Direct Hit."],
        ["Death Metal", "Pick up 10,000 waste metal from pieces of destroyed buildings."],
        ["Deep Undercover", "While using the Cloak and Dagger, kill the same enemy 3 times, all within the same area in a single life."],
        ["Demoman Milestone 1", "Achieve 5 of the achievements in the Demoman pack."],
        ["Demoman Milestone 2", "Achieve 11 of the achievements in the Demoman pack."],
        ["Demoman Milestone 3", "Achieve 17 of the achievements in the Demoman pack."],
        ["Deputized", "Get 10 assists with another Engineer where a sentry gun was involved in the kill."],
        ["Deus Ex Machina", "Defeat a wave in an advanced difficulty mission without dying once."],
        ["Die Another Way", "Kill a Sniper after your backstab breaks his Razorback."],
        ["Diplomacy", "Kill 50 enemies with the Ambassador."],
        ["Dive Into a Good Book", "Get to Loot Island and claim your reward!"],
        ["Division of Labor", "Kill 10 enemies with a Medic assisting you, where neither of you die."],
        ["Do Androids Dream?", "As a Scout, use the Sandman to mark 15 robots for death in a single wave."],
        ["Doc Holiday", "Have a dispenser heal 3 teammates at the same time."],
        ["Doc, Stock, and Barrel", "Repair a sentry gun under fire while being healed by a Medic."],
        ["Doctor Assisted Homicide", "Assist in killing 20 nemeses."],
        ["Doctoring the Ball", "Kill 3 enemies while under the effects of a Medic's ÜberCharge."],
        ["Dodgers 1, Giants 0", "Kill an enemy Heavy and take his Sandvich."],
        ["Does It Hurt When I Do This?", "Kill 50 Scouts with your syringe gun."],
        ["Dogfight", "Kill a parachuting player while parachuting."],
        ["Dominator", "Get 3 dominations in a single life."],
        ["Don't Touch Sandvich", "Kill 50 Scouts using Natascha."],
        ["Doomsday Milestone", "Achieve 7 of the achievements in the Doomsday pack."],
        ["Double Blind Trial", "Deploy an ÜberCharge within 8 seconds of a nearby enemy Medic deploying his."],
        ["Double Mauled Scotch", "Kill 2 people in a single sticky jump."],
        ["Dr. Nooooo", "Backstab a Medic that is ready to deploy an ÜberCharge."],
        ["Dropped Dead", "Kill a Scout in midair with your Sniper Rifle or the Huntsman."],
        ["Drugstore Cowboy", "Have dispensers you created dispense a combined amount of 100,000 health over your career."],
        ["Duty Bound", "While rocket jumping kill an enemy with the Equalizer before you land or just after landing."],
        ["Dynasty", "Win 20 games."],
        ["Eagle Eye", "While using The Classic, kill a rocket/grenade jumping enemy in midair with a full charge, no-scope headshot."],
        ["Emergency Brake", "Kill a charging Demoman."],
        ["Enemy at the Gate", "Kill an opponent within the first second of a round."],
        ["Engine Block", "Prevent the bomb from ever reaching an alarm zone during the final wave of an advanced difficulty mission."],
        ["Engineer Milestone 1", "Achieve 5 of the achievements in the Engineer pack."],
        ["Engineer Milestone 2", "Achieve 11 of the achievements in the Engineer pack."],
        ["Engineer Milestone 3", "Achieve 17 of the achievements in the Engineer pack."],
        ["Engineer to Eternity", "Kill an Engineer as he repairs his sentry gun while it's under enemy fire."],
        ["Escape Ferocity", "Kill an enemy who has damaged the Australium carrier in the last 3 seconds."],
        ["Escape the Heat", "Jump into a pool of refreshing water while on fire."],
        ["Factory Worker", "Kill 20 enemies while being recharged by a dispenser."],
        ["Failure to Launch", "Kill 3 players riding the elevator within 10 seconds."],
        ["Fall Classic", "Cause an environmental death or suicide using the Force-A-Nature's knockback."],
        ["Family Practice", "ÜberCharge 5 of your Steam Community Friends."],
        ["Fast Cache", "Pick up a credit pile that is about to expire."],
        ["Fast Fingers", "Backstab a Scout that is using the Back Scatter."],
        ["Fire and Forget", "Kill 15 players while you're dead."],
        ["Fire Chief", "Kill 1000 enemies."],
        ["Firefighter", "Kill 500 enemies."],
        ["Firewall", "Ignite 5 Spies who have a sapper on a friendly building."],
        ["Firewatch", "Ignite 10 Snipers while they are zoomed in."],
        ["First Blood", "Get the first kill in an Arena or Competitive match."],
        ["First Blood, Part 2", "Kill 5 enemies with the First Blood crit buff in an Arena match."],
        ["First Do No Harm", "Play a full round without killing any enemies, and score the highest on a team of 6 or more players."],
        ["Fistful of Sappers", "Destroy 25 sappers on buildings built by other team members."],
        ["Five Second Plan", "Kill an enemy in the first 5 seconds after you exit a teleporter."],
        ["Five the Fast Way", "Capture the final control point within five seconds of your team capturing the previous control point."],
        ["Flamethrower", "Set five enemies on fire in 30 seconds."],
        ["Flight Cancelled", "Kill 25 parachuting players with a critical headshot."],
        ["Flight Control", "Kill a parachuting player while parachuting."],
        ["Flight Crew", "Play in a game with five or more players from your Friends list."],
        ["Flip-Kabob", "Ignite a player that is being flipped by someone using the Flippin' Awesome taunt."],
        ["For Whom the Shell Trolls", "Bounce an opponent into the air with a rocket and then kill them with the shotgun before they land."],
        ["For Your Eyes Only", "Provide an enemy with a freezecam shot of you flicking a cigarette onto their corpse."],
        ["Foul Territory", "Cause an environmental death by stunning or slowing an enemy."],
        ["Foundry Force Five", "Play in a game with five or more players from your Friends list."],
        ["Foundry Milestone", "Achieve 7 of the achievements in the Foundry pack."],
        ["Frags of our Fathers", "Gib 1000 people."],
        ["Frags to Riches", "Earn all credit bonuses in an advanced difficulty mission."],
        ["Freezer Burn", "Provide enemies with freezecam shots of each of your taunts."],
        ["Friendship is Golden", "Extinguish a burning teammate with your Jarate."],
        ["Frontier Justice", "Have your sentry kill the enemy that just killed you within 10 seconds."],
        ["Full Spectrum Warrior", "Ignite 3 enemy players using your Rainblower taunt."],
        ["FYI I am A Medic", "Use your bonesaw to kill a spy who has been calling for 'Medic!'."],
        ["FYI I am a Spy", "Backstab a Medic who has healed you in the last 5 seconds."],
        ["Geneva Contravention", "Kill 3 defenseless players after a single match has ended."],
        ["German Engineering", "Use a canteen charged with 'ÜberCharge' to destroy 15 robots."],
        ["Get Along!", "Manage to get to and then remove a sapper placed on your building while you were several meters away."],
        ["Get Off My Lawn", "Play an advanced mission without losing a single gate in Mannhattan."],
        ["Ghastly Gibus Grab", "Dominate a player wearing any achievement Gibus hat to earn your own Ghostly Gibus."],
        ["Ghost in the Machine", "Use a canteen charged with 'Teleport to Spawn' and then kill the bomb carrier within 5 seconds."],
        ["Gift Grab", "Collect three gifts dropped by opponents."],
        ["Glasg0wned", "Kill 25 Scouts and Pyros with the Grenade Launcher."],
        ["Gore-a! Gore-a! Gore-a!", "Provide the enemy with a freezecam of you taunting over 3 of their body parts."],
        ["Gored!", "Collect the Horseless Headless Horsemann's Haunted Metal."],
        ["Gorky Parked", "Kill 25 enemies while you're standing on a control point you own."],
        ["Got A Light?", "Ignite an enemy Spy while he's flicking a cigarette."],
        ["Grand Rounds", "Heal 200 teammates after they've called for 'Medic!'."],
        ["Grey Matter", "Get 25 headshots as a Sniper."],
        ["Group Health", "Work with 2 other Medics to deploy 3 simultaneous ÜberCharges."],
        ["Gun Down", "Destroy an active sentry gun using your pistol."],
        ["Guns of the Navar0wned", "Kill 5 Engineer sentries while you are standing outside of their range."],
        ["Hack of All Trades", "Play an entire mission as a single class, and do this for every class."],
        ["Hamburger Hill", "Defend a cap point 30 times."],
        ["Hard Reset", "As a Pyro, reset the bomb 3 times in a single wave."],
        ["Hard to Kill", "Get five kills in a row without dying."],
        ["Hardcore", "Accumulate 1000 total kills."],
        ["Have a Plan", "Capture the flag in CTF."],
        ["He Who Celt It", "Use the Sticky Launcher to kill an enemy player via environmental damage."],
        ["Head of the Class", "Play a complete round with every class."],
        ["Head-On Collision", "Kill a charging Demoman while charging."],
        ["Heavy Industry", "Fire $200,000 worth of minigun rounds in a single life."],
        ["Heavy Mettle", "During a wave, use rage as a Heavy to push a robot about to deliver the bomb."],
        ["Heavy Milestone 1", "Achieve 10 of the achievements in the Heavy pack."],
        ["Heavy Milestone 2", "Achieve 16 of the achievements in the Heavy pack."],
        ["Heavy Milestone 3", "Achieve 22 of the achievements in the Heavy pack."],
        ["Helltower: Competitive Spirit", "Win 142 rounds"],
        ["Helltower: Hat Out of Hell", "Get the loot from Skull Island in Hell"],
        ["Helltower: Hell on Wheels", "Send Redmond/Blutarch to Hell 10 times"],
        ["Helltower: Hell's Spells", "Get and use a rare spell"],
        ["Helltower: Mine Games", "Perform 17 environmental kills in Hell"],
        ["Helltower: Skeleton Coup", "Kill 99 skeletons"],
        ["Helltower: Spelling Spree", "Use spells to kill 25 players"],
        ["Helltower: The Mann-tastic Four", "Earn 4 of the Helltower achievements"],
        ["High Value Target", "Backstab an enemy who is dominating 3 or more of your teammates."],
        ["Highland Fling", "Sticky jump a really long way..."],
        ["Hipshot", "While using The Classic, kill 10 enemies with a full charge, no-scope headshot."],
        ["Home Movie", "Achieve 100 YouTube™ views for your movie."],
        ["Honky Tonk Man", "Smash an enemy player's head in with your guitar."],
        ["Hot on Your Heels", "Kill 50 enemies with your flamethrower, from behind."],
        ["Hot Potato", "Reflect 100 projectiles with your compressed air blast."],
        ["Hotshot", "Kill a Soldier with a reflected critical rocket."],
        ["House Call", "Join a game that one of your friends is in and then deploy an ÜberCharge on him."],
        ["How the Pests Was Gunned", "Destroy 50 enemy stickybombs lying in range of friendly buildings."],
        ["Hypocritical Oath", "Kill an enemy Spy that you have been healing."],
        ["I Fry", "Ignite 10 disguised Spies."],
        ["I'm Bat Man", "Survive 500 damage in one life."],
        ["Icing on the Cake", "Get 20 kills on players that you're dominating."],
        ["Identity Theft", "Backstab the enemy that you're currently disguised as."],
        ["If You Build It", "Destroy 3 enemy buildings while they are still under construction."],
        ["If You Build It, They Will Die", "Haul a level 3 sentry gun into a position where it achieves a kill shortly after being redeployed."],
        ["Impenetrable Defense", "Successfully defend Dustbowl without giving up a capture."],
        ["Impossible Defense", "Successfully defend Gravel Pit without giving up a capture."],
        ["Indie Film Sensation", "Achieve 10,000 YouTube™ views for your movie."],
        ["Infernal Medicine", "Extinguish 100 burning teammates."],
        ["Insurance Fraud", "Kill an enemy while you're being healed by an enemy Medic."],
        ["Intern", "Accumulate 7000 heal points in a single life."],
        ["Iron Kurtain", "Take 1000 points of damage in a single life."],
        ["Is It Safe?", "Backstab 50 enemies who are capturing control points."],
        ["Jackpot!", "Win 10 rounds playing PASS Time."],
        ["Jarate Chop", "Jarate and then kill 3 enemies with your Kukri."],
        ["Jarring Transition", "Use Jarate to reveal a cloaked Spy."],
        ["Joint Operation", "Sap an enemy sentry gun within 3 seconds of a teammate sapping another."],
        ["Jumper Stumper", "Kill a rocket or grenade-jumping enemy in midair with your Sniper Rifle or the Huntsman."],
        ["Kill Everyone You Meet", "Kill 1000 enemies."],
        ["Kilt in Action", "Kill 500 enemy Soldiers"],
        ["Kollectivization", "Get 1000 assists."],
        ["Konspicuous Konsumption", "Eat 100 sandviches."],
        ["Kook the Spook", "Kill 10 Spies with your Kukri."],
        ["Krazy Ivan", "Kill 50 enemies while both you and your victim are underwater."],
        ["Kritical Terror", "Use a canteen charged with 'Crit Boost' to destroy a giant robot."],
        ["Laddy Macdeth", "Kill 50 enemies with direct hits from the Grenade Launcher."],
        ["Land Grab", "Help a teammate construct a building."],
        ["Left 4 Heads", "Decapitate 4 players with only 10 seconds between each kill."],
        ["Lenin A Hand", "Help 5 teammates get revenge on their nemeses."],
        ["Lift-offed", "Push a player into the rocket's exhaust path at the end of the round."],
        ["Lightning Offense", "Win Well in 5 minutes or less."],
        ["Local Cinema Star", "Achieve 1000 YouTube™ views for your movie."],
        ["Loch Ness Bombster", "Kill an enemy player with stickybombs within 5 seconds of them teleporting."],
        ["Log Jammin", "Kill 15 enemies in the rafters above the central capture point."],
        ["Lumberjack", "Kill 3 people with your axe in one life."],
        ["Makin' Bacon", "Kill 50 Heavies with your flamethrower."],
        ["Marxman", "Kill 10 enemies in mid-air with the minigun."],
        ["Masked Mann", "Collect a Soul Gargoyle in Mann Manor."],
        ["Mass Hysteria", "Have 6 teammates using Pyrovision at the same time."],
        ["Master of Disguise", "Trick an opposing Medic into healing you."],
        ["Maximum Performance", "Max out all resistances on a single class."],
        ["Maximum Potential", "Collect enough casualties to get the max clip for the Air Strike."],
        ["May I Cut In, Too?", "Melee kill 10 players while they are doing the Square Dance taunt."],
        ["May I Cut In?", "Backstab an enemy and the Medic healing him within 10 seconds of each other."],
        ["Medals of Honor", "Finish a round as an MVP on a team of 6 or more players 10 times."],
        ["Medic Milestone 1", "Achieve 10 of the achievements in the Medic pack."],
        ["Medic Milestone 2", "Achieve 16 of the achievements in the Medic pack."],
        ["Medic Milestone 3", "Achieve 22 of the achievements in the Medic pack."],
        ["Medical Breakthrough", "Assist in destroying 5 enemy Engineer buildings with a single ÜberCharge on a Demoman."],
        ["Medical Intervention", "Save a falling teammate from dying on impact."],
        ["Metal Massacre", "Destroy 1,000,000 robots."],
        ["Midwife Crisis", "Heal an Engineer as he repairs his sentry gun while it's under enemy fire."],
        ["Mission Control", "Pick up the Australium from its home position and capture it without dropping it."],
        ["Moon Shot", "Stun an enemy for the maximum possible duration by hitting them with a long-range ball."],
        ["Mutually Air-Sured-Destruction", "While rocket jumping, use a rocket to kill a rocket jumping enemy who also kills you with a rocket."],
        ["Mutually Assured Destruction", "Kill an enemy sniper with a rocket after he kills you."],
        ["My Brilliant Career", "Top the scoreboard 10 times on teams of 6 or more players."],
        ["Near Death Experience", "Kill 20 enemies with your Equalizer while you have less than 25 health."],
        ["Negative Charge", "Kill 5 Medics that are ready to deploy an ÜberCharge in a wave."],
        ["Nemesis", "Get five revenge kills."],
        ["Next of Kindling", "Ignite an enemy, and the Medic healing him."],
        ["No Man's Land", "Use a sentry gun to kill 25 enemy players that are capturing a point."],
        ["No-Hitter", "Steal and then capture the enemy intelligence without firing a shot."],
        ["Nose Dive", "Kill 10 parachuting players."],
        ["Not a Crazed Gunman, Dad", "In a single life, kill 3 enemies while they are achieving an objective."],
        ["Now Legal To Eat", "Ooohh Ooh Ahh Ahhhh! ...in Mannhattan"],
        ["Number One Assistant", "Score 5 assists with the Jarate in a single round."],
        ["OMGWTFBBQ", "Kill an enemy with a taunt."],
        ["On Her Majesty's Secret Surface", "Start capping a capture point within a second of it becoming available."],
        ["On The Rocks", "Lose at Rock, Paper, Scissors 3 times in a row with Rock."],
        ["Operation High Dive", "Parachute 19.47 miles."],
        ["Optical Defusion", "Kill MONOCULUS!"],
        ["Out of the Park", "Bat an enemy 25 meters."],
        ["Out, Damned Scot!", "Kill 500 enemy Demomen"],
        ["Palace-Aid", "Kill a tank before it crashes through the barrier in Rottenburg."],
        ["Parting Shot", "Headshot an enemy player the moment his invulnerability wears off."],
        ["Party Crasher", "Kill 3 players who are doing the Conga within 5 seconds."],
        ["Party Loyalty", "Kill 50 enemies within 3 seconds of them attacking your Medic."],
        ["Patent Protection", "Destroy an enemy Engineer's sentry gun with a sentry under control of your Wrangler."],
        ["Peer Review", "Kill 10 Medics with your bone saw."],
        ["Permanent Revolution", "Kill 5 enemies without spinning down your gun."],
        ["Photostroika", "Provide an enemy with a freezecam shot of you taunting while invulnerable."],
        ["Pilot Light", "Ignite a rocket-jumping Soldier while he's in midair."],
        ["Pincushion", "Hit an enemy with 3 arrows, without killing them."],
        ["Pipebagger", "Kill at least three players with a single detonation of stickybombs."],
        ["Placebo Effect", "Kill 2 enemies in a single life, while having your ÜberCharge ready, but undeployed."],
        ["Plan B", "Kill 10 enemies while you're both underwater."],
        ["Plan Nine to Outer Space", "Launch the rocket as all 9 classes."],
        ["Play Doctor", "In a team with no Medics, be the first person to switch to Medic after a teammate calls for 'Medic!', and then heal 500 health."],
        ["Point Breaker", "Kill 15 enemies who are standing on a control point they own."],
        ["Pop Fly", "Kill 20 players while double-jumping."],
        ["Power Down", "Kill 15 enemies while they are capturing a point."],
        ["Power Trip", "Capture the final control point within 15 seconds of your team capturing the previous control point."],
        ["Powerhouse Offense", "Win 2Fort with a shutout."],
        ["Pownd on the Range", "Kill 10 enemies outside the normal sentry gun range using the Wrangler."],
        ["Preventive Medicine", "Block the enemy from capturing a control point with an ÜberCharged teammate."],
        ["Prime Cuts", "While using The Classic, gib all 9 classes during a single round."],
        ["Process of Elimination", "Win 140 Rounds."],
        ["Project Excelsior", "Parachute 19.47 miles."],
        ["Punching Bag", "Melee kill 10 Snipers using The Classic."],
        ["Purge", "Kill 15 enemies capturing a control point you own."],
        ["Pushkin the Kart", "Get 50 caps on payload maps."],
        ["Pyro Milestone 1", "Achieve 10 of the achievements in the Pyro pack."],
        ["Pyro Milestone 2", "Achieve 16 of the achievements in the Pyro pack."],
        ["Pyro Milestone 3", "Achieve 22 of the achievements in the Pyro pack."],
        ["Pyromancer", "Do 1 million points of total fire damage."],
        ["Pyrotechnics", "Kill 3 enemies in a single ÜberCharge."],
        ["Quadruple Bypass", "Heal a teammate who's taking fire from 4 enemies at once."],
        ["Quick Draw", "Kill a spy and two sappers within 10 seconds."],
        ["Quick Hook", "Kill a player in Well before the round starts."],
        ["Race for the Pennant", "Run 25 kilometers."],
        ["Raid Array", "Complete the Crash Course, Doe's Drill, and Mann-euvers missions."],
        ["Rain on Their Parade", "Jarate an enemy and the Medic healing him."],
        ["Rasputin", "In a single life, get shot, burned, bludgeoned, and receive explosive damage."],
        ["Rationing", "Kill an enemy with your shotgun while you're out of minigun ammo."],
        ["Raze the Roof", "Kill two people on the roof of the center control point in a single life."],
        ["Ready for Duty", "Complete each class to unlock the next."],
        ["Real Steal", "Win a round in which the enemy team has attempted to capture your final control point."],
        ["Real Steal", "As an Engineer, escape with your sentry as a sentry buster is about to detonate."],
        ["Reanimator 2", "Use one ÜberCharge to quickly revive 2 teammates within 5 seconds."],
        ["Red Oktoberfest", "Earn a domination for a Medic who's healing you."],
        ["Redistribution of Health", "Heal 1000 damage with med-kits in a single life."],
        ["Relentless Offense", "Win Hydro without giving up a capture."],
        ["Retire the Runner", "Kill a Scout while they are under the effect of Crit-a-Cola."],
        ["Revengineering", "Use a revenge crit to kill the enemy player that destroyed your sentry gun."],
        ["Ride of the Valkartie", "Ride the cart for 30 seconds."],
        ["Riftwalker", "Kill an enemy within 5 seconds of you traveling through an Engineer's teleporter."],
        ["Rio Grind", "Perform 50 repairs and/or reloads on a Sentry gun being Wrangled by another Engineer."],
        ["Robbed Royal", "Destroy 100 enemy stickybombs with the Scottish Resistance."],
        ["Robbin' Hood", "Take down an intelligence carrier with a single arrow."],
        ["Robot Flush", "Kill 5 robots with a single rocket while upgraded with rocket specialist."],
        ["Rocket Booster", "Win a round after the enemy team has opened the rocket lid."],
        ["Rode Hard, Put Away Wet", "Jarate an enemy that you're dominating."],
        ["Round-Tripper", "Capture the enemy intelligence 25 times."],
        ["Running With Scissors", "Win at Rock, Paper, Scissors 3 times in a row with Scissors."],
        ["S*M*A*S*H", "Assist a Medic in exploding 5 enemies with a single ÜberCharge."],
        ["Sackston Hale", "Craft the Saxton Hale Mask."],
        ["Sap Auteur", "Destroy 1000 Engineer buildings with sappers."],
        ["Sapsucker", "Sap an enemy building, then backstab the Engineer who built it within 5 seconds."],
        ["Saturation Bombing", "Jarate 4 enemy players with a single throw."],
        ["Sawbones", "Hit enemies with your bonesaw 5 times in a row without dying or missing."],
        ["Scared Stiff", "Kill a player scared by a ghost."],
        ["Scotch Guard", "Kill 3 enemies capping or pushing a cart in a single stickybomb detonation 3 separate times."],
        ["Scotch Tap", "Glory in the slaughter of your enemies using the Eyelander."],
        ["Scout Milestone 1", "Achieve 10 of the achievements in the Scout pack."],
        ["Scout Milestone 2", "Achieve 16 of the achievements in the Scout pack."],
        ["Scout Milestone 3", "Achieve 22 of the achievements in the Scout pack."],
        ["Screamin' Eagle", "Kill 20 enemies from above."],
        ["Search Engine", "Kill 3 cloaked Spies with a sentry gun under control of your Wrangler."],
        ["Second Degree Burn", "Kill a burning enemy who was ignited by another Pyro."],
        ["Second Eye", "Provide an enemy player with a freezecam of you shaking your rump."],
        ["Second Opinion", "ÜberCharge 2 teammates at once."],
        ["Self-destruct Sequence", "Headshot 10 enemy Snipers."],
        ["Semper Fry", "Kill 20 enemies while you are on fire."],
        ["Sentry Gunner", "Accumulate 10 sentry gun kills with a single sentry."],
        ["Set the Table", "Initiate 10 point captures that ultimately succeed."],
        ["Severed Ties", "While using the Back Scatter, kill 20 friends from behind."],
        ["Shafted", "Stab an enemy with an arrow."],
        ["Shell Extension", "During a wave, use a canteen charged with 'Ammo Reload' to refill an empty weapon slot."],
        ["Shock Treatment", "Kill a spy whose backstab attempt was blocked by your Razorback."],
        ["Shoot the Breeze", "Kill a fully invisible Spy in a single hit."],
        ["Shorn Connery", "Decapitate a cloaked Spy."],
        ["Show Trial", "Kill an enemy with a taunt."],
        ["Showboat", "Do 10 partner taunts with a teammate while capturing a control point."],
        ["Side Retired", "Capture the last point in a CP map."],
        ["Silent Pardner", "Upgrade 50 buildings built by other team members."],
        ["Silicon Slaughter", "Destroy 100,000 robots."],
        ["Six-String Stinger", "Provide an enemy player with a freezecam of your guitar playing skills."],
        ["Skullpluggery", "While using the Ambassador, kill 20 Snipers with a headshot."],
        ["Slammy Slayvis Woundya", "Decapitate an enemy Soldier who is brandishing the Equalizer."],
        ["Slash and Burn", "Backstab an enemy, who then switches to Pyro before they respawn."],
        ["Sleeper Agent", "Kill an enemy who triggered your feign death in the last 20 seconds."],
        ["Sleepy Holl0WND", "Kill the Horseless Headless Horsemann."],
        ["Sly Voltage", "As a Spy, sap 10 robots at once."],
        ["Snakebit", "Win a round in which the enemy team has attempted to capture your final control point."],
        ["Snakewater Salesman", "Win 141 Rounds."],
        ["Sniper Milestone 1", "Achieve 5 of the achievements in the Sniper pack."],
        ["Sniper Milestone 2", "Achieve 11 of the achievements in the Sniper pack."],
        ["Sniper Milestone 3", "Achieve 17 of the achievements in the Sniper pack."],
        ["Socket to Him", "Headshot an enemy Demoman."],
        ["Software Downgrade", "As a team, kill 50 stunned radiowave robots in an advanced mission in Mannhattan."],
        ["Soldier Milestone 1", "Achieve 5 of the achievements in the Soldier pack."],
        ["Soldier Milestone 2", "Achieve 11 of the achievements in the Soldier pack."],
        ["Soldier Milestone 3", "Achieve 17 of the achievements in the Soldier pack."],
        ["Something Stickied This Way Comes", "Kill 30 players with air burst stickybombs."],
        ["Soviet Block", "While invulnerable and on defense, block an invulnerable enemy Heavy's movement."],
        ["Soviet Union", "Get 25 enemy kills where you either assist or are assisted by another Heavy."],
        ["Space Camp", "Kill an enemy within the broken crate area while they attempt to pick up the neutral Australium."],
        ["Spam Blocker", "During a wave, defend the hatch 10 times from robots about to deliver a bomb."],
        ["Spark Plugger", "As a Sniper, kill 4 robots simultaneously."],
        ["Specialist", "Accumulate 10000 heal points health in a single life."],
        ["Spies Like Us", "While cloaked, bump into an enemy cloaked Spy."],
        ["Spontaneous Combustion", "Ignite 10 cloaked Spies."],
        ["Spray of Defeat", "Use a grenade to gib a player."],
        ["Spy Milestone 1", "Achieve 5 of the achievements in the Spy pack."],
        ["Spy Milestone 2", "Achieve 11 of the achievements in the Spy pack."],
        ["Spy Milestone 3", "Achieve 17 of the achievements in the Spy pack."],
        ["Spyalectical Materialism", "Kill or assist in killing 10 cloaked Spies."],
        ["Spymaster", "Backstab 1000 enemies."],
        ["Spynal Tap", "Kill 20 spies within 5 seconds of them sapping a friendly building."],
        ["Stalin the Kart", "Block the enemy from moving the payload cart 25 times."],
        ["Stand and Deliver", "Win 139 Rounds."],
        ["Star of My Own Show", "Spend some time editing a replay."],
        ["Stealing Home", "Start capping a capture point within a second of it becoming available."],
        ["Steel Fragnolias", "Complete all waves successfully in a mission."],
        ["Sticky Thump", "Using the Scottish Resistance, kill 3 players in separate explosions without placing new stickybombs."],
        ["Strike Zone", "Kill or assist kill 50 enemies while they are stunned or slowed."],
        ["Supreme Soviet", "Get ÜberCharged 50 times."],
        ["Surgical Prep", "Have an ÜberCharge ready before the Setup phase ends."],
        ["System Upgrade", "Max out all primary weapon upgrades."],
        ["T-1000000", "Collect 1,000,000 credits in your career."],
        ["Tam O'Shatter", "Destroy 5 enemy Engineer buildings during a single ÜberCharge from a Medic."],
        ["Tartan Spartan", "Do 1 million points of total blast damage."],
        ["Team Doctor", "Accumulate 25000 heal points as a Medic."],
        ["Tech Wrecker", "As a Demoman, kill 10 robots in a single detonation."],
        ["Terminated, Too", "Kill a player by pushing them into the cauldron fire."],
        ["Texas Ranger", "Haul buildings 1 km over your career."],
        ["Texas Two-Step", "Use your shotgun to finish off an enemy recently damaged by your sentry gun."],
        ["That's a Wrap", "Save your very first replay."],
        ["The Argyle Sap", "Blow up an Engineer, his sentry gun, and his dispenser with a single stickybomb detonation."],
        ["The Big Hurt", "Stun 2 Medics that are ready to deploy an ÜberCharge."],
        ["The Boostie Boys", "Buff 15 teammates with the Buff Banner in a single life."],
        ["The Crucible", "Win 137 Rounds."],
        ["The Cycle", "In a single life, kill an enemy while you are on the ground, in the air, and in the water."],
        ["The Extinguished Gentleman", "Have dispensers you built extinguish 20 burning players."],
        ["The Fight Stuff", "Win 138 Rounds."],
        ["The Great Deflate", "Kill 79 enemies who have Balloonicorn pets."],
        ["The High Road", "Sticky jump onto a cap point and capture it."],
        ["The Last Wave", "Provide an enemy with a freezecam shot of you waving to them."],
        ["The Longest Daze", "Kill 5 stunned or slowed players."],
        ["The Man from P.U.N.C.T.U.R.E.", "Stab an enemy while fencing."],
        ["The Man with the Broken Guns", "Backstab an Engineer, then sap 3 of his buildings within 10 seconds."],
        ["The Melbourne Supremacy", "Dominate a Sniper."],
        ["The Power and the Glory", "Win 142 Rounds."],
        ["The Scottish Play", "Get a melee kill while sticky jumping."],
        ["The Snakeout", "Wipe the other team with 12 or more players on the server."],
        ["The Stickening", "Kill 3 Heavies from full health with a single stickybomb detonation."],
        ["The Targe Charge", "Charge and kill someone with your shield bash."],
        ["The Wrench Connection", "Kill a disguised spy with your Wrench."],
        ["There Can Be Only One", "Decapitate your nemesis."],
        ["Three Times a Laddy", "Dominate 3 Engineers."],
        ["Time For Your Close-Up, Mr. Hale", "Render a replay into a movie."],
        ["Trade Secrets", "Kill 20 players carrying the intelligence."],
        ["Trailblazer", "Ignite 10 enemies that have recently used a teleporter."],
        ["Trauma Queen", "Deploy 3 ÜberCharges in less than 5 minutes, and assist in 5 kills during that time."],
        ["Trench Warfare", "Kill your nemesis with a shovel."],
        ["Tri-Splatteral Damage", "Kill 3 enemies with a single critical rocket."],
        ["Triage", "Deploy an ÜberCharge on a teammate less than a second before they're hit by a critical explosive."],
        ["Triple Play", "Capture three capture points in a row in one life."],
        ["Triple Prey", "In a single round, get a kill with 3 different weapons."],
        ["Triple Steal", "Capture the enemy intelligence 3 times in a single CTF round."],
        ["Triplecrossed", "Backstab 3 Snipers in a single life."],
        ["Trust Your Feelings", "Get 5 kills with the Sniper Rifle without your scope."],
        ["Tune Merasmus's Multi-Dimensional Television", "Reveal the mystery of the PASS Time TV Room."],
        ["Turbocharger", "Buff 4 or more teammates as a Soldier at the same time in a single wave."],
        ["Two Minute Warring", "Be part of a team that wins within two minutes."],
        ["U-Turn", "Kill an enemy that you couldn't see at the beginning of your charge."],
        ["Überectomy", "Kill a Medic that is ready to deploy an ÜberCharge."],
        ["Ubi concordia, ibi victoria", "Assist in killing 3 enemies on an enemy control point, in a single life."],
        ["Uncivil Engineer", "Provide an enemy player with a freezecam of you and the sentry that just killed them."],
        ["Undelete", "During a wave, use a canteen charged with 'Instant Building Upgrade' to build a new sentry gun within 3 seconds of your previous sentry gun's destruction."],
        ["Unforgiven", "Kill 3 enemies with revenge crits without dying."],
        ["Upper Hand", "Kill 3 players during the same parachute deploy."],
        ["Urban Strike", "Kill 500 gate crashing robots in Mannhattan."],
        ["Vanguard Party", "Be the first on your team to start capturing a control point in a round."],
        ["Vial Sharing", "As a Medic, share your canteen 5 times in a single wave."],
        ["Wage Against the Machine", "Earn a credit bonus at the end of a wave."],
        ["Wall of Pain", "Block 5,000 damage with the shield as a Medic in a single life."],
        ["War Crime and Punishment", "In a single life, kill 3 enemies who have damaged a Medic that is healing you."],
        ["War Crime Spybunal", "Kill a Spy who just backstabbed a teammate."],
        ["We Can Fix It In Post", "While watching a replay, press space bar to enter the editor."],
        ["Weenie Roast", "Have 2 enemy Scouts on fire at the same time."],
        ["Well Plaid!", "Kill 10 enemies while assisting or being assisted by another Demoman."],
        ["Wet Work", "Kill five enemies while they are in the water."],
        ["Wetwork", "Stab an enemy to death while under the influence of Jarate."],
        ["Where Eagles Dare", "Get the highest possible rocket jump using jump and crouch."],
        ["Who's Your Daddy?", "Headshot 3 Scouts with the Ambassador."],
        ["William Tell Overkill", "Pin an enemy Heavy to the wall via his head."],
        ["Wings of Glory", "Kill an enemy soldier while both you and the target are airborne."],
        ["With Friends Like these...", "Play in a game with five or more players from your Friends list."],
        ["Wizards Never Prosper", "Kill MERASMUS!"],
        ["World Traveler", "Play a complete game on 2Fort, Dustbowl, Granary, Gravel Pit, Hydro, and Well (CP)."],
        ["Worth a Thousand Words", "Provide the enemy with a freezecam of your 21 gun salute."],
        ["You Only Shiv Thrice", "Backstab 3 enemies within 10 seconds."],
        ["You'll Feel a Little Prick", "Assist in killing 3 enemies with a single ÜberCharge on a Scout."],
    ];

    assert.strictEqual(officialAchievements.length, 520, "sanity check on this test's own reference list");

    const dataPairs = game.achievements
        .map(a => [a.name, a.description])
        .sort((a, b) => a[0].localeCompare(b[0]));

    const expectedPairs = [...officialAchievements].sort((a, b) => a[0].localeCompare(b[0]));

    assert.deepStrictEqual(dataPairs, expectedPairs);

});
