import { test } from "node:test";
import assert from "node:assert";

import {
    APP_GUIDES,
    GAME_GUIDES,
    ALL_GUIDES,
    getGuideBySlug,
    getGameGuideForSlug
} from "../src/data/guides/index.js";

test("Phase 37 ships exactly the 9 approved App Guides (5 rewritten + 4 new)", () => {

    assert.strictEqual(APP_GUIDES.length, 9);

    assert.deepStrictEqual(
        APP_GUIDES.map(guide => guide.slug).sort(),
        [
            "achievement-completion-and-tracking",
            "catalog-and-filters",
            "getting-started",
            "player-progress",
            "podiums-and-leaderboards",
            "profile-and-statistics",
            "session-planner-and-recommendations",
            "steam-login-and-your-data",
            "understanding-achievement-availability"
        ]
    );

});

test("every real catalog game has a real, sourced Game Guide", () => {

    // Per the approved scope: every non-debug game in this app's catalog
    // (backend/catalog/games/*.json) has real, sourced content here - see
    // each game's own guides/games/<slug>.js for its sourcing notes. This
    // count should only grow further once a new game is added to the
    // catalog and its guide is actually authored, never bumped to pad the
    // list ahead of that.
    assert.strictEqual(GAME_GUIDES.length, 565);

    assert.deepStrictEqual(
        GAME_GUIDES.map(guide => guide.gameSlug).sort(),
        ["20-minutes-till-dawn", "7-billion-humans", "7-days-to-die", "a-hat-in-time", "a-little-to-the-left", "a-short-hike", "a-way-out", "adventure-capitalist", "against-the-storm", "age-of-empires-1-de", "age-of-empires-2-de", "age-of-empires-4", "age-of-mythology-retold", "age-of-wonders-3", "age-of-wonders-planetfall", "airmech-strike", "alan-wake", "alien-isolation", "alien-swarm", "aliens-fireteam-elite", "aliens-vs-predator-2010", "anno-2205", "apex-legends", "ares-extinction-agenda", "ark-survival-ascended", "ark-survival-evolved", "art-of-rally", "ashes-of-the-singularity-escalation", "assassins-creed-3", "assassins-creed-4-black-flag", "assassins-creed-revelations", "assassins-creed-rogue", "assassins-creed-syndicate", "assassins-creed-unity", "astral-ascent", "atom-zombie-smasher", "atomic-heart", "attack-on-titan-2", "automation-empire", "autonauts", "baba-is-you", "back-4-blood", "backpack-battles", "backpack-hero", "bad-north", "balatro", "baldurs-gate-3", "banished", "barotrauma", "bastion", "batman-arkham-asylum", "batman-arkham-city", "batman-arkham-origins", "battle-brothers", "battlefield-1", "battlefield-2042", "battlefield-5", "bayonetta", "beamng-drive", "besiege", "bioshock-2", "bioshock-infinite", "bioshock-remastered", "blood-and-bacon", "bloody-good-time", "bloons-td-6", "book-of-demons", "borderlands-2", "borderlands-game-of-the-year", "braid", "brawlhalla", "bright-memory-infinite", "brotato", "brothers-a-tale-of-two-sons", "burnout-paradise-remastered", "call-of-duty-black-ops", "call-of-duty-black-ops-2", "call-of-duty-modern-warfare-2", "call-of-duty-modern-warfare-2019", "car-mechanic-simulator-2021", "carx-drift-racing-online", "castle-crashers", "celeste", "chained-echoes", "chicory", "chivalry-2", "chivalry-medieval-warfare", "chrono-trigger", "cities-skylines", "cities-skylines-2", "civilization-5", "civilization-beyond-earth", "civilization-vi", "cliff-empire", "closure", "colony-survival", "command-and-conquer-remastered", "company-of-heroes-2", "company-of-heroes-3", "conan-exiles", "content-warning", "cossacks-3", "counter-strike-source", "craft-the-world", "crawl", "crusader-kings-2", "crusader-kings-3", "crypt-of-the-necrodancer", "cult-of-the-lamb", "cuphead", "curse-of-the-dead-gods", "cyber-shadow", "cyberpunk-2077", "dark-souls-3", "dark-souls-remastered", "darkest-dungeon", "dave-the-diver", "dawn-of-man", "dawn-of-war-2", "days-gone", "dead-cells", "dead-island-definitive-edition", "dead-rising-2", "dead-rising-3", "dead-space-2023", "deaths-door", "deep-rock-galactic", "deep-rock-galactic-survivor", "defense-grid-2", "demolition-inc", "devil-may-cry-5", "devil-may-cry-hd-collection", "devour", "dinkum", "dirt-3-complete-edition", "dirt-4", "dirt-rally", "dirt-rally-2", "disco-elysium", "dishonored", "distant-worlds-universe", "dmc-devil-may-cry", "dome-keeper", "doom-1993", "doom-2016", "doom-3", "doom-eternal", "doom-plus-doom-ii", "dorfromantik", "dragon-age-inquisition", "dragon-quest-xi", "dragons-dogma-dark-arisen", "dredge", "duck-game", "dungeon-defenders", "dungeon-of-the-endless", "dying-light", "dyson-sphere-program", "ea-sports-fc-24", "ea-sports-fc-25", "ea-sports-fc-26", "elden-ring", "endless-space-2", "enshrouded", "enter-the-gungeon", "euro-truck-simulator-2", "europa-universalis-4", "everspace-2", "exapunks", "f1-2020", "f1-24", "factorio", "fall-guys", "fallout-76", "fallout-new-vegas", "far-cry-3", "far-cry-4", "far-cry-5", "far-cry-primal", "farming-simulator-15", "farming-simulator-17", "farming-simulator-19", "farming-simulator-22", "fields-of-mistria", "fifa-23", "final-fantasy-ix", "final-fantasy-v", "final-fantasy-vii", "final-fantasy-x-x2-hd", "final-fantasy-xii-zodiac-age", "final-fantasy-xiii", "firewatch", "fistful-of-frags", "football-manager-2021", "football-manager-2024", "for-honor", "forager", "forza-horizon-4", "forza-horizon-5", "forza-motorsport-2023", "frostpunk", "frozen-synapse", "ftl", "furi", "galactic-civilizations-3", "game-of-thrones-telltale", "garrys-mod", "ghost-recon-wildlands", "ghostrunner", "god-of-war", "going-medieval", "gotham-city-impostors", "grand-theft-auto-iv", "grand-theft-auto-v", "green-hell", "grey-goo", "grid-2", "grid-2019", "grid-autosport", "griftlands", "grounded", "guacamelee-2", "gunfire-reborn", "gwent", "hades", "hades-2", "half-life-2", "half-life-2-episode-one", "half-life-2-episode-two", "halo-the-master-chief-collection", "hammerwatch", "hearts-of-iron-4", "helldivers-2", "helldivers-dive-harder", "heroes-of-hammerwatch", "hitman-world-of-assassination", "hogwarts-legacy", "hollow-knight", "homefront", "homeworld-remastered", "hotline-miami", "human-fall-flat", "human-resource-machine", "humankind", "huntdown", "hyper-light-drifter", "imperator-rome", "injustice-gods-among-us", "inside", "insurgency", "insurgency-sandstorm", "into-the-breach", "intrusion-2", "islanders", "it-takes-two", "jojos-bizarre-adventure-all-star-battle-r", "journey", "jurassic-world-evolution", "just-cause-2", "just-cause-3", "just-cause-4", "killer-is-dead", "killing-floor", "killing-floor-2", "kingdom-classic", "kingdom-new-lands", "kingdom-rush", "kingdom-two-crowns", "left-4-dead", "left-4-dead-2", "legend-of-grimrock", "legend-of-grimrock-2", "lego-jurassic-world", "lego-marvel-super-heroes", "lego-star-wars-the-force-awakens", "lets-build-a-zoo", "life-is-strange", "life-is-strange-before-the-storm", "like-a-dragon-ishin", "limbo", "little-nightmares", "loop-hero", "luck-be-a-landlord", "mad-games-tycoon-2", "mad-max", "mafia-2-definitive-edition", "mafia-definitive-edition", "magicka", "manor-lords", "mark-of-the-ninja", "marvel-rivals", "marvels-midnight-suns", "mass-effect-3", "mass-effect-legendary-edition", "master-of-orion", "max-payne-3", "men-of-war-assault-squad-2", "metal-gear-rising-revengeance", "metal-hellsinger", "metro-2033-redux", "metro-exodus", "metro-last-light-redux", "mgs-v-ground-zeroes", "mini-metro", "monday-night-combat", "monster-hunter-rise", "monster-hunter-world", "monster-train", "moonlighter", "mortal-kombat-1", "mortal-kombat-11", "mortal-kombat-x", "mount-and-blade-2-bannerlord", "mount-and-blade-warband", "muck", "mudrunner", "my-summer-car", "naraka-bladepoint", "naruto-shippuden-ultimate-ninja-storm-4", "nba-2k23", "nba-2k24", "necesse", "need-for-speed-payback", "neon-abyss", "neon-white", "nidhogg", "nightingale", "nioh-2", "nioh-complete-edition", "no-mans-sky", "northgard", "nova-drift", "octopath-traveler", "offspring-fling", "once-human", "order-of-battle-world-war-ii", "ori-and-the-blind-forest", "ori-and-the-will-of-the-wisps", "orion-prelude", "overcooked-2", "owlboy", "oxenfree", "oxygen-not-included", "painkiller-hell-and-damnation", "palworld", "panzer-corps-2", "papers-please", "party-animals", "path-of-exile", "payday-3", "payday-the-heist", "peak", "peglin", "people-playground", "persona-5-royal", "phasmophobia", "pillars-of-eternity", "pizza-tower", "planet-zoo", "planetary-annihilation-titans", "plants-vs-zombies-goty", "plateup", "portal", "portal-2", "powerwash-simulator", "prey-2017", "prison-architect", "project-cars", "project-cars-2", "project-highrise", "prototype-2", "psychonauts", "pubg-battlegrounds", "pvz-battle-for-neighborville", "pyre", "raft", "rage", "rage-2", "railway-empire", "rainbow-six-siege", "ratropolis", "rayman-legends", "ready-or-not", "red-dead-redemption-2", "red-faction-armageddon", "red-faction-guerrilla-remastered", "resident-evil-2-remake", "resident-evil-4-remake", "resident-evil-5", "resident-evil-7", "resident-evil-revelations", "resident-evil-village", "return-of-the-obra-dinn", "rime", "rise-of-nations-extended", "rise-of-the-tomb-raider", "risk-global-domination", "risk-of-rain", "risk-of-rain-2", "rivals-of-aether", "robocraft", "rocket-league", "rogue-legacy", "rust", "sable", "saints-row-iv", "saints-row-the-third", "sanctum-2", "satisfactory", "savage-lands", "scp-secret-laboratory", "sea-of-thieves", "sekiro", "serious-sam-3-bfe", "serious-sam-4", "serious-sam-hd-tfe", "serious-sam-hd-tse", "shadow-of-mordor", "shadow-of-war", "shadow-warrior-3", "shovel-knight", "sifu", "sins-of-a-solar-empire-rebellion", "skullgirls", "skyrim", "skyrim-special-edition", "slay-the-spire", "sleeping-dogs", "slime-rancher", "slime-rancher-2", "sniper-elite-3", "sniper-elite-4", "sniper-elite-5", "sniper-elite-nazi-zombie-army", "sniper-elite-v2", "snowrunner", "songs-of-conquest", "songs-of-syx", "sonic-adventure-2", "sonic-cd", "sonic-frontiers", "sonic-mania", "space-engineers", "space-hulk-deathwing-enhanced", "space-marine-2", "spacechem", "spec-ops-the-line", "speedrunners", "spelunky", "spelunky-2", "splinter-cell-blacklist", "star-wars-battlefront", "star-wars-outlaws", "stardew-valley", "steamworld-dig-2", "steel-division-2", "stellaris", "street-fighter-5", "street-fighter-6", "streets-of-rage-4", "streets-of-rogue", "subnautica", "subnautica-below-zero", "sun-haven", "sunless-sea", "sunset-overdrive", "superliminal", "surviving-mars", "tales-from-the-borderlands", "team-fortress-2", "techtonica", "terraria", "the-banner-saga", "the-crew-2", "the-division", "the-first-descendant", "the-forest", "the-forgotten-city", "the-last-of-us-part-1", "the-lego-movie-videogame", "the-messenger", "the-planet-crafter", "the-riftbreaker", "the-stanley-parable", "the-walking-dead", "the-walking-dead-season-two", "the-walking-dead-telltale-definitive-series", "the-witcher-2", "the-witcher-3", "the-wolf-among-us", "they-are-billions", "thomas-was-alone", "thronefall", "titan-quest", "titanfall-2", "tomb-raider-2013", "tooth-and-tail", "total-war-attila", "total-war-empire", "total-war-napoleon", "total-war-pharaoh", "total-war-rome-2", "total-war-shogun-2", "total-war-three-kingdoms", "total-war-warhammer", "total-war-warhammer-2", "total-war-warhammer-3", "towerfall", "transistor", "transport-fever-2", "trials-fusion", "trine-2", "trine-4", "trine-5", "trine-enchanted-edition", "trombone-champ", "tropico-5", "tropico-6", "trove", "two-point-hospital", "ultimate-chicken-horse", "ultra-street-fighter-4", "underrail", "unity-of-command-2", "universe-sandbox-legacy", "unrailed", "unravel-two", "v-rising", "va11-hall-a", "vampire-survivors", "verdun", "victoria-3", "viscera-cleanup-detail", "void-bastards", "wallpaper-engine", "war-thunder", "warframe", "warhammer-40k-boltgun", "warhammer-40k-darktide", "warhammer-40k-mechanicus", "warhammer-vermintide-2", "wartales", "watch-dogs", "watch-dogs-2", "watch-dogs-legion", "what-remains-of-edith-finch", "wildermyth", "wildfrost", "wingspan", "wizard-of-legend", "wobbly-life", "wolfenstein-2", "wolfenstein-the-old-blood", "world-of-goo", "world-of-warships", "world-war-z", "worms-reloaded", "worms-ultimate-mayhem", "worms-wmd", "xcom-2", "yakuza-like-a-dragon", "yooka-laylee", "yu-gi-oh-duel-links", "yu-gi-oh-master-duel", "zombie-army-trilogy"]
    );

    assert.deepStrictEqual(
        GAME_GUIDES.map(guide => guide.slug).sort(),
        [
            "20-minutes-till-dawn-achievement-guide",
            "7-billion-humans-achievement-guide",
            "7-days-to-die-achievement-guide",
            "a-hat-in-time-achievement-guide",
            "a-little-to-the-left-achievement-guide",
            "a-short-hike-achievement-guide",
            "a-way-out-achievement-guide",
            "adventure-capitalist-achievement-guide",
            "against-the-storm-achievement-guide",
            "age-of-empires-1-de-achievement-guide",
            "age-of-empires-2-de-achievement-guide",
            "age-of-empires-4-achievement-guide",
            "age-of-mythology-retold-achievement-guide",
            "age-of-wonders-3-achievement-guide",
            "age-of-wonders-planetfall-achievement-guide",
            "airmech-strike-achievement-guide",
            "alan-wake-achievement-guide",
            "alien-isolation-achievement-guide",
            "alien-swarm-achievement-guide",
            "aliens-fireteam-elite-achievement-guide",
            "aliens-vs-predator-2010-achievement-guide",
            "anno-2205-achievement-guide",
            "apex-legends-achievement-guide",
            "ares-extinction-agenda-achievement-guide",
            "ark-survival-ascended-achievement-guide",
            "ark-survival-evolved-achievement-guide",
            "art-of-rally-achievement-guide",
            "ashes-of-the-singularity-escalation-achievement-guide",
            "assassins-creed-3-achievement-guide",
            "assassins-creed-4-black-flag-achievement-guide",
            "assassins-creed-revelations-achievement-guide",
            "assassins-creed-rogue-achievement-guide",
            "assassins-creed-syndicate-achievement-guide",
            "assassins-creed-unity-achievement-guide",
            "astral-ascent-achievement-guide",
            "atom-zombie-smasher-achievement-guide",
            "atomic-heart-achievement-guide",
            "attack-on-titan-2-achievement-guide",
            "automation-empire-achievement-guide",
            "autonauts-achievement-guide",
            "baba-is-you-achievement-guide",
            "back-4-blood-achievement-guide",
            "backpack-battles-achievement-guide",
            "backpack-hero-achievement-guide",
            "bad-north-achievement-guide",
            "balatro-achievement-guide",
            "baldurs-gate-3-achievement-guide",
            "banished-achievement-guide",
            "barotrauma-achievement-guide",
            "bastion-achievement-guide",
            "batman-arkham-asylum-achievement-guide",
            "batman-arkham-city-achievement-guide",
            "batman-arkham-origins-achievement-guide",
            "battle-brothers-achievement-guide",
            "battlefield-1-achievement-guide",
            "battlefield-2042-achievement-guide",
            "battlefield-5-achievement-guide",
            "bayonetta-achievement-guide",
            "beamng-drive-achievement-guide",
            "besiege-achievement-guide",
            "bioshock-2-achievement-guide",
            "bioshock-infinite-achievement-guide",
            "bioshock-remastered-achievement-guide",
            "blood-and-bacon-achievement-guide",
            "bloody-good-time-achievement-guide",
            "bloons-td-6-achievement-guide",
            "book-of-demons-achievement-guide",
            "borderlands-2-achievement-guide",
            "borderlands-game-of-the-year-achievement-guide",
            "braid-achievement-guide",
            "brawlhalla-achievement-guide",
            "bright-memory-infinite-achievement-guide",
            "brotato-achievement-guide",
            "brothers-a-tale-of-two-sons-achievement-guide",
            "burnout-paradise-remastered-achievement-guide",
            "call-of-duty-black-ops-2-achievement-guide",
            "call-of-duty-black-ops-achievement-guide",
            "call-of-duty-modern-warfare-2-achievement-guide",
            "call-of-duty-modern-warfare-2019-achievement-guide",
            "car-mechanic-simulator-2021-achievement-guide",
            "carx-drift-racing-online-achievement-guide",
            "castle-crashers-achievement-guide",
            "celeste-achievement-guide",
            "chained-echoes-achievement-guide",
            "chicory-achievement-guide",
            "chivalry-2-achievement-guide",
            "chivalry-medieval-warfare-achievement-guide",
            "chrono-trigger-achievement-guide",
            "cities-skylines-2-achievement-guide",
            "cities-skylines-achievement-guide",
            "civilization-5-achievement-guide",
            "civilization-beyond-earth-achievement-guide",
            "civilization-vi-achievement-guide",
            "cliff-empire-achievement-guide",
            "closure-achievement-guide",
            "colony-survival-achievement-guide",
            "command-and-conquer-remastered-achievement-guide",
            "company-of-heroes-2-achievement-guide",
            "company-of-heroes-3-achievement-guide",
            "conan-exiles-achievement-guide",
            "content-warning-achievement-guide",
            "cossacks-3-achievement-guide",
            "counter-strike-source-achievement-guide",
            "craft-the-world-achievement-guide",
            "crawl-achievement-guide",
            "crusader-kings-2-achievement-guide",
            "crusader-kings-3-achievement-guide",
            "crypt-of-the-necrodancer-achievement-guide",
            "cult-of-the-lamb-achievement-guide",
            "cuphead-achievement-guide",
            "curse-of-the-dead-gods-achievement-guide",
            "cyber-shadow-achievement-guide",
            "cyberpunk-2077-achievement-guide",
            "dark-souls-3-achievement-guide",
            "dark-souls-remastered-achievement-guide",
            "darkest-dungeon-achievement-guide",
            "dave-the-diver-achievement-guide",
            "dawn-of-man-achievement-guide",
            "dawn-of-war-2-achievement-guide",
            "days-gone-achievement-guide",
            "dead-cells-achievement-guide",
            "dead-island-definitive-edition-achievement-guide",
            "dead-rising-2-achievement-guide",
            "dead-rising-3-achievement-guide",
            "dead-space-2023-achievement-guide",
            "deaths-door-achievement-guide",
            "deep-rock-galactic-achievement-guide",
            "deep-rock-galactic-survivor-achievement-guide",
            "defense-grid-2-achievement-guide",
            "demolition-inc-achievement-guide",
            "devil-may-cry-5-achievement-guide",
            "devil-may-cry-hd-collection-achievement-guide",
            "devour-achievement-guide",
            "dinkum-achievement-guide",
            "dirt-3-complete-edition-achievement-guide",
            "dirt-4-achievement-guide",
            "dirt-rally-2-achievement-guide",
            "dirt-rally-achievement-guide",
            "disco-elysium-achievement-guide",
            "dishonored-achievement-guide",
            "distant-worlds-universe-achievement-guide",
            "dmc-devil-may-cry-achievement-guide",
            "dome-keeper-achievement-guide",
            "doom-1993-achievement-guide",
            "doom-2016-achievement-guide",
            "doom-3-achievement-guide",
            "doom-eternal-achievement-guide",
            "doom-plus-doom-ii-achievement-guide",
            "dorfromantik-achievement-guide",
            "dragon-age-inquisition-achievement-guide",
            "dragon-quest-xi-achievement-guide",
            "dragons-dogma-dark-arisen-achievement-guide",
            "dredge-achievement-guide",
            "duck-game-achievement-guide",
            "dungeon-defenders-achievement-guide",
            "dungeon-of-the-endless-achievement-guide",
            "dying-light-achievement-guide",
            "dyson-sphere-program-achievement-guide",
            "ea-sports-fc-24-achievement-guide",
            "ea-sports-fc-25-achievement-guide",
            "ea-sports-fc-26-achievement-guide",
            "elden-ring-achievement-guide",
            "endless-space-2-achievement-guide",
            "enshrouded-achievement-guide",
            "enter-the-gungeon-achievement-guide",
            "euro-truck-simulator-2-achievement-guide",
            "europa-universalis-4-achievement-guide",
            "everspace-2-achievement-guide",
            "exapunks-achievement-guide",
            "f1-2020-achievement-guide",
            "f1-24-achievement-guide",
            "factorio-achievement-guide",
            "fall-guys-achievement-guide",
            "fallout-76-achievement-guide",
            "fallout-new-vegas-achievement-guide",
            "far-cry-3-achievement-guide",
            "far-cry-4-achievement-guide",
            "far-cry-5-achievement-guide",
            "far-cry-primal-achievement-guide",
            "farming-simulator-15-achievement-guide",
            "farming-simulator-17-achievement-guide",
            "farming-simulator-19-achievement-guide",
            "farming-simulator-22-achievement-guide",
            "fields-of-mistria-achievement-guide",
            "fifa-23-achievement-guide",
            "final-fantasy-ix-achievement-guide",
            "final-fantasy-v-achievement-guide",
            "final-fantasy-vii-achievement-guide",
            "final-fantasy-x-x2-hd-achievement-guide",
            "final-fantasy-xii-zodiac-age-achievement-guide",
            "final-fantasy-xiii-achievement-guide",
            "firewatch-achievement-guide",
            "fistful-of-frags-achievement-guide",
            "football-manager-2021-achievement-guide",
            "football-manager-2024-achievement-guide",
            "for-honor-achievement-guide",
            "forager-achievement-guide",
            "forza-horizon-4-achievement-guide",
            "forza-horizon-5-achievement-guide",
            "forza-motorsport-2023-achievement-guide",
            "frostpunk-achievement-guide",
            "frozen-synapse-achievement-guide",
            "ftl-achievement-guide",
            "furi-achievement-guide",
            "galactic-civilizations-3-achievement-guide",
            "game-of-thrones-telltale-achievement-guide",
            "garrys-mod-achievement-guide",
            "ghost-recon-wildlands-achievement-guide",
            "ghostrunner-achievement-guide",
            "god-of-war-achievement-guide",
            "going-medieval-achievement-guide",
            "gotham-city-impostors-achievement-guide",
            "grand-theft-auto-iv-achievement-guide",
            "grand-theft-auto-v-achievement-guide",
            "green-hell-achievement-guide",
            "grey-goo-achievement-guide",
            "grid-2-achievement-guide",
            "grid-2019-achievement-guide",
            "grid-autosport-achievement-guide",
            "griftlands-achievement-guide",
            "grounded-achievement-guide",
            "guacamelee-2-achievement-guide",
            "gunfire-reborn-achievement-guide",
            "gwent-achievement-guide",
            "hades-2-achievement-guide",
            "hades-achievement-guide",
            "half-life-2-achievement-guide",
            "half-life-2-episode-one-achievement-guide",
            "half-life-2-episode-two-achievement-guide",
            "halo-the-master-chief-collection-achievement-guide",
            "hammerwatch-achievement-guide",
            "hearts-of-iron-4-achievement-guide",
            "helldivers-2-achievement-guide",
            "helldivers-dive-harder-achievement-guide",
            "heroes-of-hammerwatch-achievement-guide",
            "hitman-world-of-assassination-achievement-guide",
            "hogwarts-legacy-achievement-guide",
            "hollow-knight-achievement-guide",
            "homefront-achievement-guide",
            "homeworld-remastered-achievement-guide",
            "hotline-miami-achievement-guide",
            "human-fall-flat-achievement-guide",
            "human-resource-machine-achievement-guide",
            "humankind-achievement-guide",
            "huntdown-achievement-guide",
            "hyper-light-drifter-achievement-guide",
            "imperator-rome-achievement-guide",
            "injustice-gods-among-us-achievement-guide",
            "inside-achievement-guide",
            "insurgency-achievement-guide",
            "insurgency-sandstorm-achievement-guide",
            "into-the-breach-achievement-guide",
            "intrusion-2-achievement-guide",
            "islanders-achievement-guide",
            "it-takes-two-achievement-guide",
            "jojos-bizarre-adventure-all-star-battle-r-achievement-guide",
            "journey-achievement-guide",
            "jurassic-world-evolution-achievement-guide",
            "just-cause-2-achievement-guide",
            "just-cause-3-achievement-guide",
            "just-cause-4-achievement-guide",
            "killer-is-dead-achievement-guide",
            "killing-floor-2-achievement-guide",
            "killing-floor-achievement-guide",
            "kingdom-classic-achievement-guide",
            "kingdom-new-lands-achievement-guide",
            "kingdom-rush-achievement-guide",
            "kingdom-two-crowns-achievement-guide",
            "left-4-dead-2-achievement-guide",
            "left-4-dead-achievement-guide",
            "legend-of-grimrock-2-achievement-guide",
            "legend-of-grimrock-achievement-guide",
            "lego-jurassic-world-achievement-guide",
            "lego-marvel-super-heroes-achievement-guide",
            "lego-star-wars-the-force-awakens-achievement-guide",
            "lets-build-a-zoo-achievement-guide",
            "life-is-strange-achievement-guide",
            "life-is-strange-before-the-storm-achievement-guide",
            "like-a-dragon-ishin-achievement-guide",
            "limbo-achievement-guide",
            "little-nightmares-achievement-guide",
            "loop-hero-achievement-guide",
            "luck-be-a-landlord-achievement-guide",
            "mad-games-tycoon-2-achievement-guide",
            "mad-max-achievement-guide",
            "mafia-2-definitive-edition-achievement-guide",
            "mafia-definitive-edition-achievement-guide",
            "magicka-achievement-guide",
            "manor-lords-achievement-guide",
            "mark-of-the-ninja-achievement-guide",
            "marvel-rivals-achievement-guide",
            "marvels-midnight-suns-achievement-guide",
            "mass-effect-3-achievement-guide",
            "mass-effect-legendary-edition-achievement-guide",
            "master-of-orion-achievement-guide",
            "max-payne-3-achievement-guide",
            "men-of-war-assault-squad-2-achievement-guide",
            "metal-gear-rising-revengeance-achievement-guide",
            "metal-hellsinger-achievement-guide",
            "metro-2033-redux-achievement-guide",
            "metro-exodus-achievement-guide",
            "metro-last-light-redux-achievement-guide",
            "mgs-v-ground-zeroes-achievement-guide",
            "mini-metro-achievement-guide",
            "monday-night-combat-achievement-guide",
            "monster-hunter-rise-achievement-guide",
            "monster-hunter-world-achievement-guide",
            "monster-train-achievement-guide",
            "moonlighter-achievement-guide",
            "mortal-kombat-1-achievement-guide",
            "mortal-kombat-11-achievement-guide",
            "mortal-kombat-x-achievement-guide",
            "mount-and-blade-2-bannerlord-achievement-guide",
            "mount-and-blade-warband-achievement-guide",
            "muck-achievement-guide",
            "mudrunner-achievement-guide",
            "my-summer-car-achievement-guide",
            "naraka-bladepoint-achievement-guide",
            "naruto-shippuden-ultimate-ninja-storm-4-achievement-guide",
            "nba-2k23-achievement-guide",
            "nba-2k24-achievement-guide",
            "necesse-achievement-guide",
            "need-for-speed-payback-achievement-guide",
            "neon-abyss-achievement-guide",
            "neon-white-achievement-guide",
            "nidhogg-achievement-guide",
            "nightingale-achievement-guide",
            "nioh-2-achievement-guide",
            "nioh-complete-edition-achievement-guide",
            "no-mans-sky-achievement-guide",
            "northgard-achievement-guide",
            "nova-drift-achievement-guide",
            "octopath-traveler-achievement-guide",
            "offspring-fling-achievement-guide",
            "once-human-achievement-guide",
            "order-of-battle-world-war-ii-achievement-guide",
            "ori-and-the-blind-forest-achievement-guide",
            "ori-and-the-will-of-the-wisps-achievement-guide",
            "orion-prelude-achievement-guide",
            "overcooked-2-achievement-guide",
            "owlboy-achievement-guide",
            "oxenfree-achievement-guide",
            "oxygen-not-included-achievement-guide",
            "painkiller-hell-and-damnation-achievement-guide",
            "palworld-achievement-guide",
            "panzer-corps-2-achievement-guide",
            "papers-please-achievement-guide",
            "party-animals-achievement-guide",
            "path-of-exile-achievement-guide",
            "payday-3-achievement-guide",
            "payday-the-heist-achievement-guide",
            "peak-achievement-guide",
            "peglin-achievement-guide",
            "people-playground-achievement-guide",
            "persona-5-royal-achievement-guide",
            "phasmophobia-achievement-guide",
            "pillars-of-eternity-achievement-guide",
            "pizza-tower-achievement-guide",
            "planet-zoo-achievement-guide",
            "planetary-annihilation-titans-achievement-guide",
            "plants-vs-zombies-goty-achievement-guide",
            "plateup-achievement-guide",
            "portal-2-achievement-guide",
            "portal-achievement-guide",
            "powerwash-simulator-achievement-guide",
            "prey-2017-achievement-guide",
            "prison-architect-achievement-guide",
            "project-cars-2-achievement-guide",
            "project-cars-achievement-guide",
            "project-highrise-achievement-guide",
            "prototype-2-achievement-guide",
            "psychonauts-achievement-guide",
            "pubg-battlegrounds-achievement-guide",
            "pvz-battle-for-neighborville-achievement-guide",
            "pyre-achievement-guide",
            "raft-achievement-guide",
            "rage-2-achievement-guide",
            "rage-achievement-guide",
            "railway-empire-achievement-guide",
            "rainbow-six-siege-achievement-guide",
            "ratropolis-achievement-guide",
            "rayman-legends-achievement-guide",
            "ready-or-not-achievement-guide",
            "red-dead-redemption-2-achievement-guide",
            "red-faction-armageddon-achievement-guide",
            "red-faction-guerrilla-remastered-achievement-guide",
            "resident-evil-2-remake-achievement-guide",
            "resident-evil-4-remake-achievement-guide",
            "resident-evil-5-achievement-guide",
            "resident-evil-7-achievement-guide",
            "resident-evil-revelations-achievement-guide",
            "resident-evil-village-achievement-guide",
            "return-of-the-obra-dinn-achievement-guide",
            "rime-achievement-guide",
            "rise-of-nations-extended-achievement-guide",
            "rise-of-the-tomb-raider-achievement-guide",
            "risk-global-domination-achievement-guide",
            "risk-of-rain-2-achievement-guide",
            "risk-of-rain-achievement-guide",
            "rivals-of-aether-achievement-guide",
            "robocraft-achievement-guide",
            "rocket-league-achievement-guide",
            "rogue-legacy-achievement-guide",
            "rust-achievement-guide",
            "sable-achievement-guide",
            "saints-row-iv-achievement-guide",
            "saints-row-the-third-achievement-guide",
            "sanctum-2-achievement-guide",
            "satisfactory-achievement-guide",
            "savage-lands-achievement-guide",
            "scp-secret-laboratory-achievement-guide",
            "sea-of-thieves-achievement-guide",
            "sekiro-achievement-guide",
            "serious-sam-3-bfe-achievement-guide",
            "serious-sam-4-achievement-guide",
            "serious-sam-hd-tfe-achievement-guide",
            "serious-sam-hd-tse-achievement-guide",
            "shadow-of-mordor-achievement-guide",
            "shadow-of-war-achievement-guide",
            "shadow-warrior-3-achievement-guide",
            "shovel-knight-achievement-guide",
            "sifu-achievement-guide",
            "sins-of-a-solar-empire-rebellion-achievement-guide",
            "skullgirls-achievement-guide",
            "skyrim-achievement-guide",
            "skyrim-special-edition-achievement-guide",
            "slay-the-spire-achievement-guide",
            "sleeping-dogs-achievement-guide",
            "slime-rancher-2-achievement-guide",
            "slime-rancher-achievement-guide",
            "sniper-elite-3-achievement-guide",
            "sniper-elite-4-achievement-guide",
            "sniper-elite-5-achievement-guide",
            "sniper-elite-nazi-zombie-army-achievement-guide",
            "sniper-elite-v2-achievement-guide",
            "snowrunner-achievement-guide",
            "songs-of-conquest-achievement-guide",
            "songs-of-syx-achievement-guide",
            "sonic-adventure-2-achievement-guide",
            "sonic-cd-achievement-guide",
            "sonic-frontiers-achievement-guide",
            "sonic-mania-achievement-guide",
            "space-engineers-achievement-guide",
            "space-hulk-deathwing-enhanced-achievement-guide",
            "space-marine-2-achievement-guide",
            "spacechem-achievement-guide",
            "spec-ops-the-line-achievement-guide",
            "speedrunners-achievement-guide",
            "spelunky-2-achievement-guide",
            "spelunky-achievement-guide",
            "splinter-cell-blacklist-achievement-guide",
            "star-wars-battlefront-achievement-guide",
            "star-wars-outlaws-achievement-guide",
            "stardew-valley-achievement-guide",
            "steamworld-dig-2-achievement-guide",
            "steel-division-2-achievement-guide",
            "stellaris-achievement-guide",
            "street-fighter-5-achievement-guide",
            "street-fighter-6-achievement-guide",
            "streets-of-rage-4-achievement-guide",
            "streets-of-rogue-achievement-guide",
            "subnautica-achievement-guide",
            "subnautica-below-zero-achievement-guide",
            "sun-haven-achievement-guide",
            "sunless-sea-achievement-guide",
            "sunset-overdrive-achievement-guide",
            "superliminal-achievement-guide",
            "surviving-mars-achievement-guide",
            "tales-from-the-borderlands-achievement-guide",
            "team-fortress-2-achievement-guide",
            "techtonica-achievement-guide",
            "terraria-achievement-guide",
            "the-banner-saga-achievement-guide",
            "the-crew-2-achievement-guide",
            "the-division-achievement-guide",
            "the-first-descendant-achievement-guide",
            "the-forest-achievement-guide",
            "the-forgotten-city-achievement-guide",
            "the-last-of-us-part-1-achievement-guide",
            "the-lego-movie-videogame-achievement-guide",
            "the-messenger-achievement-guide",
            "the-planet-crafter-achievement-guide",
            "the-riftbreaker-achievement-guide",
            "the-stanley-parable-achievement-guide",
            "the-walking-dead-achievement-guide",
            "the-walking-dead-season-two-achievement-guide",
            "the-walking-dead-telltale-definitive-series-achievement-guide",
            "the-witcher-2-achievement-guide",
            "the-witcher-3-achievement-guide",
            "the-wolf-among-us-achievement-guide",
            "they-are-billions-achievement-guide",
            "thomas-was-alone-achievement-guide",
            "thronefall-achievement-guide",
            "titan-quest-achievement-guide",
            "titanfall-2-achievement-guide",
            "tomb-raider-2013-achievement-guide",
            "tooth-and-tail-achievement-guide",
            "total-war-attila-achievement-guide",
            "total-war-empire-achievement-guide",
            "total-war-napoleon-achievement-guide",
            "total-war-pharaoh-achievement-guide",
            "total-war-rome-2-achievement-guide",
            "total-war-shogun-2-achievement-guide",
            "total-war-three-kingdoms-achievement-guide",
            "total-war-warhammer-2-achievement-guide",
            "total-war-warhammer-3-achievement-guide",
            "total-war-warhammer-achievement-guide",
            "towerfall-achievement-guide",
            "transistor-achievement-guide",
            "transport-fever-2-achievement-guide",
            "trials-fusion-achievement-guide",
            "trine-2-achievement-guide",
            "trine-4-achievement-guide",
            "trine-5-achievement-guide",
            "trine-enchanted-edition-achievement-guide",
            "trombone-champ-achievement-guide",
            "tropico-5-achievement-guide",
            "tropico-6-achievement-guide",
            "trove-achievement-guide",
            "two-point-hospital-achievement-guide",
            "ultimate-chicken-horse-achievement-guide",
            "ultra-street-fighter-4-achievement-guide",
            "underrail-achievement-guide",
            "unity-of-command-2-achievement-guide",
            "universe-sandbox-legacy-achievement-guide",
            "unrailed-achievement-guide",
            "unravel-two-achievement-guide",
            "v-rising-achievement-guide",
            "va11-hall-a-achievement-guide",
            "vampire-survivors-achievement-guide",
            "verdun-achievement-guide",
            "victoria-3-achievement-guide",
            "viscera-cleanup-detail-achievement-guide",
            "void-bastards-achievement-guide",
            "wallpaper-engine-achievement-guide",
            "war-thunder-achievement-guide",
            "warframe-achievement-guide",
            "warhammer-40k-boltgun-achievement-guide",
            "warhammer-40k-darktide-achievement-guide",
            "warhammer-40k-mechanicus-achievement-guide",
            "warhammer-vermintide-2-achievement-guide",
            "wartales-achievement-guide",
            "watch-dogs-2-achievement-guide",
            "watch-dogs-achievement-guide",
            "watch-dogs-legion-achievement-guide",
            "what-remains-of-edith-finch-achievement-guide",
            "wildermyth-achievement-guide",
            "wildfrost-achievement-guide",
            "wingspan-achievement-guide",
            "wizard-of-legend-achievement-guide",
            "wobbly-life-achievement-guide",
            "wolfenstein-2-achievement-guide",
            "wolfenstein-the-old-blood-achievement-guide",
            "world-of-goo-achievement-guide",
            "world-of-warships-achievement-guide",
            "world-war-z-achievement-guide",
            "worms-reloaded-achievement-guide",
            "worms-ultimate-mayhem-achievement-guide",
            "worms-wmd-achievement-guide",
            "xcom-2-achievement-guide",
            "yakuza-like-a-dragon-achievement-guide",
            "yooka-laylee-achievement-guide",
            "yu-gi-oh-duel-links-achievement-guide",
            "yu-gi-oh-master-duel-achievement-guide",
            "zombie-army-trilogy-achievement-guide"
        ]
    );

});

test("every guide has a unique slug across App and Game guides combined", () => {

    const slugs = ALL_GUIDES.map(guide => guide.slug);

    assert.strictEqual(new Set(slugs).size, slugs.length);

});

test("every guide has a non-empty title, summary, icon, and at least one section", () => {

    for (const guide of ALL_GUIDES) {

        assert.ok(guide.title?.length > 0, `${guide.slug} is missing a title`);
        assert.ok(guide.summary?.length > 0, `${guide.slug} is missing a summary`);
        assert.ok(guide.icon?.length > 0, `${guide.slug} is missing an icon`);
        assert.ok(Array.isArray(guide.sections) && guide.sections.length > 0, `${guide.slug} has no sections`);

    }

});

test("every section has a non-empty heading and at least one non-empty body paragraph", () => {

    for (const guide of ALL_GUIDES) {

        for (const section of guide.sections) {

            assert.ok(section.heading?.length > 0, `${guide.slug} has a section with no heading`);
            assert.ok(Array.isArray(section.body) && section.body.length > 0, `${guide.slug}'s "${section.heading}" section has no body`);

            for (const paragraph of section.body) {

                assert.ok(paragraph?.length > 0, `${guide.slug}'s "${section.heading}" section has an empty paragraph`);

            }

        }

    }

});

test("every guide's relatedSlugs resolves to a real, existing guide (no typos/dangling references)", () => {

    for (const guide of ALL_GUIDES) {

        for (const relatedSlug of guide.relatedSlugs ?? []) {

            const related = getGuideBySlug(relatedSlug);

            assert.ok(related, `${guide.slug} references a related guide "${relatedSlug}" that doesn't exist`);
            assert.notStrictEqual(related.slug, guide.slug, `${guide.slug} lists itself as a related guide`);

        }

    }

});

test("getGuideBySlug finds an existing App Guide by slug", () => {

    const guide = getGuideBySlug("getting-started");

    assert.ok(guide);
    assert.strictEqual(guide.title, "Getting Started");
    assert.strictEqual(guide.category, "app");

});

test("getGuideBySlug returns null for an unknown slug", () => {

    assert.strictEqual(getGuideBySlug("this-guide-does-not-exist"), null);

});

test("getGameGuideForSlug finds each real game's guide", () => {

    const expected = {
        "hades": "hades-achievement-guide",
        "portal-2": "portal-2-achievement-guide",
        "hollow-knight": "hollow-knight-achievement-guide",
        "celeste": "celeste-achievement-guide",
        "inside": "inside-achievement-guide"
    };

    for (const [gameSlug, guideSlug] of Object.entries(expected)) {

        const guide = getGameGuideForSlug(gameSlug);

        assert.ok(guide, `expected a real guide for ${gameSlug}`);
        assert.strictEqual(guide.slug, guideSlug);
        assert.strictEqual(guide.category, "game");

    }

});

test("getGameGuideForSlug returns null for a game that has no guide at all (debug-game)", () => {

    assert.strictEqual(getGameGuideForSlug("debug-game"), null);

});
